### ISSUE TITLE
no refreshIndex method in Repository object

### ISSUE THREAD

**Issue by qmacpit** [nodegit/nodegit#1001]
nodegit@0.12.2
consider following code(it's almost 1:1 taken from example
https://github.com/nodegit/nodegit/blob/master/examples/create-new-repo.js): 
Git.Repository.init(repoPath, 0)
      .then((repo) => {
       //repo.refreshIndex() throw no such function error
       repo.openIndex() //this works though
      });

**Comment by johnhaley81** [comment]
The API was changed in https://github.com/nodegit/nodegit/releases/tag/v0.13.0. That was looking at `nodegit#master` at the time and 0.13.0 wasn't released yet. This should be fine now.
