### ISSUE TITLE
Error has no code

### ISSUE THREAD

**Issue by vjpr** [nodegit/nodegit#1027]
There does not seem to be an error code for when a remote upstream does not exist. Not sure if error codes are used elsewhere...

When running:

```
const origin = await git.Remote.lookup(repo, 'origin')
const currentBranch = await repo.getCurrentBranch()
const upstreamBranch = await git.Branch.upstream(currentBranch).catch(e => console.log(e))
```

I get:

```
Error: Config value 'branch.latest.remote' was not found
```

...with no error code.

**Comment by johnhaley81** [comment]
We just pass back the message we receive from libgit2 when an error is thrown. The low level C function result wouldn't provide much information since they aren't unique and out of context you wouldn't gain much information from them.
