### ISSUE TITLE
Uncaught Error: A dynamic link library (DLL) initialization routine failed on Windows 10, electron 1.0.2 and 0.37.8, nodegit 0.13.0

### ISSUE THREAD

**Issue by neloe** [nodegit/nodegit#1034]
I'm trying to use nodegit and electron for a cross platform application.  When I run on windows 10, I get:

`Uncaught Error: A dynamic link library (DLL) initialization routine failed. `  from `node_modules\nodegit\dist\nodegit.js:15`

I've tried combinations of electron 1.0.2 and nodegit (of which there doesn't seem to be a prebuilt binary for), and electron 0.37.8 (which is what the latest .tar.gz on S3 seems to be, so I switched to using 0.37.8).

my packages.json contains (configuration for 0.37.8):

```
  "devDependencies": {
    "electron-prebuilt": "0.37.8"
  },
  "engines": {
    "atom-shell": "0.37.8",
    "electron": "0.37.8"
  }
```

I added the atom-shell line under engines because of an earlier issue I saw when googling around on this same issue.

I've been installing simply with `npm install electron-prebuilt` and `npm install nodegit`.  Installing from the manually downloaded tar.gz gave me issues (an ENOENT error that seems so be a npm problem).

Other (maybe relevant) information:
```
$ node --version
v 4.4.4
```

**Comment by neloe** [comment]
I obtained a back trace with this minimal example:
test.js:
```var test = require('nodegit')```
```node_modules\.bin\electron test.js```

Backtrace:
```
Uncaught Exception:
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\...\node_mo...\nodegit.node
  at Error (native)
  at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
  at Object.Module._extensions..node(module.js:440:18)
  at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
  at Module.load(module.js:314:12)
  at Function.Module._load(module.js:314:12)
  at Module.require(module.js:367:17)
  at require(internal/module.js:16:19)
  at Object.<anonymous>
(C:\...\node_modules\nodegit...:12)
   at Module._compile(module.js:413:34)
```

**Comment by jschr** [comment]
Running into the same error, windows 10 as well. Node 6.2.0

**Comment by johnhaley81** [comment]
Try putting this into `.npmrc` at the root of your project

```
runtime = electron
target = 1.2.1
target_arch = x64
disturl = https://atom.io/download/atom-shell
progress = true
```

Changing values where appropriate.

**Comment by danielmhair** [comment]
I'm having the same error. @johnhaley81, I did as you suggested. Same error.

**Comment by danielmhair** [comment]
Actually, my error message is slightly different:

```bash
[2016-06-21 13:53:09.609] [ERROR] console - App threw an error during load
[2016-06-21 13:53:09.610] [ERROR] console - Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\oracledb\build\Release\oracledb.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Hair4\Projects\chemtrack-sds-search\node_modules\oracledb\lib\oracledb.js:32:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
```

**Comment by danielmhair** [comment]
```
Node v 6.2.1
NPM v 3.10.2
Electron v. 1.2.0
```

**Comment by johnhaley81** [comment]
That's happening with the `oracledb` package and not `nodegit`.

**Comment by neloe** [comment]
The .npmrc contents above fixed my problem (I wanted to test it on a few machines I hadn't gotten it to manually build on).  Thank you!

**Comment by danielmhair** [comment]
Hey @johnhaley81, I figured out the error. It ended being Electron that had the error. For reference, anyone that has an error regarding `A dynamic link library (DLL) initialization routine failed.`, review the following: https://github.com/oracle/node-oracledb/issues/449 and https://github.com/oracle/node-oracledb/issues/176

**Comment by TerryChan** [comment]
> 
> 
> Try putting this into `.npmrc` at the root of your project
> 
> ```
> runtime = electron
> target = 1.2.1
> target_arch = x64
> disturl = https://atom.io/download/atom-shell
> progress = true
> ```
> 
> Changing values where appropriate.

I got the same issue when I install nodegit in windows 10 - in electron. I can install nodegit successfully without the .npmrc, but when I run the elctron app, I got the "A dynamic link library..." issue which is same as the author.
After I added the .npmrc in my root folder, then install the nodegit again, the nodegit build failed:

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.23.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.23.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

Do you know how to fix this issue? I really want to use nodegit in my electron app, since it's really powerful.

By the way, I can use nodegit in nodejs application successfully, but failed in electron app.
