### ISSUE TITLE
Failed at the nodegit@0.13.0 install script 'node lifecycleScripts/install'

### ISSUE THREAD

**Issue by ibc** [nodegit/nodegit#1037]
- Debian Jessie.

`npm install nodegit` fails with that error.

What I see is that in package.json there is:

```json
"scripts": {
  "install": "node lifecycleScripts/install"
}
```

AFAIK this is wrong. Depending on the NPM version (and not sure what else) the `install` script is executed before moving the lib to its proper location under `node_modules`.

`postinstall` is the way to go.

**Comment by ibc** [comment]
npm-debug.log:

```
12414 info install yallist@2.0.0
12415 info postinstall yallist@2.0.0
12416 info install nodegit@0.13.0
12417 verbose unsafe-perm in lifecycle false
12418 info nodegit@0.13.0 Failed to exec install script
12419 verbose unlock done using /root/.npm/_locks/nodegit-b231cb226d0e9aaf.lock for /root/my_project/node_modules/nodegit
12420 verbose stack Error: nodegit@0.13.0 install: `node lifecycleScripts/install`
12420 verbose stack Exit status 1
12420 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
12420 verbose stack     at emitTwo (events.js:87:13)
12420 verbose stack     at EventEmitter.emit (events.js:172:7)
12420 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
12420 verbose stack     at emitTwo (events.js:87:13)
12420 verbose stack     at ChildProcess.emit (events.js:172:7)
12420 verbose stack     at maybeClose (internal/child_process.js:827:16)
12420 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
12421 verbose pkgid nodegit@0.13.0
12422 verbose cwd /root/my_project
12423 error Linux 3.16.0-4-amd64
12424 error argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "nodegit"
12425 error node v4.4.4
12426 error npm  v2.15.1
12427 error code ELIFECYCLE
12428 error nodegit@0.13.0 install: `node lifecycleScripts/install`
12428 error Exit status 1
12429 error Failed at the nodegit@0.13.0 install script 'node lifecycleScripts/install'.
12429 error This is most likely a problem with the nodegit package,
12429 error not with npm itself.
12429 error Tell the author that this fails on your system:
12429 error     node lifecycleScripts/install
12429 error You can get information on how to open an issue for this project with:
12429 error     npm bugs nodegit
12429 error Or if that isn't available, you can get their info via:
12429 error
12429 error     npm owner ls nodegit
12429 error There is likely additional logging output above.
12430 verbose exit [ 1, true ]
12431 verbose unbuild node_modules/nodegit
12432 info preuninstall nodegit@0.13.0
12433 info uninstall nodegit@0.13.0
12434 verbose unbuild rmStuff nodegit@0.13.0 from /root/my_project/node_modules
12435 info postuninstall nodegit@0.13.0
12436 silly gentlyRm /root/my_project/node_modules/nodegit is being purged from base /root/my_project
12437 verbose gentlyRm don't care about contents; nuking /root/my_project/node_modules/nodegit
12438 silly vacuum-fs purging /root/my_project/node_modules/nodegit
12439 silly vacuum-fs quitting because other entries in /root/my_project/node_modules
```

**Comment by tbranyen** [comment]
Can you submit a patch?

**Comment by ibc** [comment]
Well, that depends. Do developers of this project have something to say regarding the issue and my early proposal? Maybe I miss something as I don't know the project internals (and don't want to). If there are no concerns I can submit a PR.

**Comment by ibc** [comment]
Well, it fails if `/etc/sudoers` (Debian OS) contains:

```
Defaults env_keep += HOME
```

This means that when executing `sudo -s` original user's environments is kept. That produces, "somehow", an error when nodegit is built.

No idea, so feel free to close this issue at your convenience.

**Comment by maxkorp** [comment]
Is that something that changed? This was all stuff that we worked up during npm1 and early npm2. Speaking just for myself, I'm definitely open to the change however.

**Comment by ibc** [comment]
I don't fully understand what happens. Indeed the issue happens when, having the above `sudoers` configuration, the user runs `sudo -s` (so he becomes root but keeps his environment) and then `npm i nodegit`.

But the error log does not clarify too much why it fails nor how it's related to the explained scenario.

**Comment by johnhaley81** [comment]
@ibc can you try again with 0.14.0?

**Comment by ibc** [comment]
Environment:

* Debian 8.4
* `sudo -s` executed (with `Defaults env_keep += HOME` in `/etc/sudoers` , so I'm root but I keep my user environment).
* `npm i nodegit`:

```bash
root@web-server:~# npm i nodegit
|
> nodegit@0.15.1 preinstall /home/ibc/node_modules/nodegit
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script
[nodegit] npm@2 installed, pre-loading required packages
[nodegit] Configuring libssh2.
{ [Error: Command failed: /bin/sh -c /home/ibc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/ibc/node_modules/nodegit/vendor/openssl/openssl
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /home/ibc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/ibc/node_modules/nodegit/vendor/openssl/openssl' }
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH

[nodegit] ERROR - Could not finish preinstall
{ [Error: Command failed: /bin/sh -c /home/ibc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/ibc/node_modules/nodegit/vendor/openssl/openssl
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /home/ibc/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/home/ibc/node_modules/nodegit/vendor/openssl/openssl' }
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "nodegit"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.15.1 preinstall: `node lifecycleScripts/preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.15.1 preinstall script 'node lifecycleScripts/preinstall'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ibc/npm-debug.log
```

NOTE: The same happens if I run `npm i nodegit` as normal user (no `sudo`).

**Comment by philkunz** [comment]
I experience the same issue on latest ubuntu desktop with latest nodegit.

**Comment by luffyzc** [comment]
I experience the same issue with the latest version 

`npm WARN jsdoctest@1.0.0 No description
npm WARN jsdoctest@1.0.0 No repository field.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "nodegit"
npm ERR! node v6.2.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.14.1 preinstall: `node lifecycleScripts/preinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.14.1 preinstall script 'node lifecycleScripts/preinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.`

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/luffyzc/My Program/Nodejs/API Documentation/npm-debug.log`

**Comment by sgen** [comment]
I'm having the same issue.

OS: Ubuntu Desktop 15.10
Node.js Version: 5.12.0
npm version: 3.8.6

output:

`> nodegit@0.14.1 preinstall /home/sgen/Documents/javascript/test/nodegit/node_modules/.staging/nodegit-7aec4eff
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ [Error: Command failed: /home/sgen/Documents/javascript/test/nodegit/node_modules/.staging/nodegit-7aec4eff/vendor/libssh2/configure --with-libssl-prefix=/home/sgen/Documents/javascript/test/nodegit/node_modules/.staging/nodegit-7aec4eff/vendor/openssl/openssl
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/sgen/Documents/javascript/test/nodegit/node_modules/.staging/nodegit-7aec4eff/vendor/libssh2/configure --with-libssl-prefix=/home/sgen/Documents/javascript/test/nodegit/node_modules/.staging/nodegit-7aec4eff/vendor/openssl/openssl' }
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH

[nodegit] ERROR - Could not finish preinstall
{ [Error: Command failed: /home/sgen/Documents/javascript/test/nodegit/node_modules/.staging/nodegit-7aec4eff/vendor/libssh2/configure --with-libssl-prefix=/home/sgen/Documents/javascript/test/nodegit/node_modules/.staging/nodegit-7aec4eff/vendor/openssl/openssl
configure: error: cannot find OpenSSL or Libgcrypt,
try --with-libssl-prefix=PATH or --with-libgcrypt-prefix=PATH
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/sgen/Documents/javascript/test/nodegit/node_modules/.staging/nodegit-7aec4eff/vendor/libssh2/configure --with-libssl-prefix=/home/sgen/Documents/javascript/test/nodegit/node_modules/.staging/nodegit-7aec4eff/vendor/openssl/openssl' }
/home/sgen/Documents/javascript/test/nodegit
└── (empty)

npm WARN nodegit No description
npm WARN nodegit No repository field.
npm WARN nodegit No license field.
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "nodegit"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.14.1 preinstall: `node lifecycleScripts/preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.14.1 preinstall script 'node lifecycleScripts/preinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sgen/Documents/javascript/test/nodegit/npm-debug.log
npm ERR! code 1
`

**Comment by azotova** [comment]
Hi, I am experiencing a similar issue on Mac OS 10.11.6 (and 10.11.5). Node v. 4.4.3.
```
npm info preinstall nodegit@0.15.1

> nodegit@0.15.1 preinstall /Users/anastasiazotova/lampa-docker/lampa-root/lada/node_modules/nodegit
> node lifecycleScripts/preinstall

[nodegit] Running pre-install script
[nodegit] npm@2 installed, pre-loading required packages
[nodegit] ERROR - Could not finish preinstall
{ [Error: stderr maxBuffer exceeded] cmd: '/bin/sh -c npm install --ignore-scripts' }
npm verb unsafe-perm in lifecycle true
npm info nodegit@0.15.1 Failed to exec preinstall script
npm verb unlock done using /Users/anastasiazotova/.npm/_locks/nodegit-a5f407442d9071bb.lock for /Users/anastasiazotova/lampa-docker/lampa-root/lada/node_modules/nodegit
npm verb stack Error: nodegit@0.15.1 preinstall: `node lifecycleScripts/preinstall`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:827:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid nodegit@0.15.1
npm verb cwd /Users/anastasiazotova/lampa-docker/lampa-root/lada
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.15.1 preinstall: `node lifecycleScripts/preinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.15.1 preinstall script 'node lifecycleScripts/preinstall'.
```

**Comment by saper** [comment]
@azotova your problem is different and pretty interesting, can you file another issue for the "stderr maxBuffer exceeded"?

**Comment by azotova** [comment]
@saper  Done: #1103  Thanks for looking into this (although updating Node solved the issue for me).

**Comment by maxkorp** [comment]
Currently, nodegit requires you to have the openssl dev headers installed. 
On ubuntu: `sudo apt-get install libssl-dev`
That should take care of it. If it doesn't, let us know and we'll reopen. 
related: https://github.com/nodegit/nodegit/issues/1093

**Comment by aeweidne** [comment]
Still getting the issue...

```
[nodegit] WARN - Could not finish postinstall
{ [Error: Command failed: /bin/sh -c node /home/pubby/node_modules/nodegit/dist/nodegit.js
/home/pubby/node_modules/nodegit/dist/nodegit.js:15
    throw ex;
    ^
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/pubby/node_modules/nodegit/build/Release/nodegit.node)
```

**Comment by maxkorp** [comment]
@aeweidne If thats your only build error then something else is up. Are you building for electron or something?

**Comment by aeweidne** [comment]
I got this when trying to install `nodegit` during staging to Bluemix and as well as when trying to build a Docker image from the standard node 4.4.x image

**Comment by maxkorp** [comment]
Yeah, your image will have to install libssl-dev (or openssl-devel on centos i think it's called). See: #1093

**Comment by aeweidne** [comment]
Hm, I thought I already was but I guess I was mistaken.  Thanks for the info and quick response.

**Comment by saper** [comment]
@aeweidne I am afraid the problem is because of the old GNU C++ library installed. Can you try compiling from source? You will probably need a newer compiler as well :(

**Comment by aafrey** [comment]
@maxkorp `sudo apt-get install libssl-dev` fixed this issue for me on Ubuntu

**Comment by ibc** [comment]
This issue should not be closed. The very same happens in Ubuntu 16.04. It is not fixed at all by just installing `libssl-dev`.

**Comment by maganap** [comment]
Same issue here on Debian. Updated to latest stable npm, node and libssl-dev.

node v6.9.2
npm  v4.0.5
Debian GNU/Linux 8 (jessie)

`npm ERR! Linux 3.16.0-0.bpo.4-amd64
npm ERR! argv "/root/.nvm/versions/node/v6.9.2/bin/node" "/root/.nvm/versions/node/v6.9.2/bin/npm" "install"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.6.3 install: `node lifecycleScripts/install`
npm ERR! Exit status 13
npm ERR! 
npm ERR! Failed at the nodegit@0.6.3 install script 'node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.
`

**Comment by bjentsch** [comment]
Try installing `node-legacy`:
`sudo apt install nodejs-legacy`

For me, the error was that the script tried to execute some command with `node ...`, which wasn't found because it is only contained in the `nodejs-legacy` bundle.

**Comment by vilazae** [comment]
Hello to everyone!, I'm having the same issue. Could you give me some suggestions?

**OS**: CentOS release 6.8 (Final)
**Node.js**: v6.9.2
**npm**: v3.10.9

output:
```bash
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> nodegit@0.16.0 install /translations/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /translations/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/translations/node_modules/nodegit/vendor/openssl/openssl
/translations/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/translations/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/translations/node_modules/nodegit/vendor/libssh2':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/translations/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/translations/node_modules/nodegit/vendor/openssl/openssl' }
/translations/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/translations/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/translations/node_modules/nodegit/vendor/libssh2':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /translations/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/translations/node_modules/nodegit/vendor/openssl/openssl
/translations/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/translations/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/translations/node_modules/nodegit/vendor/libssh2':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/translations/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/translations/node_modules/nodegit/vendor/openssl/openssl' }
npm WARN translation-scripts@1.0.0 No repository field.
npm ERR! Linux 2.6.32-642.11.1.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "nodegit"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /translations/npm-debug.log
```

Regards!

**Comment by tristanlee85** [comment]
I feel I am running into a similar issue as others here. I'm on OSX 10.12.2. For the sake of trying, I did install `libssh2` via Homebrew, but it hasn't changed anything. Here's my output:

```
$ sudo npm install nodegit -g --save

> nodegit@0.16.0 install /usr/local/lib/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /usr/local/lib/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/nodegit/vendor/openssl/openssl
/usr/local/lib/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/usr/local/lib/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/local/lib/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/nodegit/vendor/openssl/openssl' }
/usr/local/lib/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/usr/local/lib/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /usr/local/lib/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/nodegit/vendor/openssl/openssl
/usr/local/lib/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/usr/local/lib/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/usr/local/lib/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/usr/local/lib/node_modules/nodegit/vendor/openssl/openssl' }
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nodegit" "-g" "--save"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tristanlee85/Documents/sustaining/npm-debug.log
tristanlee85@Tristans-MBP:sustaining$
```

**Comment by gnitter** [comment]
@tristanlee85, installing libgcrypt worked for me on macOS 10.12.3.Thanks!

**Comment by deive** [comment]
@tristanlee85 Installed libgcrypt via [Brew](http://brewformulas.org/Libgcrypt) also worked!
`brew install libgcrypt`

**Comment by deive** [comment]
Even after `brew install libgcrypt` this is failing for me:
Darwin 16.4.0
node v7.5.0
npm  v4.1.2

**Comment by tbranyen** [comment]
We haven't done a build for 7.5.0 yet, could be why? Try downgrading to 7.4.0 and see if that helps.

**Comment by deive** [comment]
@tbranyen Sorry, I missed that. Just downgraded to node v7.4.0, npm  v4.0.5 and it is still failing with the same error.
Gotta go now, I'll try investigating further tomorrow...

**Comment by deive** [comment]
@tbranyen That was all my fault, I was in a project directory that had `"nodegit": "0.16.0"` specified. Sorry - 0.17.0 is working fine.

**Comment by tbranyen** [comment]
:+1: good to know!

**Comment by johnny0614** [comment]
@tristanlee85 installing libgcrypt works for me on macOS 10.12.3 and nodegit@0.18.0. many thanks.

**Comment by kenji-1996** [comment]
Had no end of trouble with this;
Lowering node version fixed it but caused a magnitude of errors in my day to day dev
Installing every package under the sun didnt help

Changing to sudo with `sudo -s` and running `yarn add nodegit` worked for me; Couldnt tell you why but hopefully this might help someone in the same position.

**Comment by tbranyen** [comment]
@kenji-1996 That indicates something wrong with your system. `sudo` is not required at all to install NodeGit. If this was required on your system, it most likely means you don't have permissions set up correctly for npm.
