### ISSUE TITLE
How to checkout a branch?

### ISSUE THREAD

**Issue by ibc** [nodegit/nodegit#1038]
I know that `git checkout` is a sugar API provided by the `git` command line. However I find no way to properly checkout a remote branch with `nodegit`.

May I know how to do that please?

**Comment by andrewstart** [comment]
This has worked for me:
```
//repo is a Repository from Clone() or Open()
//branchName is your branch name, of course
repo.getBranch('refs/remotes/origin/' + branchName)
    .then(function(reference) {
        //checkout branch
        return repo.checkoutRef(reference);
    });
```

**Comment by ibc** [comment]
Thanks a lot. Will check it.

**Comment by tbranyen** [comment]
Hiya everyone, please use the Gitter channel for general support. Would rather support requests not add to our overall Issue count, thanks!

**Comment by ibc** [comment]
I second that. However, given that the `nodegit` documentation says absolutely nothing regarding branches, IMHO this is an issue to be fixed by adding the proper documentation.

A question about an undocumented feature is an issue, not a support request. Otherwise, do you prefer that users will ask the same questions again and again in the support channel?

Please, document the project as it deserves.

**Comment by tbranyen** [comment]
@ibc, questions have already been asked over and over again in our issue tracker, so I expect the same would happen in Gitter. It's where I'd like to see questions about usage posted. We will most likely never have 100% documentation unless someone really dedicate joins to do that. There hundreds of methods we expose and probably thousands of use cases that currently need documenting. Don't forget to update them when the API changes every year!

My recommendation in the Gitter channel would have been to look at how libgit2 recommends doing it and then mapping those calls to NodeGit. That's the most bullet-proof way of getting started.

Thanks for understanding!
