### ISSUE TITLE
why do we need a public key for cred?

### ISSUE THREAD

**Issue by lenrico** [nodegit/nodegit#1042]
Hi,

I read the docs here http://www.nodegit.org/api/cred/ and i do not understood why i need a public key for ssh authentication?

On my shell i do everyday something like this...

`$ ssh-add .ssh/id_rsa`
`$ git clone git://user@fqdn:repo.git`

or this

`GIT_SSH_COMMAND='ssh -i .ssh/id_rsa_file' git clone git://user@fqdn:repo.git`

and never needed a public key before.

Best
Enrico

**Comment by tbranyen** [comment]
Because Git binary does all that for you. We're much more low level and libgit2 requires that information.
