### ISSUE TITLE
Nodegit v0.13.1 403s when downloading on Windows

### ISSUE THREAD

**Issue by 50Wliu** [nodegit/nodegit#1049]
This might actually be an Atom build script issue; if so, apologies in advance.

I'm currently trying to build Atom, but the build script fails every time after Nodegit fails to download its binary from `https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.13.1-electron-v0.37-win32-ia32.tar.gz`, which is returning a 403 error.  Interestingly `https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.13.0-electron-v0.37-win32-ia32.tar.gz` works fine.

I'm on Windows 10 x64.

**Comment by johnhaley81** [comment]
Yes I didn't publish 0.37 binaries. If you guys need them I can publish them up for you.

**Comment by johnhaley81** [comment]
Published.
