### ISSUE TITLE
Is there a prebuilt binary for nw.js 0.15.2?

### ISSUE THREAD

**Issue by spirodonfl** [nodegit/nodegit#1056]
I'm trying to install nodegit and it makes attempts to download prebuilt binaries for nwjs v0.15.x (depending on my configs) but fails to do so.

I'm not entirely sure how to build from scratch with the nwjs headers. It seems electron is the most supported app here (I understand why).

**Comment by spirodonfl** [comment]
Just as an update, I've tried building nodegit myself, ran nwjs, required nodegit, keep getting a DLL initialization error. I know that means I'm missing the nwjs headers or something else. I'm hoping I can be pointed in the right direction. I've built my own custom node modules without the nwjs header and it's worked just fine.

**Comment by johnhaley81** [comment]
We currently do not have a system set up to build/publish nwjs binaries yet. NodeGit is a beast and I'm not surprised that while other native node modules might have worked for you NodeGit does not. It *must* be built against the target.

**Comment by maxkorp** [comment]
The trick really is just to install it normally, then to run `nw-gyp rebuild` or whatever the standard rebuild process is these days

**Comment by maxkorp** [comment]
Closing this as a wont-fix
