### ISSUE TITLE
Possible memory leak when opening Repository.

### ISSUE THREAD

**Issue by Stradivario** [nodegit/nodegit#1059]
This video represent the situation

https://drive.google.com/file/d/0B9yXLQTv57ryTjFZd3BFaUMxSEU/view

I am sending 5000 request through API and and everything seems ok,
but when i try to open a repository it just keeps building and building memory blocks ;( 
Help me guys i am not sure even if i resolve the whole chain and return everything as expected and everything is working again as i expected i figure out that it was building a lot of memory.

Thanks for all responses
Wish you a best luck.

**Comment by tbranyen** [comment]
Do you ever close or free the repositories when you're done with them?

Check out: http://www.nodegit.org/api/repository/

**Comment by Stradivario** [comment]
![image](https://cloud.githubusercontent.com/assets/19847933/16322532/5f54227a-39ac-11e6-9210-4901c0ee25ae.png)

This is what happens when i try to free the repository...

**Comment by tbranyen** [comment]
That sounds like you're doing something like this:

``` js
const free = myRepo.free;

free();
```

Can you confirm that you're calling the free method directly off the repo object? It'd also be helpful to see your code.

**Comment by Stradivario** [comment]
This is my Test Promise function

`		testPromise: function testPromise(request, reply) {
	        console.log('Entered inside TEST function')
	        git.createConfig({
	            status: 'commitHistory',
	            name: request.payload.name,
	            branch: request.payload.branch,
	            number: request.payload.number
	        }, reply, (cfg)=>{
	        	var promise = git.promiseReturn(cfg.src, cfg.remoteName, cfg.branch, cfg.number);
	        	var source = Rx.Observable.fromPromise(promise);
				var subscription = source.subscribe(
				(data)=>{
			        return reply({
			            payload: {
			                commits: data,
			                status: 'OK'
			            }
			        });
				},
				(e)=>{
					console.log('onError: %s', e);
	            		return reply({
	            			payload: {
	            				err: e,
	            				status: 'ERROR'
	            			}
	            		});
				},
				()=>{
					console.log('onCompleted');
					subscription.dispose();
				});
				
	        });
		}`


`var promise = git.promiseReturn(cfg.src, cfg.remoteName, cfg.branch, cfg.number);`

Here i create an instance of this function:

`
gitAPI.prototype.promiseReturn = function(src, remoteName, branch, number) {
    var p = new RSVP.Promise(function (resolve, reject) {
            var repository;
            var commitHistory = [];
            open(src)
                .catch((err)=>{
                    reject("ERORR:", src + ' cannot be opened.');
                })
                .then((_repository)=>{
                    repository = _repository;
                    return repository.getCurrentBranch().then((ref)=>{
                        return repository.getBranchCommit(ref.shorthand());
                    })
                    .then((commit)=>{
                        let hist = commit.history()
                        var p = new Promise((resolve, reject)=>{
                                hist.on("end", resolve);
                                hist.on("error", reject);
                            });
                        hist.start();
                        return p;
                    })
                    .then((commits)=>{
                    _repository = _repository.free();
                        repository.free()
                        console.log('Number of Commits: ', commits.length)
                        if (number) {
                            commits.length = number;
                        }
                        for (let i = 0; i < commits.length; i++) {
                            let sha = commits[i].sha(),
                                msg = commits[i].message().split('\n')[0];
                            let obj = {
                                sha: sha,
                                msg: msg
                            };
                            commitHistory.push(obj);
                        }
                        
                        return resolve(commitHistory);
                    });
                })
    });
    console.log(util.inspect(process.memoryUsage()));
    return p;
}
`

**Comment by prajapati-parth** [comment]
@tbranyen I faced the same problem, when keeping the repo open led to continuous memory consumption. I used `.free()` and it solved the issue. I'm still confused about the memory consumption by the open repo. And it's not present in the documentation.
