### ISSUE TITLE
cannot create a branch using Repository#createBranch

### ISSUE THREAD

**Issue by calvinmwhu** [nodegit/nodegit#1064]
I'm trying to create a branch using the Repository#createBranch method but it throws an empty error "{}". Could you guys take a look at what I'm doing wrong ?

```
exports.createBranch = function (req, res) {
    var branchName = req.body["branch_name"];
    var name = req.body["name"];
    var email = req.body["email"];
    var message =  "branch {0} created".format(branchName);
    NodeGit.Repository.open(config.database).then(function (repo) {
        return repo.getHeadCommit();
    }).then(function (commit) {
        var signature = NodeGit.Signature.now(name, email);
        return repo.createBranch(branchName, commit, 0, signature, message);
    }).then(function (branch) {
        console.log(branch);
        res.status(200).json({message: "OK", data: branch.toString()});
    }).catch(function (err) {
        res.status(500).json({message: err, data: []});
    }).done(function () {
        console.log("finished");
    });
};
```

I'm pretty sure the parameters branchName, name, email, and message are valid parameters. And `repo.getHeadCommit()` succeeds. But the error occurs when `createBranch` method gets called and it turned out to be an empty error "{}".

**Comment by calvinmwhu** [comment]
NVM,  turns out that I mis-used "repo".

**Comment by softbharath** [comment]
I am able to create a branch locally but unable to push it to remote repository. if possible, Could you please share the sample code for create branch with push to remote. this is my code

var nodegit = require("nodegit");
var path = require("path");
var config = require('./config/config');
var pushToRemote = require('./push_remote.js');

var repository;

var remoteRepoName = "P1"
var branchName = "new-branch";

//Gitserver URL (currently in AWS EC2)
var remoteGitURL = config.remoteGitURL + remoteRepoName + '.git'

nodegit.Repository.open(path.resolve(__dirname, "xxxx"))
  .then(function(repo) {
    repository = repo;
    // Create a new branch on head
    return repo.getHeadCommit()
    .then(function(commit) {
      return repo.createBranch(
        branchName,
        commit,
        0,
        repo.defaultSignature(),
        "Created new-branch on HEAD");
        console.log("2");

    })
      // Add a new remote
      .then(function() {

        return pushToRemote.push(repository,remoteGitURL,branchName,function(error,map){
          if(error)
          {
            console.log("Error Creating remote repo:" + error);
          }
        });
      });
    });

**Comment by softbharath** [comment]
Hi, Looks like it is pushing it to remote, I checked the wrong repository earlier.
