### ISSUE TITLE
problems to build branch master from sources on debian 

### ISSUE THREAD

**Issue by aanno** [nodegit/nodegit#1065]
I've got problems to build nodegit (branch master) from sources like described in http://www.nodegit.org/guides/install/from-source/ on a debian _32-bit_ system:

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy

$ uname -a
Linux jenkins 2.6.32-40-pve #1 SMP Fri Jul 24 11:16:05 CEST 2015 i686 GNU/Linux

The following problems have occurred:

* Wrong line endings in most of vendor/libssh2 (most prominent: vendor/libssh2/configure, which leads to './configure: /bin/sh^M: Defekter Interpreter'). Fixable by using dos2unix
* nodegit.node is installed via remote; this should not happen when building from sources; anyway - it installs a _amd64 version_ (where a x86 version is required). Fixable by 'cp ./build/Release/nodegit.node /usr/lib/node_modules/nodegit/build/Release/nodegit.node'
```
[nodegit] Success: "/usr/lib/node_modules/nodegit/build/Release/nodegit.node" is installed via remote
[nodegit] Completed installation successfully.
```
* (optional, trying to install as root 'npm install -g'): Complains about the lifecycle scripts ('cannot run in wd'). Fixable with 'npm install --unsafe-perm -g'. (Perhaps this is the problem mentioned at https://github.com/este/este/issues/511 ?!?)

**Comment by aanno** [comment]
Same problem with debian 8 and 64-bit:

# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:        8.5
Codename:       jessie

# uname -a
Linux jenkins 2.6.32-40-pve #1 SMP Fri Jul 24 11:16:05 CEST 2015 x86_64 GNU/Linux

**Comment by aanno** [comment]
I pulled with the (classical) git command line client. No idea why nobody reported it before.

**Comment by maxkorp** [comment]
So I just checked this, and including cloning with cli, my line endings are correct. I'm gonna guess it's the dated version of git, or otherwise an invalid git setting
