### ISSUE TITLE
403 when npm install nodegit - nodejs v 6.2.2

### ISSUE THREAD

**Issue by rolatsch** [nodegit/nodegit#1069]
Hi, i was forced to update to nodeJs 6.2.2 now when trying to install nodegit i get 
`node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.12.2-node-v48-win32-x64.tar.gz´

Is this nodeJS version supported by nodegit?

**Comment by rolatsch** [comment]
Nevermind. My package.json locked nodegit to version 0.12.2 wich seems not to be compatible with nodeJs 6.2.2. I have removed the entry from my package.json and installed nodegit v. 0.14.0 without any problems

**Comment by centigrade-thomas-becker** [comment]
I have the same problem, but somehow I am stuck with nodegit 0.12.x. In my package.json nodegit version was set to "^0.12.1", but I never got a newer version than 0.12.2 after installation.

I had to remove the entry from my package.json, and install it again with `npm install --save nodegit` to finally get the latest version (0.16.0)

Does anybody have an idea why this did not work? AFAIK ^0.12.1 should have resolved to 0.16.0
