### ISSUE TITLE
Assertion failure when mistakenly passing a function to Repository.getCommit()

### ISSUE THREAD

**Issue by novalis** [nodegit/nodegit#1070]
I accidentally did repo.getCommit(something.id) instead of repo.getCommit(something.id()). I got the following crash, which I had to debug by bisecting my code:

node: ../node_modules/nan/nan_object_wrap.h:33: static T\* Nan::ObjectWrap::Unwrap(v8::Localv8::Object) [with T = GitOid]: Assertion `object->InternalFieldCount() > 0' failed.
Aborted

It would be better to catch this error somewhere that a reasonable stack trace can be provided.

**Comment by johnhaley81** [comment]
Yep, you're right. This is related to #1127 so I'm going to close this out and we can continue the conversation in that issue.
