### ISSUE TITLE
why is Branch.delete a SYNC call?

### ISSUE THREAD

**Issue by calvinhmw** [nodegit/nodegit#1078]
I'm developing a node server where I need to manipulate a local git repo using nodegit.  I wonder if Branch.delete will possibly block since it is a sync method? Will an async version be developed? If Branch.delete will block, how much timeout value should I set in order to convert it into a async call?

**Comment by maxkorp** [comment]
Hrm, seems like a detection error in the code generator

**Comment by calvinhmw** [comment]
So the delete method is actually Async ?

**Comment by tbranyen** [comment]
No, he means that it *should* be async, but there is a bug in our generator (or we never flipped the switch). Once that bug is fixed, it will be actually async :-)

**Comment by calvinhmw** [comment]
So right now we just use it as sync?

**Comment by tbranyen** [comment]
Correct

**Comment by calvinhmw** [comment]
Will I expect a big overhaul to the nodegit API in the future ?

**Comment by tbranyen** [comment]
Probably not, what sort of overhaul are you expecting?

**Comment by calvinhmw** [comment]
Not really expecting any.. Just curious :)

**Comment by tbranyen** [comment]
Probably not, unless libgit2 changes. All we do is provide a very auto-generated wrapper to it with a few helper functions.

**Comment by calvinhmw** [comment]
thx!

**Comment by maxkorp** [comment]
So something like this would change, perhaps a few other methods which _should_ be async but are also sync would change as well, but no large overhauls
