### ISSUE TITLE
how do I properly stage and commit all change on a feature branch?

### ISSUE THREAD

**Issue by calvinhmw** [nodegit/nodegit#1083]
Say my repo is at current branch X whose parent branch is master. What is the equivalent API(s) calls for achieving:
git add -A
git commit -m "<commit message>" ?

Is it correct to do:

```
repo.createCommit('HEAD', , committer,  , Tree, parents).then(function(oid) {
    ...
});
```

How do I obtain Tree and parents in this case? Should I get the parents object by calling the "getHeadCommit" object on the master branch ?

**Comment by calvinhmw** [comment]
NVM. Figured it out.

**Comment by kachkaev** [comment]
@calvinhmw can you please share your solution?
