### ISSUE TITLE
Is Index#addByPath thread safe ?

### ISSUE THREAD

**Issue by calvinhmw** [nodegit/nodegit#1084]
So one part of my Node app needs to stage/add multiple files at once. This is what I do with the Q promise library:

```
var addChanges = function(index, paths) {
    var promises = paths.map(function(path) {
           return index.addByPath(path);
    });
    return Q.all(promises);
}

```
In my understand Q.all tries to run all the async functions in parallel. Can we run multiple index.addByPath() in this way since we're not sure if it is thread-safe?

**Comment by novalis** [comment]
No, this is not safe by default, as-of 0.19.  You'll need to use NodeGit.setThreadSafetyStatus(NodeGit.THREAD_SAFETY.ENABLED_FOR_ASYNC_ONLY);
