### ISSUE TITLE
Is there a command doing the same thing as git add -A ?

### ISSUE THREAD

**Issue by calvinhmw** [nodegit/nodegit#1087]
In a terminal, "git add -A" not only stages newly added/modified files but also stages deleted files. That way we don't have to call "git rm" to stage deleted files. How do I achieve this in nodegit ? Does Index.addAll() only stages newly added/modified files?

**Comment by johnhaley81** [comment]
@calvinhmw that is correct. `git add -A` is syntax sugar for what you want to do. We don't have a built-in way currently to do what you're asking. One thing you can do is iterate over all of the files and call `Index#remove` on the files you want to delete.

**Comment by kachkaev** [comment]
@johnhaley81 I'm also looking for a simple way to stage all new / changed / deleted files in HEAD and commit them if needed. Could you point to an example of that? Could not find anything simple in `examples`, so what do you think of adding it?
