### ISSUE TITLE
Cannot npm install in Ubuntu 16.04, fails during preinstall script

### ISSUE THREAD

**Issue by mlms13** [nodegit/nodegit#1088]
I've tried installing from npm as well as [building from source](http://www.nodegit.org/guides/install/from-source/), and all installs fail during the `preinstall` script. I've tried using Node 0.12, 4.4.5, and 6.3.1 (switching with NVM). I think that this issue is different from #1037 (at least as that one was originally reported), because that issue shows up while executing `install`, not `preinstall`. Some of the most recent comments in that issue seem to match my problem, though.

The preinstall script seems to throw errors while `Configuring libssh2`:

```
configure: error: cannot find OpenSSL or Libgcrypt,
```

**Comment by maxkorp** [comment]
Yeah, theres an issue with our build structure. If you `sudo apt-get install libssl` that should take care of it. It's supposed to pull its own for a static link, but that doesn't appear to happen properly.

**Comment by mlms13** [comment]
Ah yep, no `libssl` package on Ubuntu 16.04, but installing `libssl-dev` did the trick.

**Comment by mlms13** [comment]
The CI build seems to be failing on Linux for the same reason: https://travis-ci.org/nodegit/nodegit/jobs/147599864

It might be good to update the preinstall script, or at least the README.

**Comment by tbranyen** [comment]
@mlms13 that CI error looked to be completely unrelated. I've restarted the build since it looked to be network related.

**Comment by mlms13** [comment]
There are a bunch of seemingly unrelated npm failures in there, but at the very end it dies with a failure in the preinstall script. It'll be interesting to see if it completes this time.

**Comment by tbranyen** [comment]
Well it looks like it passed, but the console output is still indicating an error. I dunno?
