### ISSUE TITLE
cannot npm install nodegit with gcc-4.8.5

### ISSUE THREAD

**Issue by calvinmwhu** [nodegit/nodegit#1096]
My gcc-version is 4.8.5 but during installation I got the following error:

```
Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/app/node_modules/nodegit/build/Release/nodegit.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/app/node_modules/nodegit/dist/nodegit.js:11:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node /home/app/node_modules/nodegit/dist/nodegit.js' }


```

It looks like there is no GLIBCXX_3.4.20 in gcc4.8. Wouldn't nodegit support gcc4.7+ ?  How do I configure my gcc to make it include GLIBCXX_3.4.20 ?

**Comment by tbranyen** [comment]
You're missing the `libstdc++-dev` dependency mentioned in the README.

**Comment by calvinmwhu** [comment]
Since the docs are targeted for Ubuntu whereas I'm using Centos (centos-release-6-8.el6.centos.12.3.x86_64) and a libstdc++-dev does not seem to be available in centos's domain. Do you have ideas how I can upgrade my libstdc++.so.6 to include the GLIBCXX_3.4.20 version ?

**Comment by tbranyen** [comment]
Urgh, I wish! CentOS is something I have very limited experience with. I'd search for whatever provides libstdc++ headers in the package manager, should be a relatively easy issue to Google I'd hope. Sorry I closed the issue so quickly, but we can discuss this issue better in realtime with [Gitter](https://gitter.im/nodegit/nodegit). If we figure something out, I'd definitely be okay with updating the README to contain instructions for Cent OS.

**Comment by calvinmwhu** [comment]
ok so the solution is to install gcc-4.9
