### ISSUE TITLE
Error: Failed to write index: The index is in-memory only     at Error (native)

### ISSUE THREAD

**Issue by zhizunbaono1** [nodegit/nodegit#1101]
hi, i meet a problem.Can you help me?

When I use code like this:
```
.then(function(commit) {
      theirCommit = commit;
      return nodegit.Merge.commits(repo, ourCommit, theirCommit);
    }).then(function(index) {
      if (!index.hasConflicts()) {
        return index.write()
          .then(function() {
            console.log("index writeTree");
            return index.writeTreeTo(repo);
          })
      } else {
      ...
```

it throw a problem say:Error: Failed to write index: The index is in-memory only
    at Error (native)

Can you help me?

**Comment by dorongutman** [comment]
@zhizunbaono1 how did you solve it ?

**Comment by alangpierce** [comment]
@dorongutman I ended up running into the same issue and ended up solving it using `Merge.merge` instead of `Merge.commits`. See this comment for more details: https://github.com/nodegit/nodegit/issues/1128#issuecomment-255558213
