### ISSUE TITLE
Multiple users fetching the same repo concurrently

### ISSUE THREAD

**Issue by isvaljek** [nodegit/nodegit#1104]
What would happen if multiple users were to fetch the repo in the same moment? Is it safe? What about other operations like diff during another user's fetch?

**Comment by johnhaley81** [comment]
Currently there is no way that libgit2 (and thus NodeGit) protects from issues like these. One way you could do it is add a `.git/config.lock` file with no content and just check the existence of it before you do a fetch.

NodeGit _does_ however protect against concurrent actions like that for calls using the same binary of NodeGit.

**Comment by maxkorp** [comment]
Closing this as the response is fair, please feel free to comment and we can reopen if you have more questions.
