### ISSUE TITLE
Continued Node 0.12 support?

### ISSUE THREAD

**Issue by maxkorp** [nodegit/nodegit#1109]
Do we want to continue support for 0.12? Bumping openssl to latest breaks 0.12 support, but I don't know if thats worth fixing (not sure how long it would take). Now that node 4 is LTS (and has been for a while), are we ok potentially dropping 0.12 support?
@nodegit/owners

**Comment by maxkorp** [comment]
So bumping openssl was fixed fairly easily after all, but this is still worth talking about IMO, even if the end result doesnt happen til later.

**Comment by saper** [comment]
As long as it works... I have proposed a change to node https://github.com/nodejs/node/pull/8027 to make cross-compilation a bit easier. Still hoping that this hits the 0.12 maintenance release.

**Comment by maxkorp** [comment]
Ya, I guess we should leave it for now, EoL is end of the year, we can kill it then
https://github.com/nodejs/LTS#lts_schedule
