### ISSUE TITLE
Cloning with an SSH agent that has no identity causes NodeGit to hang

### ISSUE THREAD

**Issue by syagev** [nodegit/nodegit#1112]
May be related to #497 

Minimal example:

    const Git = require('nodegit');
    const cloneOpts = { 
        fetchOpts: { 
            callbacks: {
                 certificateCheck: () => 1,
                 credentials: (url, userName) =>
                     Git.Cred.sshKeyFromAgent(userName)
            }
        }
    };
    Git.Clone('some-private-repo', '/tmp/a', cloneOpts)
        .then(console.log)
        .catch(console.log);

A valid promise is returned but never fulfilled or rejected (no output to console in the above case).

I am able to reproduce this on Ubuntu 16.04.1, Node v6.3.1, nodegit 0.14.1 when an `ssh-agent` is up and running but has no identities loaded (i.e. `ssh-add` never called).

**Comment by maxkorp** [comment]
Thanks for reporting this! We'll take a look.

**Comment by syagev** [comment]
Sorry, my bad, the issue is not related to credentials. The callbacks aren't even being called. This was tested on a machine with no open outgoing ports (including SSH) so cloning is not really an option... 

As far as I'm concerned this is valid behaviour, event the git CLI does not seem to timeout or fail under these conditions, it just stalls.
