### ISSUE TITLE
Failed to mmap. Could not write data: Invalid argument (VirtualBox shared folder)

### ISSUE THREAD

**Issue by hardog** [nodegit/nodegit#1115]
Hello, here need help, when clone a repo, error comes to me:
```
Failed to mmap. Could not write data: Invalid argument
Error: Failed to mmap. Could not write data: Invalid argument
    at Error (native)
```
## system
cmd line type `$ uanme -a`
`Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

## tried nodegit version

`0.13.0, 0.15.0, 0.15.1`

## code

```
let Git = require("nodegit");
let Clone = Git.Clone;
let cloneOptions = {};

cloneOptions.fetchOpts = {
	callbacks: {
      certificateCheck: () => {
        return 1;
      }
    }
};

Clone(
	'repourl', 
	'/path`,
	cloneOptions
)
.then((repo) => {
	console.log('repo done!');
})
.catch((e) => {
	console.log(e.message);
	console.log(e.stack);
});
```

anyone can help me ?

**Comment by saper** [comment]
Which filesystem are you working on? Are you sharing that directory somehow via SMB, NFS, VirtualBox shared folder etc.?

**Comment by hardog** [comment]
@saper yes, VirtualBox was used and shared a folder on Mac OS system,   it's the problem?

**Comment by saper** [comment]
Yes, this "filesystem" lacks some semantics neededby libgit2 client and will not work. You might also have trouble with other tools. I'd recommend switching to NFS.

**Comment by hardog** [comment]
@saper Got it, thx a lot!

**Comment by ZiluckMichael** [comment]
Sorry for necroing this issue, but what is the solution for this? Git on its own works perfectly fine in the directory but GitKraken fails to pull. Why would a shared folder with VirtualBox cause it to fail?

**Comment by saper** [comment]
@ZiluckMichael do not use shared folder for anything serious. Try NFS or something like that instead.
