### ISSUE TITLE
Segmentation fault: 11 on Tag.list(...)

### ISSUE THREAD

**Issue by frederikbrinck** [nodegit/nodegit#1120]
Calling Tag.list() with a Remote object throws a segmentation fault. Replicate with the code below:

```
return git.Remote.lookup(remoteRepository, 'origin')
	.then((remoteResult) => { return remoteResult; }, 
		  (error) => { return git.Remote.create(remoteRepository, 'origin', remoteWrite) })
	.then((remoteResult) => {
		return git.Tag.list(remoteResult);
// ouch...
````

Running nodegit 0.15.1, npm 3.10.7, node v6.4.0 and node-pre-gyp 0.6.18.

**Comment by maxkorp** [comment]
Tag.list takes a `Repository` object, not a `Remote`. What precisely are you aiming to do here, view the state of the tags on the remote?

**Comment by frederikbrinck** [comment]
I figured that it took a `Repository` and I managed to do what I intended. However, I suppose it is a vulnerability that Tag.list does not check the object type and just proceeds, throwing a segmentation error to the developer. Shouldn't this error be caught instead and handled by nodegit?

**Comment by maxkorp** [comment]
Yes, but this is not specific to this case. Currently, our type checking between a js object, and a nodegit object isn't there. We're just able to check that whatever was passed in is an object. 
I'll make an issue for that (as it is an issue), but it's far more generic, and requires a fix in our C++ templates.

**Comment by maxkorp** [comment]
Closing this in lieu of that issue.

**Comment by frederikbrinck** [comment]
Thanks for the clarification.
