### ISSUE TITLE
Can't install via NPM

### ISSUE THREAD

**Issue by mitchellmorris** [nodegit/nodegit#1134]
Am I missing something? Any tips how to get around this? It just started happening.

```
> nodegit@0.16.0 install /Users/superman/Sites/myproj/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ [Error: Command failed: /bin/sh -c /Users/superman/Sites/myproj/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/superman/Sites/myproj/node_modules/nodegit/vendor/openssl/openssl
/Users/superman/Sites/myproj/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/superman/Sites/myproj/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /Users/superman/Sites/myproj/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/superman/Sites/myproj/node_modules/nodegit/vendor/openssl/openssl' }
/Users/superman/Sites/myproj/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/superman/Sites/myproj/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ [Error: Command failed: /bin/sh -c /Users/superman/Sites/myproj/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/superman/Sites/myproj/node_modules/nodegit/vendor/openssl/openssl
/Users/superman/Sites/myproj/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/superman/Sites/myproj/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /Users/superman/Sites/myproj/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/superman/Sites/myproj/node_modules/nodegit/vendor/openssl/openssl' }
myproj-server@1.0.0 /Users/superman/Sites/myproj
└── (empty)

npm WARN EPACKAGEJSON myproj-server@1.0.0 No repository field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/Users/superman/npm/bin/npm" "install" "nodegit" "--save"
npm ERR! node v4.4.7
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/superman/Sites/myproj/npm-debug.log
npm ERR! code 1
```

**Comment by johnhaley81** [comment]
Latest Xcode just straight up broke things all across the world. Try running `sudo xcode-select --install` and update the xcode CLT. That fixed it for me.

**Comment by mitchellmorris** [comment]
Thanks man!

**Comment by WORMSS** [comment]
What if you are getting the same error `vendor/libssh2/missing: Unknown `--is-lightweight' option` but do not have xcode-select ??

**Comment by johnhaley81** [comment]
@WORMSS are you on OSX?

**Comment by petega** [comment]
Since this issue popped up first, when I searched for this error:
On Ubuntu 16.04 this problem might be solved by `sudo apt install libssl-dev` (thanks to @n8behavior)
See #728

**Comment by e-cloud** [comment]
I'm using Ubuntu 16.10, facing the same error.

**Comment by danShumway** [comment]
Should documentation be updated for this? Better yet, is there a node crypto library that ``nodegit`` could fall back on if ``libssl-dev`` isn't present?

**Comment by WORMSS** [comment]
@johnhaley81  no, I was using a Raspberry Pi.. 

Sorry for big delay, I must have missed your reply.

**Comment by SkeLLLa** [comment]
Same bug on gentoo linux.

**Comment by DeX3** [comment]
Happens for me as well on Mac OS Sierra 10.12.1. `sudo xcode-select --install` gives me:

```
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

App Store tells me XCode is up to date though.

**Comment by samiraguiar** [comment]
@DeX3 just had this problem on Sierra. Had to uninstall node and homebrew, then reinstall homebrew, install node from brew and it worked.

**Comment by malko** [comment]
installing libssl-dev on ubuntu 16.10 also solved problem for me.

**Comment by jimCresswell** [comment]
I want to use NodeGit to build an application that people can install with Docker or `npm -g`. That's not going to work in all cases if people need to install extra libraries. As @danShumway asked, is there a way to work around systems missing the crypto libraries? cc @sponte

**Comment by maxkorp** [comment]
The issue lies in the fact that it will only use the included openssl if that copy is already built, but that copy is built by the install. Something of a chicken and egg problem that needs to be resolved first. Haven't quite figured out a way around it yet though. Fixing that will allow it to use the locally included copy and should take care of that issue.

**Comment by jimCresswell** [comment]
@maxkorp okay, I'm not sure I have the skills to help but I'm up for it in principle, please let me know if I can be useful. I'm looking at pulling test and specs and documents versioned with systems out of those systems but respecting branches, NodeGit (what is the correct capitalisation of that?) seems like the best tool for the job.

**Comment by tjcarroll11** [comment]
I'm trying to get this to run on CentOS and am running into the same issue. I can't install libssl-dev because it doesn't exist for CentOS, and installing openssl-devel does not fix the problem. I'd love to use NodeGit, but this is obviously a blocker =/.

**Comment by clearly** [comment]
`yum groupinstall "Development tools"` no workie on Amazon Linux.

Any smart guys know how to solve this?

**Comment by CMCDragonkai** [comment]
Also related: https://github.com/nodegit/nodegit/issues/1247

**Comment by TaylorAckley** [comment]
Thanks @clearly !

**Comment by fractalf** [comment]
Having trouble installing on Ubuntu. Installed `libssl-dev` as suggested above..
```
$ npm install nodegit --save

> nodegit@0.20.3 install /home/alf/code/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.20.3-node-v59-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.20.3 and node@9.2.0 (node-v59 ABI, glibc) (falling back to source compile with node-gyp)
```
Seems like a file request fails..

**Comment by TaylorAckley** [comment]
@fractalf try running `npm rebuild nodegit`

https://docs.npmjs.com/cli/rebuild

**Comment by wiredearp** [comment]
On Ubuntu 16.04, I was able to `apt-get install libssl-dev` to progress somewhat further before I got hit by another error called `curl/curl.h: No such file or directory`, but then I `sudo apt-get install libcurl4-openssl-dev` and the thing managed to finally install.

**Comment by michaelkruglos** [comment]
`sudo apt install libcurl4-openssl-dev` fixed the issue for me on Ubuntu 16.04

**Comment by dvakatsiienko** [comment]
> Latest Xcode just straight up broke things all across the world. Try running `sudo xcode-select --install` and update the xcode CLT. That fixed it for me.

This fix worked for me on macOS Sierra, but after upgrading to macOS Mojave this fix does not work anymore.

`brew install libgcrypt` did fixed this issue though. I will test this a bit alter on clean macOS Mojave clean install. But as for now it looks like that nodegit is not working on Mojave by default, except `libgcrypt` is installed with brew.

**Comment by maxkorp** [comment]
Guh, then it's configuring libssh "wrongly" however. But it works.

**Comment by Stranger469** [comment]
`sudo xcode-select --install` is not work for macos 10.14 mojave, it still throws `configure: error: No crypto library found!`
```bash
```

**Comment by implausible** [comment]
Would you please ping me if what @maxkorp suggested has fixed your errors? That would be super awesome! Trying to stay on top of what got fixed and what didn't in our big build change!

**Comment by RaevLogic** [comment]
@maxkorp and @implausible check the nodegit slack. Someone with a similar `configure: error: No crypto library found!` problem just installed `nodegit@0.23.0-alpha.1` and it fixed the issue for them.

**Comment by maxkorp** [comment]
THIS IS GOING TO CLOSE SO MANY ISSUES

**Comment by RaevLogic** [comment]
All hail Steve.

**Comment by dvakatsiienko** [comment]
this is very very wanted for us!

**Comment by setshaft** [comment]
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

Adding these to rc file for allowing compilers to find openssl, solved the issue for me.

**Comment by Leekao** [comment]
I solved this issue by running "sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /" on my macOS.

**Comment by elviejo79** [comment]
On Ubuntu 18.04
I got the error:

```sh
WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.26.3-node-v79-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.26.3 and node@13.3.0 (node-v79 ABI, glibc) (falling back to source compile with node-gyp)
/bin/sh: 1: krb5-config: not found
gyp: Call to 'krb5-config gssapi --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp
ERR! configure error
```

my solution was:
```sh
 sudo apt install libkrb5-dev
```
