### ISSUE TITLE
Require latest version not working

### ISSUE THREAD

**Issue by almarieSaayman** [nodegit/nodegit#1145]
I have a windows machine, I did not test on another platform. 
When I install the latest version (0.16.0) using npm and I execute the following script:

console.log('before');
let _nodegit = require('nodegit');
console.log('after');

Only 'before' gets logged. When I installed version 0.15.1 everything seemed to be working fine again.

For now I will be using version 0.15.1.

**Comment by DanUgore** [comment]
I've encountered the same problem. Thank you for providing a temporary solution.

**Comment by johnhaley81** [comment]
If @almarieSaayman or @DanUgore can provide more details about their environment then we can reopen this issue but for now I'm going to close it since there's no good way to track down what's broken.
