### ISSUE TITLE
Libgit2 Slack

### ISSUE THREAD

**Issue by tommoor** [nodegit/nodegit#1155]
Your README links to a private Slack room:

https://github.com/nodegit/nodegit#have-a-problem-come-chat-with-us

What happened to Gitter? How do folks get into this private slack community?

**Comment by rcjsuen** [comment]
Looks like the channel is actually located at:
http://slack.libgit2.org/

There is a separate #nodegit channel there.

**Comment by rcjsuen** [comment]
I submitted pull request #1170 to edit the `README.md` file.

**Comment by johnhaley81** [comment]
Merged #1170
