### ISSUE TITLE
npm install nodegit failing on mac 10.12.1

### ISSUE THREAD

**Issue by willwade** [nodegit/nodegit#1156]
mac os x 10.12.1
Xcode installed
node 4.2.2

npm install nodegit is failing on:

node lifecycleScripts/preinstall && node lifecycleScripts/install

and this is the error log:

	3415 info nodegit@0.16.0 Failed to exec install script
	3416 verbose unlock done using /Users/willwade/.npm/_locks/nodegit-5643d9eb4a969649.lock for /Users/willwade/Downloads/node-web-scraper-master 2/node_modules/nodegit
	3417 verbose stack Error: nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
	3417 verbose stack Exit status 1
	3417 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
	3417 verbose stack     at emitTwo (events.js:87:13)
	3417 verbose stack     at EventEmitter.emit (events.js:172:7)
	3417 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
	3417 verbose stack     at emitTwo (events.js:87:13)
	3417 verbose stack     at ChildProcess.emit (events.js:172:7)
	3417 verbose stack     at maybeClose (internal/child_process.js:818:16)
	3417 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
	3418 verbose pkgid nodegit@0.16.0
	3419 verbose cwd /Users/willwade/Downloads/node-web-scraper-master 2
	3420 error Darwin 16.1.0
	3421 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "nodegit"
	3422 error node v4.2.2
	3423 error npm  v2.14.7
	3424 error code ELIFECYCLE
	3425 error nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
	3425 error Exit status 1
	3426 error Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
	3426 error This is most likely a problem with the nodegit package,
	3426 error not with npm itself.
	3426 error Tell the author that this fails on your system:
	3426 error     node lifecycleScripts/preinstall && node lifecycleScripts/install
	3426 error You can get their info via:
	3426 error     npm owner ls nodegit
	3426 error There is likely additional logging output above.
	3427 verbose exit [ 1, true ]
	3428 verbose unbuild node_modules/nodegit
	3429 info preuninstall nodegit@0.16.0
	3430 info uninstall nodegit@0.16.0
	3431 verbose unbuild rmStuff nodegit@0.16.0 from /Users/willwade/Downloads/node-web-scraper-master 2/node_modules
	3432 info postuninstall nodegit@0.16.0
	3433 silly gentlyRm /Users/willwade/Downloads/node-web-scraper-master 2/node_modules/nodegit is being purged from base /Users/willwade/Downloads/node-web-scraper-master 2
	3434 verbose gentlyRm don't care about contents; nuking /Users/willwade/Downloads/node-web-scraper-master 2/node_modules/nodegit
	3435 silly vacuum-fs purging /Users/willwade/Downloads/node-web-scraper-master 2/node_modules/nodegit
	3436 silly vacuum-fs quitting because other entries in /Users/willwade/Downloads/node-web-scraper-master 2/node_modules

**Comment by suprememoocow** [comment]
I'm getting a similar error on macOs Sierra, possibly related:

```
$ npm run installDebug

> nodegit@0.16.0 installDebug /Users/andrewn/code/opensource/nodegit
> BUILD_DEBUG=true npm install

> nodegit@0.16.0 install /Users/andrewn/code/opensource/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] npm@2 installed, pre-loading required packages
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/andrewn/code/opensource/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/andrewn/code/opensource/nodegit/vendor/openssl/openssl
/Users/andrewn/code/opensource/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/andrewn/code/opensource/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/andrewn/code/opensource/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/andrewn/code/opensource/nodegit/vendor/openssl/openssl' }
/Users/andrewn/code/opensource/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/andrewn/code/opensource/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/andrewn/code/opensource/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/andrewn/code/opensource/nodegit/vendor/openssl/openssl
/Users/andrewn/code/opensource/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/andrewn/code/opensource/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/andrewn/code/opensource/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/andrewn/code/opensource/nodegit/vendor/openssl/openssl' }

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.0.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrewn/code/opensource/nodegit/npm-debug.log

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.0.0/bin/node" "/usr/local/bin/npm" "run" "installDebug"
npm ERR! node v7.0.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! nodegit@0.16.0 installDebug: `BUILD_DEBUG=true npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 installDebug script 'BUILD_DEBUG=true npm install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     BUILD_DEBUG=true npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrewn/code/opensource/nodegit/npm-debug.log
```

**Comment by pronebird** [comment]
Same error.

**Comment by mattboutet** [comment]
`brew install libgcrypt` worked for me, but first I had to update homebrew, twice - if you have trouble with libgcrypt, it could just be an out-of-date version of homebrew.

**Comment by wadeanthony0100** [comment]
`brew install libgcrypt` also solved this for me. Should this be documented as a Mac OS requirement? Some documentation would be a nice to have IMO.

**Comment by DinkDonk** [comment]
I get the same error. `brew install libgcrypt` did not solve it for me.

**Comment by johnhaley81** [comment]
Yes, Apple removed libgcrypt from OSX by default now so we need to list it as a requirement now. Sorry about that.

@DinkDonk did you ever get it to build on your machine?

**Comment by johnhaley81** [comment]
Issue to add libgcrypt as a requirement for OSX #1200

**Comment by DinkDonk** [comment]
Tried building now after pulling the latest nodegit changes. Did a reinstall of libcrypt for good measure. It works!

Thank you 🥇

**Comment by gzhappysky** [comment]
brew install libgcrypt worked for me

**Comment by dolanmiu** [comment]
```bash
$ brew install libgcrypt
```

Worked for me too

**Comment by hassankhan** [comment]
I've tried reinstalling `libgcrypt` several times but no luck. I'm on 10.11, if that makes any difference
