### ISSUE TITLE
AWS 403 error for prebuilt binaries on node 7.0.0

### ISSUE THREAD

**Issue by andy-ms** [nodegit/nodegit#1157]
I am getting this error after upgrading to node 7.0.0:

```
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.16.0 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp)
```

The install works in node 6.9.1.
Tested on Windows 10.

**Comment by aspirisen** [comment]
Have the same

**Comment by thisconnect** [comment]
me too https://travis-ci.org/thisconnect/nodegit-kit/jobs/173458364 https://github.com/thisconnect/nodegit-kit/issues/19

**Comment by dukeofsussex** [comment]
Nearly the same here, 403ing on `ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-node-v45-linux-x64.tar.gz `

**Comment by michael34435** [comment]
same here

**Comment by matteocng** [comment]
System: Linux
Node: 7.2.0
Npm: 3.10.10 / Yarn: 0.17.9
Nodegit: 0.16.0

`node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-node-v51-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.16.0 and node@7.2.0 (node-v51 ABI) (falling back to source compile with node-gyp)`

Then it builds successfully and works.

**Comment by AKFourSeven** [comment]
Same here cannot install nodegit because of the missing binaries.

**Comment by johnhaley81** [comment]
Looks like NodeGit doesn't build on node v7 at all right now. We have to figure out a way to link to OpenSSL better. Fix should be incoming soon. Thanks!

**Comment by tbranyen** [comment]
@johnhaley81 ha just hit this myself >_< damn arch linux bumping to 7

**Comment by maxkorp** [comment]
Wait, whats the openssl bug?

**Comment by maxkorp** [comment]
Yeah, master builds for me on node 7.4 on osx

**Comment by tbranyen** [comment]
@maxkorp check latest master, we merged 7.4.0 support ^_^

**Comment by cnadeau** [comment]
It's causing problem on alpine linux within a container

exact same cause as : https://github.com/nodegit/nodegit/issues/1039

because it's not using glibc, but musl libc

Would it be possible to do something regarding that?

**Comment by tbranyen** [comment]
I'm not sure, but that seems likely.

**Comment by maxkorp** [comment]
Thats probably the issue, and it's really probably out of our scope to fix that, unfortunately, unless we wanna custom roll some CI.

**Comment by cnadeau** [comment]
Your call :-) But since Alpine kind of became the de facto base image for Docker, you should think about it. 

NOTE: It does build from source within the container on 0.16 so it is possible to get 0.17 built within it as well. 

I would be happy to be able to help you getting this done. PM me if you are interested.

Thanks for the quick reply!

**Comment by tbranyen** [comment]
@cnadeau definitely! i personally don't know how we could support this without bulking up our already large build matrix. if you can find a non-intrusive resolution that would be super ideal :)

**Comment by cnadeau** [comment]
I'll see what I can do next week :-)

**Comment by cnadeau** [comment]
@tbranyen I have not experience with travis and thought it would not be that complicated, but after reading a bit, aside manually spinning up a container to build it, I don't see a good solution.

My guess would be to define CXX flag to g++ for a new platform 

https://github.com/nodegit/nodegit/blob/master/.travis.yml#L49

to get 

https://github.com/nodegit/nodegit/blob/master/generate/templates/templates/binding.gyp#L108

used by node-gyp

but again, no travis neither C++ expert.

Any comments/reactions/suggestions are welcomed

**Comment by maxkorp** [comment]
The other problem with using a newer gcc is that actually kills a lot of older app builds on LTS ubuntu etc :/

**Comment by Croydon** [comment]
Node 7 is end of life, this issue should be closed.

**Comment by maxkorp** [comment]
Yeah we build 6, 8 and 9 now.

**Comment by rutpshah** [comment]
I am still getting this error on Node v10.13.0
