### ISSUE TITLE
NG 0.16.0 Travis issues

### ISSUE THREAD

**Issue by dukeofsussex** [nodegit/nodegit#1158]
Working fine for Node 4,5,6, but not for iojs.

Added the travis snippet from the Readme, but no luck: https://travis-ci.org/pencilblue/pencilblue/jobs/176044958

This is what happens when I set the `BUILD_ONLY=true` flag: https://travis-ci.org/pencilblue/pencilblue/builds/176333203

**Comment by johnhaley81** [comment]
We don't support io.js anymore (haven't for a while). Issue to remove them from the webpage: https://github.com/nodegit/nodegit.github.com/issues/47
