### ISSUE TITLE
Self-hosted gitlab always return HTTP 411 when pushing

### ISSUE THREAD

**Issue by michael34435** [nodegit/nodegit#1162]
Hey, guys.
I want to cherry-pick a commit and push it to my gitlab server. But it always return `Error: Unexpected HTTP status code: 411`
I have no idea what's wrong with my code... please give me a help

environment:
macOS 10.12.1
node.js 7.1.0 (--harmony-async-await)
nodegit 0.16.0

Here is my code:
```javascript
const repo = await Git.Repository.open(process.cwd())
const remote = await repo.getRemote('origin')
const current = await repo.getCurrentBranch()
await remote.push(
  [`${current.name()}:${current.name()}`],
  {
    callbacks: {
      certificateCheck: () => 1,
      credentials: (url) => {
        if (url.indexOf('http') === -1) {
          return Git.Cred.sshKeyFromAgent(USERNAME)
        } else {
          return Git.Cred.userpassPlaintextNew(USERNAME, PASSWORD)
        }
      }
    }
  }
)
```

Thanks!

**Comment by michael34435** [comment]
I guess that I found the problem.
I use `http protocol` and nodegit reject me and return 411 error code.
Does anyone has any idea? :(

**Comment by saper** [comment]
How many changes do you need to push?

**Comment by saper** [comment]
Can you check if this is https://github.com/libgit2/libgit2/issues/3981#issuecomment-257518324 (libgit2 requires chunked encoding to push changes)?

**Comment by michael34435** [comment]
@saper I only had one change to push and my `git push` works fine.
Is this problem related to http protocol?

**Comment by saper** [comment]
Yes, 411 is an HTTP error code, in this case related to the size limit. SSH will be fine in this situation.
