### ISSUE TITLE
Prebuilt binary list of https://s3.amazonaws.com/nodegit/nodegit/

### ISSUE THREAD

**Issue by mlhch** [nodegit/nodegit#1163]
Hi, 

I found below is a typical failure, which is due to fail to download the prebuilt binary of https://s3.amazonaws.com/nodegit/nodegit/nodegit-v0.1.4-node-v11-darwin-x64.tar.gz.

When I try to browse https://s3.amazonaws.com/nodegit/nodegit/, it says AccessDenied.

When I try `cd ./node_modules/nodegit/ && ./node_modules/node-pre-gyp/bin/node-pre-gyp info`, it says "TimeoutError: Missing credentials in config".

Is the prebuilt binary not existing? If yes, then the failure is reasonable. Or am I have no permissions? 
If yes, then this is obviously unreasonable.

I want to know a list of what versions have prebuilt binary so that I can install the corresponding versions...

```
(node-0.10.42)mbp:a-test-dir mlhch$ cnpm i nodegit@0.1.4
> nodegit@0.1.4 install /.../a-test-dir/node_modules/nodegit
> node install.js

[nodegit] Determining dependencies.
[nodegit] Removing vendor/libgit2.
[nodegit] Fetching vendor/libgit2.
[nodegit] Configuring native node module.
[nodegit] Failed to build nodegit.
[nodegit] Attempting to fallback on a prebuilt binary.
[nodegit] Fetching binary from S3.
[nodegit] Failed to build and install nodegit.
Command failed: [nodegit] Command failed: 
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: dlopen(/.../a-test-dir/node_modules/nodegit/build/Release/nodegit.node, 1): no suitable image found.  Did find:
	/.../a-test-dir/node_modules/nodegit/build/Release/nodegit.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by setiseta** [comment]
Same on Windows:
- ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-node-v51-win32-x64.tar.gz

**Comment by mlhch** [comment]
For others to reference, if I cd to the nodegit path and run its install.js via `npm install`, then I can have a great chance of building the nodegit.node successfully. Then I can save the compiled nodegit.node and place it to the corresponding location in other projects.

```
root@2f8109aae51a:/test/node_modules/nodegit# cnpm i
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN engine form-data@2.0.0: wanted: {"node":">= 0.12"} (current: {"node":"0.10.46","npm":"2.15.1"})
npm WARN cannot run in wd nodegit@0.1.4 node install.js (wd=/test/node_modules/nodegit)
async@0.9.2 node_modules/async

ejs@1.0.0 node_modules/ejs

aws-sdk@2.0.31 node_modules/aws-sdk
├── xmlbuilder@0.4.2
└── xml2js@0.2.6 (sax@0.4.2)

jshint@2.5.11 node_modules/jshint
├── strip-json-comments@1.0.4
├── underscore@1.6.0
├── exit@0.1.2
├── shelljs@0.3.0
├── console-browserify@1.1.0 (date-now@0.1.4)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.14, domutils@1.5.1)
├── minimatch@1.0.0 (sigmund@1.0.1, lru-cache@2.7.3)
└── cli@0.6.6 (glob@3.2.11)

nodeunit@0.9.5 node_modules/nodeunit
└── tap@7.1.2 (opener@1.4.2, os-homedir@1.0.1, clean-yaml-object@0.1.0, stack-utils@0.4.0, signal-exit@3.0.1, color-support@1.1.2, isexe@1.1.2, only-shallow@1.2.0, deeper@2.1.0, tap-parser@2.2.3, tmatch@2.0.1, readable-stream@2.2.2, glob@7.1.1, bluebird@3.4.6, tap-mocha-reporter@2.0.1, js-yaml@3.7.0, nyc@7.1.0, foreground-child@1.5.3, coveralls@2.11.15)
```

**Comment by sveisvei** [comment]
Getting this as well `configure: WARNING: 'missing' script is too old or missing`

**Comment by mlhch** [comment]
For others information, I've made great progress:

For me I'm installing nodegit@0.1.4, a rather old release, there is an install.js.

- Edit <project dir>/node_modules/nodegit/install.js, just print the error message using console.log:

```
// Attempt to fallback on a prebuilt binary.
.fail(function(message) {
  console.log(message); <== add this line
  console.info('[nodegit] Failed to build nodegit.');
```

Then run `npm rebuild nodegit` to generate the actual message. Mine is "Error: Command failed: /bin/sh: ./node_modules/.bin/node-gyp: No such file or directory", then I realize and checked that I'm using npm@3.x, which install dependencies in a "flat" way and cause <project dir>/node_modules/nodegit/node_modules/node-gyp goes to <project dir>/node_modules/node-gyp and <project dir>/node_modules/nodegit/node_modules/.bin/node-gyp not available. That's why it keeps saying "Failed to build nodegit".

Once I switch my npm to 2.x, everything goes well.

**Comment by thisconnect** [comment]
Why is this issue closed?
Do you suggest to downgrade to npm@2 and nodegit@0.1.4 ?

**Comment by mlhch** [comment]
nodegit@0.1.4 is a rather old version. I use it because I have a project developed and based on the old API.

Obviously, I suppose there was no npm@3 for nodegit@0.1.4 at that time. So I think this is not an issue for nodegit@0.1.4, but something else need to pay attention to when install.
