### ISSUE TITLE
transferProgress callback data

### ISSUE THREAD

**Issue by peterchoo** [nodegit/nodegit#1167]
I'm trying to get some useful data out of the transfer progress callback, but am currently failing.

I have the following callback:

```javascript
{
  transferProgress(progress) {
    return Object.keys(progress.__proto__).map(k => console.log(`${k}: ${progress[k]()}`));
  }
}
```

This is only firing once when the repository has finished downloading, but I suspect that this is due to the repository being very small.  However the data it is returning is rather useless to me:

```
totalObjects: 193
indexedObjects: 0
receivedObjects: 0
localObjects: 0
totalDeltas: 0
indexedDeltas: 0
receivedBytes: 27485
```

This looks like it is the data from the first attempted callback, and as such I cannot calculate a rough progress by comparing receivedObjects vs totalObjects.

Also, I couldn't find any particularly useful examples for this callback.

Any idea what I can do to better use this callback?

**Comment by CraZySacX** [comment]
You can try decreasing the throttle.  0 turns it off.  Default is 1 event per 100ms.

```
    transferProgress: {
      throttle: 0,
      callback: (progress) => {
        return Object.keys(progress.__proto__).map(k => console.log(`${k}: ${progress[k]()}`))
      }
    }
```

**Comment by johnhaley81** [comment]
You can do:

```javascript
transferProgress(stats) {
  const progress = (100 * (stats.receivedObjects() + stats.indexedObjects())) / (stats.totalObjects() * 2);

  return progress;
}
```
