### ISSUE TITLE
Slack Channel Access

### ISSUE THREAD

**Issue by pebanfield** [nodegit/nodegit#1169]
Hi - 

The readme says - 

Have a problem? Come chat with us!

https://libgit2.slack.com/

but this channel seems to require an invite. Perhaps this is the intent? I was hoping I could get some help with a node module version issue. Thanks. 

Peter

**Comment by rcjsuen** [comment]
See issue 1155. It seems like like the channel is actually located at:
http://slack.libgit2.org/

There is a separate #nodegit channel there.

**Comment by pebanfield** [comment]
ah k missed that - thanks!
