### ISSUE TITLE
Installing nodegit on Centos 6

### ISSUE THREAD

**Issue by blackshade91** [nodegit/nodegit#1171]
Installing nodegit with npm I have this error:

make: *** [Release/obj.target/openssl/vendor/openssl/asm/x64-elf-gas/aes/aesni-sha256-x86_64.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/EasyDev-App/source/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-042stab120.6
gyp ERR! command "/usr/local/bin/node" "/opt/EasyDev-App/source/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/opt/EasyDev-App/source/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/opt/EasyDev-App/source/node_modules/nodegit/build/Release"
gyp ERR! cwd /opt/EasyDev-App/source/node_modules/nodegit
gyp ERR! node -v v7.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
make: Leaving directory `/opt/EasyDev-App/source/node_modules/nodegit/build'
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /opt/EasyDev-App/source/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/EasyDev-App/source/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/opt/EasyDev-App/source/node_modules/nodegit/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/EasyDev-App/source/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 2.6.32-042stab120.6
node-pre-gyp ERR! command "/usr/local/bin/node" "/opt/EasyDev-App/source/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd
/opt/EasyDev-App/source/node_modules/nodegit
node-pre-gyp ERR!
node -v v7.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /opt/EasyDev-App/source/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/EasyDev-App/source/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/opt/EasyDev-App/source/node_modules/nodegit/build/Release' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN mongodb-core@1.2.26 requires a peer of kerberos@~0.0 but none was installed.
npm WARN test@ No repository field.
npm WARN test@ No license field.
npm ERR! Linux 2.6.32-042stab120.6
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/EasyDev-App/source/npm-debug.log

  post-deploy hook failed

Deploy failed

**Comment by johnhaley81** [comment]
We currently aren't building on Node v7. Please follow #1157 for updates. Thanks!
