### ISSUE TITLE
maintained?

### ISSUE THREAD

**Issue by thisconnect** [nodegit/nodegit#1176]
hi is Nodegit maintained?

**Comment by luii** [comment]
+1

**Comment by maxkorp** [comment]
Yes, although we've been a less active lately than one would hope.

**Comment by johnhaley81** [comment]
Hey! We all were buckled down for a bit focusing on getting [GitKraken 2.0](https://blog.axosoft.com/2017/01/25/gitkraken-v2/) going.

We now resume our regularly scheduled program.
