### ISSUE TITLE
remote.push() never finishes

### ISSUE THREAD

**Issue by rolandjitsu** [nodegit/nodegit#1185]
I made a simple function I can use to push to a remote repo, but it seems to be behaving strangely:
```js
function push(remoteName, refSpecs) {
	return remote(remoteName)
		.mergeMap((remote) => Observable.fromPromise(remote.push(refSpecs, {callbacks: {credentials: (url, user) => {
			const cred = Cred.sshKeyFromAgent(user);
			console.log(cred.hasUsername(), url)
			return cred;
		}}})));
}
```

It looks like the credentials callback is called endlessly. It logs `git` for the user and the url points to the right remote repository.

**Comment by rcjsuen** [comment]
This is probably a duplicate of #1133.

**Comment by rolandjitsu** [comment]
Probably, I'll close this one.
