### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory'... in Electron

### ISSUE THREAD

**Issue by dolanmiu** [nodegit/nodegit#1192]
When using `nodegit` in Electron, I get the following error only when using nodegit on the **renderer** thread. It works totally fine on the **main** thread. I don't want to have to IPC to the main thread to use this library!

Error:

```
> webpack --config config/webpack.prod.js --progress --profile --bail

 69% 653/655 build modulesModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Debug/nodegit.node in /Volumes/Storage/Git/Git-Proton/node_modules/nodegit/dist
    at /Volumes/Storage/Git/Git-Proton/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Volumes/Storage/Git/Git-Proton/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Volumes/Storage/Git/Git-Proton/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
    at Tapable.<anonymous> (/Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
    at Storage.finished (/Volumes/Storage/Git/Git-Proton/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at ReadFileContext.callback (/Volumes/Storage/Git/Git-Proton/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
resolve file
  /Volumes/Storage/Git/Git-Proton/node_modules/nodegit/build/Debug/nodegit.node doesn't exist
  /Volumes/Storage/Git/Git-Proton/node_modules/nodegit/build/Debug/nodegit.node.js doesn't exist
  /Volumes/Storage/Git/Git-Proton/node_modules/nodegit/build/Debug/nodegit.node.ts doesn't exist
resolve directory
  /Volumes/Storage/Git/Git-Proton/node_modules/nodegit/build/Debug/nodegit.node doesn't exist (directory default file)
  /Volumes/Storage/Git/Git-Proton/node_modules/nodegit/build/Debug/nodegit.node/package.json doesn't exist (directory description file)
```

**Comment by rcjsuen** [comment]
@dolanmiu Did you try running webpack with `webpack --display-error-details`?

**Comment by dolanmiu** [comment]
@rcjsuen when I do that, the same error happens, same output

**Comment by rcjsuen** [comment]
> Whats odd is that I do not have a Debug folder, BUT, I have a Release folder. Is this a clue?

I don't know. It might. If you look at your build output, what happens in the case where you're using the renderer thread instead of the main thread? On that note, I'm having difficulties understanding how this is a problem with NodeGit and Electron. Isn't this a problem with NodeGit and webpack?

**Comment by dolanmiu** [comment]
@rcjsuen it works on the main thread. It does not work on the renderer thread. 

This is so puzzling.

**Comment by rcjsuen** [comment]
> it works on the main thread. It does not work on the renderer thread.

Yes, I understand that. I mean where is webpack searching for `nodegit.node` if you put your code in the main thread?

I'm still having difficulties understanding how this is an issue with Electron. webpack is not a requirement for creating and running Electron applications. Can you launch your application if you don't use webpack?

**Comment by rcjsuen** [comment]
@dolanmiu Do you have your broken code in a branch somewhere or is it what's on [master](https://github.com/dolanmiu/Git-Proton) right now?

**Comment by dolanmiu** [comment]
@rcjsuen yes, master should work. Webpack must be search for `nodegit.node` in the Release folder. Otherwise it would complain.

I am starting to think maybe it is related to a configuration within webpack? Maybe I need to specify `Debug Mode` or something.

**Comment by rcjsuen** [comment]
I had to make a change to `package.json` because of a [bug](https://github.com/s-panferov/awesome-typescript-loader/issues/190) in the Awesome Typescript loader. Otherwise, your code in `master` builds fine for me.

**Comment by dolanmiu** [comment]
@rcjsuen i know, it will work fine because i try not to push broken code into master

however, if you pull `master` now, it should break because of this commit:

https://github.com/dolanmiu/Git-Proton/commit/c4735a2c2a8d270486e5512d38e341090aeaeb94

this should reproduce the bug i am seeing

**Comment by rcjsuen** [comment]
@dolanmiu Your issue definitely looks like a webpack problem. I suggest you look into making some [changes](https://github.com/dolanmiu/Git-Proton/pull/1) to your `webpack.prod.js` file.

I don't think this is a bug with NodeGit.

**Comment by dolanmiu** [comment]
Thanks! this worked

Seems like this `fs` thing is common in webpack:

https://github.com/webpack/webpack/issues/839#issuecomment-76738356

http://stackoverflow.com/questions/40207277/using-webpack-to-use-require-modules-in-browser
