### ISSUE TITLE
API supports git archive?

### ISSUE THREAD

**Issue by vongohren** [nodegit/nodegit#1227]
The title says the most, but i basically want to use the archive function to fetch out a specific file from a specific repo and in a specific branch, in a nodemodule

**Comment by rcjsuen** [comment]
No, this functionality is not implemented in NodeGit.

**Comment by Snorlock** [comment]
Plans on implementing it?

**Comment by rcjsuen** [comment]
Actually, I'm not quite sure what you are trying to do. As far as I know, `git archive` lets you retrieve a tree of files, not a particular file. You seem to want the ability to retrieve the contents of an arbitrary file from some random remote repository.

**Comment by Snorlock** [comment]
Yeah, i have found out that archive can do exactly this.
git archive --remote=${url} ${branch} ${path}/${file}

feks you can try

`git archive --remote=git@github.com:nodegit/nodegit.git HEAD vendor/openssl/buildinf.h`

This will give you the tar of the file. You can then do this:

`git archive --remote=git@github.com:nodegit/nodegit.git HEAD vendor/openssl/buildinf.h | tar -xO`

This will print the contents of the file. Im using this to fethc jsonfiles from repos during my buildprosess. Currently i have just doen this straight through shelljs, but maybe its faster with this git implementation. And can look smoother in the code.

**Comment by vongohren** [comment]
Closing because found a fix

**Comment by codymullins** [comment]
@vongohren what was the fix?

**Comment by vongohren** [comment]
The fix was what mentioned earlier. Im using this directly through shelljs.
