### ISSUE TITLE
The renamed file is displayed as a deletion and an addition.

### ISSUE THREAD

**Issue by elisei-timofte** [nodegit/nodegit#1228]
I need to proper display a file rename. Is there a way to do that?

**Comment by rcjsuen** [comment]
I'm not sure if anyone can help you without any code to show what it is you've tried. For starters it's not even clear whether you're trying to track renames in the index or in a commit.

**Comment by elisei-timofte** [comment]
Sure, I've forgot the code.

    getDiffs : ->
       @_commit.getDiff()
       .then CommitInfos.processDiffList
       .then (diffInfo) =>
         _.extend @,
           diff      : diffInfo.diffResult
           files     : diffInfo.diffFiles
           fileStats : diffInfo.fileStats

    CommitInfos.processDiffList = (diffList) ->
      diffResult = []
      diffFiles  = []
      fileStats  = added: 0, deleted: 0, modified: 0

      Promise.all diffList.map (diff) ->
        diff.patches().then (patches) ->
          Promise.all patches.map (patch) ->

            diffFiles.push [ patch.oldFile().path(), patch.isAdded() && ++fileStats.added && 'added' || patch.isDeleted() && ++fileStats.deleted && 'deleted' || ++fileStats.modified && 'modified' ]

            patch.hunks().then (hunks) ->
              Promise.all hunks.map (hunk) ->
                hunk.lines().then (lines) ->
                  diffResult.push
                    pathOld   : patch.oldFile().path().trim()
                    pathNew   : patch.newFile().path().trim()
                    header    : hunk.header().trim()
                    diffLines : lines.map (line) ->
                      oldLineNo : line.oldLineno()
                      newLineNo : line.newLineno()
                      operation : String.fromCharCode(line.origin())
                      content   : line.content()

      .then -> {diffResult, diffFiles, fileStats}

**Comment by elisei-timofte** [comment]
Here is the output.

<img width="267" alt="screen shot 2017-02-21 at 12 49 37" src="https://cloud.githubusercontent.com/assets/6162068/23161837/4aa85674-f834-11e6-88b7-9d8286b8bc5f.png">

**Comment by rcjsuen** [comment]
@elisei-timofte You need to "compress" your diff with the [`findSimilar`](https://libgit2.github.com/libgit2/#v0.25.1/group/diff/git_diff_find_similar) function.

```JavaScript
var git = require(".");
var repo_dir = "tmp";
var repo;
var diff;

git.Repository.open(repo_dir)
.then(function(_repo) {
  repo = _repo;
  return repo.getHeadCommit();
})
.then(function(c) {
  return c.getDiff();
})
.then(function(d) {
  diff = d[0];
  var opts = {
    flags: git.Diff.FIND.RENAMES
  };
  return diff.findSimilar(opts);
})
.then(function() {
  console.log(diff.numDeltas());
  var delta = diff.getDelta(0);
  console.log(delta.status() === git.Diff.DELTA.RENAMED);
})
.catch(function(err) {
  console.log(err);
});
```

**Comment by rcjsuen** [comment]
You might also want to check out see #1116.

**Comment by elisei-timofte** [comment]
Thanks @rcjsuen.

**Comment by rcjsuen** [comment]
@elisei-timofte No problem.

Does the suggested code I posted work for you? If yes, could you close this issue? Thanks. :)

**Comment by elisei-timofte** [comment]
I'm working on it. I'll close the issue for now. I'll reopen it if needed. Thanks again.

**Comment by elisei-timofte** [comment]
I've found a better solution for my case. I've used `findSimilar`, but I've got the renamed thing from patches, since I was already maping them. This is my final code. 

Note: See `patch.isRenamed()` in the code below

    getDiffs : ->
      @_commit.getDiff()
      .then CommitInfos.processDiffList
      .then (diffInfo) =>
        _.extend @,
          diff      : diffInfo.diffResult
          files     : diffInfo.diffFiles
          fileStats : diffInfo.fileStats

    CommitInfos.processDiffList = (diffList) ->
      diffResult = []
      diffFiles  = []
      diffs      = []
      fileStats  = added: 0, deleted: 0, modified: 0, renamed: 0

      Promise.all diffList.map (diff) ->
        diffs.push diff

        # squash the addition and deletion of the same file in a rename action
        diff.findSimilar flags: Git.Diff.FIND.RENAMES
      .then ->
        Promise.all diffs.map (diff) ->
          diff.patches().then (patches) ->
            Promise.all patches.map (patch, index) ->

              diffFiles.push  
                oldFilePath: patch.oldFile().path() 
                newFilePath: patch.newFile().path()
                action     : patch.isAdded() && ++fileStats.added && 'added' || patch.isDeleted() && ++fileStats.deleted && 'deleted' || patch.isRenamed() && ++fileStats.renamed && 'renamed' || ++fileStats.modified && 'modified' 

              patch.hunks().then (hunks) ->
                Promise.all hunks.map (hunk) ->
                  hunk.lines().then (lines) ->
                    diffResult.push
                      pathOld   : patch.oldFile().path().trim()
                      pathNew   : patch.newFile().path().trim()
                      header    : hunk.header().trim()
                      diffLines : lines.map (line) ->
                        oldLineNo : line.oldLineno()
                        newLineNo : line.newLineno()
                        operation : String.fromCharCode(line.origin())
                        content   : line.content()

      .then -> {diffResult, diffFiles, fileStats}

Thanks again @rcjsuen. You're hint was a game changer for me.
