### ISSUE TITLE
Clone of NodeGit repository is incomplete

### ISSUE THREAD

**Issue by rcjsuen** [nodegit/nodegit#1233]
1. Run this program.
2. Open the `tmp/vendor/libgit2` folder.
3. It is empty.

```JavaScript
var git = require(".");
var repo_dir = "tmp";

git.Clone("https://github.com/nodegit/nodegit.git", repo_dir, {
  fetchOpts: {
    callbacks: {
    }
  }
})
.then(function() {
  console.log("done");
})
.catch(function(err) {
  console.log(err);
});
```

**Comment by rcjsuen** [comment]
NodeGit doesn't fetch submodules by default so this is why the folder is empty.

**Comment by paymog** [comment]
Is there a flag for fetching submodules?

**Comment by implausible** [comment]
It is unimplemented at the time. You may want to take this upstream to libgit2, as it needs to be implemented there.
