### ISSUE TITLE
Support for Node 7.7.1

### ISSUE THREAD

**Issue by Ajaxy** [nodegit/nodegit#1251]
Hi! I'm running into this issue:

```
/home/zinchuk/www/jsapi/node_modules/nodegit/dist/nodegit.js:15
    throw ex;
    ^

Error: The module '/home/zinchuk/www/jsapi/node_modules/nodegit/build/Release/nodegit.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

When can we wait support for Node 7.7.1 or what should I do to make it myself? Read the "building from source" article, but no idea what to do next.

Thanks!

**Comment by dinoboff** [comment]
Any chance you upgraded node after installing nodegit? Try reinstalling nodegit or all your dependencies.

**Comment by Ajaxy** [comment]
Done, many times, no luck.

**Comment by rcjsuen** [comment]
Which part did you get stuck on when you were trying to build from source?

**Comment by Ajaxy** [comment]
I just didn't get, what to do next, how to use the new build in my project?

**Comment by rcjsuen** [comment]
If you're just doing something quick and dirty, you can just replace your

**Comment by rcjsuen** [comment]
Sorry, clicked the wrong button...

If you're just doing something quick and dirty, you can just replace your `/home/zinchuk/www/jsapi/node_modules/nodegit/build/Release/nodegit.node` file with the one from your build in the `dist/` folder.

**Comment by rcjsuen** [comment]
@Ajaxy There should be NodeGit 0.19.0 binaries that are compatible with Node 7.7.x available now.

**Comment by Ajaxy** [comment]
Thank you!

сб, 22 апр. 2017 г. в 16:52, Remy Suen <notifications@github.com>:
