### ISSUE TITLE
Nodegit not compatible with recent node version

### ISSUE THREAD

**Issue by morlauth** [nodegit/nodegit#1259]
I am using node version 7.6.0 on Mac OS X. I installed the latest version of nodegit: v.0.18.0 but I get an error.
The error states that my version of node is not compatible with this module. Here is the message:
`Error: The module '/Users/tinocaer/Pipeline/node_modules/nodegit/build/Release/nodegit.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).`

How can I fix this?

Thanks

**Comment by johnhaley81** [comment]
I don't know why your version of node 7.6.0 is _not_ 51 because it very much should be.

```
johnhosx :: ~ » node --version                                                                                                                         1 ↵
v7.6.0
johnhosx :: ~ » node
> process.versions.modules
'51'
>
```

Are you compiling against electron or something else?

**Comment by morlauth** [comment]
I am using electron.

**Comment by morlauth** [comment]
Electron says it uses version 53. I typed what you type into the console and I got the same results, so its definitely electron.

**Comment by johnhaley81** [comment]
Ahh ok cool, that makes a lot more sense. What are you using to rebuild native node modules?

**Comment by morlauth** [comment]
I'm just using the npm rebuild... I haven't come into this issue before.

**Comment by johnhaley81** [comment]
You can add a `.npmrc` to the root of your electron project that will force native node modules to build against a specific platform. 

`.npmrc` Ex:

```
runtime = electron
target = 1.6.2
target_arch = x64
disturl = https://atom.io/download/atom-shell
```

**Comment by morlauth** [comment]
It worked! Thanks!
