### ISSUE TITLE
setUpstream doesn't work

### ISSUE THREAD

**Issue by ghost** [nodegit/nodegit#1261]
Hey guys. 

I'm messing around with the nodegit and trying to make it create new branch and push to the upstream. Unfortunately it doesn't work for some reason. 

```javascript
'use strict'
import NodeGit from 'nodegit';
import path from 'path';

const repoPath = path.resolve(__dirname, 'test/.git');

const stat = {};
NodeGit.Repository.open(repoPath).then(repo => {
    stat.repo = repo;
    console.log('fetchAll');
    return stat.repo.fetchAll({
        callbacks: {
            credentials: function (url, userName) {
                console.log('url userName', url, ">>> ", userName, " <<<");
                return NodeGit.Cred.sshKeyFromAgent(userName);
            }
        }
    });
}).then(() => {
    stat.repo.getBranch('siela')
        .then(ref => {
            NodeGit.Branch.delete(ref);
        }).catch(err => {
            console.log('err:', err);
        });
}).then(() => {
    return stat.repo.getMasterCommit();
})

.then(masterCommit => {
    return stat.repo.createBranch('siela', masterCommit)
        .then(ref => {
            return ref;
        });
})

.then(ref => {
    NodeGit.Branch.setUpstream(ref, 'origin siela')
        .then(() => {
            stat.repo.checkoutBranch(ref);
        })
        .catch(err => { console.log(err); });
})

.catch(err => { console.log(err) });
```

Unfortunately all tests ends with:

> { Error: cannot set upstream for branch 'siela'
    at Error (native) errno: -3 }

**Comment by johnhaley81** [comment]
`origin siela` isn't a valid ref name. Try `refs/remote/origin/siela`

**Comment by wsielski** [comment]
I've tried `refs/remote/origin/siela`, `origin/siela`, `siela`, `origin siela` neither is working and all  ends with same error:

> { Error: cannot set upstream for branch 'siela'
    at Error (native) errno: -3 }

**Comment by rcjsuen** [comment]
@wsielski Does `refs/remotes/origin/siela` actually exist?

Can you try `setUpstream` and setting the upstream branch to `null` and then setting it back to `origin/master`? Do you get the error for `origin/master`?

**Comment by wsielski** [comment]
@rcjsuen setting `null` upstream on newly created local branch ends with this error

> { Error: could not find key 'branch.siela.remote' to delete
    at Error (native) errno: -1 }

Setting the upstream to `origin/master` works fine.

`refs/remotes/origin/siela` does not exists. What I'm trying to achieve here is exactly this chain of commands:

```
# creating local branch from source origin/master
git checkout -b siela origin/master

# create remote branch and set upstream 
git push -u origin siela
```

**Comment by rcjsuen** [comment]
Yeah, the branch doesn't exist so you can't set a tracking branch.

Push first with a `siela:refs/remotes/origin/siela` refspect to create the branch on your remote before trying to call `setUpstream`.

**Comment by rcjsuen** [comment]
Sorry, I think I wrote the wrong thing [earlier](https://github.com/nodegit/nodegit/issues/1261#issuecomment-290018621). You need to push `siela:/refs/heads/siela` first.

**Comment by rcjsuen** [comment]
Please show your code.

**Comment by rcjsuen** [comment]
@TPiddy Please share your full code.

**Comment by TPiddy** [comment]
`const remoteBranch = '${REMOTE_ORIGIN}/${branch}';
    let commit = await repo.getBranchCommit(fromBranch);
    let ref = await repo.createBranch(branch, commit, 1); // ref.name() is refs/heads/branch
    await repo.checkoutBranch(branch);
    const pushResult = await pushToRepo(repo, [`${ref.name()}:${ref.name()}`]); // creates refs/remotes/origin/branch
    return Branch.setUpstream(ref, remoteBranch)`

**Comment by rcjsuen** [comment]
@TPiddy Can you try using `Branch.setUpstream(ref, 'origin/branch')`?

**Comment by TPiddy** [comment]
@rcjsuen That worked! Thanks so much!

**Comment by muhonglong** [comment]
`Branch.setUpstream(ref, 'origin/branch')` worked only when the ref is checked out.
In other cases, `Branch.upstream` returns error even though no err in `setUpstream`.
