### ISSUE TITLE
how do i use blame?

### ISSUE THREAD

**Issue by malickz** [nodegit/nodegit#1264]
i tried doing the blame for a file using Blame.file() but it returns me another blame object rather than the actual git blame output. please correct me where im using it wrong.
```
       Git.Repository.open("./tmp").then((repo) => {
          Git.Blame.file(repo, "package.json", "-p").then((b) => {
            console.log(b);
          });
        });
```

**Comment by rcjsuen** [comment]
This is working as intended. You are supposed to use the [`BlameHunk`](http://www.nodegit.org/api/blame_hunk) objects in the returned [`Blame`](http://www.nodegit.org/api/blame/) object and generate the output yourself.

```JavaScript
var count = 1;
for (var i = 0; i < blame.getHunkCount(); i++) {
    var hunk = blame.getHunkByIndex(i);
    for (var j = 0; j < hunk.linesInHunk(); j++) {
        console.log(count + ":" + hunk.finalCommitId().toString().substring(0, 8));
        count++;
    }
}
```

If you have further questions, please ask them in the `#nodegit` [Slack channel](http://slack.libgit2.org/).
