### ISSUE TITLE
Passing CloneOptions

### ISSUE THREAD

**Issue by cazgp** [nodegit/nodegit#127]
I tried using a javascript object, and various combinations of arrays and strings.

I then tried instantiating `git.CloneOptions`, but it was complaining about needing `git_clone_options`. There appears to be a libgit2 macro `GIT_CLONE_OPTIONS_INIT` but I've no idea how to call it.

Any help / pointers would be great, thank you.

**Comment by danielbeeke** [comment]
Git.Clone(commit.repo, builder.getSourcePath(commit), { checkoutBranch: commit.branch })
