### ISSUE TITLE
Force Push

### ISSUE THREAD

**Issue by jhamet93** [nodegit/nodegit#1270]
I was looking through the examples and some of the previous options and I was curious how to perform a force push.

I'm use the Remote.push method and none of the options passed to this function seemed like a flag to add the force flag.

Is this feature currently supported in nodegit?

**Comment by rcjsuen** [comment]
It's supposed to be defined in a `Refspec` but I don't think there is a way to set this information at the moment. There is a [`force()`](http://www.nodegit.org/api/refspec/) function but that's only for retrieving the configuration and not for setting the configuration.

**Comment by jhamet93** [comment]
Would this be a valid thing to create a pull request for ? 

In the script I was writing, I need to force push to a branch so if this a reasonable feature, I can take a stab at this.

**Comment by rcjsuen** [comment]
Yes. If you'd like to submit a pull request for this, @jhamet93. It would certainly be most welcome.

**Comment by maxkorp** [comment]
Forcepush is definitely supported, it's in use in GitKraken. I don't have the source to look at that anymore though. 

CC @johnhaley81

**Comment by johnhaley81** [comment]
You use refspecs to do it. Your refspec for force pushing must include a `+` at the start.

ex: `+refs/head/master:refs/head/master`

**Comment by jhamet93** [comment]
@johnhaley81 

Yup, that was it. Thanks!

**Comment by a7madgamal** [comment]
would be nice to add this to the docs :)
