### ISSUE TITLE
Join slack instructions not working

### ISSUE THREAD

**Issue by aslakhellesoy** [nodegit/nodegit#1284]
The [README](https://github.com/nodegit/nodegit#have-a-problem-come-chat-with-us) says to join the `#nodegit` channel, but after joining libgit2.slack.com only the read-only `#announcements` channel is visible.

**Comment by rcjsuen** [comment]
@aslakhellesoy You should be able to just join as-is via the `/join` command. Anyway, I've invited you to the channel. Are things looking okay on your end?

**Comment by rcjsuen** [comment]
Closing as this was resolved on Slack.
