### ISSUE TITLE
IndexEntry mtime and ctime is 0?

### ISSUE THREAD

**Issue by zhaopengme** [nodegit/nodegit#1299]
code 

```
if (nodegit.Index.entryIsConflict(entry)) {
  console.log(entry.mtime.seconds());
  console.log(  entry.ctime.seconds());
}
```

![image](https://user-images.githubusercontent.com/1415418/26945211-9c007668-4cbd-11e7-883a-09d7fc7bd934.png)

I want to fixed conflict, and  use the mtime or ctime to determine which file is up to date.

but now IndexEntry mtime and ctime is 0?

**Comment by rcjsuen** [comment]
I was able to reproduce this bug but it's not immediately obvious to me if this is a NodeGit bug or a libgit2 bug.

**Comment by rcjsuen** [comment]
@zhaopengme Someone encountered the same problem with [libgit2](https://github.com/libgit2/libgit2/issues/3940#issuecomment-250442473) so it doesn't seem like an issue with NodeGit's bindings.

**Comment by rcjsuen** [comment]
Git doesn't seem to store this information when it creates the conflict. I don't think there is a bug in NodeGit here, @zhaopengme.
```Shell
$ git status
On branch ours
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:   everyonesFile.txt

no changes added to commit (use "git add" and/or "git commit -a")

$ git ls-files --debug
everyonesFile.txt
  ctime: 0:0
  mtime: 0:0
  dev: 0        ino: 0
  uid: 0        gid: 0
  size: 0       flags: 1000
everyonesFile.txt
  ctime: 0:0
  mtime: 0:0
  dev: 0        ino: 0
  uid: 0        gid: 0
  size: 0       flags: 2000
everyonesFile.txt
  ctime: 0:0
  mtime: 0:0
  dev: 0        ino: 0
  uid: 0        gid: 0
  size: 0       flags: 3000
```

**Comment by ethomson** [comment]
Indeed, git does not store the information...  it's not even clear to me what time it would store?  Would it store the time of the commit?  Or the time the file was introduced on that branch?  The former is trivial to figure out already (you know the commits being merged).  The latter is potentially very time consuming, walking history.

I'm not sure what you mean by "up to date"?  Maybe there's a better solution to your problem, @zhaopengme
