### ISSUE TITLE
god never install success

### ISSUE THREAD

**Issue by ijry** [nodegit/nodegit#1300]
Windows 10  never and never    npm install nodegit  successed 
![qq 20170609133752](https://user-images.githubusercontent.com/3102798/26962467-dc422c70-4d18-11e7-8903-1307716540e0.png)

**Comment by rcjsuen** [comment]
@ijry You appear to be using Node 8. NodeGit currently does not compile on Node 8. See #1295.

**Comment by ijry** [comment]
when we can get a fix version , thks?

**Comment by rcjsuen** [comment]
> when we can get a fix version , thks?

I'm not sure if anyone is actively working on this at the moment. I suggest you keep tabs on #1295 and #1298.
