### ISSUE TITLE
 merge question.

### ISSUE THREAD

**Issue by zhaopengme** [nodegit/nodegit#1302]
I have a merge question.
e.g.

remote/master modify A.txt
master modify A.txt

merge.merge('master','remote/master')

A.txt is a conflict file.

I want to auto merge,and use the lastest file.

so how to do ?

thanks!

**Comment by rcjsuen** [comment]
The [`merge-with-conflicts.js`](https://github.com/nodegit/nodegit/blob/master/examples/merge-with-conflicts.js#L173-L175) example kind of does this already. Just override the content with what you want (in your case the local version) instead.
