### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by ijry** [nodegit/nodegit#1304]
<img width="485" alt="2017-06-14 1 18 46" src="https://user-images.githubusercontent.com/3102798/27116706-51c7df9a-5105-11e7-98e9-35ffbf278ff7.png">

**Comment by rcjsuen** [comment]
This is generally an indication that the compiled NodeGit binary you're using was built with a Node/v8 version that doesn't match the version of Node/v8 that you're using to run your application.

#1259 might be of interest to you.

Please reach out to the NodeGit team via #nodegit on [Slack](http://slack.libgit2.org/) for further assistance.
