### ISSUE TITLE
NODE_MODULE_VERSION error

### ISSUE THREAD

**Issue by Viltaria** [nodegit/nodegit#1307]
The module '/workspace/code/repo-name/node_modules/nodegit/build/Release/nodegit.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

npm rebuild and npm install didn't solve this issue, any ideas?

**Comment by zhaopengme** [comment]
remove  `node_modules/nodegit/build/*`  
and `npm rebuild`   .
pls try.

**Comment by Viltaria** [comment]
That seemed to work, thanks!
