### ISSUE TITLE
enable Index.addAll and related

### ISSUE THREAD

**Issue by fyockm** [nodegit/nodegit#131]
`tree.diffWorkDir` only returns changes to existing files. It does not seem return any new files added. Basically, I want something that will act like `git add -A .` from the base working directory. 

Also, `tree.diffWorkDir` only seems to work once there's been an initial commit. Is there a better way to add all the files in a directory to the index, than walking recursively through the directory structure and calling `index.addByPath` for each file?

**Comment by johnhaley81** [comment]
This is being implemented now in #413

**Comment by johnhaley81** [comment]
This is now merged into master.
