### ISSUE TITLE
How to sort tag list by create time ?

### ISSUE THREAD

**Issue by huoteng** [nodegit/nodegit#1314]
```
Git.Repository.open(dir).then(Git.Tag.list);
```
As above, code return the tag name array, not the tag entity array. How can I get the time of a tag ?

**Comment by rcjsuen** [comment]
I think you have to lookup each tag manually and then retrieve its timestamp.

**Comment by huoteng** [comment]
I guess I missing something, #298 may can solve my problem.

**Comment by gaspard** [comment]
@huoteng You can look at if you are stuck (Lua API)[https://libgit2.github.com/luagit2/modules/Reference.html#Reference.lookup] (contains more information on API).

What you want is this:

```js
nodegit.Repository.open(repoPath).then(repo =>
    nodegit.Tag
      .list(repo)
      .then(list =>
        Promise.all(
          list.map(tagName =>
            nodegit.Reference.lookup(repo, `refs/tags/${tagName}`)
            .then(ref => nodegit.Commit.lookup(repo, ref.target()))
            .then(commit => ({
              tag: tagName,
              date: commit.date().toJSON(),
            }))
          )
        )
      )
      .then(tags => tags.sort((a, b) => (a.date < b.date ? -1 : 1)))
```

**Comment by huoteng** [comment]
@gaspard Thank you so much. I'll try it out right now.

**Comment by douglasjunior** [comment]
I think it would be great to have some option like ["last_git_tag" from "fastlane"](https://docs.fastlane.tools/actions/last_git_tag/).

Having to lookup through all the tags to find the most recent one, tends to be problematic over time.
