### ISSUE TITLE
"examples/add-and-commit.js" throw "Error: Invalid path: xxx" on windows

### ISSUE THREAD

**Issue by BoyBoBo** [nodegit/nodegit#1339]
os: windows 7
nodegit: 0.18.3

This line will throw "Error: Invalid path: xxx"
> index.addByPath(path.join(directoryName,  fileName))

I changed it to the following, it's ok
> index.addByPath(directoryName + '/' + fileName)

**Comment by rcjsuen** [comment]
Thank you for the bug report, @BoyBoBo! I have opened #1346 which fixes the problem.
