### ISSUE TITLE
Cloning the latest tag of a repository

### ISSUE THREAD

**Issue by AlexandruDoda** [nodegit/nodegit#1343]
Hey,

Is there any way to clone a specific tag instead of branches in Nodegit? 
And also, is it possible to clone the latest tag of a repository?

Trying to clone the latest stable version of Wordpress for my application to a local server and could only figure how to specify branches, and not tags.

Cheers!

**Comment by saper** [comment]
Can you clone "the latest tag" with the normal git command line?

**Comment by AlexandruDoda** [comment]
I've gotta have it built in to the app because it pulls the repo and stores it on the server so it can be manipulated / downloaded.

<img width="1048" alt="screenshot 2017-08-05 23 32 44" src="https://user-images.githubusercontent.com/8274669/28998549-68efd6c8-7a36-11e7-8d15-6fe23abce186.png">

**Comment by saper** [comment]
well, you need to invent it, then... There are GitHub APIs to work with releases, but that is out of scope of node-git.
