### ISSUE TITLE
cannot create a tree from a not fully merged index

### ISSUE THREAD

**Issue by 6174** [nodegit/nodegit#1345]
When merge two conflicted refs 

```js
try {
  await repo.mergeBranches(branchName, `origin/${branchName}`);
} catch (err) {
  if (err instanceof nodegit.Index) {
    const index = err 
    await index.writeTreeTo(repo)
    if (index.hasConflicts()) {
      console.log("hasConflicts")
    }
    return
  }
}
```

error show "cannot create a tree from a not fully merged index", and nothing changed in working directory

How can I write merge result to working directory?

**Comment by rcjsuen** [comment]
Move your `index.hasConflicts()` call up. Does your index have conflicts?

**Comment by 6174** [comment]
@rcjsuen  mergeBranches method throw an err , and the error is instanceof nodegit.Index , so it's the only way to call hasConflicts in catch section

**Comment by rcjsuen** [comment]
@6174 Yes, I understand that. Does `index.hasConflicts()` return `true`?

**Comment by 6174** [comment]
@rcjsuen  Yes

**Comment by rcjsuen** [comment]
@6174 So there's your problem. The merge won't happen because there are conflicts between your two branches. If you want to force a merge into your working directory, use `Merge.merge`.

**Comment by 6174** [comment]
@rcjsuen  

I change to `Merge.merge` method , But can't save to working directory either, `index.hasConflict()` return `0` 

```js
try {
      const theirHead = await nodegit.AnnotatedCommit.fromRef(repo, remoteRef);
      await nodegit.Merge.merge(repo, theirHead, null, {
        checkoutStrategy: nodegit.Checkout.STRATEGY.FORCE,
      });
      const index = await repo.refreshIndex()
      if (index.hasConflicts()) {
        console.log("has conflicts")
      }
} catch(err){
 throw err
}
```

I use `git status` the result is 
```
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working tree clean
```

**Comment by rcjsuen** [comment]
@6174 What is the return code from `Merge.merge`?

Also, do you get a merge conflict if you try to merge from the command line?

**Comment by 6174** [comment]
@rcjsuen  The return code is `-14`, and there is a conflict.

**Comment by rcjsuen** [comment]
@6174 `-14` indicates that your Git repository has been [locked](https://github.com/libgit2/libgit2/blob/a9d6b9d529daa920b558ee3f34151422d10bc95e/include/git2/errors.h#L42). I suggest you resolve that first before trying anything else.

**Comment by 6174** [comment]
@rcjsuen thx, after I remove `.git/index.lock`, `Merge.merge` worked
