### ISSUE TITLE
Error: callback failed to initialize SSH credentials errno: -1

### ISSUE THREAD

**Issue by ftdube** [nodegit/nodegit#1357]
Hi!

I'm trying to use nodegit to clone a repository located on a self-hosted GitLab server and get the list of tags that are available.  Basically I'm trying to do, using typescript : 

```
let git = require('nodegit');
let cloneOptions = {
    fetchOpts: {
        callbacks: {
            certificateCheck: () => { return 1; },
            credentials: (url: string , userName: string) => {
                return Cred.sshKeyFromAgent(userName);
            }
       }
   }
};

this.git.Clone(packageConfig.url, packageConfig.name, cloneOptions)
    .then((repository: Repository) => {
        Tag.list(repository)
           .then((tags) => {
               // Use Tags
           })
           .catch((err: any) => {
                console.log(err);
           });
   })
   .catch((err: any) => {
       console.log(err);
    });
```

However, each time I get to the cloning part, I get the following error : 
_Error: callback failed to initialize SSH credentials errno: -1_

I am working on Windows,
Node : 4.7.0
Nodegit : 0.20.1
types/nodegit : 0.18.1

**Comment by saper** [comment]
How are you authenticating against the git remote repository server?

**Comment by ftdube** [comment]
Thank you for the help, I ended up succeeding by using Cred.sshKeyNew
