### ISSUE TITLE
Revwalk.getCommits always returns empty array

### ISSUE THREAD

**Issue by mn113** [nodegit/nodegit#1358]
I'm trying to use this function to simply count commits in a repo. It's a little tricky since there is scant documentation.

My code:
```
NodeGit.Repository.open(repo_path)
.then(function(repository) {

	var revwalk = repository.createRevWalk();
	
	var totalCommits = revwalk.getCommits(MAX_COMMITS)
	.then(arrayCommit => {
		console.log(arrayCommit);	// []
		return arrayCommit.length;
	});

});
```
`[]` is logged to the console. I'm able to open the repos and access other details inside them. They do have commits. It's just the RevWalk that does nothing.

How is one supposed to use this function? It's all very mysterious.

**Comment by rcjsuen** [comment]
@mn113 Try this?
```JavaScript
var NodeGit = require(".");
var walker = null;
return NodeGit.Repository.open(".")
	.then(function (repository) {
		walker = repository.createRevWalk();
		return repository.getHeadCommit();
	})
	.then(function (commit) {
		walker.sorting(NodeGit.Revwalk.SORT.TIME);
		walker.push(commit.id());
		return walker.getCommits(10)
	})
	.then(function (commits) {
		console.log(commits);
	});
```

**Comment by mn113** [comment]
I got somewhere by adding the following before revwalk.getCommits:
```
	var revwalk = repository.createRevWalk();
	revwalk.sorting(NodeGit.Revwalk.SORT.REVERSE);
	revwalk.pushHead();	// places us at the last commit
```
I am now able to count commits from the head backwards. Still not sure if this is the recommended way.

It was basically trial-and-error of the functions in Revwalk. I suggest that improving documentation here should be a priority.

**Comment by mn113** [comment]
@rcjsuen Thanks, didn't see your response in time but it looks good. It was a case of setting the sorting and pushing a starting id to my walker. It was the `push` terminology that threw me off, what with it having another git meaning.

**Comment by rcjsuen** [comment]
@mn113 I am closing this issue as it seems your problem has been resolved based on [your comment](https://github.com/nodegit/nodegit/issues/1358#issuecomment-324469743). Please feel free to reopen it if otherwise.

**Comment by hemanth-gopi** [comment]
As @mn113 mentioned, the documentation is still a hit and miss even in 2020. Faced the same problem while trying to use nodegit for a Git Gui client in electron. Consider improving the documentation.
