### ISSUE TITLE
Add more platforms to the setup

### ISSUE THREAD

**Issue by Fohlen** [nodegit/nodegit#1362]
Heya guys.
At @inexorgame we are starting to rely heavily on `nodegit`
Is there any way that more platforms will be supported in the future by nodegit?
As far as I can tell, Docker could be used with a set of base images just to do that easily.

**Comment by rcjsuen** [comment]
@Fohlen When you say "more platforms", what are you referring to exactly? More operating systems (say NetBSD and OpenBSD)? More Linux distributions? More versions of existing supported operating systems?

How can Docker images be used to easily do this?

**Comment by saper** [comment]
@Fohlen Docker will not help whenever a different kernel is required.

**Comment by Fohlen** [comment]
Firstly, I apologize for the rather vague ticket description.

@rcjsuen with more platforms, in specifically, I imagine:
- more versions of `Node.js` (newer ones, if possible)
- more versions of `npm` (the 5 series in particular)
- more linux distributions, such as Cent OS and Arch Linux
- the latest version of OSX (since it is building manually on Mac currently)
- Windows 8 & 10 (AppVeyor)

Over at @inexorgame we use a combination of traditional bash scripts and Docker with different base images to build the same thing under different platforms. This approach may be comfortable for `nodegit`, or may not.

Commenting on @saper, this is true. OpenBSD/NetBSD might be needed to be build on some private Jenkins, if there is enough user demand.

If necessary, I think we can also add some templates in a PR, maybe they come in handy.

**Comment by rcjsuen** [comment]
@Fohlen I guess when you say "the setup" you mean for the NodeGit binaries to be available via installation from npm without having to manually compile NodeGit, correct?

From looking at the latest builds, we do currently build on Node 8.4.0 and npm 5.3.0 on Travis CI and Node 8.3.0 and npm 5.3.0 on AppVeyor. It seems like Travis CI is building on OS X El Captain (and not macOS Sierra). It seems you have to either use [Windows Server 2012 R2 or Windows Server 2016](https://www.appveyor.com/docs/build-environment/#operating-system) on AppVeyor so there's not much we can do there I think?

As for Cent OS and Arch Linux, there are several open issues about those two (as well as other) Linux distributions so the demand is certainly there.

**Comment by rsmarples** [comment]
There are some outstanding pull requests for better BSD platform support - namely #1237, #1344 and #1374.

With these changes, nodegit compiles at least on modern BSD platforms and I can vouch for NetBSD.

**Comment by Fohlen** [comment]
I have to report that according to our CI only

- `Node 6.11.4, 7.10.1` on `Ubuntu Trusty`, `OSX` and `Windows` are supported.
We tested a couple more of platforms but as it seems currently `Node >7` and other distros than `Trusty` are unsupported.

**Comment by Fohlen** [comment]
https://github.com/nodegit/nodegit/blob/master/.travis.yml#L17

What's the issue here to:

- support the actual latest versions of Node 6 and 7 or support even more platforms
- if you're concerned about your AWS storage, you should consider moving your binaries to [bintray](https://bintray.com). They offer up to 1 TB for open source projects
- additionally:
 - you should use Docker to build (!at least) for Ubuntu Xenial. Seriously Trusty Tahr is no more platform to target end users (maybe servers, but not end users)

As for the Windows and OSX support, there should be more node versions covered as well. Anyhow, nvm and windows-nvm can easily be used here..

**Comment by Croydon** [comment]
I guess this can be closed in favor of #1298

**Comment by Fohlen** [comment]
I will be closing this. It is insane that such a huge project does not build for the `LTS` version of node.

**Comment by rcjsuen** [comment]
@Fohlen NodeGit currently builts for Node.js v6, v8, and v10.

https://github.com/nodegit/nodegit/blob/1bc53bff8e2e22815c2103372baf14e4e64a5576/.travis.yml#L23-L26
