### ISSUE TITLE
how to get un push commit?

### ISSUE THREAD

**Issue by zhaopengme** [nodegit/nodegit#1375]
I want to know how many of commis are not pushed to the repository, just like using `git status`.
![image](https://user-images.githubusercontent.com/1415418/30510641-7a50bcb8-9afa-11e7-82d4-0d2e43905529.png)

**Comment by rcjsuen** [comment]
Maybe [this](http://www.nodegit.org/api/graph/#aheadBehind) can help you?

**Comment by zhaopengme** [comment]
thanks!Solved my big trouble.
