### ISSUE TITLE
Unable to git clone https://chromium.googlesource.com/v8/v8

### ISSUE THREAD

**Issue by john-yan** [nodegit/nodegit#1376]
Hi,

git clone https://chromium.googlesource.com/v8/v8 seems to be hang and unsuccessful.

```javascript
var git = require("nodegit");
 
 console.log("Start: git clone https://chromium.googlesource.com/v8/v8");
 git.Clone("https://chromium.googlesource.com/v8/v8", "v8").then(function (repo) {
     console.log("Done.");
   });
```

Environment:

root@cb707fb2c168:/project/src/monitor# uname -a      
Linux cb707fb2c168 4.9.41-moby #1 SMP Wed Sep 6 00:05:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
root@cb707fb2c168:/project/src/monitor# node -v
v6.11.3

OS: Ubuntu

**Comment by john-yan** [comment]
nodegit@0.20.2

**Comment by john-yan** [comment]
same issue with node v8.5.0

**Comment by rjmunro** [comment]
Add a `.catch()` and see if you get an error.

**Comment by john-yan** [comment]
Hello @rjmunro , sorry that I was wrong about this on node v8.5. It hangs for a long time, but it finally finishes with success.
