### ISSUE TITLE
[nodegit] ERROR - the latest libstdc++ is missing on your system!

### ISSUE THREAD

**Issue by punter82** [nodegit/nodegit#1379]
Hi Everyone
I have a wierd error trying to install nodegit on Redhat linux.
It is an amazon EC2 linux box. uname -a gives Linux ip-10-1-3-124.ec2.internal 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

Also it says i have the latest 
yum install libstdc++
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Package libstdc++-4.8.5-16.el7.x86_64 already installed and latest version
Nothing to do

any light on this would be appreciated. Thanks in advance

**Comment by punter82** [comment]
I figured how to make this work. We can close this

**Comment by akinza** [comment]
@punter82 Can you please state how did u fix the issue.

**Comment by punter82** [comment]
@akinza  I switched to Ubuntu. With the previous linux server i had so many issues and ubuntu comes with gcc 4.9 series which helps with nodegit.

**Comment by diman82** [comment]
Any updates on this issue? It has been opened for almost 2 years by now..

**Comment by punter82** [comment]
Hey @diman82 as mentioned in my above comment i switched to Ubuntu. We can close this issue for now.

**Comment by diman82** [comment]
Hi @punter82 thanks, but it isn't really a solution :)

**Comment by punter82** [comment]
Hi @diman82  of course not :) But i closed it since i was not using amazon EC2 linux box.
