### ISSUE TITLE
Nodegit Preinstall error on Redhat linux Amazon EC2

### ISSUE THREAD

**Issue by punter82** [nodegit/nodegit#1380]
Hi, Need some help here. 

{ Error: Command failed: /cms/node/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/cms/node/node_modules/nodegit/vendor/openssl/openssl
/cms/node/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/cms/node/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/cms/node/node_modules/nodegit/vendor/libssh2':
configure: error: C compiler cannot create executables
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
  killed: false,
  code: 77,
  signal: null,
  cmd: '/cms/node/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/cms/node/node_modules/nodegit/vendor/openssl/openssl' }
/cms/node/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/cms/node/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/cms/node/node_modules/nodegit/vendor/libssh2':
configure: error: C compiler cannot create executables
See `config.log' for more details

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /cms/node/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/cms/node/node_modules/nodegit/vendor/openssl/openssl
/cms/node/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/cms/node/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/cms/node/node_modules/nodegit/vendor/libssh2':
configure: error: C compiler cannot create executables
See `config.log' for more details

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
  killed: false,
  code: 77,
  signal: null,
  cmd: '/cms/node/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/cms/node/node_modules/nodegit/vendor/openssl/openssl' }

==============================================
I did install gcc 4.9 on the box and did a symlink.
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc492/libexec/gcc/x86_64-unknown-linux-gnu/4.9.2/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc-4.9.2/configure --disable-multilib -prefix=/usr/local/gcc492 --with-gmp-lib=/usr/local/lib --with-mpfr-lib=/usr/local/lib --with-mpc-lib=/usr/local/lib
Thread model: posix
gcc version 4.9.2 (GCC) 
ln -s /usr/local/gcc492/bin/gcc /bin/gcc

**Comment by punter82** [comment]
Planning to change the OS as i am running out of options.. Will switch to Ubuntu and give it a shot again

**Comment by arnm** [comment]
still an issue
