### ISSUE TITLE
s3 bucket is not accepting new prebuilt binaries

### ISSUE THREAD

**Issue by implausible** [nodegit/nodegit#1392]
Users will currently be unable to access prebuilt binaries for future builds. Current workaround is to build from source.

**Comment by a-teammate** [comment]
so this means there is no way for users without C build system to use nodegit currently?

**Comment by implausible** [comment]
Axosoft is going to end up picking up an s3 bin to replace the old servers. Will update this issue when I'm done.

**Comment by rcjsuen** [comment]
Thank you Axosoft for doing this!

**Comment by lashower** [comment]
As a temporary work around, I think there is a way to share distributions through GitHub. Can't remember how to do that yet.

**Comment by Mklueh** [comment]
It seems to work again. Thank you=)

**Comment by mojavelinux** [comment]
Why are you not hosting the binaries on Bintray? It seems like it would be much more reliable, less of a hassle, and not cost a dime. This is exactly the use case Bintray was designed to solve. (Btw, I do not work for Bintray).

https://bintray.com/

**Comment by mbfisher** [comment]
Any update on this? Thanks!

**Comment by implausible** [comment]
From 0.21.0 forward prebuilts are up again.

**Comment by hernandev** [comment]
IPFS :) indestructible hosting :)
