### ISSUE TITLE
(Bug) Revert.revert requires a RevertOptions parameter

### ISSUE THREAD

**Issue by ecoulson** [nodegit/nodegit#1403]
Revert.revert requires a Revert Options parameter or a null to be passed into the method unlike other methods such as Merge.merge https://github.com/nodegit/nodegit/blob/6ff67a883c66a1cee23feb53b5f82c36c8a4df04/lib/merge.js#L28-L39
and Revert.commit https://github.com/nodegit/nodegit/blob/6ff67a883c66a1cee23feb53b5f82c36c8a4df04/lib/revert.js#L16-L29. 

When a RevertOptions parameter is not passed into Revert.revert this error is thrown
`(node:46081) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Callback is required and must be a Function.` when talking with @rcjsuen in slack he noticed that the error was misleading and originated from the c++ layer.

Here is the code that threw this error
```
/**
 * @description reverts the git branch to the requested commit
 * @param {String} hash represents the hash of the commit
 * @async
 */
async function revert(hash) {
	return new Promise(async function handlePromise(resolve, reject) {
		try {
			let repo = await openRepository(sitePath);

			logger.info('Setting new head...');
			let newHead = await repo.getCommit(hash);

			logger.info('Reverting...');
			await Git.Revert.revert(
				repo,
				newHead,
			);
			return resolve();
		} catch(err) {
			logger.error(`${err}`);
			return reject(err);
		}
	});
}
```

**Comment by ethomson** [comment]
That error's not coming from libgit2, we don't have any notion of promises.  😀

**Comment by rcjsuen** [comment]
@ethomson Yeah, it's coming from NodeGit's generated C++ layer. Don't worry, it's not an issue with libgit2. :)

**Comment by ethomson** [comment]
Thanks @rcjsuen for the clarification.  😁
