### ISSUE TITLE
ERR! Tried to download(403):

### ISSUE THREAD

**Issue by jhuseinovic** [nodegit/nodegit#1405]
$ npm install nodegit

> nodegit@0.18.3 install /home/ubuntu/wave/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.18.3-node-v57-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.18.3 and node@8.9.1 (node-v57 ABI) (falling back to source compile with node-gyp)

**Comment by opeltre** [comment]
Same error with npm 4.6.0, node 9.2.0 on arch linux, but nodegit@0.20.3 

But surprisingly install went through on my local machine with npm 4.4.2, node 8.6.0 same OS, after installing `libcurl-gnutls` and `libidn2` ... of @0.20.3 as well (?!)

**Comment by Mklueh** [comment]
Same here when using meteor-launchpad

**Comment by implausible** [comment]
https://github.com/nodegit/nodegit/issues/1392
