### ISSUE TITLE
nodegit.s3.amazonaws.com 403

### ISSUE THREAD

**Issue by reggi** [nodegit/nodegit#1409]
[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
[nodegit] Running install script
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.20.3-node-v59-darwin-x64.tar.gz

it seems that this is unavailable

https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.20.3-node-v59-darwin-x64.tar.gz

**Comment by maxkorp** [comment]
Just means the prebuilt binary doesnt exist, probably not in the build matrix if I had to guess. 

Does it fail to install entirely, or just fail to download?

**Comment by opeltre** [comment]
see #1405 as well...
On linux 403 is at 
https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.20.3-node-v59-linux-x64.tar.gz

And node-pre-gyp fails to build
https://github.com/nodegit/nodegit/files/1524316/log.txt

**Comment by Mklueh** [comment]
As it doesn´t work for weeks now, is there at least a workaround to include it manually?

**Comment by Mklueh** [comment]
I´ve downgraded to Node 8.9.1 - same problem.

I wish one of you could really help us out, there are several issues related to this problem now without a solution/workaround.

#1382
#1385
#1390
#1405
#1409

**Could somebody responsible for the archives please tell us if you are working on it, or what problems you are facing that hinders you fixing it?**

Thank you in advance

**Comment by cjhoward92** [comment]
You need to build it from source. The pre-builts are all jacked up at the moment. There is some issue with the server that manages pre-builts and we do not have ownership of this server, so we have not figured out what to do quite yet. @implausible can shed some more light on it, but for now you need to build from source if you want the latest version.

**Comment by implausible** [comment]
https://github.com/nodegit/nodegit/issues/1392
