### ISSUE TITLE
Add "help wanted" or "first good issue" labels to issues to make contribution easier

### ISSUE THREAD

**Issue by MartinHelmut** [nodegit/nodegit#1411]
## Description

Hey,

I would really like to contribute to the project in documentation or other parts. Like you mentioned in your [contribution guide](https://github.com/nodegit/nodegit/blob/master/CONTRIBUTING.md#how-to-help) you need help and want people to contact you by the slack channel. But not everyone uses Slack or just wants to quickly solve an issue. Other people maybe come from other platforms and know about labels like _"help wanted"_, _"documentation"_ or _"good first issue"_ and are looking for something like that.

## Proposal

Add the following tags to the list of issues:

* **help wanted**
* **documentation** (already exists, but could get more attention)
* **first good issue**

And also important, you are all awesome ❤️😎 Nodegit helped me already a lot!

**Comment by implausible** [comment]
:+1: You got it!
