### ISSUE TITLE
Emscripten binding templates.

### ISSUE THREAD

**Issue by tbranyen** [nodegit/nodegit#142]
I've successfully built libgit2 with Emscripten and am able to call into its functions within Node.  This is an interesting fallback option for when compilation or prebuilt binaries fail to work.

However for this to work we'll have to modify our main script here:

https://github.com/nodegit/nodegit/blob/master/index.js#L14-L18

And create another template that can bind directly to the Emscripten exported functions mimicking our native classes exported through nodegit.node.

**Comment by Ajedi32** [comment]
This is a really cool idea. I'm really curious as to whether this sort of thing could potentially be used to get a full-featured git client running in a browser. Chrome [has an API for fileSystem access](https://developer.chrome.com/apps/fileSystem), so this actually seems like it might be plausible to me.

**Comment by eric-schleicher** [comment]
Is this a dead subject? or is there a working port of libgit2 that can be used in the browser or in node?

**Comment by petersalomonsen** [comment]
@eric-schleicher This works: https://github.com/fintechneo/angular-git-filebrowser

Video demos: https://youtu.be/rcBluzpUWE4 and https://youtu.be/xfGrMwLy_tw
