### ISSUE TITLE
AWS lambda function,Web3 and NodeJS 

### ISSUE THREAD

**Issue by Akhilesh1189** [nodegit/nodegit#1423]
I want to upload web3 module on aws lambda function but i am getting error.please tell me how to fix this issue:-
{
  "errorMessage": "/var/lang/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/node_modules/scrypt/build/Release/scrypt.node)",
  "errorType": "Error",
  "stackTrace": [
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/node_modules/scrypt/index.js:3:20)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/node_modules/scrypt.js/node.js:1:76)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)"
  ]
}

**Comment by rcjsuen** [comment]
@Akhilesh1189 Could you explain how your error is related to NodeGit?

**Comment by Akhilesh1189** [comment]
Yes,i want to use web3 module in our project.so i have added module in our local. that is working fine. but when i am doing upload on aws lambda fucntion. then getting that error.

Thanks@rcjsuen

**Comment by rcjsuen** [comment]
@Akhilesh1189 And how is this related to NodeGit?
