### ISSUE TITLE
Bug: Cannot install on windows 10 x64 (reproducible)

### ISSUE THREAD

**Issue by dheerajbhaskar** [nodegit/nodegit#1427]
## Bug Overview

This is a bug which prevents installation of nodegit.

## Environment versions

```
C:\Users>node -v
v9.4.0

C:\Users>npm -v
The system cannot find the file specified.
5.6.0

C:\Users>ver

Microsoft Windows [Version 10.0.16299.192]

C:\Users>systeminfo | findstr /C:"OS"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              LENOVO 76CN43WW, 30 Mar
```

## npm commands run (can be reproduced using the same commands)

```
npm init -y
npm i nodegit
```

## Console output and npm debug log file
https://gist.github.com/dheerajbhaskar/4e517b4a34e7be48ff1fdb1dae6a0642

**Comment by rcjsuen** [comment]
```
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.20.3-node-v59-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.20.3 and node@9.4.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
The system cannot find the file specified.
gyp: Call to 'echo "$CXX"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
```
Seems like it couldn't find a binary on Amazon S3 so it tried to compile NodeGit but you don't have a compiler setup...maybe?

**Comment by dheerajbhaskar** [comment]
@rcjsuen thanks for the quick reply.

Oh! I see. This error might be happening because I'm on the most recent version of node, perhaps, for which nodegit doesn't yet have compiled binaries?

I wasn't planning on compiling nodegit on my system. I could, but I don't know how much effort it would take to setup the build tool chain. Or, is having a compiler setup the expected thing for a regular install? 🤔

Wouldn't it be better to get the amazon s3 link working, because I'm sure more people will start facing this, no?

**Comment by rcjsuen** [comment]
There have been many reports of issues with S3. See #1390, #1392, #1405, and #1409.

If you're using more recent versions of Node then I think you might be forced to compile it yourself.

**Comment by dheerajbhaskar** [comment]
Thanks for helping me with this.

I think it's because of the node version. I'll double check if this is the case and probably compile it myself if it is.

Thanks again.
