### ISSUE TITLE
No error thrown if push to blocked branch on GitHub

### ISSUE THREAD

**Issue by ghaiklor** [nodegit/nodegit#1445]
We have a repository, where pushing direct to branch `master` is protected by GitHub (configured on settings page).

When trying to push branch `master` from local repository to `master` on GitHub (_via nodegit_), expected result is to have an error thrown or an error code, that represents an error.

But, instead, it doesn't throw an error and doesn't return any error codes, they are undefined. Which is successful push, regard to nodegit documentation.

It took a lot of time to figure out why push was successful from nodegit perspective, but no changes on GitHub as a result.

Here is the code I'm using to push:

```js
const errorCode = await remote.push([
        'refs/heads/master:refs/heads/master'
    ], {
    callbacks: {
        certificateCheck: () => 1,
        credentials: gitCredentialsCallback,
        transferProgress: gitTransferProgressCallback(remoteUrl)
    }
});
```

The issue was resolved by allowing push into `master`, of course, but the behavior of nodegit in this case is embarrassing and could lead to unexpected decisions, when debugging such case.

**Comment by rcjsuen** [comment]
@ghaiklor Did you try setting a callback `pushUpdateReference` callback? The callback will be used to report whether the remote accepted or rejected the reference updates.
```JavaScript
const errorCode = await remote.push([
        'refs/heads/master:refs/heads/master'
    ], {
    callbacks: {
        certificateCheck: () => 1,
        credentials: gitCredentialsCallback,
        transferProgress: gitTransferProgressCallback(remoteUrl)
        pushUpdateReference: function(refname, message) {
          console.log(refname + "\t" + message);
        }
    }
});
```

**Comment by ghaiklor** [comment]
@rcjsuen no, I didn't. Let me check this and report asap.

**Comment by ghaiklor** [comment]
@rcjsuen yep, it worked, thanks for pointing me to the right direction. My final solution turns out to be:

```js
    // @see https://github.com/nodegit/nodegit/issues/1445
    // Since, we can't throw an error inside of callback, I've forced to have this flag to indicate errors
    let doesErrorOccur = false;
    const errorCode = await remote.push(refSpecs, {
        callbacks: {
            certificateCheck: () => 1,
            credentials: gitCredentialsCallback,
            transferProgress: gitTransferProgressCallback(remoteUrl),
            pushUpdateReference: (refname, message) => {
                if (message && message.length > 0) {
                    logger.error(chalk.red(`[${remoteUrl}]: ${refname} -> ${message}`));
                    doesErrorOccur = true;
                }
            }
        }
    });
```
