### ISSUE TITLE
Drop Node.js 7 from CI builds

### ISSUE THREAD

**Issue by rcjsuen** [nodegit/nodegit#1446]
I don't see any good reason for keeping Node.js 7 in the CI builds. It's not an LTS release and the "latest and greatest" has been superceded by Node.js 9.

Should we drop Node.js 7 from Travis CI and AppVeyor?

**Comment by Croydon** [comment]
I support this. 

Node 7 is EOF since 2017-06-30 (https://github.com/nodejs/Release#release-schedule)

**Comment by implausible** [comment]
IT needs to be dropped for sure.
