### ISSUE TITLE
Cloning Takes Forever

### ISSUE THREAD

**Issue by twalk4821** [nodegit/nodegit#1450]
HI -

I am working on a project where we are cloning about 100 repositories for analysis. Unfortunately for our automated tests, cloning the projects takes eons. I am wondering if there are any optimizations I could utilize to speed up the cloning process. Unfortunately cloning bare repositories is not an option, since it is necessary to walk the commit tree and do diffs on the files. 

Thanks,
Tyler Walker

**Comment by cjhoward92** [comment]
If I remember correctly, the clone implementation in `libgit2` is really slow, and that's what we use. As for any optimizations, I'm not sure there are any as of yet. Ideally, we would like to fix clone in `libgit2` to be better optimized.

**Comment by cjhoward92** [comment]
Is there a reason that you can't use a bare repository if you only need to worry about commits? The main difference between a bare and normal repo is the fact that a bare repo does not have a working directory. If you only need to worry about commits a bare repo should be fine.

**Comment by twalk4821** [comment]
Thanks for getting back to me.

I did try to use the bare repositories, but I was under the perhaps mistaken impression that you cannot recover the content of the commits from the bare repository. Is this incorrect?

**Comment by rcjsuen** [comment]
@twalk4821 What do you mean by "recover the content of the commits"? You can still read the repository's history and content just fine with a bare repository.

**Comment by cjhoward92** [comment]
If you need to get to the blobs in each commit, you still can. You just can't have a working directory.

**Comment by twalk4821** [comment]
I am trying to remember exactly where I was encountering an error, but yeah that's exactly what I'm trying to do. Let me give that another try and get back to you. Thanks.

**Comment by twalk4821** [comment]
Essentially I need a string of the commits contents, either of the diff or the state of the repo at that commit

**Comment by cjhoward92** [comment]
You can get the state of the repo at the point no problem. You might be able to get the state at two different commits and then diff them manually if you need to as well.

**Comment by twalk4821** [comment]
Thanks for your guys' help. Not sure what the problem was before. But that works much faster.

**Comment by tbranyen** [comment]
Sounds like this issue can be safely closed. I'll close now and someone else can reopen if it's in error.
