### ISSUE TITLE
Support for in-memory repositories

### ISSUE THREAD

**Issue by sffc** [nodegit/nodegit#1453]
I want to clone, edit, and push a repository using nodegit without having to interact with any type of local filesystem.

The upstream issue libgit2/libgit2#18 says that this is possible with the "SQLite backend".  Is there a binding for the sqlite backend from nodegit?  If not, this would be a useful feature to add.

**Comment by implausible** [comment]
This is very intriguing.

**Comment by rcjsuen** [comment]
@sffc There is no support for this at the moment. Please see #1296.

For reference, libgit2's custom backends are hosted at [libgit2/libgit2-backends](https://github.com/libgit2/libgit2-backends).
