### ISSUE TITLE
Nodegit for electron1.8

### ISSUE THREAD

**Issue by MrDarkSkil** [nodegit/nodegit#1456]
Can you update nodegit for electron1.8 ? 

I got an 404 error
https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.21.1-electron-v1.8-win32-x64.tar.gz

**Comment by implausible** [comment]
Thanks for reporting this. It seems to be failing only on windows installations Will need to look at this.

**Comment by dolanmiu** [comment]
Having the same issue

Fix:

I fixed this by installing `electron` `1.7.12`

**Comment by rcjsuen** [comment]
@MrDarkSkil @dolanmiu There should be v0.22.0 available for download.

Does this link work for you two?
https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.22.0-electron-v1.8-win32-x64.tar.gz

**Comment by MrDarkSkil** [comment]
Yep nice work :)
