### ISSUE TITLE
How can I stage lines and hunks?

### ISSUE THREAD

**Issue by demian85** [nodegit/nodegit#146]
Hi,

I've been working on a 'git-gui' desktop app. I invite you to take a look: https://github.com/demian85/git-watcher

All the current functionality is provided by native git commands and the git-utils module.

Now, to make it more useful, I would like to implement at least the following features:

Amend commit: I need to show files from previous commit and allow to stage them in a 'sandbox' to avoid modifying the current repository.
Stage by lines and hunks: The same as git-gui.
I've done a bit of research and my conclusion is that there is no way to implement those features without using a native git API.

Can nodegit help me? I couldn't find a clue by looking at the old documentation.

Thanks for your help.

pd: I've asked the same question in the node-gitteh project: https://github.com/libgit2/node-gitteh/issues/71

**Comment by johnhaley81** [comment]
We're still trying to get this in. @orderedlist have you made any progress on this?

**Comment by orderedlist** [comment]
Currently working on custom staging. The only process available in libgit2 for this at the moment involves creating a new `IndexEntry`, writing a blob to the repo with the desired version of the file (not the diff, the full modified file), setting the path and the blob on the `indexEntry`, and using `index.add(entry)` to write that item to the index.

Not the prettiest, but at least it's possible. Hopefully I'll be able to add examples soon.

**Comment by johnhaley81** [comment]
I'm going to remove this from the 0.3.0 release but we'll need some examples for this still.

**Comment by richtmat** [comment]
are there any news on this issue? I would like to stake hunks as well.

**Comment by johnhaley81** [comment]
Implemented in #678

**Comment by richtmat** [comment]
@johnhaley81 sorry, didn't see that. thanks!

**Comment by johnhaley81** [comment]
No worries. Should have updated the issue as well :)
