### ISSUE TITLE
Passing Buffer type argument to Odb.write gives error

### ISSUE THREAD

**Issue by nijynot** [nodegit/nodegit#1465]
I tried passing in a buffer, `Buffer.from('some string')` to `Odb.write(data, len, type)`, but it gives me this error
```
Error: Buffer data is required.
```
And if we look at the test for Odb.write, it also doesn't pass in `Buffer` either, just a string. Tried using a string instead of a `Buffer`, and then everything worked fine with no errors. https://github.com/nodegit/nodegit/blob/master/test/tests/odb.js#L49

Is everything working as intended? Is `data` supposed to be a string? If so, then the `data`'s type should be `string`.

**Comment by rcjsuen** [comment]
@nijynot From looking at the libgit2 header files, I think `string` is valid. Perhaps `Buffer` was correct back in 2014 (32f7838e5db23b044e9b7ea8b4af9d244c52bf5c), I'm not sure.
