### ISSUE TITLE
NodeGit fails with memory access error with Node 9.9.0 on x64 Arch

### ISSUE THREAD

**Issue by EneOli** [nodegit/nodegit#1469]
As the title says, nodegit does not work on the latest node version.
It gives me a memory access error. But node 8.10 works just fine.

Tested on x64 Arch

P.S. I recommend using nvm for switching between node versions.

**Comment by rcjsuen** [comment]
@EneOli The Travis CI builds are using (and passing) with Node v9.9.0 on Trusty.

**Comment by EneOli** [comment]
Well, I tested it today with a fresh virtual machine with Ubuntu 17.10. Same problem. Do you have any suggestions?

**Comment by rcjsuen** [comment]
Well, let's try to narrow the problem down first.

1. When does it fail? Right after you call `require('nodegit')`?

2. Does it fail with Node v9.0.0? Which version of Node v9.x does it start failing in?

3. Do older or other versions of NodeGit work?

4. Can you compile and run regular libgit2 programs and/or its test suites?

**Comment by revan730** [comment]
Hi, same problem here, running Node v.9.9.0 on Arch Linux x64.It fails with SIGSEGV right after `require('nodegit')`.The latest node version which works is 9.8.0-1 (downgraded with pacman).Even 9.8.0-2 fails, so it`s not strictly 9.9.X problem

**Comment by EneOli** [comment]
Allright. It looks like the problem is solved. I don't konw exactly why but it is solved.

What did I do?

1. Delete node_modules folder
2. Changing to node version 9.9.0 via nvm
3. `npm install`
4. Run the script and it works
