### ISSUE TITLE
config.log: Permission Denied

### ISSUE THREAD

**Issue by iamSokhi** [nodegit/nodegit#1475]
<img width="1283" alt="screen shot 2018-03-29 at 3 01 49 pm" src="https://user-images.githubusercontent.com/8376051/38081648-29848cbe-3362-11e8-8d7f-59a68fe03beb.png">

I get this error when I run `sudo npm i nodegit -g` on Mac OS 10.3.3.

Here is the log:
<img width="1046" alt="screen shot 2018-03-29 at 3 03 49 pm" src="https://user-images.githubusercontent.com/8376051/38081764-71a21a0c-3362-11e8-84ae-fedf860de4e6.png">

**Comment by iamSokhi** [comment]
I had to login with root user to execute node-git pre-install/install scripts.

**Comment by tagazok** [comment]
I would not consider having to login as root a good solution for the problem :/
Any other idea?
