### ISSUE TITLE
remote.push doesn't catch hook declined error

### ISSUE THREAD

**Issue by mtsvickers** [nodegit/nodegit#1483]
I have code to push a repo to a remote, which works 90% of the time, but there is a specific error (pre-receive hook declined) which doesn't get caught and acts as though it worked when it didn't. Is there a way I can catch this somehow so I know the push failed?

Push code:
```
.then(function(remoteResult) {
  remote = remoteResult;
  pushref = "refs/heads/master:refs/heads/master";
  return remote.push(
     [pushref],
     {
       callbacks: {
         credentials: function(url, userName) {
           return nodegit.Cred.sshKeyFromAgent(userName);
         }
       }
    }
   );
})
.catch(function(err) {
    console.log(err);
})
.done(function() {
    console.log("Git Push Succeeded");
});
```

The Error which isn't caught:
```
! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@git.wpengine.com:production/somesite.git'
```

**Comment by rcjsuen** [comment]
It's possible that #1229 is what is needed here.

**Comment by mtsvickers** [comment]
Yes, that worked. Thank you!

**Comment by rcjsuen** [comment]
@mtsvickers Hm..."that worked", eh? So maybe I'm wrong and `pushUpdateReference` already works...?

**Comment by mtsvickers** [comment]
@rcjsuen  It did for me. I couldn't get it to return any information which is why I used the hacky global var, but I may have just been doing something wrong when I tried returning data (if you know what it was I'd love to do it the right way!). 
Here's the code I used:
```
var e = null;
// [...other code here]
return remote.push(
	[pushref],
	{
		callbacks: {
			credentials: function(url, userName) {
		            return nodegit.Cred.sshKeyFromAgent(userName);
			},
			pushUpdateReference: function(ref, status, data) {
				if( status.indexOf('declined') >= 0 ) {
					e = new Error(status);
			}
			return;
		}
	}
}
);
})
.then(function() {
	if( e !== null ) {
		return callback(e);
	}
	return;
})
```

**Comment by rcjsuen** [comment]
@mtsvickers I think you have to use another variable to store the data.
