### ISSUE TITLE
Push fail provides no feedback

### ISSUE THREAD

**Issue by Yamazaki93** [nodegit/nodegit#1489]
It appears when pushing, if a remote rejects a push because, say a branch is protected, there seemed to be no errors thrown, `Remote.push()` will resolve to `undefined`. 
Also looked into similar issue over at libgit2sharp [https://github.com/libgit2/libgit2sharp/issues/1192](url) where the callback options provides `OnPushStatusError` callback, but nodegit's `RemoteCallbacks` doesn't seemed to have comparable options. 
Maybe we can have similar options for `RemoteCallbacks`? or simply reject the promise?

For now I've been manually checking the target before and after push as a workaround to see if a push is rejected, in case anyone is encountering the same issue

Best,

**Comment by rcjsuen** [comment]
Hi @Yamazaki93. I think `pushUpdateReference` should be able to help you with that. Please see https://github.com/nodegit/nodegit/issues/1445#issuecomment-368476041 and https://github.com/nodegit/nodegit/issues/1483#issuecomment-381630069.

**Comment by Yamazaki93** [comment]
Ah that did the trick, thanks a bunch
