### ISSUE TITLE
A DLL initialization routine failed with Electron 2.0.2

### ISSUE THREAD

**Issue by fr3fou** [nodegit/nodegit#1512]
Everytime I try to run my project it gives me this error

![](https://i.imgur.com/a7hph6y.png)

Some details -

-  Windows 10 - 1803
-  Node.js - 8.11.3
-  npm - 5.6.0
-  Electron - 2.0.2
-  nodegit - 0.22.1

Here are my package.json's dependencies
```json
  "dependencies": {
    "nodegit": "^0.22.1"
  },
  "devDependencies": {
    "electron": "^2.0.2"
  }
```

And here's my code in my main.js
```js
const electron = require('electron');
const url = require('url');
const path = require('path');
const git = require('nodegit');
const { app, BrowserWindow } = electron;

let mainWindow;

app.on('ready', function () {
    mainWindow = new BrowserWindow({
        width: 600,
        height: 650,
        resizable: false
    });
    mainWindow.setMenu(null);
    mainWindow.loadFile('main.html');
    git.Clone("https://github.com/fr3fou/ppfromthepast", "./tmp")
})
```
##### Ignore the last bit, was an attempt at cloning, even without it, it still doesn't want to run without giving me that error
According to your website - `NOTE: We try to provide prebuilt binaries for electron, but we don’t always have them available for every version. `, you provide prebuilt binaries for electron, do you have some for 2.0.2 uploaded somewhere? I'll try and build it myself and report soon.
**EDIT** - Haven't been able to build the binaries myself - kept getting the same error (probs have to do with dependencies)
**EDIT 2** - Tried using an eariler version of electron, still no success.

**Comment by IMPZERO** [comment]
same

**Comment by fr3fou** [comment]
Managed to fix it by installing `electron-rebuild` again, `Python 2.7`, `Node 8.11.3` and rebuilding it using `node_modules\.bin\electron-rebuild`. Closing this now.

**Comment by TerryChan** [comment]
Same issue

**Comment by fr3fou** [comment]
@TerryChan have you tried rebuilding it with a lower node version? That fixed it for me.

**Comment by implausible** [comment]
@fr3fou https://www.nodegit.org/guides/install/electron/ should give you prebuilts instead of using electron-rebuild
