### ISSUE TITLE
Question: Anyway to go in certain folder?

### ISSUE THREAD

**Issue by IdkGoodName** [nodegit/nodegit#1516]
Is there anyway to make nodegit pick files in certain folder from Repostry?

Example:

>```css
>Repostry:
>   /node_modules
>   /stuff
>       index.js
>       main.js
>```
i want to get `index.js` and `main.js` from `stuff` folder

>And if you can answer another one:
>      How do i get repo name?

**Comment by rcjsuen** [comment]
@CreatorVilius I'm not sure if either of those two thing are possible with NodeGit.

1. I believe you have to clone the repository first. You cannot simply download a file.
1. Repositories do not have a name. When you clone a Git repository you can specify a folder for it to clone into so Git repositories don't really have a name.
