### ISSUE TITLE
Question about document Repository.free()

### ISSUE THREAD

**Issue by MrDarkSkil** [nodegit/nodegit#1522]
After cloned a Repository i would to close folder and file use.

Can I do that with: https://www.nodegit.org/api/repository/#free

Why I want to do that ? 

I made a Software with plugin support, so I can download a Plugin and load it in run time ( I use NodeGit to clone a plugin)

When a user logout I would like to delete all plugins, so on Linux and MacOS it work fine, but on Windows 2 file continues to be used by NodeGit `.pack` and `.idk` located in `.git/objects/pack`

Can you help me 😄 ?

**Comment by ArturKovacs** [comment]
Have you ever managed to figure this out?

I'm wondering if it's okay to have two `Repository` objects pointing to the same folder at the same time. And if it's not then how do I make sure that a Repository is free'd as soon as I'm done using it?

**Comment by amorawski** [comment]
I'm experiencing same issue here. Seems like cleanup should be done based on js context - but even trying to manually run global.gc() ends up with EPERM for .idx at windows.

**Comment by implausible** [comment]
Try using `NodeGit.Repository.prototype.cleanup` when you're done with a repository object.
