### ISSUE TITLE
API Docs 404

### ISSUE THREAD

**Issue by icecreammatt** [nodegit/nodegit#1523]
Site appears to be offline.

https://www.nodegit.org/
http://www.nodegit.org/api/

![screen shot 2018-07-13 at 3 37 00 pm](https://user-images.githubusercontent.com/1154569/42716885-9a37aace-86b2-11e8-80dc-3a88a7782525.png)

**Comment by tniessen** [comment]
The domain is pending ICANN verification.

**Comment by m31271n** [comment]
Is there any alternative way to visit docs now? Such as `http://<ip>:<port>`.

**Comment by tbranyen** [comment]
@m31271n docs can be accessed at https://nodegit.github.io/ until we can resolve the domain issues.
