### ISSUE TITLE
Can't fetch remote.

### ISSUE THREAD

**Issue by RobertPaul01** [nodegit/nodegit#1525]
I want to add an upstream remote and then fetch it. I've tried two different approaches of doing this:
```
const upstream = await Git.Remote.create(repo, "upstream", remote_url);
await repo.fetch(upstream, fetchOpts);
```
which results in an error: `'npm start' terminated by signal SIGSEGV (Address boundary error)`

```
const upstream = await Git.Remote.create(repo, "upstream", remote_url);
await upstream.connect(
  Git.Enums.DIRECTION.FETCH,
  fetchOpts.callbacks
);
```
which results in: `'npm start' terminated by signal SIGBUS (Misaligned address error)`

Is this not the correct way to do this?

**Comment by ndangles** [comment]
^
