### ISSUE TITLE
Website link in github repository page is broken

### ISSUE THREAD

**Issue by hitochan777** [nodegit/nodegit#1527]
The link (as shown below) in the github repository page is broken.
It is linked to `http://www.nodegit.org/%20` with redundant `%20`.
![image](https://user-images.githubusercontent.com/6002787/43031104-05b6b078-8cd6-11e8-84ea-27d0a26fe92a.png)

**Comment by hitochan777** [comment]
seems like its fixed! thanks.

**Comment by hitochan777** [comment]
It is not still working.

**Comment by tbranyen** [comment]
Not sure why it was doing that, but I just changed the URL back to https://nodegit.org/ Looks okay on my end.
