### ISSUE TITLE
Cannot install (or build) nodegit on OSX 10.13

### ISSUE THREAD

**Issue by kburson** [nodegit/nodegit#1532]
I am unable to install the nodegit lib on my computer after upgrading to a new laptop with HighSierra (OSX 10.13).

I have all the pre-reqs installed, as far as I know.  When I try to install it runs the node-gyp (generate your projects for node) that calls on XCode gcc to build the nodegit binaries, this is where it fails.  
I have attached a console log of the install process. 

for quick reference here is my env:

>   System Version: macOS *10.13.6* (17G65)
>   Kernel Version: Darwin *17.7.0*
>   Xcode:  *9.4.1*, Build version 9F2000
>   gcc: *4.2.1*
>   libcrypt:  *1.8.3*
>   libgit2:  *0.27.3*
>   node:  *10.3*
>   npm: *6.1.0*

   I am attaching the console output of the install command to show the errors:

[console.txt](https://github.com/nodegit/nodegit/files/2242798/console.txt)

there are numerous build errors, i.e:

>../vendor/libssh2/src/openssl.c:131:34: *error*: incomplete definition of type 'struct dsa_st'
>    BN_bin2bn(p, p_len, (*dsactx)->p);

with the final error being:

> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 20 errors generated.
> make: *** [Release/obj.target/libssh2/vendor/libssh2/src/openssl.o] Error 1
> gyp
> 
> ERR! build error
> gyp ERR!
> stack Error: `make` failed with exit code: 2
> gyp ERR! stack
> at ChildProcess.onExit (/Users/kburson3/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node- gyp/lib/build.js:258:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
> gyp ERR!
> System Darwin 17.7.0
> gyp ERR! command "/Users/kburson3/.nvm/versions/node/v10.3.0/bin/node" "/Users/kburson3/.nvm/versions/node/v10.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/kburson3/projects/TMO/tmo-aem-ui-integration/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/Users/kburson3/projects/TMO/tmo-aem-ui-integration/node_modules/nodegit/build/Release"
> gyp ERR! cwd /Users/kburson3/projects/TMO/tmo-aem-ui-integration/node_modules/nodegit
> gyp ERR! node -v v10.3.0
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> [nodegit] ERROR - Could not finish install
> [nodegit] ERROR - finished with error code: 1
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! nodegit@0.22.2 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
> npm ERR! Exit status 1

**Comment by fr3fou** [comment]
A friend of mine had trouble installing nodegit with Node @ 10.3, install the LTS and try again?

**Comment by kherdier** [comment]
@fr3fou worked like a charm for me, thanks !

**Comment by maxkorp** [comment]
Yup, currently it doesn't build on node 10. See here: https://github.com/nodegit/nodegit/issues/1490

Closing this since it would just be a duplicate at this point
