### ISSUE TITLE
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer

### ISSUE THREAD

**Issue by nickagel** [nodegit/nodegit#1539]

**Comment by amitsharma1729** [comment]
@dj-github tried that. ran command 
```
sudo npm install npm@latest -g
```
Output:
```
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.4.0
added 278 packages, removed 363 packages and updated 41 packages in 99.728s
```

ran 
```
npm -v
node -v
```
output
```
6.4.0
v8.11.4
```
still getting the following issue while building my project:

```
Module "site-app-Screen": command output
>  npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
ERROR: Failed to build module "site-app-Screen". Command timed out
```

**Comment by hackjie** [comment]
met the sample problem

**Comment by JackZhouMine** [comment]
met the same problem just now

**Comment by lanumula** [comment]
I am getting npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
this error, Any one fixed this issue????

**Comment by walterpalladino** [comment]
Same problem here

**Comment by hdale** [comment]
Same here. When installing Cordova : sudo npm install -g cordova same error.

**Comment by shashankdevp** [comment]
I guess its a new version of the npm which is causing this issue. Has anyone found the solution ?

**Comment by shanibaba786** [comment]
update your Node.js to 10 version it  will resolve your issue.

**Comment by rahmatrmdn** [comment]
node.js v10.x has the same error

**Comment by DzViRuZ** [comment]
open cmd go to npm folder user/yourname/appdata/roaming/npm and run this
npm i hoek

**Comment by preetskhalsa97** [comment]
For Ubuntu, navigate to /usr/lib/nodejs/npm and do:
 npm i -g hoek
(similarly  npm i -g socks if you're getting a warning for that as well)

**Comment by dAiMoN-LeUnAm** [comment]
Gracias, a mi me sirvió, ejecute:

sudo npm install npm@latest -g

Luego ejecute:

sudo npm install -g cordova ionic

Y el resultado fue:

+ cordova@8.0.0
+ ionic@4.1.2
added 649 packages from 450 contributors in 55.465s

Y la versiones fueron:
npm -v
6.4.1

node -v
v8.12.0

Gracias y saludos.

**Comment by Yowsifahamed** [comment]
I did all above  instruction  bt problems in not solved

**Comment by Yowsifahamed** [comment]
![untitled](https://user-images.githubusercontent.com/42865017/45819375-c99e1e80-bd01-11e8-9ac2-a74d01ee3082.png)

**Comment by learnmemore** [comment]
Hello, 
I tried this solution 
"open cmd go to npm folder user/yourname/appdata/roaming/npm and run this
npm i -g hoek "

I had this result : 
![image](https://user-images.githubusercontent.com/38610786/45917077-77c7d680-be70-11e8-8951-91696ac371bc.png)
It seems OK

**Comment by meman94** [comment]
We already resolved this issue in the latest development version of Cordova. However, the fix has not yet been included in a release of Cordova. That's why you still see the warning. However, there's nothing more to do than wait for the next release.

**Comment by Yowsifahamed** [comment]
![ionic](https://user-images.githubusercontent.com/42865017/47636716-5351cf00-db7f-11e8-824b-1cf45575906f.png)
it is stopped here Why

**Comment by Subhang23** [comment]
![image](https://user-images.githubusercontent.com/43785080/51784858-5441cf00-2175-11e9-9ab7-303d0174761d.png)
Can anyone just me me out with this?

**Comment by rogersnowden** [comment]
Why in the hell to people put dark red letters on a black background?

**Comment by rcjsuen** [comment]
@rogersnowden Did you mean to comment in another issue? We are not talking about terminal colours here.

**Comment by Subhang23** [comment]
@rogersnowden I was new back then and did not have much experience. So I didn't know how to change color.
