### ISSUE TITLE
createBranch API params

### ISSUE THREAD

**Issue by vritant24** [nodegit/nodegit#1549]
The API in the documentation for `Repository.createBranch` is written as : `repository.createBranch(name, commit, force)`

But in the example over here: https://github.com/nodegit/nodegit/blob/master/examples/create-branch.js,  it is used as:

```
return repo.createBranch(
  "new-branch",
  commit,
  0,
  repo.defaultSignature(),
  "Created new-branch on HEAD");
```

What are the 4th and 5th parameters given to the function? Am I missing something / looking at the wrong documentation or example?

**Comment by implausible** [comment]
I think the example is out of date. We'll need to update that example!

**Comment by RaevLogic** [comment]
If it's just adjusting the example in 'create-branch.js' to match the current documentation, I can take care of that when I get home in a few.

**Comment by RaevLogic** [comment]
So here is the updated code within the `create-branch.js` file. Let me know if I need to change anything, otherwise, I can submit a PR as soon as someone gives me the green light on the update.
![createbranch api params fix](https://user-images.githubusercontent.com/38801291/45983468-93b6ae00-c011-11e8-95b0-89375bbe7f83.png)

**Comment by implausible** [comment]
Yes, I believe that looks correct. The parameters are name of branch, commit to create branch at, and force (overwrite branch if it exists).

**Comment by RaevLogic** [comment]
Yes, I left the original first three parameters as they were. I simply removed the 4th and 5th parameters. PR created, thanks @implausible

**Comment by implausible** [comment]
Closed by https://github.com/nodegit/nodegit/pull/1552

**Comment by vritant24** [comment]
Thanks for the quick fix!
