### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by shaunc** [nodegit/nodegit#1556]
## System information
  - node version:
  - npm or yarn version:
  - OS/version/architechture:
  - Applicable nodegit version:

(NA)

```
node -v
npm -v # (or yarn -v)
node -e "console.log(process.platform)"
node -e "console.log(require('os').release())"
node -e "console.log(console.log(process.arch))"
```

https://nodegit.org doesn't connect; at http://nodegit.org, I see:

![image](https://user-images.githubusercontent.com/193170/46049257-680ff280-c0fb-11e8-81fa-9f6e863a0800.png)

**Comment by RaevLogic** [comment]
Judging from the Nodegit slack channel, ICANN is a different organization not under the control of the Nodegit maintainers. An earlier response on that page indicated verification was complete but it might take 24 to 48 hours for the site to come back up. So unless they need new verification again, we're all just waiting on ICANN at the moment.

**Comment by shaunc** [comment]
ah ... I figured it was pretty obvious; I didn't check slack though -- sorry for the "duplicate".
