### ISSUE TITLE
nodegit.org is down

### ISSUE THREAD

**Issue by Croydon** [nodegit/nodegit#1557]

**Comment by implausible** [comment]
I think @tbranyen is looking into the situation.

**Comment by tbranyen** [comment]
I contacted namecheap to let them know the problem has resurfaced.

**Comment by tbranyen** [comment]
They said they resolved it, so lets see how if it eventually fixes itself.

**Comment by Stranger469** [comment]
It's still not working now.

**Comment by biohazard999** [comment]
Still dead.

**Comment by tbranyen** [comment]
Looks good now on my end. If its still not working for you it may be a DNS propagation issue and just be patient.

**Comment by tbranyen** [comment]
I also just enabled HTTPS, so try and use: https://www.nodegit.org/ to skirt around insecure caching.
