### ISSUE TITLE
Cutting 0.23.0

### ISSUE THREAD

**Issue by maxkorp** [nodegit/nodegit#1564]
So it's good that we're being cautious around releasing 0.23.0. I think we should try to get it out soonish though, like before end of the month, if everybody is cool with that. I'm fine with sooner as well (e.g. I would not be mad about a release friday). This fixes a _lot_ of install issues we've been getting for a while, and that I suspect are only going to get worse with mojave dropping.

CC: @implausible @tbranyen @stevex86 @rcjsuen @Croydon @johnhaley81

**Comment by tbranyen** [comment]
I agree. Given there is a soft-launch (pre-release tag), folks can start onboarding to it sooner than later, and then we cut a stable release at the end of the month.

**Comment by maxkorp** [comment]
Do we want to make a note about that in the readme maybe?

**Comment by implausible** [comment]
I'm for a stable release by end of the month. What's nice about the soft release we're doing now is that we're able to deterministically quash long standing issues without having jeopardized an unstable full release... Magical!

I'd be fine doing a full release anytime next week imo.

**Comment by implausible** [comment]
We've closed https://github.com/nodegit/nodegit/issues/1566 and I've added one more prerelease v0.23.0-alpha.2. @tbranyen @maxkorp Does a full release next week sound good to you?

**Comment by maxkorp** [comment]
I am very down.

**Comment by implausible** [comment]
I'm working on the release now. Just being slowed down because github has been really messed about the past 2 days.

**Comment by maxkorp** [comment]
Oh yeah things have been mucho bork since hooks went down.

**Comment by implausible** [comment]
0.23.0 is out
