### ISSUE TITLE
OpenSSL is still mean spirited on latest on MacOS

### ISSUE THREAD

**Issue by maxkorp** [nodegit/nodegit#1566]
## System information
  - node version: v10.11.0
  - npm or yarn version: npm 6.4.1
  - OS/version/architechture: Darwin x86 18.0.0
  - Applicable nodegit version: Master (0.23.0-alpha.1)

Trying to build locally (`npx run rebuild`) libssh2 fails to configure (even with openssl headers linked in the ldflags) 3 times in a row, and then the build just continues.

```
nodegit git:(generation-cleanup) npx node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.11.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  ACTION binding_gyp_configureLibssh2_target_configure .
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/maxkorp/development/personal/nodegit/vendor/libssh2/configure
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-libmbedtls-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   '/Users/maxkorp/development/personal/nodegit/vendor/libssh2/configure' }
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-libmbedtls-prefix=PATH
 or --with-wincng on Windows

(node:28790) UnhandledPromiseRejectionWarning: Error: Command failed: /Users/maxkorp/development/personal/nodegit/vendor/libssh2/configure
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-libmbedtls-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
(node:28790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28790) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack-objects.o
  CC(target) Release/obj.target/libgit2/vendor/libgit2/src/pack.o
  CC(target) Release/obj.target/libgit2/vendor/libgit2/src/parse.o
  CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_generate.o
  CC(target) Release/obj.target/libgit2/vendor/libgit2/src/patch_parse.o
../vendor/libgit2/src/patch_parse.c:461:12: warning: unused function
      'parse_number' [-Wunused-function]
static int parse_number(git_off_t *out, git_patch_parse_ctx *ctx)
           ^
1 warning generated.

... and so on
```

Something is bork. 

I installed and linked to openssl via brew.
```
brew install openssl
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
```

This was working pre node-v10 PR.

**Comment by maxkorp** [comment]
Ok a bit of research here, it looks like on macOS we explicitly don't copy the env anymore (unexpected but somehow unsurprising) but that prevents system headers passed via LDFLags from working. I wonder if `acquireopenssl` is not working locally?

**Comment by Stranger469** [comment]
#1134 you can see this issus, they seems to solve this problem by `npm install nodegit@0.23.0-alpha.1`

**Comment by stevex86** [comment]
IIRC, issue with copying the env is that it could not properly detect the right OpenSSL during the `configureLibssh2` step. My hunch is that probably something to do with include directories; I didn't spend a lot of time investigating once I figured out that copying the env was causing the builds to fail.

**Comment by implausible** [comment]
You shouldn't need openssl as a dependency unless you're using Electron for nodegit. Is there a particular reason you need to utilize the system openssl instead of the one provided with node? Or are you looking to change the source of the osx openssl as well?

NodeGit should build fine without overriding openssl.

**Comment by erikwilson** [comment]
@maxkorp  After upgrading to OSX 10.14 (Mojave), there may be a problem where XCode Command Line Tools does not install all of the necessary headers. The following command may help:
`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`

**Comment by maxkorp** [comment]
@implausible @stevex86 it definitely breaks for me on mojave without explicitly including other headers. 

@erikwilson I'll try that and see if that helps, thanks for popping in :)

**Comment by maxkorp** [comment]
🙃🙃🙃🙃🙃🙃🙃🙃
🙃 THAT WORKED 🙃
🙃🙃🙃🙃🙃🙃🙃🙃

So what do we actually _do_ about this?

**Comment by maxkorp** [comment]
Yeah it looks like it's a missing zlib header that causes the whole thing to go down. HOPEFULLY this should be fixed with an xcode-select bugfix and upgrade

**Comment by maxkorp** [comment]
Thanks to @erikwilson we have this:
https://developer.apple.com/documentation/xcode_release_notes/xcode_10_release_notes#3035623

Search for /usr/include

> However, some software may fail to build correctly against the SDK and require macOS headers to be installed in the base system under /usr/include. If you are the maintainer of such software, we encourage you to update your project to work with the SDK or file a bug report for issues that are preventing you from doing so. As a workaround, an extra package is provided which will install the headers to the base system. In a future release, this package will no longer be provided. You can find this package at: 
```
/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

The world is full of hate. 

We'll have to figure out which files are missing (I _think_ zlib but we will have to test that) and bundle them appropriately. I wonder if node also includes their zlib headers like they do with openssl.

Life is pain.

**Comment by maxkorp** [comment]
WTF Even as root I cant remove any of the installed files.

**Comment by maxkorp** [comment]
As an aside, to clean up that package you have to list out out the files while booted into the os install, save them to a file, and then boot into recovery mode and remove them from there. 

Based on this, but with some tweaks: https://wincent.com/wiki/Uninstalling_packages_(.pkg_files)_on_Mac_OS_X

On host:
```
cd /
pkgutil --only-files --files com.apple.pkg.macOS_SDK_headers_for_macOS_10.14 > ~/pkg-files.txt
pkgutil --only-dirs --files com.apple.pkg.macOS_SDK_headers_for_macOS_10.14 > ~/pkg-dirs.txt
```

In recovery mode
```
cd /Volumes/{nameOfMacOSVolume}
cat Users/{username}/pkg-files.txt | tr '\n' '\0' | xargs -n 1 -0 sudo rm
cat Users/{username}/pkg-dirs.txt | tr '\n' '\0' | xargs -n 1 -0 sudo rmdir
```

Using rmdir will prevent it from deleting dirs that have other files in them

Then back on the host
```
sudo pkgutil --forget com.apple.pkg.macOS_SDK_headers_for_macOS_10.14
```

**Comment by maxkorp** [comment]
Also I removed just zlib from the package, and that does not appear to cause it to break

**Comment by erikwilson** [comment]
Looks like it might just be C standard library stuff :(
```
grep -h include /usr/local/opt/openssl/include/openssl/* | grep -o '<.*>' | grep -v openssl | sort -u
<assert.h>
<ctype.h>
<errno.h>
<inttypes.h>
<krb5.h>
<limits.h>
<resource.h>
<stdarg.h>
<stddef.h>
<stdint.h>
<stdio.h>
<stdlib.h>
<string.h>
<sys/socket.h>
<sys/time.h>
<sys/timeb.h>
<sys/times.h>
<sys/timeval.h>
<sys/types.h>
<time.h>
<windows.h>
<winsock.h>
```

**Comment by implausible** [comment]
@maxkorp It's still strange that you're trying to use system openssl headers. The install path as of now should never utilize or require brew or your system ssl headers.

The header data should be located in `/your_home_dir/.node-gyp/10.11.0/include/node` where the header files are supposed to be. Then the link to node is supposed to provide the openssl implementation for those headers. Why are you trying to link against the system in response? I think you might be better off investigating why the provided headers from node for openssl are failing to work when configuring libssh2, than to bind against a system lib. Does that make sense? I hope I'm explaining this clearly.

**Comment by implausible** [comment]
I would be concerned if we started including _other_ openssl headers than the one node provides before attempting to debug libssh2's rejection of the node headers.

**Comment by erikwilson** [comment]
I don't think it is a result of including other openssl headers than intended, simply openssl relies on some basic system headers, maybe such as types, which Mojave does not put in /usr/include by default.

**Comment by implausible** [comment]
Oh I see, thanks for clarifying for me :smile:

**Comment by maxkorp** [comment]
yeah it's _something_ to that effect. I'm trying to figure out what specifically, but it's super slow going, as there is no clean uninstall path for the package. I might throw up a vm and manually _install_ those files one at a a time to see at what point it starts working.

As an aside, if this is in fact related to libc stuff, the fix for this might open avenues into fixing nodegit on alpine images.

**Comment by stevex86** [comment]
I just got a fresh install of Mojave on a machine. There's no developer packages installed except the Xcode command line tools and Node. I was able to compile a dummy native Node module that includes `openssl/ssl.h` and calls `SSL_library_init()`. The libssh2 configure script checks to see if OpenSSL is available by compiling a dummy program containing `#include <openssl/ssl.h>`. I'm inclined to believe it's some other package that's causing the configure step to fail.

**Comment by stevex86** [comment]
Yup – `libssh2/configure` succeeds if I pass `LDFLAGS=-L/usr/local/opt/openssl/lib` and `CPPFLAGS=-I/usr/local/opt/openssl/include` to an OpenSSL distribution downloaded from Homebrew.

As an experiment, I changed the `CPPFLAGS` to `-I/path/to/node-gyp-includes` and left `LDFAGS` as-is. `configure` still succeeds. But when I take away the `LDFLAGS`, `configure` fails.

The block that tests for OpenSSL must be trying to ensure that we can link against the library.

**Comment by maxkorp** [comment]
I'd be OK with that, assuming it's reliable across versions.

**Comment by maxkorp** [comment]
Although, if it's configured to point at files that don't exist, how is that going to work?

**Comment by implausible** [comment]
So configure performs a link to confirm that libssh2 can link with libssl... But we know for certain that when it links via node-gyp it will have openssl symbols. Libssh2 configure itself doesn't set up any makefiles that node-gyp ends up using, so the fact that libssh2 configure fails isn't necessarily going to fail the nodegit build, because node / conan will provide them by link time.

Also, I only know this because @stevex86 has been researching like a madman today.

**Comment by stevex86** [comment]
So it looks like `libssh2/configure` is adding the `-lssl` and `-lcrypto` to the compiler command it uses to test for OpenSSL's existence.

Running `clang -lssl -lcrypto foo.c` on High Sierra produces a binary that is properly linked to the system providers of `libssl` and `libcrypto` (LibreSSL).

```/usr/lib/libssl.35.dylib (compatibility version 36.0.0, current version 36.0.0)
/usr/lib/libcrypto.35.dylib (compatibility version 36.0.0, current version 36.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)```

Running `clang -lssl -lcrypto foo.c` on Mojave fails to link, complaining that it cannot locate `libssl` or `libcrypto`. This is despite the _exact same_ system libraries existing in the same locations on Mojave. 

This explains why setting the `LDFLAGS` and pointing to an absolute path from Homebrew allowed the configure step to complete successfully: the linker was able to find `libssl` and `libcrypto` dylibs. Something fucky is going on with the linker here. Maybe installing the aforementioned SDK headers package has a side effect on the paths `ld` searches for system dylibs?

**Comment by implausible** [comment]
To get a sense of what side effects we utilize from performing configure see:
https://github.com/nodegit/nodegit/blob/master/vendor/libssh2/src/libssh2_config.h.in

Nowhere in this template are we restricting what paths or places we find openssl, just that we do or do not have it. As long as we configure it for what we know we're building, we shouldn't even need to configure for mac os.

**Comment by erikwilson** [comment]
I'm curious if any dylib can be linked without that header pkg installed, it has /usr/lib/dylib1.o and crt1.o, which ld might need? Doing the link step separate might provide some more info

**Comment by erikwilson** [comment]
After some experimentation, it looks like clang is doing some weird things. It has nothing to do with the objects in /usr/lib, but if we add a -v flag to clang we can better see how it is linking. Without the header package installed it adds a `-syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk` flag to ld. Using dtruss with clang we can see it is stating /usr/include/sys/cdefs.h to determine if it should add the syslibroot flag (`sudo dtruss clang -v -lssl foo.o -o foo 2>&1 | grep '/usr/include'`). If we `touch /usr/include/sys/cdefs.h` then clang works. Fun stuff :)

**Comment by maxkorp** [comment]
> If we `touch /usr/include/sys/cdefs.h` then clang works

Whut

can we like, stat that ourselves, and if it doesnt exist, touch it, then configure, then rm it if we added it?

**Comment by erikwilson** [comment]
Yah... ugh. :( Unfortunately -syslibroot flag does some weird things to ld, so even if we add something like -L/usr/lib that doesn't work, although it appears referencing it directly like an object when linking would work (eg `clang -v /usr/lib/libssl.dylib foo.o -o foo`). Or we can go to the new syslibroot in /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib and create a symlink for libssl & libcrypto (why is there not one?).

**Comment by implausible** [comment]
I cant reiterate enough that getting libssh2 to configure against the system lib when we dont respect the system lib or its headers is ill advised :sweat:

**Comment by erikwilson** [comment]
Yah, I agree, it looks like node-gyp is just not getting the LDFLAGS pointing to the right place or completely ignoring them. :(

**Comment by erikwilson** [comment]
Ah, I see, `./utils/configureLibssh2.js` is being opinionated about using an empty environment, if I change line 20 to
```js
var newEnv = Object.assign({}, process.env);
```
then the appropriate LDFLAGS variable is passed to configure. So minimally configureLibssh2.js needs to be doing more configuration, or pass in environment variables.

**Comment by erikwilson** [comment]
Sorry, I didn't really read on to the rest of the code, where there is a comment literally on the next line that talks about MacOs builds failing if we copy the environment.

I think we should treat the code the same and always copy the environment, just need to fix darwin builds. It looks like node-gyp is providing only the headers and not any libraries for OpenSSL.

**Comment by erikwilson** [comment]
After digging a little bit more, found this: https://github.com/nodejs/node-gyp/wiki/Linking-to-OpenSSL

So if node statically links openSSL that makes it very difficult for libssh2 to configure since it doesn't know where or how to test the library is usable, as node-gyp & node don't include the library itself. Forcing the script to download openssl to vendor still fails because --with-libssl-prefix or other config options are never pointed to the right location. 

Although, personally I am beginning to wonder why go through the trouble, using system libssl with system integrity protection enabled may be better than downloading and using some random 3rd party pre-built ssl binary. 

It appears node-gyp does not by default dynamically link the resulting nodegit.node executable anyways (from that link since ~node v0.6, and otool -L), so it appears there are some undefined symbols relating to ssl in the resulting binary (from nm), which presumably the node process itself might provide.

**Comment by implausible** [comment]
Right, so I am advocating to preconfigure libssh2_config.h, the only side effect we utilize in libssh2 configure for osx.

**Comment by erikwilson** [comment]
That sounds like a good solution, the configuration really depends on what is statically linked in node.

As a side note, if I were a malicious node module writer, targeting user writable openssl headers might be a fun idea.

**Comment by implausible** [comment]
Yes, there are definitely some spooky things one could do during npm install. :frowning_face:

**Comment by stevex86** [comment]
This is the `libssh2_config.h` generated on my machine (Mac OS High Sierra):
https://pastebin.com/7usEuVP3

For each of the defines that are turned on, it seems to indicate whether the system has POSIX C headers. Other than that, the interesting ones are `HAVE_LIBSSL`, `HAVE_LIBZ`, and `LIBSSH2_OPENSSL`. Both OpenSSL and zlib are linked into Node. For Electron builds, zlib is provided by libgit2.

Since MacOS is a relatively stable environment, and we don't seem to be using any libraries that are not provided, I feel very safe to provide the `libssh2_config.h` header statically.

**Comment by stevex86** [comment]
I also ran the configure script on my machine against an Electron build and `diff`'d it against the Node build. No differences.

**Comment by maxkorp** [comment]
npm module install scripts are a GIGANTIC attack vector, yes. 

So we'd not need to configure on linux then, either?

**Comment by implausible** [comment]
@erikwilson Does this seem to fix your issues? https://github.com/nodegit/nodegit/pull/1569

**Comment by erikwilson** [comment]
Looks like it works to me. Another option might be to disable just the crypto lib check in configure.ac & generate a new configure, assume openssl will be used.

**Comment by erikwilson** [comment]
Actually, monkeying around with vendor autoconfig stuff probably isn't a good idea either. I don't know the whole repercussion of the build system using electron and byo openssl. Since Apple appears to hate developers and this is only an issue in Mojave (and likely future OSX versions) for verifying openssl availability, as a pre-configure step we could link to /usr/lib in /tmp (eg ln -s /usr/lib /tmp/usrlib) and then pass LDFLAGS=-L/tmp/usrlib or similar to bypass the use of syslibroot flag.

**Comment by implausible** [comment]
So we're not planning on moving away from our conan openssl vendor, and I also agree with you that monkeying around in vendor autoconfig stuff probably isn't a good idea. I think we'll roll with our solution. Once that is merged in I am going to close this issue.

**Comment by erikwilson** [comment]
Cool, I'm not saying that you should move away from conan openssl, just there might be a solution where you can still configure for systems that need it and fix configuring on Mojave.

**Comment by implausible** [comment]
https://github.com/nodegit/nodegit/pull/1569 closes this issue. There is also a new prerelease 0.23.0-alpha.2 on the next tag.
