### ISSUE TITLE
npm install nodegit --no-bin-links

### ISSUE THREAD

**Issue by josephi** [nodegit/nodegit#1567]
## System information
  - node version: 8.11.3
  - npm or yarn version: 5.6.0
  - OS/version/architechture: Windows Server 2008 R2 64x
  - Applicable nodegit version: 0.22.2

```
npm install nodegit --no-bin-links

[nodegit] Running pre-install script
16:53:41 [nodegit] Running install script
16:53:41 events.js:183
16:53:41       throw er; // Unhandled 'error' event
16:53:41       ^
16:53:41 
16:53:41 Error: spawn node-pre-gyp.cmd ENOENT
16:53:41     at _errnoException (util.js:992:11)
16:53:41     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
16:53:41     at onErrorNT (internal/child_process.js:372:16)
16:53:41     at _combinedTickCallback (internal/process/next_tick.js:138:11)
16:53:41     at process._tickCallback (internal/process/next_tick.js:180:9)
16:53:41     at Function.Module.runMain (module.js:695:11)
16:53:41     at startup (bootstrap_node.js:191:16)
16:53:41     at bootstrap_node.js:612:3
```

Hi,

I am trying to install nodegit --no-bin-links but it fails, any clue?

THX

**Comment by implausible** [comment]
It's dying because nodegit needs node-pre-gyp to pull binaries. This is supposed to be in the bin folder for nodegit by design. I would advise not installing nodegit with --no-bin-links.

You can find out more here: https://www.npmjs.com/package/node-pre-gyp

**Comment by josephi** [comment]
> It's dying because nodegit needs node-pre-gyp to pull binaries. This is supposed to be in the bin folder for nodegit by design. I would advise not installing nodegit with --no-bin-links.
> 
> You can find out more here: https://www.npmjs.com/package/node-pre-gyp

Thank for the quick response.
Is there a way to run the package without accessing the web?

**Comment by implausible** [comment]
Are you asking if you can compile the NodeGit binary locally? I assume so, because without the web there'd be no way to pull the necessary node_modules (unless you have your own npm registry cache).
