### ISSUE TITLE
Revwalk.next() always throws an error when reaching the end.

### ISSUE THREAD

**Issue by joshwcomeau** [nodegit/nodegit#1568]
## System information
  - node version: `8.11.1`
  - npm or yarn version: Yarn `1.6.0`
  - OS/version/architechture: MacOS `10.13.2`
  - Applicable nodegit version: `0.22.2`

---

Hi folks!

I'm attempting to walk through the history of commits. I find the OID of the most recent commit, and then I set up an async loop, like:

```js
const init = async () => {
  const repo = await nodegit.Repository.open('... some path');

  const commitId = getMostRecentCommitId(repo)

  const revwalk = nodegit.Revwalk.create(repo);
  revwalk.push(commitId);

  let reachedEnd = false;

  while (!reachedEnd) {
    const oid = await revwalk.next();

    if (!oid) {
      reachedEnd = true;
      continue;
    }

    const commit = await nodegit.Commit.lookup(repo, oid);

    // process commit
  }
}
```

I get the result I want - it iterates through and builds up my commits - but it always ends by throwing:

```
{ Error: Method next has thrown an error. errno: -31, errorFunction: 'Revwalk.next' }
```

This happens with the code above, as well as when using `Revwalk.walk(oid, (err, commit) => { ... })`.

I'm guessing this is unexpected behaviour? I would expect the final iteration to return `null` for the `oid`, not throw an error.

**Comment by rcjsuen** [comment]
@joshwcomeau I believe this is the expected behaviour as it matches what libgit2's API states.

https://github.com/libgit2/libgit2/blob/814e7acbabc2e756f809057b7746e08839c44cde/include/git2/revwalk.h#L199-L217

**Comment by implausible** [comment]
This is the expected behavior. You can check for this error using the provided enum entry: `NodeGit.Error.CODE.ITEROVER`. https://www.nodegit.org/api/error/#CODE
