### ISSUE TITLE
[Documentation] Commit.history() -> EventEmitter, start function missing

### ISSUE THREAD

**Issue by gins3000** [nodegit/nodegit#1571]
Hi, I am using nodegit in a Typescript project, and came across a typings mismatch for which I filed an issue over at DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29969

> `Commit.history()`'s documentation says `Don't forget to call start() on the returned event.` and the return type is `EventEmitter`.
> 
> `EventEmitter` does not have a function called `start()`.

Turns out the documentation at https://www.nodegit.org/api/commit/#history seems to be mismatching already.

As can be seen in the nodejs docs (https://nodejs.org/api/events.html#events_class_eventemitter) there is no start function on EventEmitter.

Perhaps it would be good to review what Commit.history() actually returns and update its return type in the documentation, so that the types can also be updated without conflicting with the official documentation.

**Comment by implausible** [comment]
Fair enough.
