### ISSUE TITLE
Investigate using libcurl from conan

### ISSUE THREAD

**Issue by implausible** [nodegit/nodegit#1577]
Currently we dynamically link against the system libcurl. Since this was introduced, we have had portability problems. It might be better to pull down libcurl from conan and statically link against it.

Things to watch out for:
- the libcurl provided by conan does not come with the appropriate features necessary to authenticate proxy requests over NTLM, Kerberos, Digest, and Basic auth.
- the libcurl has additional dynamic links to satisfy authentication features listed above, making it suffer the same portability problems.

**Comment by rcjsuen** [comment]
Do we only use libcurl because of libgit2? If yes, see libgit2/libgit2#4207.

**Comment by implausible** [comment]
That's right, we don't use libcurl anymore as of v0.25.0 :smile:
