### ISSUE TITLE
I miss NodeGit.Odb.prototype.addDiskAlternate

### ISSUE THREAD

**Issue by novalis** [nodegit/nodegit#1580]
We're using NodeGit.Odb.prototype.addDiskAlternate in https://github.com/twosigma/git-meta.  Until this is replaced, we can't upgrade to 0.24.  

Thanks.

**Comment by implausible** [comment]
I'll make sure this gets back in. Thanks for letting me know.

**Comment by novalis** [comment]
Any word on this?

**Comment by implausible** [comment]
Thanks for the reminder! I've opened a branch for fixing this in 0.25.0.

**Comment by novalis** [comment]
Woot, thanks!
