### ISSUE TITLE
How to iterate over conflicts?

### ISSUE THREAD

**Issue by JCMais** [nodegit/nodegit#1589]
`git_index_conflict_iterator_new` and `git_index_conflict_next` are currently ignored, and I don't see any way to do that on the code.

https://github.com/nodegit/nodegit/blob/2274679c21468a619689c2a2d581d0c4bde29a9c/generate/input/descriptor.json#L1556-L1561

**Comment by implausible** [comment]
```javascript
index.entries().filter((indexEntry) => index.entryIsConflict(indexEntry));
```
