### ISSUE TITLE
Access yarn as an alternative to npm if npm command fail in preinstall script

### ISSUE THREAD

**Issue by rmannibucau** [nodegit/nodegit#1593]
preinstall script relies on npm but on computers with only node+yarn it fails so I guess a fallback on yarn can be an option?

**Comment by LuckyPigeon** [comment]
I can help, but what exactly would you like me to do?

**Comment by rmannibucau** [comment]
I guess a try(npm).catch(useYarn) logic-like can work.

**Comment by rmannibucau** [comment]
It is already there, just need a fallback on yarn in https://github.com/nodegit/nodegit/blob/master/lifecycleScripts/preinstall.js#L10

**Comment by LuckyPigeon** [comment]
I got an error after I use npm test to test my code, the error log show that `jshint: not found`. How can I solve this error?

**Comment by implausible** [comment]
I've restarted that test suite; however, you still have linter errors. Make sure you are using LF terminators and adding EOL LF.
