### ISSUE TITLE
Strange C++ Error probably on Reset

### ISSUE THREAD

**Issue by GCSBOSS** [nodegit/nodegit#1596]
## System information
  - node version: v10.8.0.
  - npm or yarn version: 6.3.0
  - OS/version/architecture: Windows 10 x64 (10.0.17134)
  - Applicable nodegit version: 0.23.0

![image](https://user-images.githubusercontent.com/11818414/49699293-6ad89a80-fbb6-11e8-91e5-1bb4b3524c75.png)

`npm ERR! Exit status 3221225477`

Relevant code: 

```js
let current = await repo.getHeadCommit();
await repo.fetchAll();
let newest = repo.getReferenceCommit('origin/master');
if(current.id == newest.id)
    return;
await Reset(repo, newest, Reset.TYPE.HARD);
```

**Comment by GCSBOSS** [comment]
This fixed the code, though that error should probably be handled more gracefully.
```js
let current = await repo.getHeadCommit();
await repo.fetchAll();
let newest = await repo.getReferenceCommit('origin/master');
if(current.sha() == newest.sha())
    return;
await Reset(repo, newest, Reset.TYPE.HARD);
```

**Comment by implausible** [comment]
We should also be very careful when reading from a repo and writing to a repo at the same time.

**Comment by implausible** [comment]
It's possible we could improve the errors; however, in general passing a promise into a method that doesn't expect it is going to lead to a crash.
