### ISSUE TITLE
[Suggestion] Add docs for installing `libgit2` library

### ISSUE THREAD

**Issue by myuseringithub** [nodegit/nodegit#1633]
Suggestions: 
- **preinstall script**: Add a `preinstall` script to package.json that will fail in case `libgit2` isn't available in the environment 
- **libgit2 installation guide**: I think you should add just a short notice about how to install the `libgit2` library. I personally couldn't seem to find a simple installation guide for Debian. I tried `sudo apt-get install -y libgit2` but the package isn't registered, later I noticed that `libgit2-dev` is available. The guide I expect for Linux Debian is as follows: 

Required machine peer dependency: 
- **libgit2** - `sudo apt-get install -y libgit2-dev`

___
Using `WSL` on Windows 10

**Comment by implausible** [comment]
We either precompile libgit2 in our prebuilts and we ship nodegit such that it will build libgit2 for nodegit on npm install. We have no intention of supporting third party shared copies of libgit2.
