### ISSUE TITLE
Rebase failing on 0.24.0

### ISSUE THREAD

**Issue by tjcarroll11** [nodegit/nodegit#1640]
I recently tried upgrading from `0.18.0` to `0.24.0` and found rebase started consistently failing with this error:

`libgit2 this patch has already been applied errno_ -18`

I reverted to `0.18.0`, and the issue no longer occurs.

## System information
  - node version: v8.9.0
  - npm or yarn version: npm v6.4.1
  - OS/version/architecture: linux 3.10.0
  - Applicable nodegit version: 0.24.0

## Code

I created a wrapper around your repo class to create common operations. I edited this a little to make it more understandable, but here's the what I'm doing. 

```
class RepoWrapper {

    RepoWrapper(repo) {
        this.repo = repo;
    }

    async addAndCommit(name, email, message) {
        let signature = getSignature(name, email);
        let treeOid  = await this.addAll();
        let parent = await this.repo.getHeadCommit();
        return this.repo.createCommit('HEAD', signature, signature, message, treeOid, [parent]);
    }

    async addAll() {
        let status = await this.repo.getStatus();
        let filesToAdd = status.map(oneFile => oneFile.path());
        let index = await this.repo.refreshIndex();
        await index.addAll(filesToAdd);
        await index.write();
        return index.writeTree();
    }

    async resetBackOne() {
        const headCommit = await this.repo.getHeadCommit();
        const resetTo = await headCommit.parent(0);
        return nodegit.Reset.reset(this.repo, resetTo, nodegit.Reset.TYPE.SOFT);;
    }

    async rebase(repo, upstreamName, name, email) {
        const fullUpstreamRef = 'refs/remotes/a-remote-name/' + upstreamName;
        let headBranch = this.repo.getCurrentBranch();
        await Promise.all([
            // this method just fetches the latest version of the branch 
            this.refreshRemoteBranch(upstreamName),
            this.addAndCommit(name, email, 'Commit temp commit')
        ]);
        // Gets the branch with some additional metadata
        const newBaseBranch = await this.getBranch(fullUpstreamRef);
        let success;
        try {
            await this.repo.rebaseBranches(
                headBranch.longName,
                fullUpstreamRef,
                null,
                nodegit.Signature.now('Name', 'email@email.com')
            );
            await this.resetBackOne();
            success = true;
        } catch(err) {
            console.log(err);
            success = false;
        }
        return {success, newBaseBranch};
    }
}
```

**Comment by implausible** [comment]
When this error is thrown by `rebaseBranches`, it gives a user of the library an opportunity to decide how they want to continue. At this point, your only valid options are to change the content in the index, abort the rebase, or continue the rebase. If you receive this error and do not want to provide user input on what to do next, you can use https://www.nodegit.org/api/repository/#continueRebase

**Comment by tjcarroll11** [comment]
Thanks for the quick response! So what causes this error? How do I avoid it in the first place?

**Comment by implausible** [comment]
Say that you have some branches like:
```
a -> b -> c => branch 1
 \ -> e -> c -> f => branch 2
```
Where the commit `c` represents an equivalent change in branches 1 and 2. If you rebase branch 2 onto branch 1, when trying to replay commit `c`, the rebase operation will fail to change anything in the index, because the changes in `c` have already been applied. What this means is that for 2 arbitrary branches, it is not easily detectable that this situation will happen, so it must be taken into account when running your rebase.

Our helper functions `rebaseBranches` and `continueRebase` wrap libgit2's rebase iterator and throw when it encounters this scenario so that a user of our API can decide what to do for that particular operation.

**Comment by tjcarroll11** [comment]
Ah that makes sense. Thanks!
