### ISSUE TITLE
CherryPick.cherrypick return undefined

### ISSUE THREAD

**Issue by Hikyu** [nodegit/nodegit#1646]
## System information
  - node version: v10.7.0
  - npm or yarn version: 6.1.0
  - OS/version/architecture: windows 10
  - Applicable nodegit version: 0.24.1

## Example
```
    let repo = await repository()
    let oid = await Git.Oid.fromString(ref)
    let commit = await Git.Commit.lookupPrefix(repo, oid, ref.length)
    console.log(commit.message())
    Git.Cherrypick.cherrypick(repo, commit, {}).then(res=>{
        console.log(res) // undefined
    })
```

**Comment by rcjsuen** [comment]
The documentation is a bit weak here. If the promise resolves then you can assume that the operation completed successfully. You don't need to check for a return code.

**Comment by Hikyu** [comment]
> The documentation is a bit weak here. If the promise resolves then you can assume that the operation completed successfully. You don't need to check for a return code.

@rcjsuen But When a conflict occurs，the operation also completed successfully。

**Comment by rcjsuen** [comment]
@Hikyu Ah. Sounds like you need to use `repository.state()` then and compare it with one of the [`Repository.STATE` enums](https://www.nodegit.org/api/repository/#STATE).

Does that help?

**Comment by Hikyu** [comment]
> @Hikyu Ah. Sounds like you need to use `repository.state()` then and compare it with one of the [`Repository.STATE` enums](https://www.nodegit.org/api/repository/#STATE).
> 
> Does that help?

@rcjsuen Whether or not conflict  happens, repository.state() return CHERRYPICK, and how can I tell these things? thanks

**Comment by rcjsuen** [comment]
@Hikyu You can check using [`Index`'s `hasConflicts()` function](https://www.nodegit.org/api/index/#hasConflicts).

```JavaScript
return Cherrypick.cherrypick(repo, commit, {})
.then(function() {
  return repo.index();
})
.then(function(index) {
  // this will return 1 or 0
  console.log(index.hasConflicts());
});
```
Does this help?

**Comment by Hikyu** [comment]
@rcjsuen  It works, thank you!

**Comment by rcjsuen** [comment]
@Hikyu Happy to help! Good luck with your project!
