### ISSUE TITLE
Add named constants for possible flags in DiffOptions, etc.

### ISSUE THREAD

**Issue by J-Fields** [nodegit/nodegit#1648]
For instance, to get `--ignore-space-at-eol` behavior when diffing, you must put `16777216` into `DiffOptions.flags`.  There should be named constants for this and other such bitmap parameters. Mappings exist in `generate/input/libgit2-docs.json` already, but are not available in code.
I'm happy to submit a pull request if necessary.

## System information
  - node version: v10.15.1
  - npm version: 6.4.1
  - OS/version/architecture: win32 x64
  - Applicable nodegit version: 0.24.1

**Comment by implausible** [comment]
Perhaps https://www.nodegit.org/api/diff/#OPTION is what you're looking for?

**Comment by J-Fields** [comment]
Thanks @implausible. This isn't very well documented from what I can tell - do you think we could mention this at https://www.nodegit.org/api/diff_options/ for instance?
