### ISSUE TITLE
Where are the prebuild binaries hosted?

### ISSUE THREAD

**Issue by s-a** [nodegit/nodegit#1651]
I try write a deployment of an application using Zeit''s pkg. I need to figure out where to get the prebuild binaries for `nodegit.node` My plan is to write a short script to download them automatically respecting the corrent node version and os target. I found something like `https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-node-v45-linux-x64.tar.gz` online but cannot access these files. Does there exist a list of available downloads with version an os info?

upd:  
I just found this https://npm.taobao.org/mirrors/nodegit/v0.24.1/ but it does not contain `x86` binaries. Is there a similiar official URL out there?

**Comment by implausible** [comment]
v0.16.0 is far out of our support range for nodegit. More recent versions are located in the https://axonodegit.s3.amazon.aws.com/nodegit/nodegit bucket.

**Comment by s-a** [comment]
Thanks for your reply. `0.16.0` was just an URL example. Id like get the latest version. https://axonodegit.s3.amazon.aws.com/nodegit/nodegit return s `404`

**Comment by implausible** [comment]
It's a bit complicated to work out, but you'll want to start here:
https://github.com/mapbox/node-pre-gyp.

The format you're looking for the files you're looking for are: `{module_name}-v{version}-{node_abi}-{platform}-{arch}.tar.gz`. So the NodeGit pre-gyp file for your v0.16.0 on linux for x64 and on node 6 would be like: `nodegit-v0.16.0-node-v48-linux-x64.tar.gz`.

**Comment by JoshuaCWebDeveloper** [comment]
If you have the AWS CLI installed, you can list all available releases by running:
```bash
aws s3 ls axonodegit/nodegit/nodegit/ --no-sign-request
```
