### ISSUE TITLE
Some problems with the fs‘ writeSync function

### ISSUE THREAD

**Issue by wjz1209391890** [nodegit/nodegit#1652]
node version: 10.14.0
npm or yarn version: yarn v6.4.1
OS/version/architecture: windows 10  x64

In the program, the writeSync method of the fs module is called multiple times. If the power-off operation is performed midway, part of the file content is empty, but the file size exists. Is this because the partial cache is not flushed to the disk?

**Comment by implausible** [comment]
I'm sorry, but unless you can provide more details you might be looking for https://github.com/nodejs/node.
