### ISSUE TITLE
Does nodegit support `git-upload-pack`?

### ISSUE THREAD

**Issue by saoudrizwan** [nodegit/nodegit#1655]
I'm trying to allow clients to clone git repos from my server. Of course there's some back and forth that needs to be done before the official packs are sent, but for now I'm forking a process that calls 
`git-`(`upload-pack` or `receive-pack`)`--stateless-rpc <local working directory>`
to communicate with the client. Any guidance would be appreciated.

**Comment by implausible** [comment]
https://libgit2.org/libgit2/#HEAD/group/remote/git_remote_upload
https://www.nodegit.org/api/remote/#upload

**Comment by julien-c** [comment]
@saoudrizwan Do you have an example of you want about it? That would be super helpful
