### ISSUE TITLE
How to git push --force-with-lease

### ISSUE THREAD

**Issue by guillaumewuip** [nodegit/nodegit#1660]
## System information
  - node version: any
  - npm or yarn version: any
  - OS/version/architecture: any
  - Applicable nodegit version: any

```
node -v
npm -v # (or yarn -v)
node -e "console.log(process.platform)"
node -e "console.log(require('os').release())"
node -e "console.log(console.log(process.arch))"

// not usefull for this issue
```

I want to do a `git push --force-with-lease` (see [git documentation](https://git-scm.com/docs/git-push#Documentation/git-push.txt---no-force-with-lease)) with NodeGit but  I don't find any mention of this in the docs. Is it possible ?
For now I'm using regular `force` (as explain in https://github.com/nodegit/nodegit/issues/1270)  but it's dangerous for my use case.

**Comment by rcjsuen** [comment]
There is no support for this in libgit2 at the moment (see libgit2/libgit2#3947).

It sounds to me like if you wanted to implement this by hand, that you'd first fetch to check the remote refs and compare it with yourself and then push if it works out...?

**Comment by guillaumewuip** [comment]
Yep @rcjsuen I think this is the only way to do something similar :) 
Thanks !
