### ISSUE TITLE
How to clone tags?

### ISSUE THREAD

**Issue by EneOli** [nodegit/nodegit#1687]
Hello everyone,

as the title says, I would like to know how to clone a specific tag via Clone(...);
Thank you very much.

**Comment by EneOli** [comment]
Nevermind, we use now isomorphic-git, which supports this feature. Closing issue

**Comment by mfechner** [comment]
Very nice tip, switch now also to isomorphic-git as it works perfectly fine with node version 12.

**Comment by EneOli** [comment]
P.S. isomorphic-git does not relay on node-gyp and does not need to be build and even works on browsers.
