### ISSUE TITLE
Can I listen to file changes in the local repository?

### ISSUE THREAD

**Issue by zangxx66** [nodegit/nodegit#1692]
## System information
  - node version:10.15.3
  - npm or yarn version:6.4.1
  - OS/version/architecture: win32 10.0.18362 x64
  - Applicable nodegit version:0.24.3

```
node -v
npm -v # (or yarn -v)
node -e "console.log(process.platform)"
node -e "console.log(require('os').release())"
node -e "console.log(console.log(process.arch))"
```
Can I listen to file changes in the local repository?

**Comment by implausible** [comment]
No, you'll want an external library for watching changes in a folder. See https://npmjs.com/package/nsfw or https://npmjs.com/package/chokidar.
