### ISSUE TITLE
Can node-gyp be shipped as a devDependency?

### ISSUE THREAD

**Issue by aaronjanse** [nodegit/nodegit#1700]
I've noticed that `node-gyp` significantly increases the install time for `nodegit`.

My understanding is that we only need `node-gyp` when building, so can we move `node-gyp` from `dependencies` to `devDependencies` in the `package.json`?

**Comment by tbranyen** [comment]
Unfortunately not, otherwise if a user attempted to compile with `npm install nodegit` the build chain would be incomplete. Prebuilt binaries are not available for all platforms.
