### ISSUE TITLE
Async functions seem to not return real Promises

### ISSUE THREAD

**Issue by micha149** [nodegit/nodegit#1714]
## System information
  - node version: v10.16.0
  - npm or yarn version: 6.9.0
  - OS/version/architecture: OSX 10.13.6
  - Applicable nodegit version: 0.25.1

## Problem
I am using `Git.Remote.list()` to get my remotes. The resulting Promise is handled by some other 3rd Party code and I am wondering why this code assumes that my return value is not a  Promise. After inspecting the code and the actual return values I noticed, that `nodegit` doesn't return native NodeJS `Promise` instances.

## Steps to reproduce
```
const Git = require('nodegit');
console.log(Git.Remote.list(`${process.cwd()}/.git`) instanceof Promise); // false
```

**Comment by JoostK** [comment]
Nodegit uses a an implementation that follows the [Promises/A+](https://promisesaplus.com) specification, specifically https://github.com/nodegit/promise. According to that spec, everything with a `then` method with predetermined behavior is considered a "Promise":

> “promise” is an object or function with a then method whose behavior conforms to this specification.

The `async`/`await` JavaScript language feature is also able to deal with these kinds of non-native promises just fine, you can read more [here](https://esdiscuss.org/topic/awaiting-thenables).

So I would argue that an implementation testing for promises using `instanceof Promise` is not desirable, it should just test for a _thenable object_ instead.

**Comment by micha149** [comment]
You are totally right. I opened a [pull request on yargs](https://github.com/yargs/yargs/pull/1424).
