### ISSUE TITLE
Cloning progress

### ISSUE THREAD

**Issue by dan-online** [nodegit/nodegit#1732]
## System information
  - node version: v12.10.0
  - npm or yarn version: 6.11.3
  - OS/version/architecture: MacOS 10.13.6
  - Applicable nodegit version: 0.26.2

I am having trouble figuring out how to log to console the progress of cloning. Here is what I've tried:
```javascript
     nodeGit.Clone("https://github.com/dan-divy/spruce", __dirname + "/spruce", {
        transferProgress: {
          callback: (progress) => {
            console.log(progress)
          }
        }
      }).then(function() {
        console.log("Done")
      }).catch(err => {
        console.error(err)
      })
```

No errors are reported and nothing is logged to console. Perhaps I am doing something wrong but I can't find any documentation on this.

**Comment by rcjsuen** [comment]
@dan-online I think your options are "too simply". You need to use `transferProgress` inside of your `fetchOtps`. Does this help?

https://github.com/nodegit/nodegit/blob/5959031f75bc1181619e1379fdf98f5527cfce02/test/tests/clone.js#L58-L71

**Comment by dan-online** [comment]
Oh thats great thanks! Also how would I choose what branch to clone?
