### ISSUE TITLE
Library does not work in node worker threads - Module did not self-register.

### ISSUE THREAD

**Issue by Georgegriff** [nodegit/nodegit#1755]
I've seen this with a few native modules that when they try to be used within the new NodeJS Workers feature they don't work. 

I've been using this lib via a E2E test framework so a little hard to reproduce
The error message you get is `Module did not self-register.` I think this is potentially a load order issue and i've seen the same issue with other native libraries:

https://github.com/codecept-js/codeceptjs-resemblehelper/issues/57

Similar issue: https://github.com/ethereum/web3.js/issues/2723

**Comment by implausible** [comment]
We're not quite ready for this transition. We are aiming to move to NAPI in the near term to address this issue

**Comment by Georgegriff** [comment]
Awesome :)

**Comment by FerrisW** [comment]
> I'm currently seeing this error attempting to use nodegit within a VSCode extension.
> 
> What needs to be done to migrate to NAPI?

+1 
Is ther any way to solve it?

**Comment by lszomoru** [comment]
I gave this a try with `0.28.0-alpha.18` and I am still getting the same error.
