### ISSUE TITLE
nodegit depends on deprecated package request-promise-native

### ISSUE THREAD

**Issue by mpiroc** [nodegit/nodegit#1759]
nodegit depends on `request-promise-native`, which is deprecated (along with the underlying `request` package) as of Feb 11, 2020. This causes npm to print deprecation warnings at install time. This may also cause failures in CI systems that treat any output to stderr as an error, but I haven't confirmed this.

Additionally, `nodegit` does not declare a `dependency` or `peerDependency` on `request`, which is a peer dependency of `request-promise-native`. Not sure if this is intentional.

## System information
  - node version: 12.14.1
  - npm or yarn version: npm 6.13.4
  - OS/version/architecture: Windows 10/x64
  - Applicable nodegit version: All (including current release 0.26.5).

```
PS C:\Users\matth> node -v
v12.14.1
PS C:\Users\matth> npm -v # (or yarn -v)
6.13.4
PS C:\Users\matth> node -e "console.log(process.platform)"
win32
PS C:\Users\matth> node -e "console.log(require('os').release())"
10.0.18363
PS C:\Users\matth> node -e "console.log(console.log(process.arch))"
x64
```

**Comment by implausible** [comment]
This is no longer the case from 0.27.0-alpha.1 on.
