### ISSUE TITLE
nodegit gives lifecycle error with missing krb-config while runninng on centos in Docker

### ISSUE THREAD

**Issue by 27prajaktapatil** [nodegit/nodegit#1763]
## System information
  - node version: 8.12.0
  - npm or yarn version: 6.4.1
  - OS/version/architecture: CentOS
  - Applicable nodegit version: 0.26.4

```
node -v
npm -v # (or yarn -v)
node -e "console.log(process.platform)"
node -e "console.log(require('os').release())"
node -e "console.log(console.log(process.arch))"
```
error details: 

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for nodegit@0.26.5 and node@8.12.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error socket hang up
/bin/sh: krb5-config: command not found
gyp: Call to 'krb5-config gssapi --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack
at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/mnt/workspace/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/mnt/workspace/node_modules/nodegit/build/Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57" "--python=python2.7"
gyp
ERR! cwd /mnt/workspace/node_modules/nodegit
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp
ERR! not ok
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/mnt/workspace/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/mnt/workspace/node_modules/nodegit/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57 --python=python2.7' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mnt/workspace/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.19.76-linuxkit
node-pre-gyp ERR! command "/usr/local/bin/node" "/mnt/workspace/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /mnt/workspace/node_modules/nodegit
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/mnt/workspace/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/mnt/workspace/node_modules/nodegit/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57 --python=python2.7' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm WARN mocha-multi@0.5.0 requires a peer of mocha@>=1.15.1 <3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN projectName@0.0.1 No repository field.
npm WARN projectName@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.26.5 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.26.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/some_logs-debug.log
npm install failed

**Comment by implausible** [comment]
Please refer to the readme before opening an issue.
https://github.com/nodegit/nodegit/blob/master/README.md#getting-started
