### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.20' not found on CentOS

### ISSUE THREAD

**Issue by 27prajaktapatil** [nodegit/nodegit#1765]
## System information
  - node version: 8.12.0
  - npm or yarn version: 6.4.1
  - OS/version/architecture: CentOs 7-5
  - Applicable nodegit version: 0.26.4

```
node -v
npm -v # (or yarn -v)
node -e "console.log(process.platform)"
node -e "console.log(require('os').release())"
node -e "console.log(console.log(process.arch))"
```

Hello , I am trying to install nodegit on CentOs 7-5, inside a Docker container. Whenever npm or yarn tries to install nodegit, it gets an error "Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /workspace/node_modules/nodegit/build/Release/nodegit.node)"

I have already read and studied the readme, but it does not say anythinng about resolvinng this issue on CentOs

**Comment by implausible** [comment]
I've used this in a centos 7 docker build in the past:
```
RUN yum update -y
RUN yum upgrade -y
RUN yum install -y curl openssl-devel libcurl-devel python make glibc-devel gcc gcc-c++ krb5-devel
```

This is assuming your doing the nodegit build _inside of docker_, because if you're not doing it inside of docker, you may be compiling nodegit for different libraries than what is being used inside of your docker environment.

**Comment by 27prajaktapatil** [comment]
Thanks a lot @implausible , this worked.

**Comment by cameron-martin** [comment]
This seems to no longer work. Try building the following Dockerfile for evidence:

```
FROM centos:centos7

RUN yum update -y \
    && yum upgrade -y \
    && yum install -y curl openssl-devel libcurl-devel python make glibc-devel gcc gcc-c++ krb5-devel

RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash - \
 && yum install -y nodejs

RUN groupadd jenkins \
    && useradd -d /home/jenkins -g jenkins -m -s /bin/bash jenkins

USER jenkins
WORKDIR /home/jenkins

RUN npm install nodegit

RUN node -p "require('nodegit')"
```
