### ISSUE TITLE
How to use nodegit with Pulumi/Typescript?

### ISSUE THREAD

**Issue by vitobotta** [nodegit/nodegit#1769]
```
node -v
v12.12.0

npm -v # (or yarn -v)
6.11.3

node -e "console.log(process.platform)"
darwin

node -e "console.log(require('os').release())"
19.3.0

node -e "console.log(console.log(process.arch))"
x64
```

Hi! I am trying to use this package with Typescript in Pulumi, with the goal to clone a git repository. I am new to Typescript so I am having a hard time figuring out how to use nodegit with this..... I am trying the package `@types/nodegit` because I think I should be using this one with TS (?), but if I try to use nodegit  as described on nodegit.org, I get `Value of type 'typeof Clone' is not callable. Did you mean to include 'new'?`.

I am importing the package like this:

```
import * as Git from "nodegit"
```

and am trying to clone the repo like this:

```
const veleroChartRepo  = Git.Clone("https://github.com/vmware-tanzu/helm-charts.git", "/tmp/velero-chart")
```

If I do `new Git.Clone` then it complains that I am giving two arguments but none are expected.

Please be patient, I'm new to this 🗡 
Thanks!

**Comment by implausible** [comment]
The typing in the typescript package is not official and is incorrect. `NodeGit.Clone` is a function. They may have set it up so only the alias `NodeGit.Clone.clone` is callable. Try leveraging the second signature and also open an issue with the @types/nodegit package.

**Comment by vitobotta** [comment]
Thanks @implausible !
