### ISSUE TITLE
DiffStats exists in documentation, but not in project

### ISSUE THREAD

**Issue by NickHackman** [nodegit/nodegit#1775]
```
nodegit version: "0.26.5"
```
[documentation](https://www.nodegit.org/) mentions that `DiffStats` is experimental, but it doesn't exist at all in the current version of `nodegit`. Am I missing something? 

Will this and [`getStats`](https://www.nodegit.org/api/diff/#getStats) be implemented? The changelog mentions adding them, but doesn't mention them being removed at any point.

**Comment by implausible** [comment]
Closed because `getStats` is implemented and `DiffStats` is the return value of `getStats`.

**Comment by NickHackman** [comment]
@implausible thanks, going to update the `@types/nodegit` to account for them! :+1:
