### ISSUE TITLE
Unable to clone on AWS-EFS (NFS) failed to truncate pack file Permission denied

### ISSUE THREAD

**Issue by Georgegriff** [nodegit/nodegit#1776]
## System information
  - node version: 12
  - npm or yarn version: 
  - OS/version/architecture: Kubernetes (Docker image on ubi8-minimal as non-root user) writing to shared mount that is AWS-EFS (which i belive uses nfs)
  - Applicable nodegit version: 0.26.5

![image](https://user-images.githubusercontent.com/9056958/84484514-c6e01b80-ac92-11ea-83cf-2dfc3c4a17e8.png)

Apologies if this should be opened in libgit2 opening here incase there something that could be done in nodegit

We have confirmed outside of the library in restricted we can:
- Write to shared mount
- Read from shared mount
- Delete from shared mount

May be related too: 

https://github.com/JuliaLang/Pkg.jl/issues/1247
https://github.com/libgit2/git2go/issues/194

More detail:

```bash
[2020-06-12T10:04:44.858] [ERROR] remotes - Error testing remote connection [Error: failed to truncate pack file '/mnt/assets/git/tmp/41091e79-81df-48f2-a5a0-d6a901b1
2e82/objects/pack/pack_git2_wXV3By': Permission denied] {
  errno: -1,                                             
  errorFunction: 'Remote.fetch'
} 

```

```bash
bash-4.4$ ls -la /mnt/assets/git/tmp/5fc54c2b-b118-4e97-a062-300d946a43ce/
total 36
drwxr-sr-x. 6 1000680000 2002 6144 Jun 12 10:06 .
drwxr-sr-x. 3 1000680000 2002 6144 Jun 12 10:06 ..
-rw-r--r--. 1 1000680000 2002   23 Jun 12 10:06 HEAD
-rw-r--r--. 1 1000680000 2002  182 Jun 12 10:06 config
-rw-r--r--. 1 1000680000 2002   73 Jun 12 10:06 description
drwxr-sr-x. 2 1000680000 2002 6144 Jun 12 10:06 hooks
drwxr-sr-x. 2 1000680000 2002 6144 Jun 12 10:06 info
drwxr-sr-x. 4 1000680000 2002 6144 Jun 12 10:06 objects
drwxr-sr-x. 4 1000680000 2002 6144 Jun 12 10:06 refs
bash-4.4$ ls -la /mnt/assets/git/tmp/5fc54c2b-b118-4e97-a062-300d946a43ce/objects/
total 16
drwxr-sr-x. 4 1000680000 2002 6144 Jun 12 10:06 .
drwxr-sr-x. 6 1000680000 2002 6144 Jun 12 10:06 ..
drwxr-sr-x. 2 1000680000 2002 6144 Jun 12 10:06 info
drwxr-sr-x. 2 1000680000 2002 6144 Jun 12 10:06 pack
bash-4.4$ ls -la /mnt/assets/git/tmp/5fc54c2b-b118-4e97-a062-300d946a43ce/objects/pack/
total 224
drwxr-sr-x. 2 1000680000 2002   6144 Jun 12 10:06 .
drwxr-sr-x. 4 1000680000 2002   6144 Jun 12 10:06 ..
-r--r--r--. 1 1000680000 2002 219220 Jun 12 10:06 pack-0eea1f7c2b3bc716ed30f7e38044075e54010a41.idx
bash-4.4$
```

Notice that the last entry has an odd group ownership 

```
-r--r--r--. 1 1000680000 2002 219220 Jun 12 10:06 pack-0eea1f7c2b3bc716ed30f7e38044075e54010a41.idx
```

**Comment by implausible** [comment]
This will need to go upstream to libgit2.

**Comment by Georgegriff** [comment]
Ref issue https://github.com/libgit2/libgit2/issues/5556 closing

**Comment by AdamGold** [comment]
Any news regarding this?

**Comment by poeschko** [comment]
The issue libgit2/libgit2#5556 has been resolved in libgit2, so it seems this is waiting for nodegit to upgrade to a recent version of libgit2.
