### ISSUE TITLE
Node 14 support

### ISSUE THREAD

**Issue by mchepel** [nodegit/nodegit#1780]
## System information
  - node version: v14.5.0
  - npm version: 6.14.5
  - OS/version/architecture: Ubuntu 16.04 LTC - linux 4.4.0-89-generic x64
  - Applicable nodegit version: v0.26.5

nodegit failing to install with Node 14

**Comment by implausible** [comment]
We're not always prepared to work on the bleeding edge node releases. We often skip odd releases entirely and focus only on Active LTS or Maintenance LTS releases. You can expect that we will definitely support Node 14 by the time it's in LTS.

See https://nodejs.org/en/about/releases/. The developers of Node are pretty specific about what should or should not be used in production:
| Production applications should only use Active LTS or Maintenance LTS releases.

**Comment by klebba** [comment]
@implausible According to the link, Node 14 will enter LTS on October 20 — a little over 80 days from now — it would be helpful to be able to develop using `nodegit` + Node 14 before then so that we can cut over to the new LTS when it's ready. Thanks!

**Comment by implausible** [comment]
This will be solved today by 0.27.0

**Comment by klebba** [comment]
Thanks!
