### ISSUE TITLE
Feature request: ability to override Commit Date.

### ISSUE THREAD

**Issue by sure-hand** [nodegit/nodegit#1786]
I'm have a tool written which reads revisions of some configuration stored in our internal database and I want to export each revision as a JSON file and commit it to Git. But I need to set the Git commit date to the revision date in our database.

As far as I can tell, this is currently not supported. Or is it?

**Comment by rcjsuen** [comment]
@sure-hand If you create the `Commit` with a `Signature`, you should be able to set the time.

**Comment by implausible** [comment]
https://www.nodegit.org/api/repository/#createCommit takes a signature for both author and committer. Time can be set on the signature https://www.nodegit.org/api/signature/#create
