### ISSUE TITLE
Description of "origin" in DiffLine (missing documentation)

### ISSUE THREAD

**Issue by Etienne-Buschong** [nodegit/nodegit#1796]
I am currently trying to parse some information using the [DiffLine](https://www.nodegit.org/api/diff_line/) object. I am not quite sure what the instance variable `origin` represents, since the documentation is missing. Can someone clear this up for me?

Thanks in advance.

**Comment by implausible** [comment]
Field in libgit2: https://libgit2.org/libgit2/#HEAD/type/git_diff_line
Possible values in libgit2: https://libgit2.org/libgit2/#HEAD/type/git_diff_line_t
Enum in NodeGit: https://www.nodegit.org/api/diff/#LINE
