### ISSUE TITLE
Clone.clone checkoutOptions and their callback crash

### ISSUE THREAD

**Issue by MMcKester** [nodegit/nodegit#1798]
Hi,

I use [Clone.clone][1] and I am looking for a progress status callback. The function has a [CheckoutOptions][2] object, which I call like this:

```
var opts: CloneOptions = {};
opts.checkoutOpts = {
    progressCb: function() {
        console.log("Foo");
    },
}
```

But that seems to crash the BrowserWindow of my electron app where I use this. Does anyone know, by looking at the declaration of `CheckoutOptions` what I might doing wrong?

**Notice, `CheckoutOptions` is a member of `CloneOptions`**

```
export class CheckoutOptions {
    version?: number;
    checkoutStrategy?: number;
    disableFilters?: number;
    dirMode?: number;
    fileMode?: number;
    fileOpenFlags?: number;
    notifyFlags?: number;
    notifyCb?: any;
    notifyPayload?: undefined;
    progressCb?: any;
    progressPayload?: undefined;
    paths?: Strarray | string | string[];
    baseline?: Tree;
    baselineIndex?: Index;
    targetDirectory?: string;
    ancestorLabel?: string;
    ourLabel?: string;
    theirLabel?: string;
    perfdataCb?: any;
    perfdataPayload?: undefined;
    [key: string]: any;
}

export class CloneOptions {
    version?: number;
    checkoutOpts?: CheckoutOptions;
    fetchOpts?: FetchOptions;
    bare?: number;
    local?: number;
    checkoutBranch?: string;
    repositoryCbPayload?: any;
    remoteCbPayload?: any;
}
```

Thank you very much!

  [1]: https://www.nodegit.org/api/clone/
  [2]: https://www.nodegit.org/api/checkout_options/

**Comment by implausible** [comment]
This will be fixed in https://github.com/nodegit/nodegit/pull/1795. It looks like we specified the wrong return type for `git_checkout_progress_cb`
