### ISSUE TITLE
Symbol not found on macOS High Sierra

### ISSUE THREAD

**Issue by autr** [nodegit/nodegit#1804]
Hello, I am having the same bug as documented here:

https://github.com/nodegit/nodegit/issues/1622

**MacOS High Sierra**
Node v13.12.0
nodegit 0.27.0
Electron 6.1.11

```
App threw an error during load
[1] Error: dlopen(/Users/Gilbert/Code/multigit/node_modules/nodegit/build/Release/nodegit.node, 1): Symbol not found: _EVP_aes_128_cbc
[1]   Referenced from: /Users/Gilbert/Code/multigit/node_modules/nodegit/build/Release/nodegit.node
[1]   Expected in: flat namespace
```

**Comment by implausible** [comment]
Electron 6 is no longer supported and we no longer build prebuilts for it as such. I recommend upgrading to at least Electron 8. Also make sure that you follow this guide when leveraging native node modules and Electron. https://www.electronjs.org/docs/tutorial/using-native-node-modules

**Comment by weiweian90** [comment]
Electron 11.0.0 have same problem

**Comment by gpetrov** [comment]
We are experiencing the same issue in Electron 18, please reopen @implausible
