### ISSUE TITLE
Pre-built binaries for node 14.15.0 on Windows

### ISSUE THREAD

**Issue by MrWolfZ** [nodegit/nodegit#1805]
## System information
  - node version: 14.15.0
  - npm or yarn version: 6.14.8
  - OS/version/architecture: Windows 10 x64
  - Applicable nodegit version: 0.26.5

## Actual behavior

When running `npm i` on a Windows system using node 14.15.0 and using nodegit 0.26.5 the installation fails with the following error:

```
WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.26.5-node-v83-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.26.5 and node@14.15.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)
```

Since node 14 is now in LTS since a few days I would expect a pre-built binary to exist.

## Expected behavior

`npm i` finds a pre-built binary and succeeds without an error.

**Comment by MrWolfZ** [comment]
As a side-note, since access to `https://axonodegit.s3.amazonaws.com/nodegit/nodegit` is denied, is there a way to check which pre-built binaries exist?

**Comment by julien-c** [comment]
Yes, I'm doing it via the aws cli:

```
aws s3 ls --recursive s3://axonodegit/nodegit
```

**Comment by julien-c** [comment]
In your case, why don't you upgrade to `nodegit-v0.27.0`? 

I can see there's a prebuilt version there.

**Comment by MrWolfZ** [comment]
Perfect, thanks for the hint on how to check for available versions. I should have thought about checking for the latest lib version. Updating to another nodegit version is perfectly fine, I'll do that and close this issue.
