### ISSUE TITLE
How do you tell if there are actually changes? EG `git status`

### ISSUE THREAD

**Issue by mikestopcontinues** [nodegit/nodegit#1807]
I do some processing using `nodegit`, but I'd like to avoid adding extra commits if there aren't actually any changes. So lets say I'm building an index as follows:

```js
const index = await repo.refreshIndex();
await fs.writeFile(file, data);
await index.addByPath(file);
```

How do I see if the index has true changes? In my case, it's entirely possible the file I wrote is identical to its previous state.

**Comment by ithil** [comment]
I think [`Repository#getStatus`](https://www.nodegit.org/api/repository/#getStatus) is what you're looking for?

Something like this might work:

```javascript
const path = require('path')

...

const index = await repo.refreshIndex()
await fs.writeFile(file, data)
await index.addByPath(file)

repo.getStatus().then(function(arrayStatusFile) {
    var changedFiles = arrayStatusFile.map(e => path.join(pathToRepo, e.path())) // To get absolute paths
    if (changedFiles.includes(file)) {
        console.log('File has changed!')
        // Do commit here
    }
})
```

**Comment by mikestopcontinues** [comment]
@ithil Exactly what I was looking for! Thanks!
