### ISSUE TITLE
unable to get line deletions out of the API

### ISSUE THREAD

**Issue by 3p3r** [nodegit/nodegit#1811]
## System information
  - node version: 12.18.0
  - npm or yarn version: 6.14.8
  - OS/version/architecture: Ubuntu 18.04 x64
  - Applicable nodegit version: 0.27.0

Hello!

I am confused on how to consume the API to get line deletions.

Basically I want line numbers with their respective additions / deletions. Similar to how most Git GUIs highlight lines red and green respectively for characters that were deleted and added.

So far I have this piece of code that only gives me additions. How do I get the deletions?

```
const repo = await Git.Repository.open(process.cwd())
const commit = await repo.getHeadCommit()
console.log(`author email: ${commit.author().email()}`);
console.log(`author name: ${commit.author().name()}`);
console.log(`commit date: ${commit.date().getTime()}`);
console.log(`commit message: ${commit.message().trim()}`);
console.log(`commit signature: ${commit.sha()}`);
const diffs = await commit.getDiff();
diffs.forEach(async diff => {
    const patches = await diff.patches()
    patches.forEach(async patch => {
        const hunks = await patch.hunks()
        hunks.forEach(async hunk => {
            const lines = await hunk.lines();
            const contents = lines.map(line => line.content()).join('')
            console.log(`diff ${diff}, patch ${patch}: ${contents}`)
        })
    })
})
```

**Comment by implausible** [comment]
See the documentation on DiffLine https://www.nodegit.org/api/diff_line/

**Comment by 3p3r** [comment]
@implausible I am using `DiffLine` in the code I put above, but I don't see an API to get the deletions. `content()` just returns the additions.

**Comment by implausible** [comment]
Take a look at the source documentation from libgit2 https://libgit2.org/libgit2/#HEAD/type/git_diff_line.

**Comment by 3p3r** [comment]
OK that slightly makes more sense. So how do Git visualizers show this red/green comparison of old/new content? Am I looking at the wrong API here?

**Comment by implausible** [comment]
The diff lines are in order in each hunk. those with -1 for old_lineno are new lines, those with -1 for new_lineno are deleted lines... Since the ordering of the patch/hunk/line is stable, you can loop over each patch/hunk/line and display them in order and use the line info to determine whether its red, green, or neutral

**Comment by 3p3r** [comment]
thanks for the incredible explanation. that solves my problem I believe.
