### ISSUE TITLE
Disable compression of nodegit

### ISSUE THREAD

**Issue by Githubber2021** [nodegit/nodegit#1815]
## System information
  - node version: v14.15.0
  - npm or yarn version: 6.14.10
  - OS/version/architecture: darwin
  - Applicable nodegit version: 20.2.0

Hi, I am sorry if this is not the right place to ask, but I am trying to disable the compression/packing in nodegit. Git has a config called `config.compression` which isn't supported by libgit2. Does anyone have an idea how I can disable this via nodegit, or is this a question exclusively for libgit2?

Thanks!

**Comment by rcjsuen** [comment]
@Githubber2021 NodeGit is a wrapper around libgit2 so you should probably take this up with them.

**Comment by Githubber2021** [comment]
Allright, thank you!
