### ISSUE TITLE
Mismatched nodegit release/version?

### ISSUE THREAD

**Issue by nkavian** [nodegit/nodegit#1817]
## System information
  - node version: v14.13.1
  - npm or yarn version: 6.14.11
  - OS/version/architecture: Mac OS 10.14.6
  - Applicable nodegit version: 0.27.0

Compress works `refdb.compress()` but free `refdb.free()` fails with an error:

`UnhandledPromiseRejectionWarning: TypeError: refdb.free is not a function`

`npm install` setup my package.json with `"nodegit": "^0.27.0"` but when I look in `~/Library/Caches/typescript/4.1/node_modules/@types/nodegit/package.json` it says `"version": "0.26.12"`

**Comment by implausible** [comment]
We do not maintain or ship types. Please take this up with the people who maintain the ts types.

**Comment by nkavian** [comment]
I added too much, information. This bug is not related to the @type/nodegit version. Please reopen the ticket.

When using nodegit 0.26.5, code works as expected.
When using nodegit 0.27.0, the free method does not exist for refdb, config, remote, repo, etc..

**Comment by implausible** [comment]
The types are wrong. refdb does not have a free method. Please follow up with the types team. We will not be reexposing the free method as the library is garbage collected.

**Comment by nkavian** [comment]
Ah, that's all I needed to know. Version 0.27.0 added automatic garbage collection and there's no longer any need to call free methods on any objects. Thanks for all your help.
