### ISSUE TITLE
'transferProgress' not working

### ISSUE THREAD

**Issue by nkavian** [nodegit/nodegit#1818]
## System information
  - node version: v14.13.1
  - npm or yarn version: 6.14.11
  - OS/version/architecture: Mac OS 10.14.6
  - Applicable nodegit version: 0.27.0

When executing a repo fetch with fetch options, the `transferProgress: function (progress) { console.log(progress) }` prints `IndexerProgress {}` to the console where as I'm expecting a `TransferProgress` instead.

**Comment by kodiyak** [comment]
here is the types definition 
[Indexer Progress](https://www.nodegit.org/api/indexer_progress/)

**Comment by nkavian** [comment]
Closing the issue, decided to not use nodegit, so not sure if this resolves the issue or not. Thanks.
