### ISSUE TITLE
Takes forever for clone to fail with invalid/nonexistent deploy key

### ISSUE THREAD

**Issue by norrbotten** [nodegit/nodegit#1821]
## System information
  - node version: 14
  - yarn version: 1.22.5
  - OS/version/architecture: linux x64
  - Applicable nodegit version: 0.27.0

Cloning a repo like this
```typescript
git.Clone.clone(uri, path, {
  fetchOpts: {
    callbacks: {
      certificateCheck: () => 1,
      credentials: (_: any, username: string) => {
        return git.Cred.sshKeyMemoryNew(username, publicKey, privateKey, "");
      }
    }
  }
})
```
takes 20-30s to fail if your keys arent valid. Can I set a timeout somehow?

**Comment by implausible** [comment]
You'll want to take this request upstream to https://github.com/libgit2/libgit2. We just reexport what is in or slated to go into that repository. We can't change this behavior in this repo.
