### ISSUE TITLE
Empty username

### ISSUE THREAD

**Issue by paymog** [nodegit/nodegit#1829]
## System information
  - node version: v15.11.0
  - npm or yarn version: yarn version 1.22.10
  - OS/version/architecture: osx 10.15.7
  - Applicable nodegit version: 0.27.0

```
 ❯❯❯ node -v
npm -v # (or yarn -v)
node -e "console.log(process.platform)"
node -e "console.log(require('os').release())"
node -e "console.log(console.log(process.arch))"
v15.11.0
7.6.0
darwin
19.6.0
x64
undefined
```

I have the following code

```
        const repo = await Git.Clone.clone("https://github.com/myprivate/repo.git", "./tmp", {
            fetchOpts: {
                callbacks: {
                    certificateCheck: function() { return 0; },
                    credentials: function (url, userName) {
                        console.log(`url is ${url}`)
                        console.log(`username  is ${userName}`)
                        const cred = Git.Cred.sshKeyFromAgent('paymahn');
                        console.log(`cred is ${cred}`)
                        return cred;
                    }
                }
            }
        })
```

And when I run this I get the following output

```
url is https://github.com/myprivate/repo.git
username  is
cred is [object Object]
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[Error: remote credential provider returned an invalid cred type] {
  errno: -1,
  errorFunction: 'Clone.clone'
}
```

It looks like the `username` is empty which is causing invalid credentials to be created. Has anyone stumbled on this before? Why might the username be empty when this callback is called?

**Comment by Clovel** [comment]
This looks like a difference in format between the expected object and what the remote sent you. Could you print the whole object you received ? Perhaps specify what kind of remote you are using and what `git` version said remote is using ?

**Comment by paymog** [comment]
Can you clarify what you mean by "remote"? That's a new term to me and I don't want to accidentally misinterpret it. 

I don't think the primary problem is with the `cred` object - I think the primary problem is that the `username` is empty which ends up returning an invalid cred.

**Comment by Clovel** [comment]
You have your "local" `git` instance, which is your application that uses `nodegit`, and you have your **remote** `git` instance you are cloning from. The **remote** has the ability to answer various things. For example, when pushing, it can give you a link to create a merge request (GitLab remotes do this). In this case, if I understand your issue correctly, it answers w/ the `cred` object. 

I see what you mean, yet the error states : 
```log
[Error: remote credential provider returned an invalid cred type] {
  errno: -1,
  errorFunction: 'Clone.clone'
}
```
which doesn't explicitly mention the `username` field. Having `username === ''` may be an accepted value, and the exception is caused by another "cred type" format.

**Comment by paymog** [comment]
Ah I see - the remote I'm trying to pull is a private github repo that I have access to. 

I managed to fix this by using oauth authentication with `const cred = Git.Cred.userpassPlaintextNew(process.env.GITHUB_TOKEN,'x-oauth-basic');` where I supply a github token through the environment.
