### ISSUE TITLE
fetch using access token as credential 

### ISSUE THREAD

**Issue by cesarin3134** [nodegit/nodegit#1836]
Is possible run this fetch code but using an access token generated by azure devops instead of ssh key or username and password ?
```

var nodegit = require("../");
var path = require("path");

nodegit.Repository.open(path.resolve(__dirname, "../.git"))
  .then(function(repo) {
    return repo.fetch("origin", {
      callbacks: {
        credentials: function(url, userName) {
          return nodegit.Cred.sshKeyFromAgent(userName);
        }
      }
    });
  }).done(function() {
    console.log("It worked!");
  });

```
I changed this line : 
`return nodegit.Cred.sshKeyFromAgent(userName);`
with this line :
`return nodegit.Cred.sshKeyNew( "conf.myTokens", "x-oauth-basic");`

and get this error : 
`(node:50445) UnhandledPromiseRejectionWarning: Error: remote authentication required but no callback set`

is this correct ?? 
thanks

**Comment by weedz** [comment]
I think access token authentication is done with `userpassPlaintextNew`: Provide your access token as the username and `x-oauth-basic` as the password. Or, seems to be the case with github sometimes, provide your username as the username and access token as the password. This assumes the remote is using http(s), don't know if this is possible with ssh.

**Comment by cesarin3134** [comment]
hi @weedz , thanks for the advice, I'll try it and let you know , I hope it works

**Comment by cesarin3134** [comment]
I resolved using : 

`return cred.userpassPlaintextNew("x-oauth-basic", process.env.GIT_TOKEN);`

**Comment by AdamGold** [comment]
@cesarin3134 Is that a personal token or an OAuth one? I can not seem to get it working with an OAuth token.
