### ISSUE TITLE
Is nodegit compatible with Electron v12 and Node v14?

### ISSUE THREAD

**Issue by NL33** [nodegit/nodegit#1839]
## System information
  - node version: 14.6.1
  - npm or yarn version: 6.14.12
  - OS/version/architecture: Mac OS 11.1
  - Applicable nodegit version: 0.27.0
  - Electron version: 12.0.2

Is nodegit compatible with Electron version 12 and Node 14?

Sorry if I've missed it, but I've looked for a note about nodegit's latest compatibility, and I can't find it. 

I've been getting a variety of errors trying to install nodegit with electron.

I have electron-rebuild, v 2.3.5, installed, and followed these steps:

`$ npm i nodegit`

Result:

```
Pre-built binaries not found for nodegit@0.27.0 and electron@12.0.2 (electron-v12.0 ABI, unknown) (falling back to source compile with node-gyp)
...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.27.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.27.0 install script.
```

Running  electron-rebuild did not help.

And I've gone through the steps here without success: https://www.electronjs.org/docs/tutorial/using-native-node-modules

I've also tried adding an .npmrc file but same result.

So: Is nodegit compatible with Electron v12 and Node v14?

Is there a special installation setup required?

**Comment by implausible** [comment]
Not yet, closing in favor of https://github.com/nodegit/nodegit/issues/1774

**Comment by NL33** [comment]
Ok. Thanks.
