### ISSUE TITLE
Errors in installing nodegit in linux

### ISSUE THREAD

**Issue by Manju789** [nodegit/nodegit#1848]
## System information
  - node version: v6.9.2
  - npm or yarn version: 3.10.9
  - OS/version/architecture:
  - Applicable nodegit version:

``
 npm install nodegit
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future

> nodegit@0.28.0-alpha.9 install /opt/portal_server/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
node-pre-gyp
WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.28.0-alpha.9-node-v48-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for nodegit@0.28.0-alpha.9 and node@6.9.2 (node-v48 ABI, glibc) (falling back to source compile with node-gyp)
gyp

ERR! UNCAUGHT EXCEPTION
gyp ERR!
stack /opt/portal_server/node_modules/nodegit/node_modules/mkdirp/lib/opts-arg.js:7
gyp ERR!
stack     opts = { mode: 0o777, fs, ...opts }
gyp ERR! stack
^^^
gyp ERR!
stack SyntaxError: Unexpected token ...
gyp ERR!
stack     at Object.exports.runInThisContext (vm.js:76:16)
gyp ERR!
stack     at Module._compile (module.js:542:28)
gyp ERR! stack
at Object.Module._extensions..js (module.js:579:10)
gyp ERR! stack
at Module.load (module.js:487:32)
gyp ERR!
stack     at tryModuleLoad (module.js:446:12)
gyp ERR!
stack     at Function.Module._load (module.js:438:3)
gyp ERR! stack
at Module.require (module.js:497:17)
gyp ERR!
stack     at require (internal/module.js:20:19)
gyp
ERR! stack     at Object.<anonymous> (/opt/portal_server/node_modules/nodegit/node_modules/mkdirp/index.js:1:79)
gyp
ERR! stack     at Module._compile (module.js:570:32)
gyp
ERR! System Linux 3.10.0-514.2.2.el7.x86_64
gyp
ERR! command "/usr/bin/node" "/opt/portal_server/node_modules/nodegit/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/portal_server/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/opt/portal_server/node_modules/nodegit/build/Release" "--node_abi_napi=node-v48" "--napi_build_version=0" "--node_napi_label=node-v48"
gyp
ERR! cwd /opt/portal_server/node_modules/nodegit
gyp
ERR! node -v v6.9.2
gyp ERR! node-gyp -v v7.1.2
gyp ERR!
Node-gyp failed to build your package.
gyp
ERR!
Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
node-pre-gyp
ERR! build error
node-pre-gyp ERR! stack
Error: Failed to execute '/usr/bin/node /opt/portal_server/node_modules/nodegit/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/portal_server/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/opt/portal_server/node_modules/nodegit/build/Release --node_abi_napi=node-v48 --napi_build_version=0 --node_napi_label=node-v48' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/portal_server/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR!
stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack
at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack
at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp
ERR! System Linux 3.10.0-514.2.2.el7.x86_64
node-pre-gyp ERR!
command "/usr/bin/node" "/opt/portal_server/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp
ERR! cwd /opt/portal_server/node_modules/nodegit
node-pre-gyp
ERR! node -v v6.9.2
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /opt/portal_server/node_modules/nodegit/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/portal_server/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/opt/portal_server/node_modules/nodegit/build/Release --node_abi_napi=node-v48 --napi_build_version=0 --node_napi_label=node-v48' (7)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
@sindresorhus/is@2.1.1 node_modules/nodegit/node_modules/@sindresorhus/is -> node_modules/@sindresorhus/is
@types/http-cache-semantics@4.0.0 node_modules/nodegit/node_modules/@types/http-cache-semantics -> node_modules/@types/http-cache-semantics
@types/keyv@3.1.1 node_modules/nodegit/node_modules/@types/keyv -> node_modules/@types/keyv
@types/responselike@1.0.0 node_modules/nodegit/node_modules/@types/responselike -> node_modules/@types/responselike
@types/cacheable-request@6.0.1 node_modules/nodegit/node_modules/@types/cacheable-request -> node_modules/@types/cacheable-request
buffer-alloc-unsafe@1.1.0 node_modules/nodegit/node_modules/buffer-alloc-unsafe -> node_modules/buffer-alloc-unsafe
buffer-fill@1.0.0 node_modules/nodegit/node_modules/buffer-fill -> node_modules/buffer-fill
buffer-alloc@1.2.0 node_modules/nodegit/node_modules/buffer-alloc -> node_modules/buffer-alloc
chownr@2.0.0 node_modules/nodegit/node_modules/chownr -> node_modules/chownr
mimic-response@1.0.1 node_modules/nodegit/node_modules/clone-response/node_modules/mimic-response -> node_modules/clone-response/node_modules/mimic-response
clone-response@1.0.2 node_modules/nodegit/node_modules/clone-response -> node_modules/clone-response
defer-to-connect@2.0.1 node_modules/nodegit/node_modules/defer-to-connect -> node_modules/defer-to-connect
@szmarczak/http-timer@4.0.5 node_modules/nodegit/node_modules/@szmarczak/http-timer -> node_modules/@szmarczak/http-timer
detect-libc@1.0.3 node_modules/nodegit/node_modules/detect-libc -> node_modules/detect-libc
env-paths@2.2.1 node_modules/nodegit/node_modules/env-paths -> node_modules/env-paths
fs-constants@1.0.0 node_modules/nodegit/node_modules/fs-constants -> node_modules/fs-constants
http-cache-semantics@4.1.0 node_modules/nodegit/node_modules/http-cache-semantics -> node_modules/http-cache-semantics
ignore-walk@3.0.4 node_modules/nodegit/node_modules/ignore-walk -> node_modules/ignore-walk
json-buffer@3.0.1 node_modules/nodegit/node_modules/json-buffer -> node_modules/json-buffer
keyv@4.0.3 node_modules/nodegit/node_modules/keyv -> node_modules/keyv
cacheable-lookup@2.0.1 node_modules/nodegit/node_modules/cacheable-lookup -> node_modules/cacheable-lookup
mimic-response@2.1.0 node_modules/nodegit/node_modules/mimic-response -> node_modules/mimic-response
decompress-response@5.0.0 node_modules/nodegit/node_modules/decompress-response -> node_modules/decompress-response
minipass@3.1.3 node_modules/nodegit/node_modules/minipass -> node_modules/minipass
fs-minipass@2.1.0 node_modules/nodegit/node_modules/fs-minipass -> node_modules/fs-minipass
minizlib@2.1.2 node_modules/nodegit/node_modules/minizlib -> node_modules/minizlib
debug@3.2.7 node_modules/nodegit/node_modules/debug -> node_modules/needle/node_modules/debug
sax@1.2.4 node_modules/nodegit/node_modules/sax -> node_modules/needle/node_modules/sax
needle@2.6.0 node_modules/nodegit/node_modules/needle -> node_modules/needle
chownr@1.1.4 node_modules/nodegit/node_modules/tar-fs/node_modules/chownr -> node_modules/node-pre-gyp/node_modules/chownr
nopt@4.0.3 node_modules/nodegit/node_modules/node-pre-gyp/node_modules/nopt -> node_modules/node-pre-gyp/node_modules/nopt
yallist@3.1.1 node_modules/nodegit/node_modules/node-pre-gyp/node_modules/yallist -> node_modules/node-pre-gyp/node_modules/yallist
minipass@2.9.0 node_modules/nodegit/node_modules/node-pre-gyp/node_modules/minipass -> node_modules/node-pre-gyp/node_modules/minipass
fs-minipass@1.2.7 node_modules/nodegit/node_modules/node-pre-gyp/node_modules/fs-minipass -> node_modules/node-pre-gyp/node_modules/fs-minipass
minizlib@1.3.3 node_modules/nodegit/node_modules/node-pre-gyp/node_modules/minizlib -> node_modules/node-pre-gyp/node_modules/minizlib
tar@4.4.13 node_modules/nodegit/node_modules/node-pre-gyp/node_modules/tar -> node_modules/node-pre-gyp/node_modules/tar
- @types/node@15.12.4 node_modules/nodegit/node_modules/@types/node
- abbrev@1.1.1 node_modules/nodegit/node_modules/abbrev
- ansi-regex@2.1.1 node_modules/nodegit/node_modules/ansi-regex
- aproba@1.2.0 node_modules/nodegit/node_modules/aproba
- assert-plus@1.0.0 node_modules/nodegit/node_modules/assert-plus
- asynckit@0.4.0 node_modules/nodegit/node_modules/asynckit
- aws-sign2@0.7.0 node_modules/nodegit/node_modules/aws-sign2
- aws4@1.11.0 node_modules/nodegit/node_modules/aws4
- balanced-match@1.0.2 node_modules/nodegit/node_modules/balanced-match
- caseless@0.12.0 node_modules/nodegit/node_modules/caseless
- code-point-at@1.1.0 node_modules/nodegit/node_modules/code-point-at
- concat-map@0.0.1 node_modules/nodegit/node_modules/concat-map
- brace-expansion@1.1.11 node_modules/nodegit/node_modules/brace-expansion
- console-control-strings@1.1.0 node_modules/nodegit/node_modules/console-control-strings
- core-util-is@1.0.2 node_modules/nodegit/node_modules/core-util-is
- dashdash@1.14.1 node_modules/nodegit/node_modules/dashdash
- deep-extend@0.6.0 node_modules/nodegit/node_modules/deep-extend
- delayed-stream@1.0.0 node_modules/nodegit/node_modules/delayed-stream
- combined-stream@1.0.8 node_modules/nodegit/node_modules/combined-stream
- delegates@1.0.0 node_modules/nodegit/node_modules/delegates
- duplexer3@0.1.4 node_modules/nodegit/node_modules/duplexer3
- extend@3.0.2 node_modules/nodegit/node_modules/extend
- extsprintf@1.3.0 node_modules/nodegit/node_modules/extsprintf
- fast-deep-equal@3.1.3 node_modules/nodegit/node_modules/fast-deep-equal
- fast-json-stable-stringify@2.1.0 node_modules/nodegit/node_modules/fast-json-stable-stringify
- forever-agent@0.6.1 node_modules/nodegit/node_modules/forever-agent
- fs.realpath@1.0.0 node_modules/nodegit/node_modules/fs.realpath
- getpass@0.1.7 node_modules/nodegit/node_modules/getpass
- graceful-fs@4.2.6 node_modules/nodegit/node_modules/graceful-fs
- har-schema@2.0.0 node_modules/nodegit/node_modules/har-schema
- has-unicode@2.0.1 node_modules/nodegit/node_modules/has-unicode
- inherits@2.0.4 node_modules/nodegit/node_modules/inherits
- ini@1.3.8 node_modules/nodegit/node_modules/ini
- is-typedarray@1.0.0 node_modules/nodegit/node_modules/is-typedarray
- isarray@1.0.0 node_modules/nodegit/node_modules/isarray
- isexe@2.0.0 node_modules/nodegit/node_modules/isexe
- isstream@0.1.2 node_modules/nodegit/node_modules/isstream
- jsbn@0.1.1 node_modules/nodegit/node_modules/jsbn
- json-schema@0.2.3 node_modules/nodegit/node_modules/json-schema
- json-schema-traverse@0.4.1 node_modules/nodegit/node_modules/json-schema-traverse
- json-stringify-safe@5.0.1 node_modules/nodegit/node_modules/json-stringify-safe
- jsonfile@4.0.0 node_modules/nodegit/node_modules/jsonfile
- lodash@4.17.21 node_modules/nodegit/node_modules/lodash
- mime-db@1.48.0 node_modules/nodegit/node_modules/mime-db
- mime-types@2.1.31 node_modules/nodegit/node_modules/mime-types
- form-data@2.3.3 node_modules/nodegit/node_modules/form-data
- minimatch@3.0.4 node_modules/nodegit/node_modules/minimatch
- ms@2.1.3 node_modules/nodegit/node_modules/ms
- mkdirp@0.5.5 node_modules/nodegit/node_modules/node-pre-gyp/node_modules/mkdirp
- semver@5.7.1 node_modules/nodegit/node_modules/node-pre-gyp/node_modules/semver
- normalize-url@6.0.1 node_modules/nodegit/node_modules/normalize-url
- number-is-nan@1.0.1 node_modules/nodegit/node_modules/number-is-nan
- is-fullwidth-code-point@1.0.0 node_modules/nodegit/node_modules/is-fullwidth-code-point
- oauth-sign@0.9.0 node_modules/nodegit/node_modules/oauth-sign
- object-assign@4.1.1 node_modules/nodegit/node_modules/object-assign
- os-homedir@1.0.2 node_modules/nodegit/node_modules/os-homedir
- os-tmpdir@1.0.2 node_modules/nodegit/node_modules/os-tmpdir
- osenv@0.1.5 node_modules/nodegit/node_modules/osenv
- p-finally@1.0.0 node_modules/nodegit/node_modules/p-finally
- path-is-absolute@1.0.1 node_modules/nodegit/node_modules/path-is-absolute
- performance-now@2.1.0 node_modules/nodegit/node_modules/performance-now
- process-nextick-args@2.0.1 node_modules/nodegit/node_modules/process-nextick-args
- psl@1.8.0 node_modules/nodegit/node_modules/psl
- punycode@2.1.1 node_modules/nodegit/node_modules/punycode
- qs@6.5.2 node_modules/nodegit/node_modules/qs
- safe-buffer@5.1.2 node_modules/nodegit/node_modules/safe-buffer
- safer-buffer@2.1.2 node_modules/nodegit/node_modules/safer-buffer
- asn1@0.2.4 node_modules/nodegit/node_modules/asn1
- ecc-jsbn@0.1.2 node_modules/nodegit/node_modules/ecc-jsbn
- iconv-lite@0.4.24 node_modules/nodegit/node_modules/iconv-lite
- set-blocking@2.0.0 node_modules/nodegit/node_modules/set-blocking
- signal-exit@3.0.3 node_modules/nodegit/node_modules/signal-exit
- string_decoder@1.1.1 node_modules/nodegit/node_modules/string_decoder
- strip-ansi@3.0.1 node_modules/nodegit/node_modules/strip-ansi
- string-width@1.0.2 node_modules/nodegit/node_modules/string-width
- strip-json-comments@2.0.1 node_modules/nodegit/node_modules/strip-json-comments
- rc@1.2.8 node_modules/nodegit/node_modules/rc
- mkdirp@0.5.5 node_modules/nodegit/node_modules/tar-fs/node_modules/mkdirp
- tough-cookie@2.5.0 node_modules/nodegit/node_modules/tough-cookie
- tunnel-agent@0.6.0 node_modules/nodegit/node_modules/tunnel-agent
- tweetnacl@0.14.5 node_modules/nodegit/node_modules/tweetnacl
- bcrypt-pbkdf@1.0.2 node_modules/nodegit/node_modules/bcrypt-pbkdf
- sshpk@1.16.1 node_modules/nodegit/node_modules/sshpk
- universalify@0.1.2 node_modules/nodegit/node_modules/universalify
- fs-extra@7.0.1 node_modules/nodegit/node_modules/fs-extra
- uri-js@4.4.1 node_modules/nodegit/node_modules/uri-js
- ajv@6.12.6 node_modules/nodegit/node_modules/ajv
- har-validator@5.1.5 node_modules/nodegit/node_modules/har-validator
- util-deprecate@1.0.2 node_modules/nodegit/node_modules/util-deprecate
- readable-stream@2.3.7 node_modules/nodegit/node_modules/readable-stream
- are-we-there-yet@1.1.5 node_modules/nodegit/node_modules/are-we-there-yet
- uuid@3.4.0 node_modules/nodegit/node_modules/uuid
- verror@1.10.0 node_modules/nodegit/node_modules/verror
- jsprim@1.4.1 node_modules/nodegit/node_modules/jsprim
- http-signature@1.2.0 node_modules/nodegit/node_modules/http-signature
- request@2.88.2 node_modules/nodegit/node_modules/request
- wide-align@1.1.3 node_modules/nodegit/node_modules/wide-align
- wrappy@1.0.2 node_modules/nodegit/node_modules/wrappy
- once@1.4.0 node_modules/nodegit/node_modules/once
- end-of-stream@1.4.4 node_modules/nodegit/node_modules/end-of-stream
- inflight@1.0.6 node_modules/nodegit/node_modules/inflight
- glob@7.1.7 node_modules/nodegit/node_modules/glob
- rimraf@2.7.1 node_modules/nodegit/node_modules/node-pre-gyp/node_modules/rimraf
- xtend@4.0.2 node_modules/nodegit/node_modules/xtend
npm-normalize-package-bin@1.0.1 node_modules/nodegit/node_modules/npm-normalize-package-bin -> node_modules/npm-normalize-package-bin
npm-bundled@1.1.2 node_modules/nodegit/node_modules/npm-bundled -> node_modules/npm-bundled
npm-packlist@1.4.8 node_modules/nodegit/node_modules/npm-packlist -> node_modules/npm-packlist
p-cancelable@2.1.1 node_modules/nodegit/node_modules/p-cancelable -> node_modules/p-cancelable
p-timeout@3.2.0 node_modules/nodegit/node_modules/p-timeout -> node_modules/p-timeout
p-event@4.2.0 node_modules/nodegit/node_modules/p-event -> node_modules/p-event
responselike@2.0.0 node_modules/nodegit/node_modules/responselike -> node_modules/responselike
cacheable-request@7.0.2 node_modules/nodegit/node_modules/cacheable-request -> node_modules/cacheable-request
chownr@1.1.4 node_modules/nodegit/node_modules/node-pre-gyp/node_modules/chownr -> node_modules/tar-fs/node_modules/chownr
pump@1.0.3 node_modules/nodegit/node_modules/tar-fs/node_modules/pump -> node_modules/tar-fs/node_modules/pump
bl@1.2.3 node_modules/nodegit/node_modules/bl -> node_modules/tar-stream/node_modules/bl
to-buffer@1.1.1 node_modules/nodegit/node_modules/to-buffer -> node_modules/to-buffer
tar-stream@1.6.2 node_modules/nodegit/node_modules/tar-stream -> node_modules/tar-stream
to-readable-stream@2.1.0 node_modules/nodegit/node_modules/to-readable-stream -> node_modules/to-readable-stream
type-fest@0.10.0 node_modules/nodegit/node_modules/type-fest -> node_modules/type-fest
node-pre-gyp@0.13.0 node_modules/nodegit/node_modules/node-pre-gyp -> node_modules/node-pre-gyp
ramda@0.25.0 node_modules/nodegit/node_modules/ramda -> node_modules/ramda
tar-fs@1.16.3 node_modules/nodegit/node_modules/tar-fs -> node_modules/tar-fs
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/nodemon/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.10.0-514.2.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "nodegit"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.28.0-alpha.9 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.28.0-alpha.9 install script 'node lifecycleScripts/preinstall && node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/portal_server/npm-debug.log

**Comment by ianhattendorf** [comment]
node 6 is not supported, see https://github.com/nodegit/nodegit/blob/4561dcb7c120474a4553baa27e4c4c2f4be23a2b/package.json#L38.

```
% npm install --engine-strict true nodegit@0.28.0-alpha.9
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for nodegit@0.28.0-alpha.9: wanted: {"node":">= 12.19.0 < 13 || >= 14.10.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
```
