### ISSUE TITLE
How is this project covered by the MIT License?

### ISSUE THREAD

**Issue by Rabadash8820** [nodegit/nodegit#1852]
This is more of a question than an issue...

If git itself is [licensed under GPLv2](https://git-scm.com/about/free-and-open-source), then how can nodegit be licensed under MIT? My understanding of GPLv2 is that any software using GPLv2-licensed software must _itself_ be licensed under GPLv2.

I ask because I am considering making an open-source tool to work with git myself; I wasn't sure which OSS license to use, so I was looking to nodegit for guidance, and now I'm confused. 😛

**Comment by rcjsuen** [comment]
> This is more of a question than an issue...
> 
> If git itself is [licensed under GPLv2](https://git-scm.com/about/free-and-open-source), then how can nodegit be licensed under MIT?

NodeGit uses [libgit2](https://github.com/libgit2/libgit2) to read a Git repository. NodeGit does not use Git itself. libgit2 is licensed under the GPLv2 with the special linking exception.

**Comment by Rabadash8820** [comment]
Ahh very interesting. Didn't realize that exception existed. Thanks for the clarification!
