### ISSUE TITLE
npm ERR! Failed at the nodegit@0.20.3 install script.

### ISSUE THREAD

**Issue by LeandroLuna** [nodegit/nodegit#1909]
## System information
  - node version: 8.11.4
  - npm or yarn version: 5.6.0
  - OS/version/architecture: macOS Monterey 12.3.1
  - Applicable nodegit version: ??

```
Trying to install some npm modules for job, and I am constantly getting this error. Any help?

I've heard some ppl saying about incompatibility between old node version (in my case 8.11.4) and Mac M1, and for that they solved changing the arch of terminal from arm64 to i386. Anyway, I've tried to install nodegit in both architectures, but no success.

Log below:
```
[2022-04-15T20_35_17_595Z-debug.log](https://github.com/nodegit/nodegit/files/8498189/2022-04-15T20_35_17_595Z-debug.log)

**Comment by ianhattendorf** [comment]
`nodegit@0.20.3` is very old, try the latest alpha and see if you get the same issue.
