### ISSUE TITLE
Support getting diff from two commits

### ISSUE THREAD

**Issue by NicolasKim** [nodegit/nodegit#1931]
Is it possible to get diff data from two commits?

**Comment by weedz** [comment]
Not quite sure what you are looking for here, but if you want to compare two revisions you can use [`tree.diff()`](https://www.nodegit.org/api/tree/#diff):

```typescript
const to = await repo.getCommit(toRevision);
const toTree = await to.getTree();

const from = await repo.getCommit(fromRevision);
const fromTree = await from.getTree();

const diff = await toTree.diff(from);
```

This is somewhat equivalent to `git diff fromRevision..toRevision`.

**Comment by NicolasKim** [comment]
> Not quite sure what you are looking for here, but if you want to compare two revisions you can use [`Tree#diff()`](https://www.nodegit.org/api/tree/#diff):
> 
> ```ts
> const from = await repo.getCommit(fromRevision);
> const fromTree = await from.getTree();
> 
> const to = await repo.getCommit(toRevision);
> const toTree = await to.getTree();
> 
> const diff = await toTree.diff(fromTree);
> ```
> 
> This is somewhat equivalent to `git diff fromRevision..toRevision`.

Problem solved. thank you
