### ISSUE TITLE
"sshKeyMemoryNew" is not found in Typescript

### ISSUE THREAD

**Issue by nakky** [nodegit/nodegit#1962]
Probably because namespace "Cred" has changed, "sshKeyMemoryNew" is not found in Typescript.

"sshKeyNew" can be used although the following warning is issued.
>Use NodeGit.Credential.sshKeyNew instead of NodeGit.Cred.sshKeyNew

I think it will probably be solved by updating the definition of Typescript.
(It worked when I directly modified the output js file)
The definition may not have been updated because it is alpha, but it is necessary for check, so please support it.

## System information
  - node version: v16.3.0
  - npm or yarn version: yarn 1.22.18
  - OS/version/architecture: darwin 21.4.0 arm64
  - Applicable nodegit version: 0.28.0-alpha.20

**Comment by tkmcmaster** [comment]
I'm having a different problem. Typescript does have `NodeGit.Credential.sshKeyMemoryNew` for me, but it doesn't work in Node 14 or 16 when using `"nodegit": "^0.28.0-alpha.21"` and `"@types/nodegit": "^0.28.2"`. If I change to `sshKeyNew` I get the same deprecation warning. I've been trying different builds of nodegit 0.28.0 alphas for a while and have yet to find one that works on `sskKeyMemoryNew`. The same code does work in `"nodegit": "^0.27.0"`

**Comment by tkmcmaster** [comment]
@nakky Upgrade `@types/nodegit` to `^0.28.3` to fix Typescript using `NodeGit.Credential.sshKeyMemoryNew()`. https://github.com/nodegit/nodegit/pull/1973 will fix `NodeGit.Cred.sshKeyMemoryNew()`.

**Comment by nakky** [comment]
@tkmcmaster I agree with you. When I was looking inside, it seemed that the namespace of the js library had been changed, but Typescript did not support it. (I used "@types/nodegit": "^0.28.2")
Thanks for the update!! After updating to ^0.28.3 and rewriting to Credential, it worked! !
