### ISSUE TITLE
Cannot join slack

### ISSUE THREAD

**Issue by axkibe** [nodegit/nodegit#1965]
The readme suggest going to http://slack.libgit2.org/ #nodegit.

However the website continues to answer "Application error" only.

**Comment by mommy742** [comment]
same

**Comment by mommy742** [comment]
![Screenshot 2023-03-02 082124](https://user-images.githubusercontent.com/16270026/222456829-1af77fce-2557-4f28-bae2-30d76bef1e80.png)

heres what the website looks like for me.

**Comment by axkibe** [comment]
It works now.
