### ISSUE TITLE
S3 AWS Missing

### ISSUE THREAD

**Issue by FLYBYME** [nodegit/nodegit#1987]
Nodegit is failing to install

```
#18 86.27 npm ERR! install response status 404 Not Found on https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v108-linux-x64.tar.gz
```

**Comment by scriptype** [comment]
@FLYBYME I was getting a similar error in CI/CD and changing node version to 20 worked for me.

**Comment by FLYBYME** [comment]
I think it might be IP blocking

**Comment by batchor** [comment]
Same problem happened to me on both home and office PCs.

**Comment by batchor** [comment]
No body else comes into the same error? The AWS links are just dead.

 <https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v115-linux-x64.tar.gz>

**Comment by FLYBYME** [comment]
Why when you clone the repo from github it still it still pulls a tarbll of the source code from a thrid party website. 

I think its safe to say the project is died.

**Comment by ianhattendorf** [comment]
No AWS links are dead, the links you're attempting to reach simply never existed. `v115` in the URL implies Node 20. There are no builds of NodeGit v0.27 for Node 20, you'll need to use the `next` npm tag which is currently at `0.28.0-alpha.26`. 

For example Node 14 (NODE_MODULE_VERSION v83) is still up for NodeGit 0.27: https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v83-linux-x64.tar.gz. This is the latest node version built for 0.27.

> I think its safe to say the project is died.

This project is currently in maintenance mode. We still use it at GitKraken, however are focused on migrating to the Git executable for the majority of our Git needs (https://www.gitkraken.com/blog/gitkraken-client-migrating-from-libgit2-to-git-executable).

**Comment by domharrington** [comment]
@ianhattendorf thanks for responding! Would you be open to adding/allowing external contributors to the project? It seems like there's lots of people who are still using and would like to continue for it to be maintained. I'm happy to lend a hand, especially with maintenance, closing stale issues and ensuring things stay up to date. Let me know!

**Comment by llimllib** [comment]
I've updated [our soft fork](https://github.com/readmeio/nodegit/) to use [prebuildify](https://github.com/prebuild/prebuildify) to include binary bundles. Would you be interested in upstreaming this work, so the whole s3 deal could be avoided?

(Right now it only supports mac-arm and linux-x64, but adding more platforms should be easy)

**Comment by llimllib** [comment]
I've now added linux-arm-musl, linux-arm-glibc, and linux-x64-musl builds to our fork
