### ISSUE TITLE
HELP WANTED - Test coverage!

### ISSUE THREAD

**Issue by johnhaley81** [nodegit/nodegit#275]
We just did a bunch of stuff to NodeGit and have implemented more functionality in libgit2 than ever before. And now we need your help writing some test cases to help coverage test the new functionality!

You can help contribute by looking at the [CONTRIBUTING.md](https://github.com/nodegit/nodegit/blob/master/CONTRIBUTING.md) for a guide on how to get started.

**Comment by tbranyen** [comment]
Closing this for now, it's a goal we have to get better coverage, but this issue is just adding to our overall count now.

**Comment by johnhaley81** [comment]
:+1:
