### ISSUE TITLE
Tests randomly failing in AppVeyor

### ISSUE THREAD

**Issue by maxkorp** [nodegit/nodegit#316]
Regarding #310 and #315,
AppVeyor just randomly fails partway through testing on v10 with no output or reasoning. Try to log any output and it starts working, so it's seemingly impossible to figure out for now. Gonna hit up  @FeodorFitsner to see if he has any ideas. A few times now the same commit has given different results (eg make commit A, get result a,  pushing commit B on top of A, get result b, and then force push commit A back again as head, and get a different result c.

**Comment by johnhaley81** [comment]
Is this fixed via https://github.com/nodegit/nodegit/pull/324?

**Comment by johnhaley81** [comment]
Nope :(

Still an issue.

**Comment by johnhaley81** [comment]
Trying to ferret the issue out via https://github.com/nodegit/nodegit/pull/352.

It seems the be that the async cloning is killing something somewhere. I was able to repo it once locally and only through Powershell and not cmd.exe or cmder.

Removing just one of the clone tests seems to fix the issue but that's a pretty crappy solution. Any help with this though would be great.

**Comment by johnhaley81** [comment]
So we decided that for the time being we're going to skip some of the clone tests and get appveyor passing. It's not the best solution but we've spent a lot of time trying to figure out what is actually the issue and it just seems like a timing thing. After #352 is merged I'll close this out.

**Comment by johnhaley81** [comment]
Hey @FeodorFitsner, is there an environment variable that I can tie into to know that code is being run on AppVeyor?

Alternatively you can help me figure out why the clone tests are dying. :)

**Comment by johnhaley81** [comment]
10 seconds after I ask I find http://www.appveyor.com/docs/environment-variables

**Comment by johnhaley81** [comment]
#352 was finalized and we decided to remove node v0.12/0.11 from the test matrix for AppVeyor for the time being since we now support io.js. AppVeyor is passing and now good so I think we can close this issue out now.

**Comment by maxkorp** [comment]
This issue is very much alive. We still get it in the clone tests, and I suspect thats what is happening with the status tests in https://github.com/nodegit/nodegit/pull/374.

@FeodorFitsner, any chance you can take a look at this?

**Comment by FeodorFitsner** [comment]
Have you tried updating npm to 2.0: http://www.appveyor.com/docs/lang/nodejs-iojs#locking-errors

**Comment by maxkorp** [comment]
No, but that doesnt quite seem like the issue. I think the problem may have been something on our side related to slashes. Path module generally handles them, but there were some slipping through in a string passed to fs.exec. Fixing all of that up right now to see if it helps.

**Comment by maxkorp** [comment]
Hrm, this is finally occurring outside of appveyor, and happening locally on windows.

**Comment by maxkorp** [comment]
Figured it out. A few weird synchronicity issues, amongst other things. Fixed here:
https://github.com/nodegit/nodegit/pull/388
