### ISSUE TITLE
Needed Examples for 0.3.0

### ISSUE THREAD

**Issue by maxkorp** [nodegit/nodegit#321]
Here's a list of needed examples. 
 - [x] status (porcelain, z) #170 
 - [x] commit history for a specific file #220 
 - [x] index.addAll #131 
 - [x] 2 Factor Auth
 - [x] Creating a branch

**Comment by wiky** [comment]
is there any examples for 'git status' now?

**Comment by maxkorp** [comment]
Anything that's been implemented will have been checked off, so no examples at the moment. Are you looking for strictly a replica of `git status`?

**Comment by billt2006** [comment]
+1 for `git status`. I will most likely be using something like `git status -s`, but cannot figure out how to get started from the docs. :confused:

**Comment by dachev** [comment]
+1 for git status

**Comment by maxkorp** [comment]
Added 2 factor auth example finally.

**Comment by johnhaley81** [comment]
Status examples are in courtesy of @orderedlist

**Comment by maxkorp** [comment]
https://github.com/nodegit/nodegit/issues/391
Need an example for creating a branch
