### ISSUE TITLE
Fetch doesn't seem to work with https urls.

### ISSUE THREAD

**Issue by Athaphian** [nodegit/nodegit#322]
I have cloned a github repo using https. Running the fetch example gives me:

/..../node_modules/nodegit-promise/node_modules/asap/asap.js:45
                throw e;
                      ^
Error: The SSL certificate is invalid

Which is probably a correct message, since I never created any SSL certificate. I will try this example using SSH, but I would like HTTPS to work aswel.

**Comment by tjcarroll11** [comment]
Also want to note that I randomly ran into this error on a CentOS machine and found that setting 

```
certificateCheck: function() {
      return 1;
}
```

on the remote connection options cured it.
