### ISSUE TITLE
Can't build for node-webkit

### ISSUE THREAD

**Issue by achrist** [nodegit/nodegit#335]
Using version 0.2.4 I am unable to build nodegit for node-webkit. 

I have the node-webkit engine defined in a package.json file located a couple directories above where nodegit sits and it appears that the detectNodeWebkit function (in install.js) doesn't finish recursively searching directories before the "fetch" function is called. It gets called once and then "fetch" fires.

Once I found that issue I tried to just hardcode the nodeWebkit flag in install.js to true. Once I did this i get an error when running npm install. Here is the stack trace.

Command failed: 
module.js:340
   throw err;
         ^
Error: Cannot find module '/Users/adamchrist/Documents/Projects/Macaw/Code/scarlet/src/node_modules/nodegit/generate'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Function.Module.runMain (module.js:497:10)
   at startup (node.js:119:16)
   at node.js:906:3

And one final note. It looks like the nodeWebkit flag is a boolean value only:

line 229 of install.js
nodeWebkit = pkg.engines && pkg.engines["node-webkit"];

But later in the "buildNative" function it is being used as the "--target" argument for nw-gyp which expects a version number.

**Comment by johnhaley81** [comment]
Interesting, I'll take a look and try to figure out what's going on. Thanks for the bug report.

**Comment by maxkorp** [comment]
As a workaround, you were close by setting the nodewebkit flag, but it can't be set to true. It needs to be set to your version of nodewebkit, so that it can be used by nw-gyp as you noticed.

**Comment by johnhaley81** [comment]
This should be fixed now in https://github.com/nodegit/nodegit/pull/339

**Comment by johnhaley81** [comment]
Fixed and merged.
