### ISSUE TITLE
nodegit no longer builds in nwjs

### ISSUE THREAD

**Issue by johnhaley81** [nodegit/nodegit#360]
Building nodegit for nwjs now yields the following:

```bash
  CXX(target) Release/obj.target/nodegit/src/nodegit.o
In file included from ../src/nodegit.cc:6:
In file included from ../src/../include/wrapper.h:11:
../node_modules/nan/nan.h:1467:5: error: no matching function for call to 'uv_async_init'
    uv_async_init(
    ^~~~~~~~~~~~~
/Users/johnh/.nw-gyp/0.11.2/src/../deps/uv/include/uv.h:1360:15: note: candidate function not viable: no known conversion from 'void (uv_async_t *)' to 'uv_async_cb'
      (aka 'void (*)(uv_async_t *, int)') for 3rd argument
UV_EXTERN int uv_async_init(uv_loop_t*,
              ^
1 error generated.
make: *** [Release/obj.target/nodegit/src/nodegit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/nw-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/bin/nw-gyp" "build"
gyp ERR! cwd /Users/johnh/Development/GitKraken/node_modules/nodegit
gyp ERR! node -v v0.10.33
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok
```

This seems to be an ongoing issue with nw-gyp via [#46](https://github.com/rogerwang/nw-gyp/issues/46) and [#57](https://github.com/rogerwang/nw-gyp/issues/57) with seemingly no available solution. I think this stems from updating to the latest nan release in order to support io.js.

**Comment by maxkorp** [comment]
I'm trying a local merge of nw-gyp into the latest node-gyp. I'm guessing with the shift to nw.js they havent had the time yet to mess with nw-gyp

**Comment by johnhaley81** [comment]
This is definitely an issue with the update to nan@1.5.1. That breaks nw.js.

**Comment by maxkorp** [comment]
nw.js will be fixed in the next release, in the meantime I'm going to suggest using shrinkwrap in the Readme for older versions of node-webkit

**Comment by johnhaley81** [comment]
Yeah, if you need to support older node and nwjs then you'll need to force nan 1.4.3.

**Comment by maxkorp** [comment]
I've added that info to the readme, so I'm gonna close this, because theirs nothing we can do really other than advise people.
