### ISSUE TITLE
List all files in repo (git ls-tree)

### ISSUE THREAD

**Issue by danamajid** [nodegit/nodegit#365]
I'm looking to emulate the command `git ls-tree --full-tree -r HEAD`. Is this supported? Can't find any examples/directions in the docs. Thanks.

**Comment by johnhaley81** [comment]
https://github.com/nodegit/nodegit/blob/cb4a5309353add160fd55887314ff0bb69427706/examples/walk-tree.js

If you need anymore help feel free to join our [gitter channel](http://gitter.im/nodegit/nodegit).
