### ISSUE TITLE
Cache binary in system tmp

### ISSUE THREAD

**Issue by tbranyen** [nodegit/nodegit#379]
We should cache the binary in a system tmp directory so that repeated installations are significantly faster.

**Comment by maxkorp** [comment]
http://nodejs.org/api/os.html#os_os_tmpdir

Shouldn't be hard to do. I would say that after pulling from there, we should probably test load it, and if it fails, clean it out, so we don't get in some sort of loop of a bad build.

**Comment by tbranyen** [comment]
Opened an issue: mapbox/node-pre-gyp#149 as I think it makes more sense in that library than ours.

**Comment by tbranyen** [comment]
Closing, we'll re-visit if the feature ever gets added.
