### ISSUE TITLE
Commit isn't working

### ISSUE THREAD

**Issue by xasos** [nodegit/nodegit#381]
Whenever I try to commit files with working changes, it doesn't seem to commit. We have SSL already set up, but this one roadblock has come up.

Are we implementing this correctly?
https://github.com/Vadman97/LetsGit/blob/master/routes/commit.js

**Comment by johnhaley81** [comment]
Hey xasos! Sorry about the delay. Things do look alright there are a few questions but we reserve the issues for bugs and feature requests for the library. Mind heading over to our gitter channel where we can help you out in a better environment?
