### ISSUE TITLE
walker.next() needs documentation. 

### ISSUE THREAD

**Issue by danamajid** [nodegit/nodegit#382]
See below code example by @tbranyen:

```
var path = require('path');
var nodegit = require('./');

nodegit.Repository.open(path.resolve("./.git")).then(function(repo) {
 var walker = repo.createRevWalk();
 var commits = [];
 walker.pushHead();

 return walker.next(function(err, oid) {
   return repo.getCommit(oid).then(function(commit) {
      console.log('this is hit', commit);
      return commit;
   });
 }).then(function(commit) {
    console.log('this is never hit', commit);
 });
});
```

**Comment by maxkorp** [comment]
Walker.next doesn't currently generate a promise at all does it? It's based on an event emitter. I've been meaning to put in a helper function. Let me see if I have record of where I built that structure before.

**Comment by danamajid** [comment]
@maxkorp, think the below code is what you had in mind (you wrote a few weeks back on Gitter).
I've been running into the issue where `.then` is never called – which basically is caused by this issue. @tbranyen and @orderedlist are currently being of great help on Gitter.

```
// in promise chain
.then(function(repo) {
  var walker = repo.createRevWalk();
  var innerPromises = [];
  return walker.next(walkCommit)
    .then(function() {
      return nodegit.Promise.all(innerPromises);
    });

  function walkCommit(commitOid) {
    if (commitOid) {
      innerPromises.push(repo.getCommit(commitOid));
      return walker.next(walkCommit);
    }
  }
})
.then(function(allOfTheCommits) {
  // do some stuff here
})
// continue the promise chain
```

**Comment by maxkorp** [comment]
Yeah, I had to rework that. Didn't see the gitter chat notifications though, I'll hop in.

**Comment by tbranyen** [comment]
The problem is that we currently do not allow mixing of callback-style and Promises.  You gotta go either one or the other.  In the case of this example, `next` was invoked with CPS (continuation-passing style) instead of as Promise, the fix is to use `walker.next().then(function(oid)`.

I'm unsure if it makes sense to intermingle them by default.

**Comment by tbranyen** [comment]
I'm going to chalk this up as "not-a-bug", but definitely *needs-documentation*.

**Comment by maxkorp** [comment]
Yeah, intermixing doesn't really make sense.

**Comment by nilshartmann** [comment]
Using `walker.next().then(function(oid)` (as demonstrated in the example https://github.com/nodegit/nodegit/blob/master/examples/general.js#L302-L316) fails with an error in case there are no more commits to walk. The method is never invoked with `oid` set to `null` or `undefined`, so i cannot "clean" terminate the walk.
 Am I missing something? 

(nodegit 0.6.3, node v4.1.2 on Windows, babel-register 6.3.13)

**Comment by maxkorp** [comment]
That may very well have changed :/ I'll look into it it later today and see if I cant figure out whats going on.

**Comment by NonCreature0714** [comment]
Is this truly an active issue? Is so, it'd be fun to contribute

**Comment by RaevLogic** [comment]
So I was with NonCreature0714 yesterday when he commented. I've got the site generated (after updating dependencies), but I was hoping I could get some clarification on which docs need to be updated. The 'Revwalk#next' section updated with your `revwalk.next().then(function(oid) {
