### ISSUE TITLE
Cannot create a new branch

### ISSUE THREAD

**Issue by ashokfernandez** [nodegit/nodegit#391]
I am trying to create a new branch in my repo, however I am getting an error about a callback not existing. This is using version 0.2.7 from NPM

```
Git = require('nodegit');

scope = {}

Git.Repository.open("./")
	.then(function(repo) {
		scope.repo = repo;
		return repo.getMasterCommit();
	})
	.then(function(masterCommit) {
		scope.masterCommit = masterCommit;
		return Git.Branch.create(scope.repo, "new-branch", scope.masterCommit, true)
	})
	.then(function(branch) {
		console.log(branch.toString())
	})
	.catch(function(err) {
		console.log(err.toString())
	})

```

This results in the output

```
Error: Callback is required and must be a Function.
```

**Comment by tbranyen** [comment]
I think the create method takes six arguments, you've passed 4.

**Comment by ashokfernandez** [comment]
Ahh I see, I was following the examples from the test files. What should be used for the signature parameter? Also is the head commit reference that I'm using from the tests correct?

**Comment by maxkorp** [comment]
Provided you have a git user configured, you should just be able to use Signature.default, which should grab the git global user name and email. I _think_ the commit ref is correct, but I'd have to test to make sure. Those 5 args should be sufficient for you, as the promise should handle the 6th. I'm going to close this, and add creating a branch as a desired example. If you need more help, hop on into the Gitter room :+1:
