### ISSUE TITLE
Callbacks need to handle more use-cases

### ISSUE THREAD

**Issue by johnhaley81** [nodegit/nodegit#395]
Callbacks currently expect a result to be returned every time. This isn't the case however with things such as [git_status_foreac_ext](https://libgit2.github.com/libgit2/#HEAD/group/status/git_status_foreach_ext).

Also, the code that is looking for a return value currently doesn't work and we'll need https://github.com/tbranyen/combyne/pull/65 fixed before it works properly.

Additionally we'll need callbacks to handle having their own payloads instead of a universal payload that's sent to each callback. This is stopping the inclusion of many methods that use this pattern.

**Comment by johnhaley81** [comment]
This is a blocking issue for #355

**Comment by tbranyen** [comment]
Has this been resolved? Pretty sure I saw multiple payloads in the C++ last I looked.

**Comment by johnhaley81** [comment]
Not yet. The issue is with callbacks inside of a `class` function and not inside of a `struct`.

**Comment by johnhaley81** [comment]
However I was wrong about it being a blocking issue for #355 though.
