### ISSUE TITLE
Subtrees + custom error handling

### ISSUE THREAD

**Issue by leog** [nodegit/nodegit#400]
Hi there!

I was wondering if there is a plan to support subtrees commands in the near future.

Also, is there any way I can catch an error number corresponding to GIt thrown errors so I can decide what to do when errors happens?

Thanks a lot in advance.

**Comment by johnhaley81** [comment]
Nodegit just wraps libgit2 which itself doesn't have any direct subtree commands and it doesn't look like it will [any time soon](http://stackoverflow.com/questions/25372198/is-it-possible-to-use-subtree-commands-in-libgit2).

However with that being said you might be able to mimic the script of commands a `git subtree` does using what we have wrapped from libgit2.

As for your second question if a method results in an error we'll send up the string message but currently we don't send back the error number. Note that the number on the error will only refer to the [class](https://github.com/libgit2/libgit2/blob/HEAD/include/git2/errors.h#L53-L97) of error that happened. Some async methods will have a return value for an error but there isn't any real documentation on what those errors are or they are the results of a callback which are passed back up the original method.

**Comment by leog** [comment]
Thanks a lot for the detailed answers @johnhaley81.
Closing this thread.
Regards.

**Comment by johnhaley81** [comment]
Anytime :)
