### ISSUE TITLE
Tweak descriptor, run npm install, C++ not updated

### ISSUE THREAD

**Issue by tbranyen** [nodegit/nodegit#401]
When you tweak the descriptor and run `npm install` the generate scripts do not affect the C++.  If you run `node generate` first the code is updated.  Could you look into this @maxkorp?

**Comment by maxkorp** [comment]
Yeah, I need to find a way aroudn this. The point was to skip the step (and thereby not need to install/load modules) if installing from NPMs registry. I have an idea of how to rework this a bit more now, after talking through an issue on NPMs github a bit.

**Comment by tbranyen** [comment]
I believe this has been resolved as well.
