### ISSUE TITLE
segfault when cloning from private BitBucket repo

### ISSUE THREAD

**Issue by Lange** [nodegit/nodegit#406]
I spoke with @tbranyen about this in Gitter, and he said I should open a formal issue about it.

When attempting to clone from a private BitBucket repo via an HTTPS url, the clone operation will segfault if no `username@` portion of the url is provided AND a `remoteCallbacks.credentials` callback is provided:
```js
var Git = require('nodegit');

// Doesn't log anything, and makes a directory containing nothing but .git in it (no actual content, no errors)
Git.Clone.clone('https://bitbucket.org/endofline/wolv-nowplaying.git', 'tmp', {
    remoteCallbacks: {
        // Never gets called
        credentials: function (url, userName) {
            console.log('I should have gotten called!');
            return Git.Cred.sshKeyFromAgent('langeh');
        }
    }
})
    .catch(function(e) {
        console.error(e)
    });
```

Removing the callback causes the expected `401` error to print.

**Comment by johnhaley81** [comment]
Can you try repo'ing this on #390? That's a pretty big update to the latest version of libgit2 and I'm wondering if still happens after the update.

The code you have above shouldn't need to be modified.

**Comment by Lange** [comment]
I've cloned the current master branch (I noticed that #390 had been merged), and this issue still seems to happen.

This issue pretty low-priority for me, as it's not actually affecting any my production code. I just figured a segfault would be something you'd want to be aware of.

**Comment by johnhaley81** [comment]
Thanks, I do appreciated it. Something like this is definitely going to need to be fixed.

**Comment by tbranyen** [comment]
Yup so the error is that `NanNew` dies on the `NULL` username.   I've added in guards for this. in #419

**Comment by Lange** [comment]
Tested, no segfault! :clap: :beers:

**Comment by johnhaley81** [comment]
#419 is merged. Closing this out.
