### ISSUE TITLE
Potential example issue in add-and-commit.js L45-48

### ISSUE THREAD

**Issue by jeffwilcox** [nodegit/nodegit#409]
At line 45 of https://github.com/nodegit/nodegit/blob/master/examples/add-and-commit.js#L45 the sample calls `return index.addByPath(fileName)`; line 48 then calls the same method but with the directory name as well: `return index.addByPath(path.join(directoryName, fileName));`

Should l45 be removed? They feel redundant, and in the case that you're working with a subdirectory and similarly named files (like index.html), it's possible that this code could actually add two different fles to the index...

**Comment by tbranyen** [comment]
That's an interesting point, I hadn't noticed that before.  I'd be inclined to agree that 45 should be removed.  Have you tested that it still works as expected with it gone?

**Comment by jeffwilcox** [comment]
I haven't tested that way, as I'm actually not able to get file adds to work at all right now in my local development environment.

_I suspect user error on my part_

**Comment by johnhaley81** [comment]
That's committing 2 different files (and I can see how that would be hard to notice).

I'll modify the example so that it's more clear.

**Comment by jeffwilcox** [comment]
Got it... thx.
