### ISSUE TITLE
comparing from 0.1.4 to 0.2.0

### ISSUE THREAD

**Issue by cybernet** [nodegit/nodegit#410]
in the README.md file there is this part that shows a link to compare between versions, yet github responds with

There isn't anything to compare.

https://github.com/nodegit/nodegit/blob/b4e85cd641ebf537edfe2f41f4687057bc517c02/README.md
"
Migrating from old versions.

The bump from 0.1.4 to 0.2.0 was a big one. Many things changed, see here: https://github.com/nodegit/nodegit/compare/refs/tags/0.1.4...0.2.0

This update is wholly and entirely a breaking one, and older versions won't be maintained. For the purpose of migration, perhaps the biggest point to make is that async methods can now use promises, rather than just taking callbacks. Additionally, lots of method and property names have changed. "

**Comment by johnhaley81** [comment]
Thanks!

That link should be https://github.com/nodegit/nodegit/compare/v0.1.4...v0.2.0
