### ISSUE TITLE
Missing documentation for Tree.walk()

### ISSUE THREAD

**Issue by ljmatkins** [nodegit/nodegit#411]
In the tree walking example at https://github.com/nodegit/nodegit/blob/master/examples/walk-tree.js, the Tree.walk() method is used to enumerate the contents of a tree object.

However, in the documentation at http://www.nodegit.org/#Tree, there is no Tree.walk() method listed.

I also have the impression that there are in fact many such methods not listed in the Nodegit documentation.

**Comment by tbranyen** [comment]
We're working on documentation, I'd refer to the source for now or logging out the prototype chains to see what's available.  If you'd like to reopen this issue for your own tracking purposes, please do so here:

https://github.com/nodegit/nodegit.github.com/issues
