### ISSUE TITLE
Question: Is there a certificateCheck option available for pushing to a remote repository?

### ISSUE THREAD

**Issue by elaforc** [nodegit/nodegit#420]
I am currently accessing a private repository on Github using the ```https``` Oauth mechanism found [here](https://help.github.com/articles/git-automation-with-oauth-tokens/).

Using this Oauth mechanism works fine cloning a repository when I use the ```certificateCheck``` similar to the [clone.js example](https://github.com/nodegit/nodegit/blob/master/examples/clone.js#L14)

I am also trying to use a similar mechanism to push a new commit to the remote repository, but this ```certificateCheck``` mechanism does not seem to exist. I current see a ```Error: The SSL certificate is invalid``` when trying to do a push.

I can provide a code sample if needed, but thought maybe there was short answer to this question. 

Thanks for any help that anyone can provide.

**Comment by tbranyen** [comment]
Hi @elaforc we reserve the issue tracker for bugs, and have an excellent Gitter channel you can find in the README for general support questions like this.

That said, for pushing a remote you'd set the callback like this test:

https://github.com/nodegit/nodegit/blob/master/test/tests/remote.js#L100-L104

**Comment by elaforc** [comment]
Understood. Thanks for pointing me in the right direction (both with Gitter and my issue).

**Comment by tbranyen** [comment]
No worries, we're friendly folks, stop by and chat if you hit any more oddness.  Our new site should be live in the coming month(s) :D
