### ISSUE TITLE
fetchAll() fails unless a default signature is available

### ISSUE THREAD

**Issue by alexmcarthur** [nodegit/nodegit#431]
version 0.2.7

fetchAll() fails with [Error: Config value 'user.name' was not found] unless git global config 'user.name' is set to a non-empty string. If the string is empty the error is [Error: Failed to parse signature - Signature cannot have an empty name]. The fetchAll() function does not take a signature parameter, and ends up calling repo.defaultSignature().

To reproduce:
$ git config --global --unset user.name
or
$ git config --global user.name ''

Setting the system or local user.name makes no difference.
As far as I can tell there is no way to set the default user name other than via the command line.

**Comment by johnhaley81** [comment]
We definitely don't want this to fail. Maybe it could take in an optional parameter if you don't have your git options set up correctly? Or default to "unknown"?

All of our [config methods](https://libgit2.github.com/libgit2/#v0.21.5/group/config) currently are experimental. That means that the ones we do have access to in JS haven't been tested so it's use at your own risk.

**Comment by alexmcarthur** [comment]
I think either option is reasonable.

**Comment by johnhaley81** [comment]
I'm thinking that it should default to "unknown". That seems more like what git CLI does. If you want to overwrite the default signature then don't call the convenience method and call the actual `Remote.prototype.fetch` method.

**Comment by JediMindtrick** [comment]
Has this fix been published to npm?  I just encountered basically same error, except that it also needed email to be set.

**Comment by johnhaley81** [comment]
Yeah, we even have a test for it: https://github.com/nodegit/nodegit/blob/master/test/tests/signature.js#L48-L95

**Comment by JediMindtrick** [comment]
Strange.  Runs fine on my local, but when I move to an azure vm I'm seeing this kind of behavior.  Stepping through the code I definitely see the fix.   So I will continue digging.

**Comment by JediMindtrick** [comment]
Alright...so if I 
```
$ git config --global --unset user.name & git config --global --unset user.email
```
then this line (repository.js, line 542) throws an error '[Error: Config value 'user.name' was not found]' 
```
  var result = NodeGit.Signature.default(this);
```
Able to reproduce this on my local and I believe this is similar to what is happening when I deploy to a new clean environment (heroku and various bits of azure).

**Comment by jhansen-tt** [comment]
Still seeing this in my env as well. +1

**Comment by adrianpike** [comment]
I'm seeing this behavior too - what versions of libgit2 are you guys seeing this work and not work with?

**Comment by jamesyoung** [comment]
I'm seeing this issue as well using Heroku.
