### ISSUE TITLE
Add file to repo

### ISSUE THREAD

**Issue by melkior** [nodegit/nodegit#45]
Hi

Just interested, is it possible to add files to repository with nodegit? libgit2 binding for other languages do have modification features, but i really can't find anything similar in nodegit code.

Thanks.

**Comment by goforgold** [comment]
@nkallen Its a 404 URL

**Comment by faceleg** [comment]
Branch probably doesn't exist anymore

**Comment by goforgold** [comment]
Hi @faceleg 

Thanks for quick response.

Can you suggest me the best library in node.js to which cover followings?

- List branches
- Add new files, commit and push
- List commits

**Comment by tbranyen** [comment]
@goforgold this isn't the place for that question.  Ask Twitter or IRC.
