### ISSUE TITLE
Amazon S3 CDN link is broken

### ISSUE THREAD

**Issue by Jusonex** [nodegit/nodegit#482]
The link (https://nodegit.s3.amazonaws.com/nodegit/nodegit/) to the prebuilt binaries outputs "AccessDenied".

**Comment by johnhaley81** [comment]
You have to access a file directly I think. @tbranyen is that true?

**Comment by Jusonex** [comment]
Seems to be fixed now (I'm at least able to install nodegit directly via npm now)

**Comment by johnhaley81** [comment]
:+1:
