### ISSUE TITLE
Look into using `v8plus_cross_thread_call` for spawning callbacks from libgit2

### ISSUE THREAD

**Issue by johnhaley81** [nodegit/nodegit#487]
The current way we call JS functions from libgit2 is still not thread safe. This is in reference to https://github.com/nodegit/nodegit/pull/435#issuecomment-76475592

We'll need to look into getting v8plus into nodegit and using it's cross thread call to get into JS.

**Comment by johnhaley81** [comment]
This should fix #497

**Comment by maxkorp** [comment]
Since https://github.com/nodegit/nodegit/pull/546 fixed that, is this still necessary?

**Comment by johnhaley81** [comment]
Yeah, this can still go in and would help.

**Comment by tbranyen** [comment]
Last I checked we're thread safe now :+1:
