### ISSUE TITLE
Add pre-built binaries for atom-shell and nw.js

### ISSUE THREAD

**Issue by johnhaley81** [nodegit/nodegit#488]
We need some upgrades to https://github.com/mapbox/node-pre-gyp/ to get these going.

I suspect that nw.js might already work and I'll try that but https://github.com/mapbox/node-pre-gyp/pull/112 will have to land before we can provide pre-builts for that.

**Comment by maxkorp** [comment]
atleast for atom-shell/electron we can provide versions compiled against the default app name (in this case, atom, currently) but people will still need to rebuild on their own if there is a custom name applied to the app.

**Comment by tbranyen** [comment]
This has been resolved I believe? Please re-open if I'm wrong.
