### ISSUE TITLE
HTTP Proxy support

### ISSUE THREAD

**Issue by franckstauffer** [nodegit/nodegit#489]
It would be great to have support for HTTP/HTTPS proxies for people sitting behind corporate proxies who clone/push/pull to remote repositories. It looks like libgit2 is only supporting this in the winhttp transport backend and that there is an open issue libgit2/libgit2#2555 to support it by default.

**Comment by johnhaley81** [comment]
When that is closed out on libgit2 and released we'll make sure to get that into NodeGit as well. Thanks!

**Comment by franckstauffer** [comment]
As a followup, in the meantime if someone else stumbles upon that problem, using a tool like proxychains-ng rofl0r/proxychains-ng might ease the pain :)

**Comment by tbranyen** [comment]
Closing this as we cannot address it at this time.  As @johnhaley81 said, once it lands and is tagged in libgit2 it'll be available here.

**Comment by franckstauffer** [comment]
Ok fair enough...I only created the issue because @johnhaley81 invited me to do so on gitter!

**Comment by tbranyen** [comment]
Sure, don't take it as a jab, I'm just trying to tidy up the issue tracker :)

**Comment by johnhaley81** [comment]
I just wanted some kind of history :)

**Comment by maxkorp** [comment]
Labeling this, so we can zip through the closed stuff later and see if this has been addressed.

**Comment by Kerrick** [comment]
Looks like libgit2 merged in support for proxies! libgit2/libgit2#3110

**Comment by johnhaley81** [comment]
Working on merging that now :)

**Comment by vbarshai** [comment]
Has this ever been merged? Or is the issue still open? Thanks!

**Comment by cbargren** [comment]
Proxy support did get merged in, this can probably be closed.

**Comment by vbarshai** [comment]
Thanks @cbargren it's been merged in v0.15.0 but looks like the latest builds break:
babel --presets es2015 -d ./dist ./lib (no lib dir)

**Comment by hellosmithy** [comment]
Has anyone managed to get this working behind a corporate proxy?

**Comment by vbarshai** [comment]
@hellosmithy not on our side - ended up having to use proxy exports and native git commands as a workaround until a stable release.

**Comment by johnhaley81** [comment]
@cbargren and @implausible were working on getting something going here but ran into some bigger issues.

**Comment by cbargren** [comment]
Yeah, unfortunately proxy support is only implemented in the curl and openSSL transport streams, neither of which are currently used by NodeGit. @implausible knows a little more, but NodeGit needs to be able to use one of those for us to be able to utilize libgit's proxy support. It also needs to be fixed in NodeGit(the generated code isn't working properly), but that should be much simpler than the curl/openSSL issues.

**Comment by johnhaley81** [comment]
This is now fixed on master.

**Comment by clearly** [comment]
I've been trying to use this (proxyOpts on push) but don't seem to be doing something correctly. Can someone provide an example of how to use proxy with un/pw in a push? Don't see any tests that show it either.

**Comment by kriks7iitk** [comment]
D

> I've been trying to use this (proxyOpts on push) but don't seem to be doing something correctly. Can someone provide an example of how to use proxy with un/pw in a push? Don't see any tests that show it either.
> 
> To be clear, the credentials callback is never invoked. I'm using 0.19.0. My proxyOpts passed into pushOptions is as follows:
> 
> ```
>       proxyOpts : {
>         url : 'http://myproxy.country.org.com:745',
>         type : 2,
>         credentials : function() {
>           return git.Cred.userpassPlaintextNew( 'MyId', 'MyPassword );
>         },
>         version : 1
>       }
> ```

@clearly is it solved??
