### ISSUE TITLE
Create git-like CLI

### ISSUE THREAD

**Issue by secrettriangle** [nodegit/nodegit#508]
Would be great if this came with (or maybe someone made a new repo for) a git-like CLI. NodeOS is in desperate need of something like this! (nodeos/nodeos#67)

**Comment by johnhaley81** [comment]
We've definitely talked about this and I think it's a great idea.

I do think though it's out of scope for NodeGit. However, NodeGit would be a solid back-end for such an implementation though.

**Comment by piranna** [comment]
Node.js packages can work both as libraries and binaries due to the ```bin``` field, so a CLI command that delegates all its functionality to the library would be possible...

**Comment by tbranyen** [comment]
@piranna I don't think any of us want to write it.  If someone else writes it and PRs, we can discuss it for real then.

**Comment by maxkorp** [comment]
Yeah, I'd be down to _help_ maintain it, or even help write it, but I wouldn't want to be the sole source of it.

**Comment by thisconnect** [comment]
Hi, I made a start with a JavaScript API for NodeGit inspired by git cli / https://git-scm.com/. Trying to not use too many dependencies and keep it simple.  Any feedback is highly appreciated https://www.npmjs.com/package/nodegit-kit 

There is a other modules on npm https://www.npmjs.com/browse/keyword/nodegit too, maybe we could join effort?

**Comment by piranna** [comment]
@tylerl0706 has been working on a [Node.js git client](https://github.com/NodeOS/NodeOS/issues/67#issuecomment-167281113) to allow to use git repositories on NodeOS, maybe you would be interested to contact him to join efforts :-)

**Comment by thisconnect** [comment]
ty
