### ISSUE TITLE
Open a Repo from a subfolder

### ISSUE THREAD

**Issue by Globegitter** [nodegit/nodegit#509]
Reading from the docs and playing around a bit with `Git.Repository.open()`, it seems it can only open a git repository if it is the root folder. The way my app works, the user can pass in any file from within any of their repositories and then I am handling that. so it would be really convenient if I could just pass the path of the file to `Git.Repository.open()` and it would automatically detect the git repository, no matter how many levels down.

Any chance to get this functionality?

**Comment by tbranyen** [comment]
Hi @Globegitter we reserve the issue tracker for bugs, you can get general support for this project in our [Gitter channel](https://gitter.im/nodegit/nodegit)

To answer your question though, you want to use: http://www.nodegit.org/api/repository/#openExt and enable the search option.

**Comment by Globegitter** [comment]
Will do and thank you!
