### ISSUE TITLE
Cred.sshKeyNew not working: Too many redirects or authentication replays

### ISSUE THREAD

**Issue by dcodeIO** [nodegit/nodegit#511]
Hello everyone,

I am trying to automate pushing to a GitHub repository using `NodeGit.Cred.sshKeyNew`, but it looks like I am not able to get this working somehow. `NodeGit.Cred.userpassPlaintextNew` works just fine.

This is what I have:

```js
}).then(function(remoteResult) {
	remote = remoteResult;
	remote.setCallbacks({
		credentials: function(url, userName) {
			return nodegit.Cred.sshKeyNew(
				userName,
				path.join(__dirname, "..", "..", "data", "mykey-rsa.pub"),
				path.join(__dirname, "..", "..", "data", "mykey-rsa"),
				"myPass"
			);
		}
	});
	return remote.connect(nodegit.Enums.DIRECTION.PUSH);
})
```

Which always results in: `Error: Too many redirects or authentication replays`.

I did double check that:
* paths to the public and private key files are correct
* the key is properly installed on GitHub
* the key has been generated with `ssh-keygen -t rsa`
* the key's password is correct

Am I doing something wrong there?

**Comment by tbranyen** [comment]
Have you looked at https://github.com/nodegit/nodegit/blob/master/test/tests/clone.js#L92-L114 by any chance?

**Comment by dcodeIO** [comment]
Yes, looked over the test cases as well. If you intended to hint me at something, I'd be happy for an explanation.

**Comment by tbranyen** [comment]
@dcodeIO the only hint there is that it's a working example, unfortunately with the code you provided I don't know what the bug is.  Maybe try asking in the #libgit2 channel on IRC?

**Comment by mikalai-silivonik** [comment]
I used to have the same issue... In my case remote URL was set to `https` instead of `ssh`.

**Comment by johnhaley81** [comment]
@dcodeIO I think that @mikalai-silivonik is correct. If you're using `NodeGit.Cred.userpassPlaintextNew` and that's working then you're not using SSH and no SSH key in the world is going to authenticate you into an HTTPS session. Try switching protocols.

**Comment by dcodeIO** [comment]
Stupid me. Thanks!
