### ISSUE TITLE
It's looking for node-typ under `/Users/johnh/.node-gyp`

### ISSUE THREAD

**Issue by cheapsteak** [nodegit/nodegit#518]
```
Assertion failed: (handle->InternalFieldCount() > 0), function Unwrap, file /Users/johnh/.node-gyp/0.10.36/src/node_object_wrap.h, line 61.
```

Eh?

**Comment by johnhaley81** [comment]
Get off of my computer!!!

You're getting that error because I published that binary and it stored those file paths in the compiled file.

What were you calling that you got that error?

**Comment by cheapsteak** [comment]
`repo.getCurrentBranch()` after calling `Repository.open(pathToRepo);`

**Comment by johnhaley81** [comment]
Can you post the code block?

**Comment by cheapsteak** [comment]
My apologies, the error is my own.   

I misused `getCurrentBranch` as a sync function that returns a value instead of a promise.  

I was doing this  

```javascript
var currentBranchRef = repo.getCurrentBranch();
var currentBranchName = Branch.name(currentBranchRef);
```
when I should have been doing this
```javascript
var currentBranchRef = repo.getCurrentBranch();
var currentBranchName = currentBranchRef.name();
```

btw for some reason this results in a malloc error

```javascript
var currentBranchRef = await repo.getCurrentBranch();
var currentBranchName = Branch.name(currentBranchRef);
```

but that's a separate issue and I'm probably using something wrong again. feel free to close this issue :)
Thank you for the prompt responses!

fwiw the error message was 

```bash
{ then: [Function],
  state: null,
  isFulfilled: [Function],
  isRejected: [Function],
  isPending: [Function],
  value: [Function],
  reason: [Function] }
node(20817,0x7fff78ac6300) malloc: *** error for object 0x100d022e7: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
sh: line 1: 20817 Abort trap: 6           node deploy.js
```

**Comment by maxkorp** [comment]
Youre still not using promises (or a callback) for those.
```js
var currentBranchRef; 
var currentBranchName;
repo.getCurrentBranch().then(function(branchRef) {
    currentBranchRef = branchRef;
    currentBranchName = currentBranchRef.name();
});
```

**Comment by cheapsteak** [comment]
apologies, I copy pasted from the one above, changed one line and forgot to change the other  

I ended up doing this and that did work  

```javascript
var currentBranchRef = await repo.getCurrentBranch();
var currentBranchName = currentBranchRef.name();
```

**Comment by tbranyen** [comment]
@cheapsteak gah I love how async/await looks with NodeGit, ES6/7 can't come soon enough!

**Comment by maxkorp** [comment]
excellent 
![Mr Burns](http://cleaneatsfastfeets.com/wp-content/uploads/2013/05/Mr-Burns.gif)
