### ISSUE TITLE
Cannot build nodegit for nw.js - i have got cpp errors

### ISSUE THREAD

**Issue by shellka** [nodegit/nodegit#519]
i am trying to build with command: node_modules.bin\nw-gyp rebuild --target=0.12.0 --msvs_version=2013 --arch=ia32 --target-arch=ia32 --target_arch=ia32 --platform=win32
and have errors:
  Finished generating code
- CIL library _(_ CIL module *) : error LNK2005: "public: __thiscall v8::EscapableHandleScope::~EscapableHandleScope(void)" (??1EscapableHandleScope@v8@@QAE@XZ
  ) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module _) : error LNK2005: "public: char \* __thiscall v8::String::Utf8Value::operator_(void)" (??DUtf8Value@String@v8@@QAEPADXZ) already
  defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: static class v8::Array \* __cdecl v8::Array::Cast(class v8::Value *)" (?Cast@Array@v8@@SAPAV12@PAVValu
  e@2@@Z) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: static class v8::External \* __cdecl v8::External::Cast(class v8::Value *)" (?Cast@External@v8@@SAPAV1
  2@PAVValue@2@@Z) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: static class v8::Function \* __cdecl v8::Function::Cast(class v8::Value *)" (?Cast@Function@v8@@SAPAV1
  2@PAVValue@2@@Z) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: void \* __thiscall v8::Object::GetAlignedPointerFromInternalField(int)" (?GetAlignedPointerFromInterna
  lField@Object@v8@@QAEPAXH@Z) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: bool __thiscall v8::Value::IsNull(void)const " (?IsNull@Value@v8@@QBE_NXZ) already defined in nw.lib(
  nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: bool __thiscall v8::Value::IsString(void)const " (?IsString@Value@v8@@QBE_NXZ) already defined in nw.
  lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: bool __thiscall v8::Value::IsUndefined(void)const " (?IsUndefined@Value@v8@@QBE_NXZ) already defined
  in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: static class v8::Handle<class v8::Boolean> __cdecl v8::Boolean::New(class v8::Isolate *,bool)" (?New@
  Boolean@v8@@SA?AV?$Handle@VBoolean@v8@@@2@PAVIsolate@2@_N@Z) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "private: bool __thiscall v8::Value::QuickIsNull(void)const " (?QuickIsNull@Value@v8@@ABE_NXZ) already defined
  in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "private: bool __thiscall v8::Value::QuickIsString(void)const " (?QuickIsString@Value@v8@@ABE_NXZ) already def
  ined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "private: bool __thiscall v8::Value::QuickIsUndefined(void)const " (?QuickIsUndefined@Value@v8@@ABE_NXZ) alrea
  dy defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: class v8::Local<class v8::Boolean> __thiscall v8::Value::ToBoolean(void)const " (?ToBoolean@Value@v8@
  @QBE?AV?$Local@VBoolean@v8@@@2@XZ) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: class v8::Local<class v8::Int32> __thiscall v8::Value::ToInt32(void)const " (?ToInt32@Value@v8@@QBE?A
  V?$Local@VInt32@v8@@@2@XZ) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: class v8::Local<class v8::Integer> __thiscall v8::Value::ToInteger(void)const " (?ToInteger@Value@v8@
  @QBE?AV?$Local@VInteger@v8@@@2@XZ) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: class v8::Local<class v8::Number> __thiscall v8::Value::ToNumber(void)const " (?ToNumber@Value@v8@@QB
  E?AV?$Local@VNumber@v8@@@2@XZ) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: class v8::Local<class v8::Object> __thiscall v8::Value::ToObject(void)const " (?ToObject@Value@v8@@QB
  E?AV?$Local@VObject@v8@@@2@XZ) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: class v8::Local<class v8::String> __thiscall v8::Value::ToString(void)const " (?ToString@Value@v8@@QB
  E?AV?$Local@VString@v8@@@2@XZ) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
- CIL library _(_ CIL module *) : error LNK2005: "public: class v8::Local<class v8::Uint32> __thiscall v8::Value::ToUint32(void)const " (?ToUint32@Value@v8@@QB
  E?AV?$Local@VUint32@v8@@@2@XZ) already defined in nw.lib(nw.exe) [e:\repos\nodegit\build\nodegit.vcxproj]
  e:\repos\nodegit\build\Release\nodegit.node : fatal error LNK1169: one or more multiply defined symbols found [e:\repos\nodegit\build\nodegit.vcxproj]
  gyp ERR! build error
  gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
  gyp ERR! stack     at ChildProcess.onExit (e:\repos\nodegit\node_modules\nw-gyp\lib\build.js:267:23)
  gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
  gyp ERR! System Windows_NT 6.1.7601

**Comment by johnhaley81** [comment]
I'll look into this more on Monday when I get access to a windows box.

**Comment by shellka** [comment]
Ty!

**Comment by maxkorp** [comment]
Im betting nw.js/nw-gyp is having an issue with our version of nan here.

**Comment by rcjsuen** [comment]
Closing as NW.js is [no longer supported](nodegit/nodegit.github.com/issues/47).
