### ISSUE TITLE
Path issues windows

### ISSUE THREAD

**Issue by Globegitter** [nodegit/nodegit#522]
When using `patch.oldFile().path();` as per example seen here https://github.com/nodegit/nodegit/blob/master/examples/walk-history-for-file.js#L27 the path returned here stays with forward-slashes (`/`), where-as when you use nodejs' `path` it returns backwards-slashes. This now makes comparing part of the path quite hard.

The workaround I currently have it just to replace all slashes in the path string, so they match.

**Comment by tbranyen** [comment]
Git uses forward slashes internally, we should never ever change them to be back slashes.

**Comment by Globegitter** [comment]
ahh ok, so what is the recommend approach on windows then? Just not use the nodejs `path` module?

**Comment by tbranyen** [comment]
Node normalizes paths for you.  Can you paste an example where this isn't true?

**Comment by Globegitter** [comment]
That is exactly the problem - node normalizes the path to windows style, so `path\to\file` but git uses `path/to/file`.

**Comment by tbranyen** [comment]
Try using: https://nodejs.org/api/path.html#path_path_format_pathobject

**Comment by tbranyen** [comment]
I think this is out of the scope of NodeGit, which is attempting to bind 1:1 to libgit2 and where possible provide some convenience over repetitive tasks.  By allowing either Unix or Windows style, we'd be breaking a convention from within Git.

You can normalize with a simple enough replace regex: `path = path.replace(/\\/g, '/');`

**Comment by maxkorp** [comment]
@Globegitter could you not call path.normalize on the returned value, like so?
```js
path.normalize(patch.oldFile().path());
```
