### ISSUE TITLE
hey !:-) problem with Branch.iteratorNew  (support)

### ISSUE THREAD

**Issue by bbsalsero** [nodegit/nodegit#528]
could show me an exemple of how to use Branch.iteratorNew?

**Comment by maxkorp** [comment]
This feels like a language barrier issue possibly, so I'll clarify a bit.

@bbsalsero, we don't use issues for support, only for bugs and feature requests. For support, please use our gitter chatroom. It's listed in our readme, but here is a link as well. 
https://gitter.im/nodegit/nodegit
