### ISSUE TITLE
'Error: 'directory' exists and is not an empty directory' (but it doesn't exist)

### ISSUE THREAD

**Issue by BT23** [nodegit/nodegit#530]
I'm trying to clone a repo with this code and I'm getting the error ''./tmp' exists and is not an empty directory':

```javascript
var git = require('nodegit');

var repos = [https repos]

for(i = 0; i<repos.length; i++){
	git.Clone(repos[i], './tmp', {ignoreCert}).catch(function(err) { console.error(err); } );
}
```

When I run 'cd ./tmp' while in the same directory as the script, it gives me `-bash: cd: ./tmp: No such file or directory`.

**Comment by BT23** [comment]
Realized that this was my fault. The error came when the loop ran the second time.

**Comment by apgapg** [comment]
Is there any force clone option?
