### ISSUE TITLE
Repository.init should accept boolean value for is_bare

### ISSUE THREAD

**Issue by ivantm** [nodegit/nodegit#538]
The docs for the `is_bare` param of [Repository.init](http://www.nodegit.org/api/repository/#init) read:

> if true, a Git repository without a working directory is created at the pointed path. If false, provided path will be considered as the working directory into which the .git directory will be created.

Yet the type of `is_bare` is expected to be a Number. Passing a boolean leads to an error: `[Error: Number is_bare is required.]`.

Having the docs refer to true and false when the expected type is a Number seems incongruous, especially if the value of the number has no impact on the outcome (other than the whether the number is truthy or falsy). If the value of the number does matter, please update the docs to refer to numbers; otherwise I'd expect the function to be able to accept a boolean.

**Comment by tbranyen** [comment]
Yup! We're aware of this issue: https://github.com/nodegit/nodegit/pull/383 it's not trivial, but we'll hopefully get it added in eventually as it's rather confusing.

**Comment by tbranyen** [comment]
Closing as duplicate

**Comment by ylecuyer** [comment]
I ran into this issue although it has been closed a long time ago
