### ISSUE TITLE
ELIFECYCLE Error on install

### ISSUE THREAD

**Issue by fed135** [nodegit/nodegit#540]
> nodegit@0.3.3 install /home/fcharette/Documents/workspace/project/node_modules/nodegit
> node lifecycleScripts/install

module.js:318
    throw err;
          ^
Error: Cannot find module '/home/fcharette/Documents/workspace/project/node_modules/nodegit/lifecycleScripts/install'
    at Function.Module._resolveFilename (module.js:316:15)
    at Function.Module._load (module.js:258:25)
    at Function.Module.runMain (module.js:451:10)
    at startup (node.js:123:18)
    at node.js:889:3

npm ERR! Linux 3.16.0-34-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install"
npm ERR! node v1.6.3
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE
npm ERR! nodegit@0.3.3 install: `node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodegit@0.3.3 install script 'node lifecycleScripts/install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/install

I'm running Ubuntu 14.10
iojs 1.6.3

Any idea why this is happening ?

**Comment by maxkorp** [comment]
Hrm, are you running the install a second time?

**Comment by fed135** [comment]
After a bit of looking, seems like I was. Thought I was calling 'npm install' on a clean projet, turns out I wasn't. Thanks!

**Comment by maxkorp** [comment]
:+1:
