### ISSUE TITLE
How to get Tag instance by tag_name?

### ISSUE THREAD

**Issue by dickeylth** [nodegit/nodegit#543]
In the <http://www.nodegit.org/api/tag/>, I tried to figure out how to get the tag instance through tag name, but it's really very confusing!

In the `Tag.list`, it just lists the tag names instead of instances, in the `Tag.lookup`, I need to pass the oid or Tag ??? If I already get the tag instance why would I need to call the `Tag.lookup` method? That's really confusing!

Besides, the documentations are not very straight, hope to see relative demos in each api documentation.

**Comment by dickeylth** [comment]
Finally found `http://www.nodegit.org/api/repository/#getTagByName`, end issue.

**Comment by dickeylth** [comment]
Unfortunately, it only applies to annotated tags: <https://github.com/nodegit/nodegit/issues/298>.

**Comment by johnhaley81** [comment]
@dickeylth yes. Unfortunately in low level git they are very disjoint and handled differently. This is a source of much confusion right now and any help to figure out how to fix this would be welcome :)
