### ISSUE TITLE
Install error from openssl

### ISSUE THREAD

**Issue by callumacrae** [nodegit/nodegit#551]
I asked about this issue on gitter but it wasn't resolved, so I'll post it here instead.

When installing the module as a dependency, I get no errors during the install process, but nodegit.js isn't built so it fails to load.

When cloning the repo and running `npm install`, I get the following error: https://gist.github.com/callumacrae/6a56b067309325f5a668

How do I fix this?

**Comment by maxkorp** [comment]
This appears to be an issue with nans version and a bad semver qualifier on our part. see here
https://github.com/nodegit/nodegit/issues/551

**Comment by tbranyen** [comment]
Didn't I already merge a fix?

**Comment by maxkorp** [comment]
Gah, yeah, I totally didn't see that for some reason. Perhaps I hadn't pulled yet? Oh well. awesome. Nevermind me!

**Comment by callumacrae** [comment]
Master installed fine. Quite a few of the nodegit tests failed, but I followed the steps here and they worked: https://github.com/nodegit/nodegit/issues/372#issuecomment-72528008

My tests are failing, so I won't close this right away—I'll see if they're related.

**Comment by callumacrae** [comment]
Yeah, it's a different issue. Thanks!
