### ISSUE TITLE
How to get remote latest commit?

### ISSUE THREAD

**Issue by olivierlesnicki** [nodegit/nodegit#559]
I have a nodegit repo and would like to check if it's out of sync with its remote.

**Comment by tbranyen** [comment]
Hey @olivierlesnicki please ask support questions in our Gitter room: https://gitter.im/nodegit/nodegit

**Comment by jmeas** [comment]
For future visitors:

`getReferenceCommit('head');`

Docs:

http://www.nodegit.org/api/repository/#getReferenceCommit
