### ISSUE TITLE
Cloning git sub modules using "nodegit" npm module

### ISSUE THREAD

**Issue by shivakumarpm** [nodegit/nodegit#560]
While cloing any git modules (https://github.com/xyz.git) if that modules is dependent on sub modules to clone, then can i or is it possible to clone git submodules using "nodegit" modules (https://github.com/nodegit/nodegit).

**Comment by tbranyen** [comment]
Yes it is possible.  See the OP here for clues on how to do it:

**Comment by shivakumarpm** [comment]
Hi @tbranyen, one thing i am not able to understand that "libgit2sharp" is a native module, i want to clone recursively without installing git on my system. Instead i want to use node module to clone recursively. i used nodegit module like " var clone = require("nodegit").Clone.clone;
// Clone a given repository into a specific folder.
clone("https://github.com/xyz.git", "bootplate-moonstone", null)
.then(function(repo) {
finish();
})
.catch(function(err) { finish(err, {msg : 'error while cloning'});});" but it wont clones sub modules. 
Could you please guide me how to clone sub modules suing "nodegit"?

**Comment by maxkorp** [comment]
Libgit2sharp is a wrapper for libgit2 in c#, the same way that nodegit is a wrapper for libgit2 for javascript (albeit largely written in C++). The same series of commands you would use in one shouldmostly apply in the other. 

What Tim was saying is that this is the algorithm for doing what you want to do, just use nodegit commands instead of libgit2sharp commands, since the structure carries over. 

If you need more help, talk to us in our gitter room https://gitter.im/nodegit/nodegit and we'll get you all sorted out :+1:

**Comment by tbranyen** [comment]
@ggendre nope, but we are: https://github.com/nodegit/nodegit/blob/master/generate/input/descriptor.json#L1931-L1933 I don't remember why we don't compile it, but that method is ignored atm

**Comment by johnhaley81** [comment]
@ggendre A PR with that method enabled and some tests confirming the functionality would be amazing *hint hint nudge nudge*

**Comment by ggendre** [comment]
Sorry, I have not enough time to dive into this.

Instead, to ugly-fix my needs, I made a loop over the submodule list grabbed from the modules list in .gitmodules

    Ini = require('ini');
    var config = Ini.parse(fs.readFileSync(path.normalize( localPath + '/.gitmodules'), 'utf-8'));
    //if startswith submodule, push into modules
    modules = [];
    for (var i in config) {
        if (i.indexOf('submodule') === 0){
            modules.push(config[i]);
        }
    }
    for (var i in modules) {
        var modulePath = modules[i].path;
        Git.Submodule.lookup(repository, modulePath).then(function(submodule) {
            // Use submodule
            log.success("got submodule '" + submodule.path() + "'");
            try{
                submodule.init(1);
                log.success("submodule init worked");
            }catch(e){
                log.error("submodule init failed "+ e);
            }
            try{
                submodule.update(1,new Git.CheckoutOptions);
                log.success("submodule update worked");
            }catch(e){
                log.error("submodule update failed "+ e);
            }
        },function(err){
            log.error('cant get submodule : '+err)
        });
    }

This doesn't need to be recursive, submodules of submodules are retrieved with the init or update function.

This is quite ugly but I'm posting it here if it can help anybody. Maybe one day I will dive into the writing of tests you talked about, but not now :)

have a good day,

**Comment by papiro** [comment]
@ggendre, I can't believe I didn't find your post sooner.  I looked everywhere for an example of how to do this and couldn't find anything!  I too had the same issue and decided to manually parse the .gitmodules file and I even was having trouble getting the right syntax for submodule.update (didn't know about new Git.CheckoutOptions).  Thanks!

**Comment by ggendre** [comment]
for the record, nodegit now has a `foreach` and `lookup`method to browse submodules

**Comment by felixfbecker** [comment]
@ggendre Do you have a small snippet that essentially does `git clone --recursive`? Completely lost

**Comment by allomov** [comment]
@felixfbecker [here](https://gist.github.com/allomov/e9b7d4506c271a24e87d91371a323076) is a recursive function I have come to.
