### ISSUE TITLE
Globally installed NodeGit wipes out NPM

### ISSUE THREAD

**Issue by tbranyen** [nodegit/nodegit#561]
http://stackoverflow.com/questions/30128359/running-npm-install-unbuilds-global-npm

@maxkorp I know you wrote the cleanup code, any idea if we uninstall NPM? If so, we probably should stop doing that :-p

**Comment by andrepadez** [comment]
oh, thanks @tbranyen . Just came here to open this issue...

**Comment by maxkorp** [comment]
FYI if this _is_ an issue, the no more cleaning thing that landed yesterday should fix it.

**Comment by andrepadez** [comment]
I started using 0.4.0 today, and i still get npm unbuilt...

**Comment by maxkorp** [comment]
Yeah, that's landed in master, but there's on more critical bug waiting to clear (fix is found) before we publish the update.

**Comment by andrepadez** [comment]
cool thanks. let us know when, please :+1:

**Comment by tbranyen** [comment]
@andrepadez no specific time frame, you can install from master with `nodegit/nodegit#master` in your package.json.

**Comment by andrepadez** [comment]
thank you @tbranyen . will do

**Comment by andrepadez** [comment]
actually not. 
I run npm install on my module, it installs nodegit in my node_modules, but when i run my project node says it can't find module 'nodegit'.

I checked the package.json where the "main" is "lib/nodegit.js" and that file is not there.
I tried changing to "lib/index.js" but it throws some error so probably that shouldn't be the entry file also.

Help please?

**Comment by tbranyen** [comment]
@andrepadez sounds like a compile failure.  What OS are you running?

**Comment by andrepadez** [comment]
OSX Yosemite 10.10.2 (14C2055)

**Comment by tbranyen** [comment]
Hrm I know @johnhaley81 and @maxkorp are running OS X, maybe they can chime in if there's anything special you need to do before the compile will work.  I'd imagine you have XCode installed right?

**Comment by andrepadez** [comment]
@tbranyen yes i do

**Comment by johnhaley81** [comment]
I've been building 0.4.0 on OSX 10.10.3 in node 0.10.38 and 0.12.2. Are you trying to install in nw.js or electron by chance?

**Comment by andrepadez** [comment]
here's my usecase:
```
$ git clone git@github.com:vigour-io/gaston.git
$ cd gaston
$ git checkout new-gaston
$ npm install
$ ./bin/gaston.js
```
with this, i get module nodegit not found.

@johnhaley81  Can you try it? thanks

**Comment by johnhaley81** [comment]
It hangs while trying to clone `https://github.com/vigour-io/vigour-js`

```
ohnhosx-2 :: ~/Development » git clone git@github.com:vigour-io/gaston
Cloning into 'gaston'...
remote: Counting objects: 6778, done.
remote: Compressing objects: 100% (304/304), done.
Receiving objects:  68% (4610/6778), 3.04 MiB | 1.10 MiB/s
remote: Total 6778 (delta 178), reused 0 (delta 0), pack-reused 6468
Receiving objects: 100% (6778/6778), 6.27 MiB | 1.20 MiB/s, done.
Resolving deltas: 100% (1900/1900), done.
Checking connectivity... done.
johnhosx-2 :: ~/Development » cd gaston
johnhosx-2 :: ~/Development/gaston ‹master› » git checkout new-gaston
Branch new-gaston set up to track remote branch new-gaston from origin.
Switched to a new branch 'new-gaston'
johnhosx-2 :: ~/Development/gaston ‹new-gaston› » npm install
|sername for 'https://github.com': -
/assword for 'https://github.com': /
npm ERR! git clone https://github.com/vigour-io/vigour-js Cloning into bare repository '/Users/johnh/.npm/_git-remotes/https-github-com-vigour-io-vigour-js-0abf4cd2'...
npm ERR! git clone https://github.com/vigour-io/vigour-js remote: Repository not found.
npm ERR! git clone https://github.com/vigour-io/vigour-js fatal: Authentication failed for 'https://github.com/vigour-io/vigour-js/'
npm ERR! Error: Command failed: Cloning into bare repository '/Users/johnh/.npm/_git-remotes/https-github-com-vigour-io-vigour-js-0abf4cd2'...
npm ERR! remote: Repository not found.
npm ERR! fatal: Authentication failed for 'https://github.com/vigour-io/vigour-js/'
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Socket.<anonymous> (child_process.js:979:11)
npm ERR!     at Socket.emit (events.js:95:17)
npm ERR!     at Pipe.close (net.js:466:12)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.3.0
npm ERR! command "/Users/johnh/.nvm/v0.10.38/bin/node" "/Users/johnh/.nvm/v0.10.38/bin/npm" "install"
npm ERR! cwd /Users/johnh/Development/gaston
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/johnh/Development/gaston/npm-debug.log
npm ERR! not ok code 0
```

**Comment by andrepadez** [comment]
Yes that is a private repo. If you remove it from dips it should be fine.

**Comment by maxkorp** [comment]
Odd, it should generate lib/nodegit.js. 

Confirmed, doing it in a different directory works. And you have a global install of nodegit as well? based on the git repo? did you clone and link, or how did you do that?

**Comment by maxkorp** [comment]
Yup, it's there with gaston. Trying `./bin/gaston.js` fails on account of the missing vigour-js (deleted it from deps like you suggested), but the file is there in `node_modules/nodegit/lib`. I'm inclined to think something is amiss with this global install, however that's been set up. We've never really tested that.

**Comment by johnhaley81** [comment]
Yep, I can build it as well.

https://gist.github.com/johnhaley81/9bd23824958d82ac9216

**Comment by andrepadez** [comment]
so:
remove node_modules + npm install (has a cat of package.json to see the nodegit dep)
https://gist.github.com/andrepadez/4f59488358e9ac80cec8

running the project:
https://gist.github.com/andrepadez/baddec733414387bd6bb

**Comment by maxkorp** [comment]
Woah, it's downloading the binary even though it's coming from a git location o.O

That is very much a problem, albeit a separate one. Ummmmm. lemme take a look at that.

**Comment by andrepadez** [comment]
Oh, again thanks a lot for this

**Comment by maxkorp** [comment]
I'll make an issue for this, cause we'll need it to confirm that the new version fixes the original issue seen here (unless that gets published first).

**Comment by maxkorp** [comment]
This is resolved, the cleanup code went away long ago
