### ISSUE TITLE
Consider removing intelligent build (shelling to pangyp). 

### ISSUE THREAD

**Issue by maxkorp** [nodegit/nodegit#563]
I'm leaning towards getting rid of the intelligent build process soon. It's caused issues before (now we call out to pangyp instead of node-gyp, fortunately), but a lot of the benefit seems like it's meant to be handled by other workflows, eg apm handling building native modules (or gyp defines, etc for electron apps with different names/versions). Not sure how nw.js handles it, but I'm betting an nw-gyp rebuild probably will redo your whole structure, invalidating the need for this and a lot of the complexity it adds. Basically we handle this, but other native modules still don't, and it feels like that responsibility is shifting towards the package management side (I guess it was just kind of up in the air before, tbh). I still wanna pre-generate/fetch the deps, but shelling out to the build ourselves can probably go away, and reliability AND portability would benefit (along with simpler code). 

Anybody have any thoughts or opposition?

**Comment by maxkorp** [comment]
@tbranyen @johnhaley81 @orderedlist 
Anybody have thoughts on this? If nobody has any complaints I might throw this in for a 0.5 release.

**Comment by johnhaley81** [comment]
:+1: I feel like it messes up a lot of things in nwjs/electron land.

**Comment by maxkorp** [comment]
https://github.com/nodegit/nodegit/issues/574

Like that. I'm going to go through with this tonight unless someone has complaints. Too many issues, it's really not needed anymore. Even more recent versions of node 10 will auto call the appropraite node-gyp version.

**Comment by maxkorp** [comment]
Yeah this isn't ever going to be a thing until npm3+ is long since the only standard
