### ISSUE TITLE
Build is broken on windows

### ISSUE THREAD

**Issue by maxkorp** [nodegit/nodegit#565]
Getting lots of libssh issues during compile, seems tied to the commit where libssh was updated from 1.4.3 to 1.5.0. Trying a rollback now.

**Comment by tbranyen** [comment]
Huh, how is Appveyor passing then?

**Comment by maxkorp** [comment]
It's not even running the tests since the build fails. Since they don't run, they dont fail! At least as far as I can tell >.<

**Comment by maxkorp** [comment]
Confirmed, rolling back to 1.4.3 fixes it. I'll make a PR, but we'll leave it until we figure out the false positives.

**Comment by tbranyen** [comment]
I messed something up with:

https://github.com/nodegit/nodegit/blob/master/package.json#L93

it returns success during a failure :-1:

**Comment by maxkorp** [comment]
Gotcha. Awesome lol
