### ISSUE TITLE
Feature Request: high-level lookup similar to `git rev-parse`

### ISSUE THREAD

**Issue by marshall007** [nodegit/nodegit#569]
In particular, I need a way to lookup a commit based on a SHA prefix (i.e. `dae86e` vs `dae86e1950b1277e545cee180551750029cfe735`). Correct me if I'm wrong, but I don't see a way to do this with the current API short of walking the entire history.

Having a high-level function like `Repository.revParse()` would make it much easier to resolve references based on arbitrary user input.

**Comment by tbranyen** [comment]
I've used short SHA's and it worked just fine.  Have you tried it yet?

**Comment by marshall007** [comment]
@tbranyen which method did you use? I've tried `Commit.lookup`, `Commit.lookupPrefix` but I get `Error: Unable to parse OID - contains invalid characters` in either case.

**Comment by marshall007** [comment]
@tbranyen sorry to ping you again, but would you mind posting an example? This would be really useful for the project I'm currently working on.

**Comment by pwagener** [comment]
For those stumbling in here from Google trying to do a similar thing, the solution I'm going with in `v0.15.1` is ...
```
// Get a full commit from a short SHA
NodeGit.AnnotatedCommit.fromRevspec(repo, shortSHA)
                .then(annotatedCommit => {
                    return NodeGit.Commit.lookup(repo, annotatedCommit.id());
                });
```
Would love to hear of a better solution, but this works for me for now.

**Comment by rcjsuen** [comment]
@marshall007 This does what you want.

```JavaScript
var git = require("nodegit");
git.Repository.open(".").then(function(repo) {
  var oid = git.Oid.fromString("dae86e");
  return git.Commit.lookupPrefix(repo, oid, 6);
})
.then(function(commit) {
	console.log(commit.sha());
})
.catch(function(err) {
  console.log(err);
});
```
