### ISSUE TITLE
A way to get "gone" branches

### ISSUE THREAD

**Issue by gabipetrovay** [nodegit/nodegit#583]
For a branch for which the remote branch has been removed (`git push origin :test_branch`) we have a `gone` status locally:

```
$ git branch -avv
  login                                   630150b [origin/login] The splash container added to the home page
  master                                  b84120d [origin/master] Removed engine-list form package.json
* test_branch                             4ea2cab [origin/test_branch: gone] .service.json
```

How can we get this status of a branch through the `nodegit` API?

**Comment by johnhaley81** [comment]
You're going to have to load up the branches for a remote before you do the fetch with prune and then diff them to find this out. There's no built in method to do this currently.
