### ISSUE TITLE
Static link to glibc

### ISSUE THREAD

**Issue by tbranyen** [nodegit/nodegit#585]
To avoid issues where a user using a pre-compiled binary with an outdated glibc

**Comment by jugglinmike** [comment]
I think this may be what's happening here:

https://travis-ci.org/jugglinmike/jshint/jobs/70571313

Build runs without issue, but `require('nodegit')` throws an Error:

```
/home/travis/build/jugglinmike/jshint/node_modules/nodegit/lib/nodegit.js:13
    throw ex;
          ^
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /home/travis/build/jugglinmike/jshint/node_modules/nodegit/build/Release/nodegit.node)
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/jugglinmike/jshint/node_modules/nodegit/lib/nodegit.js:8:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by dorian-marchal** [comment]
Same error here, on Ubuntu 12.04.
Do you know how if I can distribute a package depending on nodegit that will work on Ubuntu 12.04 without requiring my users to update their glibc ?

**Comment by tbranyen** [comment]
@dorian-marchal you could probably adjust the `LD_PATH` and point to a precompiled glibc.

**Comment by dorian-marchal** [comment]
I'll try that, thanks

**Comment by kimmobrunfeldt** [comment]
I'm hitting the same issue here: https://travis-ci.org/kimmobrunfeldt/git-hours/jobs/72436073

**Comment by kimmobrunfeldt** [comment]
Does nodegit provide the precompiled GLIBC_2.17? I'm trying to get this fixed in Travis builds.

**Comment by maxkorp** [comment]
This may be of interest http://stackoverflow.com/questions/3214168/linking-statically-with-glibc-and-libstdc

**Comment by TheSavior** [comment]
This is a problem for me as well on Centos6

**Comment by dukex** [comment]
Someone can help me to solve it? I have the same problem in travis CI and I dont know how to I set the LD_PATH to fix this problem

**Comment by thisconnect** [comment]
The pre-compiled S3 binary did work for me on Node 5.x but not on the LTS 4.2.x. To support both I disabled S3, with BUILD_ONLY and speed up future builds by caching node_modules directory

Example .travis https://github.com/thisconnect/nodegit-kit/blob/b8349239823f32d2ed0c96ef5f41f37c99c352ea/.travis.yml
(you can remove the two `git config --global ...` configs)

**Comment by maxkorp** [comment]
With the latest versions, the glibc dependency has been lowered to not be any higher than is included in 12.04, the oldest ubuntu LTS, so this may not be an issue for most people going forward

**Comment by diegoaguilar** [comment]
How did you get to solve it?

**Comment by maxkorp** [comment]
We actually removed code dependent on c++11 and fixed our compiler requirements to work off clang referencing an older glibc

**Comment by diegoaguilar** [comment]
Well, I jave same issue, how can I get it working?

**Comment by maxkorp** [comment]
A new verson is going out right now (we just published) which should automatically push out new binaries without the issue. If for some reason you're still seeing it, updating your glibc works, although I don't know how youd do that in the container architecture

**Comment by tbranyen** [comment]
It's easy enough to upgrade your OS to get the right library to dynamically link against and the README documents this process, so closing this now.

**Comment by otbe** [comment]
Updating OS/glibc is not possible (allowed) when using enterprise linux.
Maybe you could link glibc static or depend on an older version?

**Comment by tbranyen** [comment]
We cannot depend on an older version since our core Node-interop dependency dictates what we're using today.

I investigated static linking, but was unable to get it working. If this is something that matters for enterprise Linux, do you think you'd be able to help us experiment with? We might be able to ship a static copy and link to it using `rpath` or `LD_LIBRARY_PATH` or w/e to try and resolve it.

**Comment by garlicnation** [comment]
@tbranyen I'd love to experiment w/ this as I'm in the same boat
