### ISSUE TITLE
TreeEntry has no dirtoparent when it is obtained via Tree.entries()

### ISSUE THREAD

**Issue by tomruggs** [nodegit/nodegit#591]
I'm iterating over Tree.entries() and working with each individual TreeEntry.  The problem is that if I attempt to call toString() or path() on the TreeEntries I get:

```
[90m    [36mTypeError: Arguments to path.join must be strings
        at path.js:360:15
        at Array.filter (native)
        at Object.exports.join (path.js:358:36)
        at TreeEntry.path (/opt/packages/teamcity/work/739e0919cda857a9/node_modules/nodegit/lib/tree_entry.js:82:15)
```

This is because the TreeEntries that come from the entries() list do not go through getEntry() and therefore do not ever have a dirtoparent property assigned to them.  

This was introduced a few weeks ago here: 

https://github.com/nodegit/nodegit/commit/c7f86de01542e75825f7e537c7725ab374ab6ffd#diff-a170a8f0bb4e54cd4900b5fc814eeccdR82

**Comment by johnhaley81** [comment]
This is fixed in #592
