### ISSUE TITLE
error building nodegit on docker: cc1plus: error: unrecognized command line option "-std=c++11"

### ISSUE THREAD

**Issue by TroyWorks** [nodegit/nodegit#604]
This is on docker running in boot2docker  ( Tiny Core Linux )

I've tried installing as far as I can tell latest GCC but the build keeps failing on buliding the native node module

[nodegit] Building native node module.
{ [Error: Command failed: /bin/sh -c /node_modules/nodegit/node_modules/.bin/pangyp rebuild
../vendor/libssh2/src/openssl.c: In function ‘_libssh2_pub_priv_keyfile’:
../vendor/libssh2/src/openssl.c:767: warning: value computed is not used
../vendor/libssh2/src/kex.c: In function ‘_libssh2_kex_exchange’:
../vendor/libssh2/src/kex.c:1220: warning: dereferencing pointer ‘methodlist’ does break strict-aliasing rules
../vendor/libssh2/src/kex.c:1326: note: initialized from here
../vendor/libssh2/src/transport.c: In function ‘_libssh2_transport_send’:
../vendor/libssh2/src/transport.c:716: warning: suggest braces around empty body in an ‘if’ statement
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [Release/obj.target/nodegit/src/nodegit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/node_modules/nodegit/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.18.11-tinycore64
gyp ERR! command "node" "/node_modules/nodegit/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /node_modules/nodegit
gyp ERR! node -v v0.12.4
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok

here's the more detailed log from install the dev-tools 

[root@43b1da2dae08 /]# wget http://people.centos.org/tru/devtools-2/devtools-2.repo -O /etc/yum.repos.d/devtools-2.repo
--2015-06-15 21:23:41--  http://people.centos.org/tru/devtools-2/devtools-2.repo
Resolving people.centos.org... 204.15.73.242
Connecting to people.centos.org|204.15.73.242|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 175 [text/plain]
Saving to: “/etc/yum.repos.d/devtools-2.repo”

100%[=========================================================================================================>] 175         --.-K/s   in 0s

2015-06-15 21:23:46 (5.34 MB/s) - “/etc/yum.repos.d/devtools-2.repo” saved [175/175]

[root@43b1da2dae08 /]# yum install devtoolset-2-gcc devtoolset-2-binutils devtoolset-2-gcc-c++
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.linux.duke.edu
 * epel: mirrors.syringanetworks.net
 * extras: mirror.linux.duke.edu
 * updates: mirror.linux.duke.edu
testing-devtools-2-centos-6                                                                                                 |  951 B     00:00
testing-devtools-2-centos-6/primary                                                                                         |  33 kB     00:00
testing-devtools-2-centos-6                                                                                                                119/119
Resolving Dependencies
--> Running transaction check
---> Package devtoolset-2-binutils.x86_64 0:2.23.52.0.1-10.el6 will be installed
--> Processing Dependency: devtoolset-2-runtime for package: devtoolset-2-binutils-2.23.52.0.1-10.el6.x86_64
---> Package devtoolset-2-gcc.x86_64 0:4.8.2-15.el6 will be installed
---> Package devtoolset-2-gcc-c++.x86_64 0:4.8.2-15.el6 will be installed
--> Processing Dependency: devtoolset-2-libstdc++-devel = 4.8.2-15.el6 for package: devtoolset-2-gcc-c++-4.8.2-15.el6.x86_64
--> Running transaction check
---> Package devtoolset-2-libstdc++-devel.x86_64 0:4.8.2-15.el6 will be installed
testing-devtools-2-centos-6/filelists                                                                                       | 222 kB     00:00
---> Package devtoolset-2-runtime.noarch 0:2.1-4.el6 will be installed
--> Processing Dependency: policycoreutils-python for package: devtoolset-2-runtime-2.1-4.el6.noarch
--> Running transaction check
---> Package policycoreutils-python.x86_64 0:2.0.83-19.47.el6_6.1 will be installed
--> Processing Dependency: libsemanage-python >= 2.0.43-4 for package: policycoreutils-python-2.0.83-19.47.el6_6.1.x86_64
--> Processing Dependency: audit-libs-python >= 1.4.2-1 for package: policycoreutils-python-2.0.83-19.47.el6_6.1.x86_64
--> Processing Dependency: setools-libs-python for package: policycoreutils-python-2.0.83-19.47.el6_6.1.x86_64
--> Processing Dependency: libselinux-python for package: policycoreutils-python-2.0.83-19.47.el6_6.1.x86_64
--> Processing Dependency: libcgroup for package: policycoreutils-python-2.0.83-19.47.el6_6.1.x86_64
--> Running transaction check
---> Package audit-libs-python.x86_64 0:2.3.7-5.el6 will be installed
---> Package libcgroup.x86_64 0:0.40.rc1-15.el6_6 will be installed
---> Package libselinux-python.x86_64 0:2.0.94-5.8.el6 will be installed
---> Package libsemanage-python.x86_64 0:2.0.43-4.2.el6 will be installed
---> Package setools-libs-python.x86_64 0:3.3.7-4.el6 will be installed
--> Processing Dependency: setools-libs = 3.3.7-4.el6 for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libsefs.so.4(VERS_4.0)(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libseaudit.so.4(VERS_4.2)(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libseaudit.so.4(VERS_4.1)(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libqpol.so.1(VERS_1.4)(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libqpol.so.1(VERS_1.3)(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libqpol.so.1(VERS_1.2)(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libpoldiff.so.1(VERS_1.3)(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libpoldiff.so.1(VERS_1.2)(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libapol.so.4(VERS_4.1)(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libapol.so.4(VERS_4.0)(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libsefs.so.4()(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libseaudit.so.4()(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libqpol.so.1()(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libpoldiff.so.1()(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Processing Dependency: libapol.so.4()(64bit) for package: setools-libs-python-3.3.7-4.el6.x86_64
--> Running transaction check
---> Package setools-libs.x86_64 0:3.3.7-4.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================================
 Package                                   Arch                Version                              Repository                                Size
===================================================================================================================================================
Installing:
 devtoolset-2-binutils                     x86_64              2.23.52.0.1-10.el6                   testing-devtools-2-centos-6              5.0 M
 devtoolset-2-gcc                          x86_64              4.8.2-15.el6                         testing-devtools-2-centos-6               22 M
 devtoolset-2-gcc-c++                      x86_64              4.8.2-15.el6                         testing-devtools-2-centos-6              7.2 M
Installing for dependencies:
 audit-libs-python                         x86_64              2.3.7-5.el6                          base                                      62 k
 devtoolset-2-libstdc++-devel              x86_64              4.8.2-15.el6                         testing-devtools-2-centos-6              1.9 M
 devtoolset-2-runtime                      noarch              2.1-4.el6                            testing-devtools-2-centos-6              1.0 M
 libcgroup                                 x86_64              0.40.rc1-15.el6_6                    updates                                  129 k
 libselinux-python                         x86_64              2.0.94-5.8.el6                       base                                     203 k
 libsemanage-python                        x86_64              2.0.43-4.2.el6                       base                                      81 k
 policycoreutils-python                    x86_64              2.0.83-19.47.el6_6.1                 updates                                  346 k
 setools-libs                              x86_64              3.3.7-4.el6                          base                                     400 k
 setools-libs-python                       x86_64              3.3.7-4.el6                          base                                     222 k

Transaction Summary
===================================================================================================================================================
Install      12 Package(s)

Total download size: 38 M
Installed size: 94 M
Is this ok [y/N]: y
Downloading Packages:
(1/12): audit-libs-python-2.3.7-5.el6.x86_64.rpm                                                                            |  62 kB     00:00
(2/12): devtoolset-2-binutils-2.23.52.0.1-10.el6.x86_64.rpm                                                                 | 5.0 MB     00:02
(3/12): devtoolset-2-gcc-4.8.2-15.el6.x86_64.rpm                                                                            |  22 MB     00:09
(4/12): devtoolset-2-gcc-c++-4.8.2-15.el6.x86_64.rpm                                                                        | 7.2 MB     00:02
(5/12): devtoolset-2-libstdc++-devel-4.8.2-15.el6.x86_64.rpm                                                                | 1.9 MB     00:00
(6/12): devtoolset-2-runtime-2.1-4.el6.noarch.rpm                                                                           | 1.0 MB     00:00
(7/12): libcgroup-0.40.rc1-15.el6_6.x86_64.rpm                                                                              | 129 kB     00:00
(8/12): libselinux-python-2.0.94-5.8.el6.x86_64.rpm                                                                         | 203 kB     00:00
(9/12): libsemanage-python-2.0.43-4.2.el6.x86_64.rpm                                                                        |  81 kB     00:00
(10/12): policycoreutils-python-2.0.83-19.47.el6_6.1.x86_64.rpm                                                             | 346 kB     00:00
(11/12): setools-libs-3.3.7-4.el6.x86_64.rpm                                                                                | 400 kB     00:00
(12/12): setools-libs-python-3.3.7-4.el6.x86_64.rpm                                                                         | 222 kB     00:00
---------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                              1.4 MB/s |  38 MB     00:26
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : libcgroup-0.40.rc1-15.el6_6.x86_64                                                                                             1/12
  Installing : setools-libs-3.3.7-4.el6.x86_64                                                                                                2/12
  Installing : setools-libs-python-3.3.7-4.el6.x86_64                                                                                         3/12
  Installing : libselinux-python-2.0.94-5.8.el6.x86_64                                                                                        4/12
  Installing : devtoolset-2-libstdc++-devel-4.8.2-15.el6.x86_64                                                                               5/12
  Installing : audit-libs-python-2.3.7-5.el6.x86_64                                                                                           6/12
  Installing : libsemanage-python-2.0.43-4.2.el6.x86_64                                                                                       7/12
  Installing : policycoreutils-python-2.0.83-19.47.el6_6.1.x86_64                                                                             8/12
  Installing : devtoolset-2-runtime-2.1-4.el6.noarch                                                                                          9/12
/usr/sbin/semanage: SELinux policy is not managed or store cannot be accessed.
  Installing : devtoolset-2-gcc-4.8.2-15.el6.x86_64                                                                                          10/12
  Installing : devtoolset-2-gcc-c++-4.8.2-15.el6.x86_64                                                                                      11/12
  Installing : devtoolset-2-binutils-2.23.52.0.1-10.el6.x86_64                                                                               12/12
  Verifying  : libsemanage-python-2.0.43-4.2.el6.x86_64                                                                                       1/12
  Verifying  : devtoolset-2-binutils-2.23.52.0.1-10.el6.x86_64                                                                                2/12
  Verifying  : audit-libs-python-2.3.7-5.el6.x86_64                                                                                           3/12
  Verifying  : devtoolset-2-libstdc++-devel-4.8.2-15.el6.x86_64                                                                               4/12
  Verifying  : setools-libs-python-3.3.7-4.el6.x86_64                                                                                         5/12
  Verifying  : policycoreutils-python-2.0.83-19.47.el6_6.1.x86_64                                                                             6/12
  Verifying  : libselinux-python-2.0.94-5.8.el6.x86_64                                                                                        7/12
  Verifying  : devtoolset-2-gcc-c++-4.8.2-15.el6.x86_64                                                                                       8/12
  Verifying  : devtoolset-2-gcc-4.8.2-15.el6.x86_64                                                                                           9/12
  Verifying  : devtoolset-2-runtime-2.1-4.el6.noarch                                                                                         10/12
  Verifying  : setools-libs-3.3.7-4.el6.x86_64                                                                                               11/12
  Verifying  : libcgroup-0.40.rc1-15.el6_6.x86_64                                                                                            12/12

Installed:
  devtoolset-2-binutils.x86_64 0:2.23.52.0.1-10.el6     devtoolset-2-gcc.x86_64 0:4.8.2-15.el6     devtoolset-2-gcc-c++.x86_64 0:4.8.2-15.el6

Dependency Installed:
  audit-libs-python.x86_64 0:2.3.7-5.el6                                    devtoolset-2-libstdc++-devel.x86_64 0:4.8.2-15.el6
  devtoolset-2-runtime.noarch 0:2.1-4.el6                                   libcgroup.x86_64 0:0.40.rc1-15.el6_6
  libselinux-python.x86_64 0:2.0.94-5.8.el6                                 libsemanage-python.x86_64 0:2.0.43-4.2.el6
  policycoreutils-python.x86_64 0:2.0.83-19.47.el6_6.1                      setools-libs.x86_64 0:3.3.7-4.el6
  setools-libs-python.x86_64 0:3.3.7-4.el6

Complete!
[root@43b1da2dae08 /]# npm install nodegit --save
|
> nodegit@0.4.1 install /node_modules/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary, building manually.
[nodegit] Making sure dependencies are available and native code is generated
[nodegit] Something is missing, retrieving dependencies and regenerating code
nan@1.8.4 node_modules/nan

combyne@0.8.0 node_modules/combyne

mocha@2.2.5 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.1
├── growl@1.8.1
├── commander@2.3.0
├── diff@1.4.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
└── jade@0.26.3 (commander@0.6.1, mkdirp@0.3.0)

request@2.57.0 node_modules/request
├── caseless@0.10.0
├── aws-sign2@0.5.0
├── forever-agent@0.6.1
├── stringstream@0.0.4
├── tunnel-agent@0.4.0
├── oauth-sign@0.8.0
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── node-uuid@1.4.3
├── qs@3.1.0
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── mime-types@2.0.14 (mime-db@1.12.0)
├── form-data@0.2.0 (async@0.9.2, combined-stream@0.0.7)
├── http-signature@0.11.0 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@0.9.4 (readable-stream@1.0.33)
├── tough-cookie@2.0.0
├── hawk@2.3.1 (cryptiles@2.0.4, sntp@1.0.9, boom@2.8.0, hoek@2.14.0)
└── har-validator@1.7.1 (commander@2.8.1, chalk@1.0.0, is-my-json-valid@2.12.0, bluebird@2.9.30)

lcov-result-merger@1.0.2 node_modules/lcov-result-merger
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, mkdirp@0.5.1, glob-stream@3.1.18, glob-watcher@0.0.6)

js-beautify@1.5.6 node_modules/js-beautify
├── config-chain@1.1.9 (ini@1.3.4, proto-list@1.2.4)
├── nopt@3.0.2 (abbrev@1.0.7)
└── mkdirp@0.5.1 (minimist@0.0.8)

coveralls@2.11.2 node_modules/coveralls
├── lcov-parse@0.0.6
├── log-driver@1.2.4
├── request@2.40.0 (forever-agent@0.5.2, aws-sign2@0.5.0, oauth-sign@0.3.0, stringstream@0.0.4, tunnel-agent@0.4.0, json-stringify-safe@5.0.1, qs@1.0.2, node-uuid@1.4.3, mime-types@1.0.2, form-data@0.1.4, http-signature@0.10.1, tough-cookie@2.0.0, hawk@1.1.1)
└── js-yaml@3.0.1 (argparse@0.1.16, esprima@1.0.4)

tar@2.1.1 node_modules/tar
├── inherits@2.0.1
├── block-stream@0.0.8
└── fstream@1.0.6 (graceful-fs@3.0.8, mkdirp@0.5.1, rimraf@2.4.0)

lodash@3.9.3 node_modules/lodash

nw-gyp@0.12.4 node_modules/nw-gyp
├── graceful-fs@2.0.3
├── osenv@0.1.2 (os-tmpdir@1.0.1)
├── nopt@2.2.1 (abbrev@1.0.7)
├── semver@2.2.1
├── npmlog@0.1.1 (ansi@0.3.0)
├── minimatch@0.4.0 (sigmund@1.0.1, lru-cache@2.6.4)
├── which@1.1.1 (is-absolute@0.1.7)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── fstream@0.1.31 (inherits@2.0.1, graceful-fs@3.0.8)
├── tar@0.1.20 (inherits@2.0.1, block-stream@0.0.8)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
└── rimraf@2.4.0 (glob@4.5.3)

istanbul@0.3.15 node_modules/istanbul
├── supports-color@1.3.1
├── which@1.0.9
├── abbrev@1.0.7
├── nopt@3.0.2
├── wordwrap@0.0.3
├── once@1.3.2 (wrappy@1.0.1)
├── async@0.9.2
├── esprima@2.1.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── resolve@1.1.6
├── fileset@0.1.6 (minimatch@0.4.0, glob@5.0.10)
├── js-yaml@3.3.1 (esprima@2.2.0, argparse@1.0.2)
├── escodegen@1.6.1 (esutils@1.1.6, estraverse@1.9.3, optionator@0.5.0, source-map@0.1.43, esprima@1.2.5)
└── handlebars@3.0.0 (optimist@0.6.1, source-map@0.1.43, uglify-js@2.3.6)

pangyp@2.2.1 node_modules/pangyp
├── which@1.0.9
├── rimraf@2.2.8
├── graceful-fs@3.0.8
├── osenv@0.1.2 (os-tmpdir@1.0.1)
├── nopt@3.0.2 (abbrev@1.0.7)
├── fstream@1.0.6 (inherits@2.0.1)
├── semver@4.3.6
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@4.3.5 (inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── tar@1.0.3 (inherits@2.0.1, block-stream@0.0.8)
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── npmlog@1.0.0 (ansi@0.3.0, gauge@1.0.2, are-we-there-yet@1.0.4)
└── request@2.51.0 (caseless@0.8.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.5.0, tunnel-agent@0.4.0, json-stringify-safe@5.0.1, qs@2.3.3, node-uuid@1.4.3, mime-types@1.0.2, combined-stream@0.0.7, http-signature@0.10.1, bl@0.9.4, form-data@0.2.0, tough-cookie@2.0.0, hawk@1.1.1)

jshint@2.8.0 node_modules/jshint
├── strip-json-comments@1.0.2
├── exit@0.1.2
├── shelljs@0.3.0
├── console-browserify@1.1.0 (date-now@0.1.4)
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
├── lodash@3.7.0
└── cli@0.6.6 (glob@3.2.11)

[nodegit] Detecting vendor/libgit2/fb6df50b7f250a4fd8b2fab257f119a5185e9bf5.
[nodegit] Detecting vendor/libssh2/1.4.3.
[nodegit] Detecting vendor/http_parser/2.5.0.
[nodegit] Detecting generated code.
[nodegit] vendor/libgit2/fb6df50b7f250a4fd8b2fab257f119a5185e9bf5 already exists.
[nodegit] vendor/libssh2/1.4.3 already exists.
[nodegit] Generated code is intact.
[nodegit] Removing outdated vendor/http_parser/.
[nodegit] Retrieving vendor/http_parser/.
[nodegit] Successfully updated vendor/http_parser/2.5.0.
[nodegit] Everything is ready to go, attempting compilation
[nodegit] Building native node module.
{ [Error: Command failed: /bin/sh -c /node_modules/nodegit/node_modules/.bin/pangyp rebuild
../vendor/libssh2/src/openssl.c: In function ‘_libssh2_pub_priv_keyfile’:
../vendor/libssh2/src/openssl.c:767: warning: value computed is not used
../vendor/libssh2/src/kex.c: In function ‘_libssh2_kex_exchange’:
../vendor/libssh2/src/kex.c:1220: warning: dereferencing pointer ‘methodlist’ does break strict-aliasing rules
../vendor/libssh2/src/kex.c:1326: note: initialized from here
../vendor/libssh2/src/transport.c: In function ‘_libssh2_transport_send’:
../vendor/libssh2/src/transport.c:716: warning: suggest braces around empty body in an ‘if’ statement
cc1plus: error: unrecognized command line option "-std=c++11"
make: *** [Release/obj.target/nodegit/src/nodegit.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/node_modules/nodegit/node_modules/pangyp/lib/build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.18.11-tinycore64
gyp ERR! command "node" "/node_modules/nodegit/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /node_modules/nodegit
gyp ERR! node -v v0.12.4
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /node_modules/nodegit/node_modules/.bin/pangyp rebuild' }
undefined
nodegit@0.4.1 node_modules/nodegit
├── promisify-node@0.1.5 (nodegit-promise@1.0.2)
├── which-native-nodish@1.1.1 (find-parent-dir@0.3.0, nodegit-promise@1.0.2)
├── nodegit-promise@2.0.1 (asap@2.0.3)
├── npm@2.11.2
└── fs-extra@0.18.4 (jsonfile@2.0.1, graceful-fs@3.0.8, rimraf@2.4.0)

**Comment by johnhaley81** [comment]
We published binaries for 0.4.1 after you had this error. Can you retest and confirm that it still breaks for you?

Thanks!

**Comment by melkior** [comment]
Hi,

here is experience on centos 6 with nodegit. When installed with npm install nodegit (ie. precompiled) i got error about wrong glibc version. After some juggling and trying to build nodegit from source i got -std=c++11 compiler error, so i installed devtoolset2 (important -> devtoolset-2-gcc-c++) and set CC/CXX to newer compilers:

export CC=/opt/rh/devtoolset-2/root/usr/bin/gcc
export CXX=/opt/rh/devtoolset-2/root/usr/bin/g++
BUILD_ONLY=true npm install nodegit

This worked.

**Comment by tbranyen** [comment]
Closing issue since resolved.
