### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by brettz9** [nodegit/nodegit#618]
How impossible would it be for you all to make a version that compiled to client-side JavaScript (e.g., using asm.js/Emscripten for the libgit2)? Would be really nifty to be able to reuse the same code/APIs for commits, diffs, etc., in offlineable local storage/IndexedDB...

**Comment by tbranyen** [comment]
It's a lot of work unfortunately.  I've started on an emscripten build several times, but never got very far.  We are very much IO-bound and it's tricky to make that work across the board.  You can see the initial work here:

https://github.com/nodegit/nodegit/pull/478

**Comment by tbranyen** [comment]
BTW I'm closing this since it's a conversation better left to our Gitter channel.  Please ping us in there if you wanna help out!
