### ISSUE TITLE
Support 'depth' in cloneOptions

### ISSUE THREAD

**Issue by Trendy** [nodegit/nodegit#624]
I'm using nodegit to automate the setup process of a large project with many dependencies. I'd like to be able to reduce the time it takes to clone some of the repositories by limiting the clone to the last 200 revisions, but nodegit does not support the [depth option](https://www.kernel.org/pub/software/scm/git/docs/git-clone.html) as far as I can tell. 

**Example git command:**

    git clone --depth 200 path/to/repo.git

**Comment by tbranyen** [comment]
Unfortunately we are limited by the design and API of libgit2, which currently does not support shallow clones.  You can find more information here: https://github.com/libgit2/libgit2/issues/3058

**Comment by WORMSS** [comment]
Shouldn't this still be open but with a RequiresUpstream label or something?

**Comment by maxkorp** [comment]
Odds are once it's available upstream, it will just automagically land in nodegit, unless there is something special about it that requires explicit attention on our end.

**Comment by maxkorp** [comment]
@Hatko I only did a cursory search of the libgit2 api docs [here](https://libgit2.org/libgit2/#HEAD) by doing a text search for `depth`, as well as a quick glance at the git_clone_options struct, but yeah, I don't see any sign of depth support. It would be worth asking in the libgit2 slack.

**Comment by jmcgill** [comment]
This is now available in libgit2 https://github.com/libgit2/libgit2/issues/3058
