### ISSUE TITLE
Bug when cloning two repos

### ISSUE THREAD

**Issue by Spidy88** [nodegit/nodegit#630]
When I try to clone two repos at the same time, I'm getting inconsistent behavior. Sometimes it works, sometimes it breaks with some very odd error messages. The first repo exists on Github. The second repo does not. When I run the program multiple times (and the local folders are removed each time) I've gotten the following behaviors:

1. Program freezes, creating both directories with .git file/folders and nothing else
2. Program fails with `Segmentation fault: 11`
3. Program clones first directory successfully, second fails but with wrong error message (`authentication required but no callback set`)
4. Program fails with ```node(33647,0x103a0a000) malloc: *** error for object 0x102802540: double free
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6```

These errors happened in exactly this order as well when I continued to run the program. Code attached below for help recreating.

```
var path = require('path');
var git = require('nodegit');
var tmp = require('tmp');
var Promise = require('bluebird');

var CLONE_OPTIONS = {
    remoteCallbacks: {
        certificateCheck: function() { return 1; },
        credentials: function (url, username) {
            return git.Cred.sshKeyFromAgent(username);
        }
    }
};

var upstreamPromise = cloneRepository('some-private-org', 'awesome-repo', path.join(__dirname, '/private-repo'))
    .then(repoCloneSuccess, repoCloneFailure);

var downstreamPromise = cloneRepository('Spidy88', 'forked-private-repo', path.join(__dirname, '/forked-private-repo'))
    .then(repoCloneSuccess, repoCloneFailure);

Promise.all([upstreamPromise, downstreamPromise])
    .spread(
        function(upstream, downstream) {
            console.log('Upstream: ', upstream && upstream.path());
            console.log('Downstream: ', downstream && downstream.path());
        },
        function(upstreamReason, downstreamReason) {
            console.log('Upstream failed: ', upstreamReason);
            console.log('Downstream failed: ', downstreamReason);
        }
    );

function cloneRepository(ownerName, repoName, outputPath) {
    var repoUrl = 'git@github.com:' + ownerName + '/' + repoName + '.git';
    return git.Clone(repoUrl, outputPath, CLONE_OPTIONS);
}

function repoCloneSuccess(repository) {
    console.log('Clone success');
    console.log("Is the repository bare? %s", Boolean(repository.isBare()));
    return repository;
}

function repoCloneFailure(reason) {
    console.log('Clone failed: ', reason);
    return reason;
}
```

**Comment by Spidy88** [comment]
Additional information:

The clone method uses a [shallowClone](https://github.com/nodegit/nodegit/blob/master/lib/utils/shallow_clone.js) on the options passed in. However, it is not truly a shallow clone and therefore when the clone method [removes the remoteCallbacks](https://github.com/nodegit/nodegit/blob/master/lib/clone.js#L23) it is modifying the original object. A simple fix is to not pass in the same clone options, but a long term fix would be to fix the shallow clone.

While this attributed to the `authentication required but no callback set` error, the segmentation fault and malloc_error_break errors are still occurring.

**Comment by Spidy88** [comment]
The verified solution so far is to run the first clone, and when it completes, run the second clone. Not optimal for complex applications but hopefully this helps narrow down the bug. Threading issue maybe?

**Comment by Spidy88** [comment]
Additional tests showed the when the clone directories are siblings `/tmp/a` and `/tmp/b` the bug rears its ugly head. When making them not siblings `/tmp/a/sub` and `/tmp/b/sub` the bug disappears (though recently it seems that might have been a fluke because I'm still getting segfaults and malloc errors).

If the `/tmp` folder doesn't exist when trying to clone into subdirectories like this, the command also fails stating `/tmp` already exists (I'm thinking both clones check for its existence, then try to create, and the second create fails).

**Comment by tbranyen** [comment]
I believe with our new thread locking code this should be a non-issue. Closing for now, please comment to re-open if the issue crops up again.

**Comment by marquesarthur** [comment]
I was able to reproduce the bug with the following code:

`
const fs = require('fs');
const Promise = require('promise');
const Git = require("nodegit");
const walkSync = require('walk-sync');

const config = require('../git.config.json');

const projects_file = 'git_projects.json';
const tmp_dir = 'git_analysis/tmp';
var projects = JSON.parse(fs.readFileSync(projects_file));

// FIXME remove this: it is here just to speed up tests.
projects = projects.slice(0, 2);


function makeDir(dir_path) {
    if (!fs.existsSync(dir_path)){
        fs.mkdirSync(dir_path);
    }
}

function getGitRepositoryName(url) {
    var idx = url.lastIndexOf('/');
    if (idx == -1){
        return undefined;
    }
    return url.substring(idx + 1, url.length);
}

function getFilePath(file) {
    return './' + tmp_dir + '/' + file;
}

function getFrontendFiles(paths) {
    var files = [];
    var files_folders = paths.split(",");
    files_folders.forEach(function (file) {

        if (file.endsWith('/')) {
            console.log(getFilePath(file.substr(0, file.length)));
            var aux = walkSync(getFilePath(file.substr(0, file.length)));
            files = files.concat(aux);
        } else {
            files.push(getFilePath(file));
        }
    });

    // filter acceptable file extensions
    return files.filter(function (file) {
        return file.endsWith('.css') || file.endsWith('.html') || file.endsWith('.js');
    });
}

function cloneRepos() {
    return new Promise( function(resolve, reject) {
        console.log('Cloning repos...');
        var promises = [];
        var idx = 0;
        projects.forEach(function (git_project) {

            if (typeof git_project.active !== 'undefined' && git_project.active) {
                var repo = getGitRepositoryName(git_project.git);
                var path = tmp_dir + '/' + repo;
                console.log('[' + idx + '] Cloning :: ' + repo);
                var p = Git.Clone(git_project.git, path);
                promises.push(p);
                idx++;
            }
        });

        Promise.all(promises).then(function() {
            console.log('\nDone');
            resolve('success');
        }).catch(function(e) {
            reject(e);
        });
    });
}

function checkXcompatibility() {
    console.log('\nMeasuring cross-browser compatibility...');
    var promises = [];
    var idx = 0;
    projects.forEach(function (git_project) {

        if (typeof git_project.active !== 'undefined' && git_project.active && git_project.hasFrontend) {
            var repo = getGitRepositoryName(git_project.git);
            var frontend = getFrontendFiles(git_project.srcPath);

            console.log('[' + idx + '] Measuting xcompatibility of :: ' + repo);

            frontend.forEach(function (file) {
                var path = tmp_dir + '/' + file;
                console.log('   ' + path);
            });

            idx++;
        }
    });

    console.log('\nDone');
}

function main() {
    console.log('Cloning git repos and measuring xbrowser-compatibility ...');
    makeDir(tmp_dir);
    cloneRepos().then(function () {
        checkXcompatibility();
    });
}

main();
`

My json file with a list of github projects is something like:
https://github.com/digorithm/xcompatibility-checker/blob/master/git_projects.json
