### ISSUE TITLE
openIndex(), createCommit() missing from API documentation

### ISSUE THREAD

**Issue by vsivsi** [nodegit/nodegit#634]
I expected to find documentation for `repository#openIndex()` and `repository#createCommit()` in the [API documentation](http://www.nodegit.org/api/) after encountering them in the [example code](https://github.com/nodegit/nodegit/blob/master/examples/add-and-commit.js#L38-L72).

These appear to be completely absent from the documentation, which is pretty surprising since they seem like key functionality that appears to have been added way back in or before v0.2.

**Comment by nopnop** [comment]
Yes, this is confusing. Related: #197 and #198 
Maybe, the examples need to be updated ?

**Comment by tbranyen** [comment]
@vsivsi we auto-generate the documentation on the site, so it's entirely possible they are either missing JSDoc syntax, or we have a bug in the generator.  Since they are not manually added, its not like we just forgot to add them.

**Comment by tbranyen** [comment]
https://github.com/nodegit/nodegit/blob/master/lib/repository.js#L22-L25

^^ As we can see here `openIndex` is indeed missing JSDoc syntax, which explains why it is omitted from the documentation.

**Comment by rcjsuen** [comment]
`createCommit` is now on the [website](http://www.nodegit.org/api/repository/#createCommit) and the `openIndex` function has since been removed from `Repository`. Can we close this?

**Comment by tbranyen** [comment]
Sounds good to me!
