### ISSUE TITLE
Error: Module version mismatch. Expected 43, got 14.

### ISSUE THREAD

**Issue by pebanfield** [nodegit/nodegit#637]
I am trying to run node-git inside of nw.js node-webkit and receiving this error. According to the docs I need to rebuild the node-git native module using nw-gyp. I am little out of my element with the native stuff so any help while I'm flailing around is appreciated. :)

I am using :

- Mac OS Yeosemite 64 bit with xcode command line tools installed
- node js v0.12.4
- nw.js v0.12.2
- https://github.com/mllrsohn/node-webkit-builder to build nwapp

I have built node-git from source following this doc http://www.nodegit.org/guides/install/from-source/ (Any reason not to just run npm install in myproj/node_modules/nodegit for testing?)

I have added engines with v0.12.2 to my project package json and run npm install again. 

The project I am trying to get working is here - https://github.com/pebanfield/change-viewer

But I also wanted to separate the actual parsing service into it's own node module dependency consumed by change-viewer here - https://github.com/pebanfield/change-view-service

The root of the project utilizes https://github.com/mllrsohn/node-webkit-builder and builds an nwapp directory. The nwapp node_modules directory is where my change-view-service lives so the node-git dependency is actually two projects deep if that makes sense?

I have tried using the BUILD_ONLY=true npm install argument as suggested here - https://github.com/nodegit/nodegit/issues/516

I'm stuck. Any help is appreciated. Thanks. 

Peter

**Comment by pebanfield** [comment]
The issue was that I did not specify the engines configuration at the right level of my application since I happen to have several different modules. 

If anyone else is having similar issues I have documented my setup and have created a yeoman generator here -

https://github.com/pebanfield/generator-nwjs-nodegit

**Comment by maxkorp** [comment]
@pebanfield that's awesome!

**Comment by elleryfamilia** [comment]
@pebanfield I'm trying to use this within express and I'm facing the same issue... Any ideas on how to deal with it then?

**Comment by pebanfield** [comment]
You can try the generator project above. This project contains the fix that worked for me. Express is just an npm module so it should be completely decoupled from the nodegit library. That is if I am understanding what you mean by using it "within" express. So in other words, you should be able to add node express to the generator project. Hope that helps.
