### ISSUE TITLE
Issue with NTLM auth

### ISSUE THREAD

**Issue by bigbn** [nodegit/nodegit#642]
We are using TFS in our company with git support. I can't clone any repo managed by TFS via this library.
    
    sails.log.info('Starting update');
    git.Clone('https://irtfs.****.ru/tfs/**', DEPLOY_DIR, {
        remoteCallbacks: {
          certificateCheck: function() {
            sails.log.info('Ignoring certificate check');
            return 0;
          },
          credentials: function(url, userName) {
            sails.log.info('Passing credentials');            
            return git.Cred.userpassPlaintextNew('MyUserName_PI', 'MyPassWord');
          }
        }
      }).then(function(repository) {
        sails.log.info('Repository successfully cloned');

process never enters into credentials callback and i always get an error:

    info: Starting update
    info: Ignoring certificate check
    error: Error: Unexpected HTTP status code: 401 [Error: Unexpected HTTP status code: 401]

This OS alredy icluded to domain and specified user too. How can i make it work?

**Comment by bigbn** [comment]
The same think with the basic auth. 401 error with no credentials callback called.

**Comment by tbranyen** [comment]
Sorry @bigbn I'm not sure how to help without a test case.  Have you been able to dig any further?

**Comment by johnhaley81** [comment]
This could be related: http://stackoverflow.com/questions/26145023/libgit2sharp-fetching-fails-with-too-many-redirects-or-authentication-replays

**Comment by bigbn** [comment]
There is no any positive progress. Switched to another library.

**Comment by tbranyen** [comment]
Thanks for the update @bigbn

**Comment by maxkorp** [comment]
Should we reopen this until we can figure it out? Even without @bigbn needing it, I feel like that's something worth exploring.

**Comment by emr550m** [comment]
Well, we have the same issue using this library with TFS/Git repo. credentials call back didnot triggerred while cloning. and 401 error raises. It is sad that  we have this problem till 2014. I was happy that i can  fill my git usage on node with this library. Hope it will be fixed some day.

**Comment by bryanhuntesl** [comment]
Same issue here (GitKrakken). NTLM is such a nasty authentication protocol and username/password is a suboptimal solution for git authentication. You may encourage your administrators to use the (much) more secure SSH/PKI approach or even just dump TFS. Hopefully, this is the only client I'll work with who is using TFS - it really is terrible.

**Comment by implausible** [comment]
Are you guys authenticating vs a proxy and need to build out the proxy options / callbacks on your calls?
