### ISSUE TITLE
Repository.getCommit(string) doesn't work at all.

### ISSUE THREAD

**Issue by peymanmortazavi** [nodegit/nodegit#643]
I even tested the example, it returns { repo: {} } and nothing in it.
I checked my git repo via shell and I know that my commit exists.

**Comment by tbranyen** [comment]
That is the commit object, check `__proto__` on that object and you'll see all the methods.  Please ask your questions in our Gitter support channel in the future instead of opening issues like this.  Thanks!

**Comment by peymanmortazavi** [comment]
understood. Thanks!
