### ISSUE TITLE
Remote.delete() return value differs from docs

### ISSUE THREAD

**Issue by mamacdon** [nodegit/nodegit#654]
Remote.delete() is [documented](http://www.nodegit.org/api/remote/#delete) as resolving to `0` on success, but in reality it resolves to `undefined`. Not sure if this is a doc error or a bug in the code.

Example: https://github.com/mamacdon/nodegit/commit/c2d73bcc69d289562e004f2f643e5326b35d12c0 (this test will fail)

**Comment by rcjsuen** [comment]
The documentation is the issue. If the function succeeds, the promise will be resolved and `then` is called but if the call in libgit2 returns a non-zero return code then the promise will be rejected and `catch` is called. Note that there are tons of other functions in NodeGit with this same documentation problem.

**Comment by rcjsuen** [comment]
Tracked by #1425.
