### ISSUE TITLE
are git hooks not triggered?

### ISSUE THREAD

**Issue by freder** [nodegit/nodegit#657]
hi,

I was wondering if – when using nodegit – any present git hooks are triggered?
it doesn't seem so. *post-commit* hooks for instane, only run when I commit manually from the command line.

**Comment by johnhaley81** [comment]
Hey @freder so libgit2 (the library which we're wrapping) does not (and apparently will not) support hooks (see [here](https://github.com/libgit2/libgit2/issues/964#issuecomment-109998760)). It does look like they want to put in a layer that allows applications to easily call them but that's not currently in.

**Comment by noderat** [comment]
@johnhaley81 It could be something nodegit could support itself, it makes sense it's not part of libgit2. See https://github.com/libgit2/libgit2/issues/964#issuecomment-170353017
