### ISSUE TITLE
Repository.setHeadDetached fails with an internal assertion

### ISSUE THREAD

**Issue by rhuss** [nodegit/nodegit#701]
When using this following promise 

``` javascript
function checkOutCommit(repo,commit) {
  console.log('Changing HEAD to ', commit.id());
  repo.setHeadDetached(commit.id(), repo.defaultSignature, "Checkout: HEAD " + commit.id());
  console.log('Checking out HEAD');
  return Git.Checkout.head(repo, {
    checkoutStrategy: Git.Checkout.STRATEGY.FORCE
  });
}
```

I get the following output 

```
Changing HEAD to  [Oid d1ef6ef21f21748b611e86514c4dfff07e0d8ff7]
Assertion failed: (handle->InternalFieldCount() > 0), function Unwrap, file /Users/johnh/.node-gyp/0.12.4/src/node_object_wrap.h, line 50.
```

While we are on it, was is the canonical way to check out on a particular tag in a detached state ? I tried the suggestions found on gitter and [here](https://gist.github.com/tbranyen/2481cfdb27424d60e528#file-auto-deploy-js-L69-L80)

**Comment by rhuss** [comment]
Using `Git.Signature.default(repo)` as signature works, though.

**Comment by maxkorp** [comment]
`repo.defaultSignature` is an instance method, not a property. try
```js
  repo.setHeadDetached(commit.id(), repo.defaultSignature(), "Checkout: HEAD " + commit.id());
```

**Comment by rcjsuen** [comment]
@maxkorp's comment is very likely the reason behind the crash. `setHeadDetached` no longer takes a `Signature` so I think we can close this.

There is #1127 open for introducing tighter type checking across all of NodeGit.

**Comment by rcjsuen** [comment]
Closing per above.
