### ISSUE TITLE
npm WARN invalid config access=undefined (Appveyor, io.js 2)

### ISSUE THREAD

**Issue by saper** [nodegit/nodegit#711]
Something is wrapping a whole process environment in a way that causes lots of `undefined` values added in the form of `npm_config_xxx` variables:

https://gist.github.com/821f24073a71811223f8

With additional logging one can see that thoses values get populated with the "undefined" string value.

We are recursively calling `npm` at some point (lifecycle script is called from `npm install` only to call `npm install` itself), maybe it's `npm` configuration bug (combined with difficulties to unset environment variable on some platforms). Maybe it's a promisify bug (more likely to me).

**Comment by saper** [comment]
Tried [filtering the variables out](https://github.com/saper/nodegit/blob/experimental/lifecycleScripts/install.js#L73-L78), with [no success](https://ci.appveyor.com/project/saper/nodegit/build/14).

**Comment by johnhaley81** [comment]
This sounds like what @maxkorp is trying to fix on https://github.com/nodegit/nodegit/tree/simplify-build

**Comment by saper** [comment]
Please check out also my little improvements https://github.com/saper/nodegit/tree/mynode

**Comment by saper** [comment]
I am no longer seeing this after applying #715.

**Comment by saper** [comment]
Closed via #715
