### ISSUE TITLE
npm test multilates user's .gitconfig

### ISSUE THREAD

**Issue by saper** [nodegit/nodegit#712]
I just realized that I am push my commits as `undefined` to GitHub aftery trying `nodegit` yesterday.

My `.gitconfig` got mutilated by `npm test` - via `git config --global --unset ...`.

This is not acceptable. One should set `HOME` and/or `userprofile` to some fake user home directory before doing this!

**Comment by tbranyen** [comment]
Wow that's incredibly surprising as this project has existed for literally years with contributors and never had this issue brought up.  Can you pinpoint exactly where this happens?

**Comment by saper** [comment]
I just did `git grep 'git config'` and saw those horrible things in tests.

**Comment by tbranyen** [comment]
Urgh, yeah, that's a bit naive we shouldn't be modifying the global configuration for any reason.

**Comment by tbranyen** [comment]
I like your idea about a testing home directory setup, we should definitely commit something like that.

**Comment by johnhaley81** [comment]
Fixed in #727
