### ISSUE TITLE
Perform an ls-remote without cloning the repo

### ISSUE THREAD

**Issue by xizhao** [nodegit/nodegit#721]
How can I run a `git ls-remote` if I just have a URL?

Is there a sort of `NodeGit.Remote.list(url)` cmd?

**Comment by xizhao** [comment]
https://github.com/libgit2/libgit2/issues/2923

The main issue is we can't create a repo w/o cloning. We should be able to init a dummy one, set remote and then list.

**Comment by jzahka** [comment]
+1

**Comment by johnhaley81** [comment]
Please do not +1 issues. GitHub now let's you +1 a comment.

![image](https://cloud.githubusercontent.com/assets/867780/14047988/98bfa452-f268-11e5-810c-c94a04396669.png)

**Comment by webbrandon** [comment]
looks like its possible now https://github.com/libgit2/libgit2/pull/4233

**Comment by andgeno** [comment]
> 
> 
> Can this be done in NodeGit now?

Is it possible **now**? ;-)

**Comment by implausible** [comment]
I believe you can run `NodeGit.Remote.createDetached(url: string)`, and then you can call `NodeGit.Remote.prototype.referenceList` (exposes git_remote_ls) on the detached remote in nodegit today.

**Comment by wirekang** [comment]
```js
(await Git.Remote.createDetached("https://github.com/....")).referenceList()
```
throws error: `this remote has never connected`
