### ISSUE TITLE
Cannot install version nodegit@0.5.0 on windows. 

### ISSUE THREAD

**Issue by jtraband** [nodegit/nodegit#756]
I've tried both node  v0.12.7 and node v4.2.1.  And on node v4.2.1 even nodegit@0.4.1 no longer works.  Any ideas? 

npm ERR! node v4.2.1
npm ERR! npm  v3.3.8
npm ERR! code ELIFECYCLE

npm ERR! nodegit@0.5.0 install: `node lifecycleScripts/install`
npm ERR! Exit status 13
npm ERR!
npm ERR! Failed at the nodegit@0.5.0 install script 'node lifecycleScripts/install'.

**Comment by johnhaley81** [comment]
It should be downloading pre-built binaries. Can you post a gist of the full log?

**Comment by jtraband** [comment]
gist of npm install nodegit failure on windows 10  -> https://gist.github.com/jtraband/8aa8509d529b66c7a5d9

**Comment by johnhaley81** [comment]
You need python 2 installed and configured in the path https://gist.github.com/jtraband/8aa8509d529b66c7a5d9#file-gistfile1-txt-L493

**Comment by jtraband** [comment]
Ok, this is with python 2.7.1 and MS Visual studio 2013 installed.  Different errors now but ...
https://gist.github.com/jtraband/620d53c0ad71ec2d0e1f

**Comment by metasanjaya** [comment]
Same here, Windows 7 32Bit, NW.js 0.12.3, msvs 2013, iojs 1.2.0

Please help

**Comment by jimcftr** [comment]
exact same errors here as jtraband's latest update (2 days ago), with node v4.2.1 / nodegit@0.5.0.

**Comment by maxkorp** [comment]
@jtraband Weird that it's not downloading a binary for you.I'll look into that now. 

@metasanjaya I'm betting our nw-gyp is out of date, I'll look into that as well.

**Comment by metasanjaya** [comment]
Even if I install the newest nw-gyp with npm install -g nw-gyp, it always use nw-gyp from dependencies, so I don't think it's about nw-gyp is out of date. and then always throw error.

Looking forward for update.

**Comment by filipesilva** [comment]
I am having the same issue, with logs similar to https://github.com/nodegit/nodegit/issues/756#issuecomment-150046405 (python installed, error on `msbuild.exe`). It seems that the binary not being downloaded is at the core of it. 

I'm running win10, node v4.2.1, npm 2.14.7. Any workaround possible while binaries at not available?

**Comment by maxkorp** [comment]
We're well past this now and these issues should be resolved :+1:. Please file a new issue if you have the problem on latest.
