### ISSUE TITLE
Failed to install prebuilt binary - add debug info to help figure out reason

### ISSUE THREAD

**Issue by electricmonk** [nodegit/nodegit#758]
Hi,

Installing `nodegit` in a node.js Docker image based on `node:latest`. `npm install` says "Failed to install prebuilt binary,  building manually". This takes forever. 

Same happens in my CI environment (TeamCity agents running on Docker containers).

What frustrates me the most is my inability to investigate why this happens. Any way you can pipe the error to stderr or stdout so as to help users investigate?

Thanks

**Comment by electricmonk** [comment]
Update: also happens on the 'node:0.12.7' image

**Comment by saper** [comment]
Can you produce `npm-debug.log` file and/or verbose npm output?

**Comment by electricmonk** [comment]
Not really helpful. I can post the entire verbose log, but it's _very_ verbose :)
```
[91minstall nodegit@0.5.0
[0m

> nodegit@0.5.0 install /app/node_modules/core3-git-api/node_modules/nodegit
> node lifecycleScripts/install


[nodegit] Fetching binary from S3.

[nodegit] Failed to install prebuilt binary, building manually.

[nodegit] Regenerating and configuring code
```

**Comment by saper** [comment]
> Not really helpful. I can post the entire verbose log, but it's _very_ verbose :)

Please use gist.github.com or similar service to upload your file. Or any webpage.

**Comment by electricmonk** [comment]
https://gist.github.com/electricmonk/93896810f0d8807fbe08

**Comment by saper** [comment]
You need to configure your npm `unsafe-perm` to true, or create a non-root user in the container and use it in your npm setup.

**Comment by electricmonk** [comment]
I tried both, neither seems to have any effect

**Comment by saper** [comment]
I have no solution then, sorry.

**Comment by electricmonk** [comment]
Any way we can print the failure reason to stderr / stdout?

**Comment by samkelleher** [comment]
In #774 additional log outputs have been added for each step as if there was a gyp compile error, the install would just exit without warning, the the verbose log just had a whole bunch of natter in there.

**Comment by maxkorp** [comment]
I've been meaning to make the output more verbose. As for why it fails to find a prebuilt binary? I don't think node-pre-gyp gives us anything meaningful in that regard, but I'm not totally sure about that tbh.

**Comment by maxkorp** [comment]
The actual issue at hand appears to be related to permissions with the published binary, I'm getting a 403. Adding a pr in just a second to print this info though.

**Comment by maxkorp** [comment]
Fixed in the above PR

**Comment by tbranyen** [comment]
This looks resolved, so closing for now, please comment to re-open if I closed in error.
