### ISSUE TITLE
Prebuilt binary libgit2 not built with GIT_SSH_MEMORY_CREDENTIALS defined

### ISSUE THREAD

**Issue by daxelrod** [nodegit/nodegit#760]
Hi! When I call Cred.sshKeyMemoryNew, I get this error message:

```
Error: This version of libgit2 was not built with ssh memory credentials.
    at Error (native)
```

"npm install" installed prebuilt binaries for nodegit.

I'm running Node 4.0.0 on x86_64 Linux. THis is nodegit 0.5.0.

I believe this means libgit2 [should be built with GIT_SSH_MEMORY_CREDENTIALS defined](https://github.com/libgit2/libgit2/blob/master/src/transports/cred.c#L203).

I'm filing this after talking to @johnhaley81 in gitter.

**Comment by BenHall** [comment]
I'm still seeing this with 0.16.0 :( Any ideas?

**Comment by eppsilon** [comment]
I'm seeing this too. OS X 10.12.1 with Node 6.9.0.

**Comment by BenHall** [comment]
My workaround is to write to temp files and use the non-memory method :(

**Comment by eppsilon** [comment]
I think there might be something up with the CI build environment. I tried using a locally built `nodegit` and it seems to work (though I get a different error: `username does not match previous request`).
