### ISSUE TITLE
Cannot install on Windows 10 / Py 2.7 / Error 

### ISSUE THREAD

**Issue by MocanuMarius** [nodegit/nodegit#765]
Anyone else encountered this?

https://gist.github.com/MocanuMarius/39065cd07b29991f4855

**Comment by af7** [comment]
Yes, many of us, see other same issue here:

https://github.com/nodegit/nodegit/issues/756

This issue blocks our development (for Windows), I hope for a quick resolution if possible. Thank you in advance.

**Comment by johnhaley81** [comment]
@af7 Yes we are working on figuring out what's going wrong with downloading the pre-built binary. Sorry for the delay.

**Comment by johnhaley81** [comment]
Closing this out as a duplicate of #756

**Comment by af7** [comment]
@johnhaley81 Thanks!
