### ISSUE TITLE
Unstaging index entry

### ISSUE THREAD

**Issue by kmalakoff** [nodegit/nodegit#778]
I'm trying to unstage an index entry that I previously added to the index using index.addByPath.

I found this posting saying that with libgit2, you just need to add the original entry again to unstage: https://stackoverflow.com/questions/22731553/un-stage-file-with-libgit2. Accordingly, I have tried `index.add(index.getByPath(my_path))` but the entry is not being unstaged.

| was thinking that maybe I need to lookup the id and manually create the IndexEntry from the head commit's tree entry id. I found this issue https://github.com/nodegit/nodegit/issues/611 and am also encountering the seg fault.

Just wondering if if I'm doing something wrong (I'm still new to this) or if the API is missing a way to unstage an index entry. Thank you!

**Comment by johnhaley81** [comment]
Try `NodeGit.Reset.default` to unstage a file just like you would in the CLI.

**Comment by soanvig** [comment]
@johnhaley81 
I can't use it that way... 
"nodegit": "^0.21.2",
http://www.nodegit.org/api/reset/#default

`nodegit.Reset.default()` -  _is not a function_ error

**Comment by rcjsuen** [comment]
@soanvig It is used in the tests so it should be there.

https://github.com/nodegit/nodegit/blob/78765bf811b35c4539f83f3b57d10a9333a7b3a3/test/tests/reset.js#L53-L59

**Comment by soanvig** [comment]
It must be the problem of my not typical configuration (though all
functions work...). Netherless I will debug it.

niedz., 25 mar 2018, 15:08 użytkownik Remy Suen <notifications@github.com>
napisał:

**Comment by soanvig** [comment]
Oh, I think what is the real problem here... I have suspicions, that it's the "default" method's name, which is restricted in environment I'm using (Webpack), because it's reserved name for ES6 modules.
