### ISSUE TITLE
Cherrypick.cherrypick() requires options parameter

### ISSUE THREAD

**Issue by Turbo87** [nodegit/nodegit#788]
It seems that the `options` parameter of the `Cherrypick.cherrypick()` function is actually required. If I call that function without it, the returned `Promise` is rejected with:

```
Error: CherrypickOptions cherrypick_options is required.
 at Error (native)
 at Promise.denodeify (.../node_modules/nodegit/node_modules/nodegit-promise/lib/node-extensions.js:24:20)
 at tryCallTwo (.../node_modules/nodegit/node_modules/nodegit-promise/lib/core.js:45:5)
 at doResolve (.../node_modules/nodegit/node_modules/nodegit-promise/lib/core.js:173:13)
 at new Promise (.../node_modules/nodegit/node_modules/nodegit-promise/lib/core.js:65:3)
 at Object.Promise.denodeify (.../node_modules/nodegit/node_modules/nodegit-promise/lib/node-extensions.js:19:12)
 at Object.Cherrypick.cherrypick (.../node_modules/nodegit/lib/cherrypick.js:42:22)
```

**Comment by maxkorp** [comment]
Do you get the same issue if you just calling `NodeGit.Cherrypick()` as when you call `NodeGit.Cherrypick.cherrypick()`? You _should_, I'd think. Let me see if that function is normalized properly.

**Comment by maxkorp** [comment]
Well that's disconcerting. It IS normalizing, so it should automatically ensure that an options object is passed in with defaults if you don't pass one in. We'll have to take al ook at this. Can you try passing in an empty object?

**Comment by Turbo87** [comment]
it works fine when I pass `new CherrypickOptions()` to the function, if that is what you were asking.

**Comment by maxkorp** [comment]
What about just `{}`?

**Comment by Turbo87** [comment]
that seems to work too

**Comment by Turbo87** [comment]
Calling `NodeGit.Cherrypick()` instead of `NodeGit.Cherrypick.cherrypick()` doesn't seem to work at all. I don't get an error message here but it also doesn't do anything.

**Comment by maxkorp** [comment]
Shit. Ok, so we have issues with promisify-node, where it doesn't play nice with optional parameters :/
We'll have to fix this there to make it a wide reaching fix.

**Comment by Turbo87** [comment]
cool, thanks for looking into this!

**Comment by rcjsuen** [comment]
Isn't this a problem with `normalizeOptions(*)` and not `promisify-node`? The normalizing code [will not change anything and simply returns `null`](https://github.com/nodegit/nodegit/blob/af73105ebe8200c1e5446f3489d00be75e960e17/lib/utils/normalize_options.js#L10-L12) if the provided `options` parameter is `null`.

```
if (!options) {
  return null;
}
```
