### ISSUE TITLE
0.6.0 Electron/windows not loading

### ISSUE THREAD

**Issue by fogaztuc** [nodegit/nodegit#795]
gyp exit code 13 when building 0.5.0
gyp exit code 1 when building 0.4.1

Tried on two different machines.  One is windows 8, one is windows 7

More information to follow.

**Comment by fogaztuc** [comment]
Trying to use with nw.js.  If I build from source (git clone) build works, however I get a version mismatch that feels like the nodegit build looking for libgit2 v0.23.3 but the latest version of lilbgit2 is v0.23.4.

**Comment by fogaztuc** [comment]
Tried on three different machines, would not build via npm install nodegit on any machine. When building from source and then attempting to run in nw.js got version mismatch was - expected 43 got 46.

**Comment by maxkorp** [comment]
Hrm, if building for nw.js and getting a module mismatch, I'd bet its not actually building with nw-gyp. Do you have an nw.js/node-gyp set in your engines of your root project?

**Comment by fogaztuc** [comment]
Build fails when building for either nw.js or electron.  Looking at other issues it appears this is a known issue. If so please close as a duplicate. I am not yet confident enough with this project to know for sure (i.e. everything seems to say this should be working, but I think the new versions of various items has broken stuff and the releases have not caught up with building this on the fly for nw.js or electron.)

**Comment by fogaztuc** [comment]
0.6.0 downloads a pre-built binary for electron on windows. On require("nodegit"); I get the following error at line 13 of nodegit.js. (Any help would be appreciated).

Uncaught Error: The system cannot find message text for message number 0x%1 in the message file for %2.
C:\electron\electron-quick-start\node_modules\nodegit\build\Release\nodegit.nodemodule.(anonymous function) @ ATOM_SHELL_ASAR.js:140module.(anonymous function) @ ATOM_SHELL_ASAR.js:140Module.load @ module.js:355Module._load @ module.js:310Module.require @ module.js:365require @ module.js:384(anonymous function) @ C:\electron\electron-quick-start\node_modules\nodegit\lib\nodegit.js:8Module._compile @ module.js:434Module._extensions..js @ module.js:452Module.load @ module.js:355Module._load @ module.js:310Module.require @ module.js:365require @ module.js:384(anonymous function) @ index.html:7

**Comment by alek-sys** [comment]
Just got the same problem.

Windows 7
OS Name:                   Microsoft Windows 7 Professional
OS Version:                6.1.7601 Service Pack 1 Build 7601
System Type:               x64-based PC

Electron v0.35.4

**Comment by fogaztuc** [comment]
I was using Windows 7 as well.  Using Windows 8 the failure is descriptive. The system is fails initializing a DLL.

**Comment by RichardLewin87** [comment]
fogaztuc, I am having dll initialisation issues myself (issue #828). Is this the same as what your getting?

**Comment by fogaztuc** [comment]
Yes - same issues these are a duplicate it seems now.

**Comment by maxkorp** [comment]
Yeah, looks duplicate now. If not, I'll reopen :+1:
