### ISSUE TITLE
short sha1 abbrev-commit

### ISSUE THREAD

**Issue by thisconnect** [nodegit/nodegit#810]
Is there a way to get the short form of a commit id, taking core.abbrev into account ?

On gitter somebody asked the same a while ago and the reply was to try `Object#shortId`. 
This is labeled experimental and I don't understand how to pass the commit id and get the short abbrev-commit. From the docs it seems it takes no argument and returns a buffer.

``` javascript
object.shortId().then(function(buf) {
  // Use buf
});
```

http://www.nodegit.org/api/object/

**Comment by johnhaley81** [comment]
It's labeled experimental since we don't have tests covering the functionality confirming that it works. If you want you can write a test for it which will change it to not be experimental anymore.

So that method is also labeled as a prototype method which means that it's available on all `git_object`. However NodeGit doesn't have a good way to determine what exactly a `git_object` can be so it's not on say a `git_oid` object. We might have to make that method static and then you can pass in an object and it will try to cast it for you in C land.

**Comment by thisconnect** [comment]
OK reading https://libgit2.github.com/libgit2/#HEAD/group/object I try to figure out what an object could be useful for other than than getting the shortId.. If I understand it correctly I could try to write some tests.
This works (getting the same Oid back)

```javascript
var oid = commits[0].id();
console.log(oid);
return Git.Object.lookup(repo, oid, Git.Object.TYPE.COMMIT)
.then(function(object){
    return object.id(); // works
    // return object.shortId(); // Assertion failed
})
.then(function(buf){
    console.log('buffer', buf);
});
```
correctly returns
```
[Oid 63bc699272d629380bf38f7a718e566574af3432]
buffer [Oid 63bc699272d629380bf38f7a718e566574af3432]
```

But `return object.shortId();`

```
Assertion failed: (buf->size == 0 && buf->asize == 0), function git_buf_sanitize, file ../vendor/libgit2/src/buffer.c, line 131.
[Oid 783c042e4bf666602dfef2fb812c5e9064b03714]
```

**Comment by thisconnect** [comment]
I would like to write tests in the future, but am a bit clueless about `git_object`. Looking at the api it would make sence to me to have either Commit.shortId() or Oid.shortId().

Related to this I am trying to find a way to get a commit by a shortened id. Intuitively Commit.lookupPrefix seemed to be the api to do so. http://www.nodegit.org/api/commit/#lookupPrefix
https://libgit2.github.com/libgit2/#HEAD/group/commit/git_commit_lookup_prefix

I could not find any test for Commit.lookupPrefix, can you confirm that this is the api to get a commit by shortid? Do you want me to try to add a test for lookupPrefix here:
https://github.com/nodegit/nodegit/blob/master/test/tests/commit.js ?

**Comment by thisconnect** [comment]
related #569

**Comment by thisconnect** [comment]
To answer my own question about getting a commit from a short SHA1 it is possible with Git.AnnotatedCommit.fromRevspec

**Comment by thisconnect** [comment]
Git.AnnotatedCommit.fromRevspec did work for me
