### ISSUE TITLE
Cannot download source from aws while running npm install

### ISSUE THREAD

**Issue by everolth** [nodegit/nodegit#818]
Hi, when trying to install this module in the box where I want it to run I get the following:

 nodegit@0.6.0 install /space/jenkins_slave/sportsbet/workspace/Bump Module Version/node_modules/nodegit
 node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: /bin/sh -c /space/jenkins_slave/sportsbet/workspace/Bump\ Module\ Version/node_modules/nodegit/node_modules/.bin/node-pre-gyp install --fallback-to-build=false
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.6.0-node-v46-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/space/jenkins_slave/sportsbet/workspace/Bump Module Version/node_modules/nodegit/node_modules/node-pre-gyp/lib/install.js:101:37)
node-pre-gyp ERR! stack     at emitOne (events.js:82:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:169:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/space/jenkins_slave/sportsbet/workspace/Bump Module Version/node_modules/nodegit/node_modules/node-pre-gyp/node_modules/request/request.js:951:10)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:169:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:415:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:305:20)
node-pre-gyp ERR! stack     at emitOne (events.js:77:13)
node-pre-gyp ERR! System Linux 2.6.32-504.3.3.el6.x86_64
node-pre-gyp ERR! command "/space/jenkins_slave/sportsbet/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node_4.2.1_/bin/node" "/space/jenkins_slave/sportsbet/workspace/Bump Module Version/node_modules/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /space/jenkins_slave/sportsbet/workspace/Bump Module Version/node_modules/nodegit
node-pre-gyp ERR! node -v v4.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok 
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c /space/jenkins_slave/sportsbet/workspace/Bump\\ Module\\ Version/node_modules/nodegit/node_modules/.bin/node-pre-gyp install --fallback-to-build=false' }
[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code
npm ERR! Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! argv "/space/jenkins_slave/sportsbet/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node_4.2.1_/bin/node" "/space/jenkins_slave/sportsbet/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/node_4.2.1_/bin/npm" "install" "--ignore-scripts"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code E401

npm ERR! Registry returned 401 for GET on https://registry.npmjs.org/clean-for-publish
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /space/jenkins_slave/sportsbet/workspace/Bump Module Version/node_modules/nodegit/npm-debug.log

I tried to download https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.6.0-node-v46-linux-x64.tar.gz and I also get a 401 on my browser.

**Comment by joshaber** [comment]
The s3 failure is because we don't have a binary for that combination of nodegit versions and node versions for Linux. So then it tries to build from source, but it looks like npm hiccuped:

```
npm ERR! Registry returned 401 for GET on https://registry.npmjs.org/clean-for-publish
```

I'd just try it again.

**Comment by everolth** [comment]
perfect that works now, thanks very much!
