### ISSUE TITLE
Orphan branch

### ISSUE THREAD

**Issue by melkior** [nodegit/nodegit#831]
Hi,

is it possible to create orphan branch with nodegit?

https://git-scm.com/docs/git-checkout/1.7.3.1

--orphan

Create a new orphan branch, named <new_branch>, started from <start_point> and switch to it. The first commit made on this new branch will have no parents and it will be the root of a new history totally disconnected from all the other branches and commits.

**Comment by maxkorp** [comment]
I suspect this should be plausible once some new index changes land (there is a PR for it already), but I couldn't say for sure.

**Comment by johnhaley81** [comment]
You'd create a commit without a parent and then pass the name of the new branch in. This is totally doable right now.

`repo.createCommit('new-orphan-branch-name', repo.defaultSignature(), repo.defaultSignature, 'message', treeOid); // last parameter`

**Comment by melkior** [comment]
Ok, but can you please show how to get proper treeOid in this case?

$ cat index.js

    var nodegit = require("nodegit");
    var path = require("path");
    var repo, index, oid;

    nodegit.Repository.open(path.resolve(__dirname, "repo")).then(function(repoResult) {
        repo = repoResult;
        return repo;
    }).then(function() {
        return repo.openIndex();
    }).then(function(indexResult) {
        index = indexResult;
        return index.read(1);
    }).then(function() {
        return index.addByPath('temp');
    }).then(function() {
        return index.write();
    }).then(function() {
        return index.writeTree();
    }).then(function(oidResult) {
        oid = oidResult;
        return repo.createCommit("oprhan", repo.defaultSignature(), repo.defaultSignature(), "message", oid);
    }).done(function(commitId) {
        console.log("New Commit: ", commitId);
    })


$ git ls-files
README
$ cd ..
$ node index.js 
New Commit:  [Oid 0000000000000000a0590f020000000020000000]
$ cd repo/
$ git branch
\* master
$ git ls-files
README
temp

Thanks

**Comment by AndrewJo** [comment]
@johnhaley81: I don't know if I'm doing something wrong but `repo.createCommit` doesn't seem to create a valid commit OID without a parent.

On `v0.12.2` at least, this is what I get:

```javascript
Repository.open(path.resolve(__dirname, '.git').then(function (repository) {
  return repository.getMasterCommit();
})
.then(function (commit) {
  return new Promise(function (resolve, reject) {
    return resolve(commit.treeId());
  };
})
.then(function (treeOid) {
  return repository.createCommit('new-orphan-branch-name', repository.defaultSignature(), repository.defaultSignature(), 'message', treeOid); // or pass in empty array [] for parent array but results are the same
})
.then(function (oid) {
  console.log(oid);
  // this doesn't work either
  // return repository.createBranch('new-orphan-branch-name', oid, false, repository.defaultSignature(), 'message');
});
```

The output of the oid looks something like this:
```
[Oid 0000000000000000000000000000000005008202]
```

And attempting to create a branch with this OID results in this error:

```
[Error: Object not found - no match for id (0000000000000000000000000000000005008202)]
```
