### ISSUE TITLE
Push with tags

### ISSUE THREAD

**Issue by strarsis** [nodegit/nodegit#833]
How can I push including the tags, on CLI I would additionally pass --tags.

````
remote.push(
             ['refs/heads/master:refs/heads/master'],
             { /* pushOptions - what to use for '--tags'? */ }
           );
````

Thank you and
with best regards

**Comment by jonathandelgado** [comment]
To future readers, https://github.com/libgit2/libgit2sharp/issues/595

**Comment by maxkorp** [comment]
Yup, you  just push 'refs/tags/mahFancyTag' like any other ref :+1:

**Comment by hhovhann** [comment]
> Yup, you just push 'refs/tags/mahFancyTag' like any other ref 👍

@maxkorp thanks for this answer but I am trying to use this and push changes with tag but cannot.

```
 var remoteResult = await repository.getRemote('origin');
 await remoteResult.push(["refs/heads/master:refs/heads/master", "refs/tags/v1.0.1"], fetchOptions.fetchOpts, author, "push message here");
```
Getting an error: ```Error: Failed to authenticate SSH session: Unable to send userauth-publickey request```
But keys working with all cases with push without tag commit and other stuff.

Any idea here ?

**Comment by hhovhann** [comment]
> Yup, you just push 'refs/tags/mahFancyTag' like any other ref 👍

Thanks for reply. Make sence to mentioned here that before push you need to have ```mahFancyTag``` in refs/tags/ folder, otherwise you need to create through:

```gitTag.create(repository, tagName, parent, author, configuration.tagMessage, 1)```

**Comment by maxkorp** [comment]
Correct, the tag needs to exist before you can push it.

**Comment by SaltyBadger** [comment]
@hhovhann Can you please explain what is the 'parent' object?

**Comment by hhovhann** [comment]
@SaltyBadger of course parent is when I getting commit from head and head takes from name to id, here is example:

```
        var head =  git.Reference.nameToId(repository, 'HEAD');
        var parent = repository.getCommit(head);
```
