### ISSUE TITLE
How To Create Commit in Bare Repo

### ISSUE THREAD

**Issue by Snugug** [nodegit/nodegit#842]
I'm initializing a bare repo and want to add an initial commit once it's created. I've initialized the repository just fine following the [instructions on the website](http://www.nodegit.org/guides/repositories/initializing/), but when trying to use `createCommitOnHead` I get the following error: `Oid id is required.`. Same error when trying to create a branch, or really do anything related to repo modification beyond adding a remote on a bare repo.

How can I add and commit files to a bare repository?

**Comment by maxkorp** [comment]
This should tell you what you need to know :+1:
https://github.com/nodegit/nodegit/blob/master/examples/create-new-repo.js

**Comment by oguimbal** [comment]
For future reference, I think that what you were looking for is something like that https://gist.github.com/getify/f5b111381413f9d9f4b2571c7d5822ce
