### ISSUE TITLE
Access denied when downloading from AWS

### ISSUE THREAD

**Issue by FredyC** [nodegit/nodegit#846]
This is from our Jenkins server when trying to run `npm i nodegit`. Here is the [full verbose log](http://pastebin.com/tCW10D2v)

	[nodegit] Fetching binary from S3.
	[nodegit] Failed to install prebuilt binary:
	{ [Error: Command failed: node-pre-gyp ERR! install error
	node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.6.3-node-v11-linux-x64.tar.gz
	node-pre-gyp ERR! stack     at Request.<anonymous> (/tmp/test/node_modules/nodegit/node_modules/node-pre-gyp/lib/install.js:101:37)

Trying to access url in browser gives me this:

```xml
<Error>
	<Code>AccessDenied</Code>
	<Message>Access Denied</Message>
	<RequestId>A41C60A09F9DA6E1</RequestId>
	<HostId>
		0ef7kQP6zCgwoqOoLqdz0MePNrTIzCZ5/s4iDhirbYg/Pw11ZDXo9h9jFb97oDSDXXP+0UWqnQc=
	</HostId>
</Error>
```

Strangely from my windows machine I can install nodegit just fine and it downloads binaries ok. Not sure about URL there, it's not displayed anywhere.

Also the install seems that it went ok, but it have't actually compiled anything as folder `build/Release` is empty. This will be probably related to #506, however we have `gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)` there so it's not solved by that. Anyway we could really use binaries since we are using nodegit during continuous integration and that would be rather unpleasant compile this every time.

**Comment by joshaber** [comment]
Yup, we don't currently have binary builds for node 0.11. Check out our Travis configuration to see which node versions we build for: https://github.com/nodegit/nodegit/blob/232dbb19116c58d22cd7afd7435ee0bbe063f85b/.travis.yml#L14-L16

**Comment by FredyC** [comment]
Ahh, thank you very much, that indeed helped. I should have been probably more careful and notice the line `npm WARN engine nodegit@0.6.3: wanted: {"node":">= 0.12"} (current: {"node":"0.11.16","npm":"2.3.0"})`. Perhaps because it's just warning I did't expected it to be actual issue.
