### ISSUE TITLE
Should Repository#createCommitOnHead create a new head if tree is empty?

### ISSUE THREAD

**Issue by aldialimucaj** [nodegit/nodegit#852]
Using this function on a repository with no commits currently yields with "Error: Oid id is required." The function is quite helpful but i have to write the long way if the there is no HEAD. Which makes the shorter version irrelevant once i took the effort to write the longer one. So should the option be included to also support the initial commit if none is available?

**Comment by johnhaley81** [comment]
So you're making an initial commit in the repo? I feel like that function should be able to handle it. I'd check to see what `parent` is set to [here](https://github.com/nodegit/nodegit/blob/master/lib/repository.js#L535-L545). That should be null. If it's passing something other than that then that might be killing the call to `Repository#createCommit`.

FWIW I've used `Repository#createCommit` to make an initial commit before so I know that works.

**Comment by aldialimucaj** [comment]
Thanks john for the quick reply.
