### ISSUE TITLE
Cannot install nodegit on linux machines (e.g. travis builds)

### ISSUE THREAD

**Issue by runspired** [nodegit/nodegit#853]
```cli
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/build/runspired/ember-cli-changelog/node_modules/nodegit/build/Release/nodegit.node)
```

**Comment by runspired** [comment]
Probably a duplicate: https://github.com/nodegit/nodegit/issues/758#issuecomment-155232550

**Comment by runspired** [comment]
An incorrectly closed PR which assumed this issue was no longer present: https://github.com/nodegit/nodegit/pull/744

**Comment by tbranyen** [comment]
We're still linking our prebuilts to a newer gcc. If you build it from source it should work fine. Try:

``` sh
BUILD_ONLY=true npm install nodegit
```

**Comment by runspired** [comment]
I was able to get the project directly consuming it to build (both with and without master) by following the travis-addon instructions in the above PR.

However, setting the dependency to `master` results in failed builds for projects consuming another project which has nodegit as a dependency.

See: https://travis-ci.org/runspired/ember-hammertime/jobs/100523335

**Comment by johnhaley81** [comment]
You're getting a `node-gyp` [error](https://travis-ci.org/runspired/ember-hammertime/jobs/100523335#L248) because that build is still using [old gcc](https://travis-ci.org/runspired/ember-hammertime/jobs/100523335#L31).

We might need to make gcc 4.9+ a [requirement](https://github.com/nodejs/nan/issues/500) for nan anyways since for node versions 4+

**Comment by runspired** [comment]
@johnhaley81 I did, I can make Travis pass for that repo (and that repo only) with each test scenario taking an additional 6-10minutes to run :'(

But a secondary issue arises when that repo is a dependency of another project.  It's code will never be executed on Travis, but nodegit must be a dependency.  This results in consuming projects also needing to configure Travis specially for a dependency that's unneeded during testing, with ridiculous build times if you do.

**Comment by amackera** [comment]
I'm also seeing this error trying to run a project using `nodegit` in Elastic Beanstalk.

**Comment by thinkingmedia** [comment]
I can confirm this is still an issue with 0.7.0 build.

**Comment by tbranyen** [comment]
@runspired if you setup your travis env to use the latest gcc 4.9, you shouldn't have to compile anything to make this work and your builds should take hardly any longer.

**Comment by tbranyen** [comment]
I received this error myself when installing NodeGit on Ubuntu. So I followed my own advice above and installed both GCC 4.9 and the libstdc++-4.9-dev packages by doing:

``` sh
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-4.9 libstdc++-4.9-dev
```

Pre compilation linked libraries:

``` sh
λ ldd node_modules/nodegit/build/Release/nodegit.node
node_modules/nodegit/build/Release/nodegit.node: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node_modules/nodegit/build/Release/nodegit.node)
	linux-vdso.so.1 =>  (0x00007fffdabd5000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7309f02000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7309cec000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7309ace000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7309709000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7309403000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f730ad03000)
```

Run the build with:

``` sh
BUILD_ONLY=true npm rebuild
```

Post compilation linked libraries:

``` sh
λ ldd node_modules/nodegit/build/Release/nodegit.node 
	linux-vdso.so.1 =>  (0x00007ffe26c6a000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4d5b9ea000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4d5b7cc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4d5b407000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4d5b101000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4d5c46a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4d5aeeb000)
```

So yes, you'll definitely need to rebuild if it's not working out-of-the-box.

**Comment by tbranyen** [comment]
You can do this in Travis-CI by adding the following to your .travis.yml file:

``` yaml
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
```

**Comment by hridyeshpant** [comment]
we are also hitting same issue 
>> Error: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/jenkins/workspace/master/node_modules/nodegit/build/Release/nodegit.node)

Is there any solution  for centos-release-6-7 OS?

**Comment by semos** [comment]
@hridyeshpant any solutions on this ?

**Comment by hc000** [comment]
Don't think installing libstdc 4.9 solves the issue
this is on ubuntu 14.04
```$ sudo add-apt-repository ppa:ubuntu-toolchain-r/test
$ sudo apt-get update
$ sudo apt-get install libstdc++-4.9-dev
nodegit@0.12.2 node_modules/nodegit
├── fs-extra@0.26.7 (path-is-absolute@1.0.0, klaw@1.3.0, jsonfile@2.3.1, graceful-fs@4.1.4)
└── promisify-node@0.3.0 (nodegit-promise@4.0.0)
/output/node_modules/nodegit/lib/nodegit.js:14
    throw ex;
          ^
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /output/node_modules/nodegit/build/Release/nodegit.node)```

**Comment by mikalai-silivonik** [comment]
>Is there any solution for centos-release-6-7 OS?

`BUILD_ONLY=true npm install nodegit` solved the problem for me on centos7. Thanks to https://github.com/nodegit/nodegit/issues/853#issuecomment-169240445

**Comment by heath-guidewire** [comment]
Is `BUILD_ONLY=true npm install nodegit` the same as `npm install nodegit --build-from-source`?

**Comment by maxkorp** [comment]
Not quite, there is a bit more to it that we do.

**Comment by chalangr12** [comment]
So what's the solution for this? I'm trying to run a project on elasticbeanstalk and it's failing with the same issues.

**Comment by tbranyen** [comment]
@chalangr12 solution for what? We can't build for every single architecture unfortunately, only popular ones. Can you try and suss out what dependency is causing your failure? Is it glibc?

**Comment by robertpearce** [comment]
i think the issue people are running into is that on centos at least libstdc++-4.9 isn't in the normal repos
