### ISSUE TITLE
resolve merge conflict in favor of “theirs”

### ISSUE THREAD

**Issue by adnan-kamili** [nodegit/nodegit#858]
In git we can use following command to achieve it:

git merge --strategy-option theirs

But I couldn't figure out a way in nodegit: http://www.nodegit.org/api/repository/#mergeBranches

 repo.mergeBranches("master.min", "master", null, merge.PREFERENCE.FASTFORWARD_ONLY);

A file favor enum is present

http://www.nodegit.org/api/merge/#FILE_FAVOR

But repo.mergeBranches() expects PREFERENCE enum. How do I pass FILE_FAVOR enum for merge.

http://stackoverflow.com/questions/34671270/nodegit-resolve-merge-conflict-in-favor-of-theirs

**Comment by maxkorp** [comment]
Oof, thats a good question. Digging through libgit2 docs, it looks that goes in a `MergeOptions` object. Pretty much all of the merge methods take one of those in.

**Comment by maxkorp** [comment]
On further looking, it appears that repo.mergeBranches doesn't take that merge options. I think at the time it was implemented, that wasn't all there in libgit2, so we couldn't handle that as cleanly, so we directly tied into preference). That's worth looking into.

**Comment by maxkorp** [comment]
Coopting this issue :+1:

**Comment by maxkorp** [comment]
Closing this in lieu of that issue.
