### ISSUE TITLE
Repository.open is not a function

### ISSUE THREAD

**Issue by playpianolikewoah** [nodegit/nodegit#859]
I am working with Electron and I believe I am doing this correctly. I can run nodegit from my main.js file, which is on the node side, but when I go to run nodegit remotely from the rendering side it does not work. I can get references to nodegit and the `Repository`, but it says "`open is not a function`". 

    Repository.open is not a function

This is the code:

	var remote = require('electron').remote;
	var pathToRepo = remote.require('path').resolve(currentRepoDir);
	remote.require('nodegit').Repository.open(pathToRepo).then(function(repo){
	  console.log(repo);
	});

Also this is my `package.json`

    {
      "name": "someapp",
      "version": "0.0.1",
      "description": "what it does",
      "main": "main.js",
      "engines": {
        "electron": "0.36.0",
        "atom-shell": "0.36.0"
      },
      "scripts": {
        "start": "electron main.js"
      },
      "repository": {
        "type": "git",
        "url": "git+https://gitlab.com/..."
      },
      "keywords": [
        "git",
        "gitlab"
      ],
      "author": "My name",
      "license": "MIT",
      "bugs": {
        "url": "https://gitlab.com/..."
      },
      "homepage": "https://gitlab.com/...",
      "devDependencies": {
        "grunt": "^0.4.5",
        "grunt-contrib-jasmine": "^0.9.2",
        "grunt-contrib-jshint": "^0.11.3",
        "grunt-contrib-sass": "^0.9.2",
        "grunt-contrib-uglify": "^0.11.0",
        "grunt-contrib-watch": "^0.6.1"
      },
      "dependencies": {
        "electron-prebuilt": "^0.36.0",
        "nodegit": "^0.7.0"
      }
    }

**Comment by playpianolikewoah** [comment]
I was doing it incorrectly in Electron. You can just require it.

**Comment by tbranyen** [comment]
Awesome, glad you got it working!
