### ISSUE TITLE
Add babel to let the library use ES6

### ISSUE THREAD

**Issue by johnhaley81** [nodegit/nodegit#874]
Because it's 2016.

**Comment by ChristianMurphy** [comment]
Awesome!
It could be worth considering moving for [jshint](https://github.com/jshint/jshint) to [eslint](https://github.com/eslint/eslint) + [eslint-babel](https://github.com/babel/babel-eslint).
JSHint currently only supports some of the syntax made available by babel.
ESLint (with the babel plugin) supports all valid babel code.

Reference: https://medium.com/@dan_abramov/lint-like-it-s-2015-6987d44c5b48#.6wprjkp4k

**Comment by maxkorp** [comment]
Yeah we have a few projects already wired up well on babel+eslint

**Comment by ELLIOTTCABLE** [comment]
:+1:, if only because I'm currently happily consuming NodeGit using `await/async` via Babel. It's pretty ideal.

**Comment by johnhaley81** [comment]
Implemented in #1016
