### ISSUE TITLE
calculating convenient patches locks files without autocrlf

### ISSUE THREAD

**Issue by implausible** [nodegit/nodegit#877]
When calculating patches for a diff of the working directory, if autocrlf is unset or false, the libgit2 creates a file lock for all patches until the patches are freed.

Unfortunately, @srajko and I were working on this issue today and uncovered the fact that we are also not freeing objects that libgit 2 creates for us that libgit2 wants us to free. This means that when patches are created, even after the reference to the javascript object is GCd, the patch and associated handle exist out in heap land.

Due to this problem, it is necessary that we specify in our descriptor objects that need to be freed in the  GC process. I have a branch https://github.com/nodegit/nodegit/tree/free-raw-on-demand which begins the implementation of that. The branch also starts introducing the ability to free raw objects while in javascript.

The mechanisms for freeing the resources would also need to be templated out such that if we declare in javascript, free this object, the object should now return 'not allocated' errors or we should specify some other means of emptying the object.

Interestingly enough, since this error affects patches, which are directly linked to the hunks of the diff, I am also proposing that we move the convenience classes for patches, lines, and hunks into a manual C++ template. The reasoning behind this is that at the time that patches are calculated, it is possible to transfer all of that data into a single object that is not locking any files via libgit2. This convenience wrapper would discard all libgit2 references and purely represent the diff data. This means that our convenience class can serve that data to javascript land faster and more conveniently.

Looking for opinions.

**Comment by srajko** [comment]
> Interestingly enough, since this error affects patches, which are directly linked to the hunks of the diff, I am also proposing that we move the convenience classes for patches, lines, and hunks into a manual C++ template.

I like the idea of prefetching data at the C++ level and making it available in ready-to-go JS format - that data would be accessible to the JS thread synchronously and at no risk of blocking with the new thread safety code (CC @johnhaley81 @joshaber @maxkorp @tbranyen).  It would be great to make that available for any data/type, but that's probably a longer/separate discussion.

The most critical part here is probably the other stuff - making sure we do GC those libgit2 objects that are currently getting leaked, and allowing for types that hold on to file handles to be freed explicitly.

**Comment by johnhaley81** [comment]
For very large diffs that calculation could be pretty long. I mean it'll be fast and non-blocking in C land but it's a lot of crunching data that will most likely never been used. But it that's a separate object then that's really up to the consumer on whether or not they need it. So really my vote is for a *both* option. Starting with the GCing libgit2 objects correctly and allowing the user to manually free them (if needed) while providing a JS error when accessing a freed object. And then later providing a "fast diff" similar to the "fast walk" that was implemented in #772.

Another potential way would be implementing something in libgit2 that tells the `git_patch` to acquire/release locks and we could add things in `ConvenientPatch` to only lock the files when accessing the data. /cc @carlosmn @ethomson would you guys be ok with something like that living in libgit2? From the looks of the code it does seem very intentional to have it lock the files in windows for the life of the struct.

**Comment by implausible** [comment]
It's actually not a lot of crunching data. The second you call git_patch_from_diff, you've already created all the hunks, lines, and stats for that file in libgit2. We would merely create a near carbon copy of the data that libgit 2 has with nan accessors. JS would be able to communicate with it synchronously instead of asynchronously, and we could release the patch resource internally.

The issue with acquiring / releasing locks is that the problem revolves around libgit2's use of [MapViewOfFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366761(v=vs.85).aspx). While the patch exists, libgit2 will have to keep the file handle open that keeps the handle open for the return value of this function. When we call [UnmapViewOfFile](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366882(v=vs.85).aspx) later, this invalidates the data map or view of the file. And it does look like this mapping is used for both reading and writing which confounds our ability to simply release the map after doing a memcpy of the datamap.

**Comment by johnhaley81** [comment]
I see, let's just go with the both option right now.

**Comment by implausible** [comment]
Just checking in... So I was giving the situation another look. There's a pretty large complication with allowing freeing in the codebase. So say you do free on a git_patch, hunk and line class both belong to that git_patch. Such that git_patch has member hunks, and each hunk has members lines. When we do a free on git_patch we also free the hunks and the lines. So if I call git_patch_free on a nodegit object, we have wrappers for the hunks and lines around the patch. This means when I free the patch, I now have non-nulled out dead pointers for every hunk and line that i pulled out of that patch.

**Comment by srajko** [comment]
I think this affects us whether we allow explicit freeing or not - we would have the same problem whether `git_patch_free` is called via `patch.free` or by the GC.

So maybe `needsFreeing` is not the best way to go with this `descriptor.json` parameter - it might be better to go with `ownedBy` or `owner`, where `needsFreeing: true` would be equivalent to `owner: "self"`.  That would allow us to also say things like `owner: "patch"` in the future, and when the patch is freed we would know to null out any outstanding hunks and lines.

I think `owner: "self"` is all we need to implement now though - that much is necessary to prevent leakage.

**Comment by srajko** [comment]
> That would allow us to also say things like owner: "patch" in the future, and when the patch is freed we would know to null out any outstanding hunks and lines.

Alternatively, we could prevent the patch from getting freed until the hunks and lines go out of scope.  But again, I feel like this is a separate problem to solve, in the future :-)

**Comment by implausible** [comment]
The thing is we need patch to be freeable now to release the locks, but if we have patch be freeable now, we need to build links to its child members (hunks and lines) now. Perhaps in the conversion to v8 we could add code that flags an out object as owned by, and then in the descriptor, build the links as you recommended.

**Comment by srajko** [comment]
> The thing is we need patch to be freeable now to release the locks, but if we have patch be freeable now, we need to build links to its child members (hunks and lines) now

I might be wrong, but I think we only need the links to null out the children, which I agree should be done but it might be a pretty significant chunk of work (this generalizes for all types btw - everything is owned by something, if nothing else the repo).

Making sure GC calls free, and allowing free on demand seem the most critical at this point.  Nulling and throwing errors on use is a nice-to-have, and we can provide it for the simple case (when the owner is self) but going beyond that might turn into a rabbit hole...

**Comment by implausible** [comment]
I agree, it is a pretty significant chunk of work. I'm going to put freeing on the shelf for now and work on rebuilding the convenient patch / hunk / line to work in a more safe and efficient manner. I think this whole subject of freeing our objects needs a serious revisit.

**Comment by johnhaley81** [comment]
Closed via #883

**Comment by joshaber** [comment]
I *think* we're still seeing this in Atom, even after updating to 0.11.5. I'm still digging into it.
