### ISSUE TITLE
require('nodegit') hangs

### ISSUE THREAD

**Issue by colevscode** [nodegit/nodegit#879]
If I require nodegit in a simple npm script, the script never terminates.

Here's a minimal test case:

    $ uname -mrs
    Darwin 14.3.0 x86_64

    $ npm install nodegit
     
    > nodegit@0.8.0 install /Users/.../node_modules/nodegit
    > node lifecycleScripts/install
    
    [nodegit] Fetching binary from S3.
    [nodegit] Completed installation successfully.
    nodegit@0.8.0 node_modules/nodegit
    └── promisify-node@0.3.0 (nodegit-promise@4.0.0)

    $ node -e "require('nodegit'); console.log('quitting...')" && echo "done"
    quitting...
    ^C

**Comment by tbranyen** [comment]
Thanks for reporting @colevscode, but we're aware of the issue here: https://github.com/nodegit/nodegit/issues/866

**Comment by colevscode** [comment]
Woops! Missed that somehow. Thanks!
