### ISSUE TITLE
DLL initialisation routine failed in Electron on Windows - nodegit v0.11.1, Electron v0.36.7

### ISSUE THREAD

**Issue by darkmyst** [nodegit/nodegit#902]
Seems to be exactly the same problem as #828 with exactly the same stack trace. Is this a regression?

**Comment by maxkorp** [comment]
The prebuilts were not going out, I'm betting you got a build error that just got swallowed. Going to close this assuming thats so since those are out now. If you reinstall and still get the error, post here and we'll reopen this :+1:
