### ISSUE TITLE
Tree.entryToObject documentation?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [nodegit/nodegit#903]
> **Note:** So, in general, the documentation is … pretty lacking. At the _very least_, it'd be super-nice if you'd _inline_ the documentation for the C function into the NodeGit documentation; that way I don't have to keep tabbing back and forth between the name (in the NodeGit documentation) and the actual description of what values it takes and what it does (in the `libgit2` documentation). Just a thought. /=

In the documentation for [Tree.entryToObject](http://www.nodegit.org/api/tree/#entryToObject), the first argument is an `object_out`. This makes no sense in a managed-memory context … how is this supposed to be used, on the JavaScript side?

Alternatively, is there another way to easily retrieve a `Blob` object for each entry in a `Tree`, than iterating over the results of `tree.walk().on('end' …` results and passing the `TreeEntries` to `entryToObject`?

**Comment by rcjsuen** [comment]
The linked-to function no longer exists and was removed in v0.13.0. Instead, please call `toObject` on a `TreeEntry`.
