### ISSUE TITLE
electron prebuilt binary permission issues?

### ISSUE THREAD

**Issue by joshball** [nodegit/nodegit#904]
**Note: this works fine with 0.11.0** (e.g. npm install of nodegit**@0.11.0**). 

I am trying to install nodegit in an **electron** environment with **0.11.1**

I have setup my `.npmrc` in the project to:

```
runtime = electron
target = 0.36.7
target_arch = x64
dist_url = https://atom.io/download/atom-shell
```
when I do an npm install of nodegit it fails:

```
 nodegit@0.11.1 install w:\src\electron\starters\electron-react-boilerplate\node_modules\nodegit
> node lifecycleScripts/install
[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c ""w:\src\electron\starters\electron-react-boilerplate\node_modules\nodegit\node_modules\.bin\node-pre-gyp" install --fallback-to-build=false"
node-pre-gyp http GET https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.11.1-electron-v0.36-win32-x64.tar.gz
node-pre-gyp http 403 https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.11.1-electron-v0.36-win32-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.11.1-electron-v0.36-win32-x64.tar.gz
```
Fetching the above url directly [https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.11.1-electron-v0.36-win32-x64.tar.gz]: shows `<Code>AccessDenied</Code>`

**Comment by johnhaley81** [comment]
Hmm... seems like the electron binaries didn't get published. Check [here](https://ci.appveyor.com/project/TimBranyen/electron-npg-automator/history) for windows builds and [here](https://travis-ci.org/nodegit/electron-npg-automator) for linux/osx status.

After they are done you shouldn't see this error anymore. If you do feel free to re-open this issue. Sorry about that.

**Comment by maxkorp** [comment]
@johnhaley81 @tbranyen are we able to open directorylisting permissions on this folder, so people 404 instead of 403ing? That seems fairly common.

**Comment by joshball** [comment]
Thanks guys.
