### ISSUE TITLE
Nodegit operations prevent process from exiting automatically.

### ISSUE THREAD

**Issue by bpeabody** [nodegit/nodegit#920]
I'm finding that when I use nodegit, I have to explicitly call `process.exit()` to get my process to exit. I apologize in advance if I am missing something fundamental or simple.

The sample program below never exits for me (I put the call to `.free()` in for good measure):

    const NodeGit = require("nodegit");

    NodeGit.Clone("https://github.com/nodegit/nodegit.git", "no-progress")
    .done(function (repo) {
        repo.free();
        console.log("I'm done");
    });

**Comment by johnhaley81** [comment]
There must be something in the creation/execution of an async action that's preventing the process from closing down. We'll have to dig into this.

**Comment by johnhaley81** [comment]
@bpeabody I can't get this code to hang for me. Does this still break for you?

**Comment by johnhaley81** [comment]
Here's exactly what I'm doing:

```
mkdir test
cd test
npm install nodegit
printf "const NodeGit = require('nodegit');\n\n NodeGit.Clone('https://github.com/nodegit/nodegit.git', 'no-progress').done(function (repo) { repo.free(); console.log('I am done'); });" >> test.js
node test.js
```

And no hang :(

**Comment by bpeabody** [comment]
I think I hadn't actually flubbed the upgrade and it's no longer happening for me.

**Comment by johnhaley81** [comment]
:+1:

**Comment by johnhaley81** [comment]
OMFGGGGGGGGGGGG!!!

**Comment by johnhaley81** [comment]
Also I swear that the reaction button wasn't there when I typed that....

**Comment by tbranyen** [comment]
lol I think the announcement and rollout happened as you typed it
