### ISSUE TITLE
Tree.walk() does not return the correct entries on "end"

### ISSUE THREAD

**Issue by jdgarcia** [nodegit/nodegit#928]
Scenario files in your tree:
- `test.txt`
- `foo/bar.txt`

If you use `tree.walk()`, during the `entry` events, you will end up with `test.txt` and `foo/bar.txt`, but for the `end` event, you will get `[foo/bar.txt, foo/bar.txt]`.

The `end` handler gives you files in the last tree it recursed through, with a duplicate entry for everything in it.

**Comment by tbranyen** [comment]
Hrm, should we use a Set instead of an Array and then coerce to an Array at the end?

**Comment by jdgarcia** [comment]
The PR I referenced already fixes the issue but we could do that as an extra safeguard. Though if any duplicate were to slip through, it would still get emitted twice in an `entry` event.

**Comment by jdgarcia** [comment]
Actually, I guess we could just not emit entries if they are already part of the Set.

**Comment by johnhaley81** [comment]
:+1: to using a Set and only emitting when a new entry is added. Though a good point that was brought up in #929 was that the API for this being an event emitter is a little wonky compared to the rest of the API. Other calls that we have for this would return a promise and use callbacks to notify the JS layer of updates and then resolve the promise with the results.

I don't know if it's something we should do right now but it feels like it ought to be normalized with the rest of the API for a NodeGit 1.0.0 release.

**Comment by johnhaley81** [comment]
Fixed in #929
