### ISSUE TITLE
Error: Cannot find module '../build/Debug/nodegit.node'

### ISSUE THREAD

**Issue by WilldNY** [nodegit/nodegit#940]
Hello, I installed docker-gitlab in the virtual machine, but when I'm in the project npm start when the following error:

`root@a-virtual-machine:/data/project/GitLab-Pages# npm start

GitLab-Pages@0.1.0 start /data/project/GitLab-Pages
node ./bin/www
module.js:327
throw err;
^

Error: Cannot find module '../build/Debug/nodegit.node'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/data/project/GitLab-Pages/node_modules/nodegit/lib/nodegit.js:16:12)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.2
npm ERR! npm v3.7.5
npm ERR! code ELIFECYCLE
npm ERR! GitLab-Pages@0.1.0 start: node ./bin/www
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the GitLab-Pages@0.1.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the GitLab-Pages package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs GitLab-Pages
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls GitLab-Pages
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /data/project/GitLab-Pages/npm-debug.log`

sorry, my English is very general, through the google translation tool, please forgive

**Comment by tbranyen** [comment]
What version of Node, NPM, NodeGit?

**Comment by WilldNY** [comment]
@tbranyen 
node v4.3.2
npm v3.7.5

How to check nodegit version?  I use 'npm install nodegit' installation

**Comment by saper** [comment]
@WilldNY you node seems to be compiled with debug options enabled. Does it work better if you switch to the node "Release" version?

**Comment by WilldNY** [comment]
@saper  my nodejs version is v4.3.2   ,   need to change?


this is npm log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.8.0
3 info using node@v4.3.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle GitLab-Pages@0.1.0~prestart: GitLab-Pages@0.1.0
6 silly lifecycle GitLab-Pages@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle GitLab-Pages@0.1.0~start: GitLab-Pages@0.1.0
8 verbose lifecycle GitLab-Pages@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle GitLab-Pages@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/data/proj/GitLab-Pages/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle GitLab-Pages@0.1.0~start: CWD: /data/proj/GitLab-Pages
11 silly lifecycle GitLab-Pages@0.1.0~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle GitLab-Pages@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle GitLab-Pages@0.1.0~start: Failed to exec start script
14 verbose stack Error: GitLab-Pages@0.1.0 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid GitLab-Pages@0.1.0
16 verbose cwd /data/proj/GitLab-Pages
17 error Linux 3.19.0-25-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v4.3.2
20 error npm  v3.8.0
21 error code ELIFECYCLE
22 error GitLab-Pages@0.1.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the GitLab-Pages@0.1.0 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the GitLab-Pages package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs GitLab-Pages
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls GitLab-Pages
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by saper** [comment]
This has nothing to do with node-sass. You can try starting `/usr/local/bin/node bin/www` manually or make sure your node is in your `PATH`.

**Comment by bpeabody** [comment]
I'm having a similar problem, also on a VM problem. I'm pretty sure I'm using a release version of node. My output looks like:

> nodegit@0.12.0 install /home/bpeabody/trash/nodegit
> node lifecycleScripts/install

[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: /bin/sh -c "/home/bpeabody/trash/nodegit/node_modules/.bin/node-pre-gyp" install --fallback-to-build=false
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: self signed certificate in certificate chain
node-pre-gyp ERR! stack     at Error (native)
node-pre-gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1013:38)
node-pre-gyp ERR! stack     at emitNone (events.js:67:13)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
node-pre-gyp ERR! stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
node-pre-gyp ERR! stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)
node-pre-gyp ERR! System Linux 3.16.0-0.bpo.4-amd64
node-pre-gyp ERR! command "/home/bpeabody/local/bin/node" "/home/bpeabody/trash/nodegit/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /home/bpeabody/trash/nodegit
node-pre-gyp ERR! node -v v4.4.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.24
node-pre-gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c "/home/bpeabody/trash/nodegit/node_modules/.bin/node-pre-gyp" install --fallback-to-build=false' }
[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code

[nodegit] Configuring libssh2.
[nodegit] Everything is ready to go, attempting compilation
[ 'rebuild' ]
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at Error (native)
gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1013:38)
gyp ERR! stack     at emitNone (events.js:67:13)
gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
gyp ERR! stack     at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
gyp ERR! stack     at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)
gyp ERR! System Linux 3.16.0-0.bpo.4-amd64
gyp ERR! command "/home/bpeabody/local/bin/node" "/home/bpeabody/trash/nodegit/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/bpeabody/trash/nodegit
gyp ERR! node -v v4.4.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
1

npm ERR! Linux 3.16.0-0.bpo.4-amd64
npm ERR! argv "/home/bpeabody/local/bin/node" "/home/bpeabody/local/bin/npm" "install"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! nodegit@0.12.0 install: `node lifecycleScripts/install`
npm ERR! Exit status 13
npm ERR!
npm ERR! Failed at the nodegit@0.12.0 install script 'node lifecycleScripts/install'.
npm ERR! This is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bpeabody/trash/nodegit/npm-debug.log

**Comment by bpeabody** [comment]
I think my problem might be a messed up proxy.

**Comment by saper** [comment]
@bpeabody your problem is something completely different, your proxy acts as a man-in-the-middle for your SSL connection.

**Comment by bpeabody** [comment]
Yeah, I had several problems. I was finally able to get it working, but I might consider submitting a patch for a couple of items:

1. We need to used patched versions of `node-gyp` and `node-pre-gyp` to provide kerberos support. We're getting them through a local sinopia mirror and have patches for `node-gyp` at least pending upstream, but `nodegit` is currently pinned to an older minor version; I might ask to move to a newer version if possible.
2. We don't have a version of `libstdc++` needed by the prebuilt binary that is fetched from S3. I can build successfully locally. It might be nice to be able to either detect that the pre-built version won't and fall back to build (as it does if the fetch fails) or allow for a flag to request this behavior.

**Comment by hegdeashwin** [comment]
I am getting the same error "Error: Cannot find module '../build/Debug/nodegit.node'"

I am using node.js via nvm 
Node.js version 4.2.3
npm version 2.14.7

Well, I got the below message on my Ubuntu bash terminal:
[nodegit] Fetching binary from S3.
[nodegit] Completed installation successfully.

But when i am trying use the Repository.init API nothing happens!

**Comment by centigrade-thomas-becker** [comment]
I am getting the same problem with node 6.8.1 and npm 3.10.8

```
module.js:471
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\someProject\node_modules\nodegit\dist\nodegit.js:18:12)
```

**Comment by saper** [comment]
Please check you are using Release build of node, not the Debug one. On Newer nodes you can use `node -p process.features.debug` to find out.  For the Debug node engine you can always try to build the module from source, but that might require some manual steps.
