### ISSUE TITLE
Error: 1 conflict prevents checkout - when merging clean working directory

### ISSUE THREAD

**Issue by rolatsch** [nodegit/nodegit#941]
Hello,
i am trying to pull changes from a Repository. My working directory is clean but i am getting the error stated in the title.

My merge code looks like this:
```
var mOpts = new NodeGit.MergeOptions();
NodeGit.Merge.initOptions(mOpts, 1);
mOpts.fileFavor = NodeGit.Merge.FILE_FAVOR.THEIRS;
repository.mergeBranches(dbRepo.branch, 'origin/' + dbRepo.branch, signature, NodeGit.Merge.PREFERENCE.FASTFORWARD_ONLY, mOpts);
```

I'm not sure if this is the right way to use the merge options.

Thanks in advance.

**Comment by johnhaley81** [comment]
@rolatsch Try this:

```
return repository.mergeBranches(
  dbRepo.branch,
  'origin/' + dbRepo.branch,
  signature,
  null,
  {
    fileFavor: NodeGit.Merge.FILE_FAVOR.THEIRS
  });
```

You were doing a `FASTFORWARD_ONLY` which will supercede the merge option to automatically choose a file. It will stop any and all merges which is what I'm thinking it's doing. So something is on your local that you don't have in your remote.

**Comment by rolatsch** [comment]
This still happens. It seems like when i run my code on a newly cloned repository it works once. But when i want to pull again it fails.
When i run `git status` in Git Bash i get the following output:
```
$ git status
On branch develop
Your branch is behind 'origin/develop' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working directory clean
```
Do i have to do something else after merging to finalize the pulling process?

**Comment by rolatsch** [comment]
any updates on this? Here is my full pull code
´´´
NodeGit.Repository.open(repoDir)
            .catch(function (error) {
                console.error(error);
            })
            .then(function (repo) {
                console.log('fetching changes');
                process.send({
                    "repository": dbRepo.identifier,
                    "status": "running",
                    "message": "Fetching changes from origin.",
                    "error": false
                });

                repository = repo;

                return repository.fetchAll({
                    callbacks: {
                        credentials: function () {
                            return userpassPlaintextNew(dbRepo.user, dbRepo.password);
                        },
                        certificateCheck: function () {
                            return 1;
                        }
                    }
                })
            })
            .then(function (fetches) {
                console.log('fetches: ' + fetches);

                var signature = NodeGit.Signature.now("TableauDeploymentTool", "ab@c.de");

                return repository.mergeBranches(
                    dbRepo.branch,
                    'origin/' + dbRepo.branch,
                    signature,
                    null,
                    {
                        fileFavor: NodeGit.Merge.FILE_FAVOR.THEIRS
                    });
            })
            .catch(function (error) {
                console.error(error);
            });
´´´

**Comment by johnhaley81** [comment]
@rolatsch What's `dbRepo.branch`?

**Comment by rolatsch** [comment]
@johnhaley81 `dbRepo` is an object which holds the information about my repository.
The branch property is just the branch name. For example master or development.

**Comment by johnhaley81** [comment]
@rolatsch #971 might fix this issue. Could you try that out when you get a moment please?

**Comment by rolatsch** [comment]
@johnhaley81 sorry it took me a while to give this a try. 
With the latest revision of nodegit an no changes to my code this issue still persists.

Is it worth trying to clone the repository with nodegit instead of pulling a repository which was cloned via the git command line?

**Comment by rolatsch** [comment]
Did a rewrite of my code and now it's working somehow. My old code used a subprocess to work on the repository. Maybe this caused a conflict.
