### ISSUE TITLE
Included version of OpenSSL is vulnerable to security issues.

### ISSUE THREAD

**Issue by breser** [nodegit/nodegit#947]
nodegit appears to be shipping with OpenSSL 1.0.2e:
`vendor/openssl/openssl/include/openssl/opensslv.h:#  define OPENSSL_VERSION_TEXT    "OpenSSL 1.0.2e 3 Dec 2015"`

1.0.2f and 1.0.2g have been released with fixes for the client side, 1.0.2f ones seem more important than 1.0.2g from a client perspective, (which is presumably all that's being used from nodegit):
http://openssl.org/news/secadv/20160128.txt
http://openssl.org/news/secadv/20160301.txt

Mostly by the January update.

nodegit should be including a currently released version of OpenSSL.

**Comment by tbranyen** [comment]
Thanks @breser while we hate upgrading openssl, I'd imagine the security benefits here are worth the time.

**Comment by breser** [comment]
Moving between the patch releases e to g should be relatively painless.

**Comment by tbranyen** [comment]
@breser you'd think so, but history says otherwise: https://github.com/nodegit/nodegit/commit/d0662a9895f8b229afabe20b7a18eef93a3e481e

**Comment by maxkorp** [comment]
We're on 1.0.2.h now (and have been for a few months), closing this.
