### ISSUE TITLE
"callback returned unsupported credentials type" with oauth on Linux

### ISSUE THREAD

**Issue by cjb** [nodegit/nodegit#959]
I'm trying to use [surf-build](https://github.com/surf-build/surf), which logs into github via `x-oauth-basic`.  It works on OS X, but fails on Ubuntu 15.10 with:

`Fatal Error: callback returned unsupported credentials type`

This comes from `libgit2/src/transports/ssh.c`.  Is there a discrepancy in how node-git ships libgit2/libssh on Linux vs. OS X, maybe?

Surf issue: surf-build/surf#23

Thanks!

**Comment by cjb** [comment]
Oh.  I'm calling`nodegit.Clone.clone(url='https://github.com/surf/surf-build', ..)`, and nodegit is trying to use the **ssh** transport?  That doesn't seem right!

**Comment by cjb** [comment]
For posterity, this was totally my fault.  My `.gitconfig` contains:
```
[url "git@github.com:"]
        insteadOf = https://github.com/
```
for golang related reasons, and that causes an HTTPS url to end up asking for SSH authentication, confusing the code that expected to be authenticating HTTPS.  I'll close this out with a FAQ entry that explains it.

**Comment by rcontreras-te** [comment]
> For posterity, this was totally my fault. My `.gitconfig` contains:
> 
> ```
> [url "git@github.com:"]
>         insteadOf = https://github.com/
> ```
> 
> for golang related reasons, and that causes an HTTPS url to end up asking for SSH authentication, confusing the code that expected to be authenticating HTTPS. I'll close this out with a FAQ entry that explains it.

Wow, that took a while for me to figure out and make the connection via your post.  Thanks for that!
