### ISSUE TITLE
Bug (or documentation error) in the arguments to Diff.blobToBuffer

### ISSUE THREAD

**Issue by tylerchurch** [nodegit/nodegit#963]
If you look at the argument list here for `Diff.blobToBuffer`: http://www.nodegit.org/api/diff/

And then compare that to the argument list that's actually exposed in the code; https://github.com/nodegit/nodegit/blob/83f6affb4f1305826336fd34b3126d8b35debb2a/lib/diff.js#L61

They're different, with the actual API lacking the arguments `buffer_len` (and actually computing this value itself) and `payload`.

I'd submit a fix the documentation or the API, but I wasn't sure which one was the buggy one - seems to me like computing buffer_len inside `blobToBuffer` is intentional, but it also seems odd to me (e.g. what happens if the buffer passed in isn't UTF-8? The current code assumes that it is, and I imagine it would compute an incorrect length for non UTF-8 buffers.)

**Comment by johnhaley81** [comment]
So the documentation in this case is wrong. This can be fixed by doing the same that we do [here](https://github.com/nodegit/nodegit/blob/master/lib/blob.js#L7-L14) and just override the generated docs. After that's done we can close this out.
