### ISSUE TITLE
Nodegit doesnt work on LinuxMint (Ubuntu, I guess)

### ISSUE THREAD

**Issue by martinheidegger** [nodegit/nodegit#969]
Getting this error when **running** nodegit on LinuxMint (equal to Ubuntu i guess)

```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/node_modules/nodeschool-admin/node_modules/nodegit/build/Release/nodegit.node)
```

**Comment by tbranyen** [comment]
Please read the README this is discussed under installing.

**Comment by martinheidegger** [comment]
Thank you for explaining, opened a pull request so future users have less problems.
