### ISSUE TITLE
32-bit support?

### ISSUE THREAD

**Issue by SEAPUNK** [nodegit/nodegit#974]
From atom issue atom/atom#10819 (https://github.com/atom/atom/issues/10819#issuecomment-200963545), a lot of 32-bit Linux users have been having troubles installing nodegit. From my research, it seemed to be a two-part problem of there not being a 32-bit prebuilt binary of nodegit 

`Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.11.9-node-v47-linux-ia32.tar.gz`

and npm failing during the fallback build script

```
[nodegit] Building manually. (You'll be here a while.)
[nodegit] Regenerating and configuring code
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm ERR! Linux 4.4.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--ignore-scripts"
npm ERR! node v5.9.1
npm ERR! npm  v3.8.2

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ivan/code/__/node_modules/nodegit/npm-debug.log
```

If the build problem is an issue with npm, could there at least be a prebuilt binary for 32-bit linux systems available for us to use?

**Comment by tbranyen** [comment]
Its probably because our Travis setup publishes 64bit builds and not 32bit. This was a big concern of mine with going full automated. We'll need to set up a secondary target that hits x86 32bit.

**Comment by johnhaley81** [comment]
https://github.com/travis-ci/travis-ci/issues/986#issuecomment-124141683 :(

**Comment by SEAPUNK** [comment]
Oh, that sucks. Is there a way to publish a 32-bit binary manually as a temporary workaround, then?

**Comment by tbranyen** [comment]
@johnhaley81 is anything preventing us from cross compiling with this? http://stackoverflow.com/a/22469265

**Comment by johnhaley81** [comment]
@tbranyen nice find! That might be a way forward.. When running a build with `TRAVIS_TAG` we could do 2 compiles and publishes.

**Comment by SEAPUNK** [comment]
Bump; is there any progress on this? Is there any way I can help?

**Comment by johnhaley81** [comment]
@SEAPUNK could you start looking into what tbranyen said in https://github.com/nodegit/nodegit/issues/974#issuecomment-202486125? That would be a great starting point I think. Add that to the CI matrix on Travis.

**Comment by SEAPUNK** [comment]
Alright, I'll do some research.

**Comment by SEAPUNK** [comment]
Question: Are there any needed environment variables for Travis for the builds? Are there any pieces from the build script that I can remove (e.g. publishing to S3)?

**Comment by johnhaley81** [comment]
When we push a tag travis will (pick that up)[https://github.com/nodegit/nodegit/blob/master/.travis.yml#L84] and do a publish to S3 with the resulting binary. If you don't push a tag you won't publish so I wouldn't worry about that.

Apart from that though, the (matrix)[https://github.com/nodegit/nodegit/blob/master/.travis.yml#L16-L18] is defined here and will declare environment variables that will be picked up. If you add a 32-bit one you'll have to ignore it on OSX and then use the above idea from Tim to build the 32-bit stuff on linux.

**Comment by SEAPUNK** [comment]
I've added an extra handler for an additional environment variable, `TARGET_ARCH`, and after installing the 32-bit compiler files (`lib32-gcc-libs` on Arch Linux), it seems to be compiling. I'll be sure to inspect the built `.node` file to see if it's truly built for 32-bit machines.

On a side note, I know that I had to do `--arch=ia32` on `node-gyp`, but don't you have to do the same for `node-pre-gyp`, just under a different flag?

**Comment by SEAPUNK** [comment]
Compilation broke. :(

```
  AR(target) Release/obj.target/vendor/ssh2.a
  COPY Release/ssh2.a
  CXX(target) Release/obj.target/nodegit/src/lock_master.o
In file included from /usr/include/c++/5.3.0/random:49:0,
                 from /usr/include/c++/5.3.0/bits/stl_algo.h:66,
                 from /usr/include/c++/5.3.0/algorithm:62,
                 from ../node_modules/nan/nan.h:48,
                 from ../src/lock_master.cc:1:
/usr/include/c++/5.3.0/bits/random.h:106:26: error: expected unqualified-id before ‘__int128’
       { typedef unsigned __int128 type; };
                          ^
nodegit.target.mk:228: recipe for target 'Release/obj.target/nodegit/src/lock_master.o' failed
make: *** [Release/obj.target/nodegit/src/lock_master.o] Error 1
make: Leaving directory '/home/ivan/github/nodegit/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ivan/github/nodegit/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.2.5-1-ARCH
gyp ERR! command "/usr/bin/node" "/home/ivan/github/nodegit/node_modules/.bin/node-gyp" "rebuild" "--arch=ia32"
gyp ERR! cwd /home/ivan/github/nodegit
gyp ERR! node -v v5.10.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
1

npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
npm ERR! nodegit@0.12.1 install: `node lifecycleScripts/install`
npm ERR! Exit status 13
npm ERR! 
npm ERR! Failed at the nodegit@0.12.1 install script 'node lifecycleScripts/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodegit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lifecycleScripts/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodegit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodegit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ivan/github/nodegit/npm-debug.log
```

**Comment by SEAPUNK** [comment]
**NEVER MIND**, I made it compile. I just had the wrong compilation packages installed.

**Comment by SEAPUNK** [comment]
Alright, running Travis build. Let's hope nothing explodes.

https://github.com/SEAPUNK/nodegit/commit/bf01893a89673908a64bb7de1cf6257f50303de5
https://travis-ci.org/SEAPUNK/nodegit

**Comment by SEAPUNK** [comment]
Alright, I was able to create a successful build for 32-bit systems. The problem now is when it actually tests the binary -- it can't load `nodegit.node` because it's built for 32-bit systems, but the system itself is 64-bit.

What do I do?

**Comment by SEAPUNK** [comment]
Alright, I think I got it. PR: #980

**Comment by roshimon** [comment]
Upgrading to atom 1.8.0-beta1 has fixed the issue for me. Working flawlessly now :)
