### ISSUE TITLE
403 error when trying to install nodegit via npm

### ISSUE THREAD

**Issue by kodekrash** [nodegit/nodegit#979]
when running `npm install nodegit`
```
[nodegit] Fetching binary from S3.
[nodegit] Failed to install prebuilt binary:
{ [Error: Command failed: node-pre-gyp http GET https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.12.1-node-v11-linux-x64.tar.gz
node-pre-gyp http 403 https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.12.1-node-v11-linux-x64.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.12.1-node-v11-linux-x64.tar.gz
```

**Comment by tbranyen** [comment]
@johnhaley81 is this a publish error or are they still publishing?

**Comment by johnhaley81** [comment]
Node v11 isn't in our support matrix.

**Comment by johnhaley81** [comment]
Earliest we publish is v14

**Comment by tbranyen** [comment]
So upgrading Node is the solution here?

**Comment by johnhaley81** [comment]
Yep. `node-pre-gyp info | grep 0.12.1` confirms that all binaries that we expect to publish are published.

**Comment by tbranyen** [comment]
Okay cool, closing this as non-issue.

**Comment by kodekrash** [comment]
Followup for information --

I am currently using nodejs 0.10.42 (rpm) which is shipped with Fedora 23 updates. Disturbing, now that I look at that, since node is up to 4.x / 5.x ...

Located 5.x RPMs via nodesource.com. Will try again with correct version of node/npm.
