### ISSUE TITLE
Fetch() hangs when it is used against ssh protocol with sshKeyFromAgent()

### ISSUE THREAD

**Issue by normanzb** [nodegit/nodegit#985]
It works if the repo's `origin` remote is setup to use https but it hangs if the remote is setup to use github ssh such as `git@github.com:nodegit/nodegit.git`

It calls `credentials` callback endlessly without proceeding ahead.

```
'use strict';

var console = require('console');
var git = require('nodegit');
var repo;

git.Repository.open('.')
.then(function(repository){
    repo = repository;
    return repo.getStatus();
})
.then(function(status){
    console.log(status);
    return repo.fetch('origin', {
        callbacks: {
            credentials: function(url, userName) {
                return git.Cred.sshKeyFromAgent(userName);
            }
        }
    });
})
.then(function(fetched){
    console.log('worked');
}, function(err){
    console.log(err);
});
```

**Comment by johnhaley81** [comment]
So libgit2 will call the `credentials` callback until it either returns `defaultNew` or returns a credential that works. It's probably not able to connect to the agent, the agent doesn't have the correct key or something like that. Try manually sending back the key with `sshKeyNew`.

**Comment by normanzb** [comment]
@johnhaley81 thx it works
