### ISSUE TITLE
Assertion failed: (repo), function git_repository_workdir

### ISSUE THREAD

**Issue by adius** [nodegit/nodegit#993]
When I try to clone the repo `zzflux/ProjectEuler` with `Clone.clone()` I get following error
```
Assertion failed: (repo), function git_repository_workdir, file ../vendor/libgit2/src/repository.c, line 1809.
```

**Comment by johnhaley81** [comment]
@adius could we see what your code looks like please?

**Comment by adius** [comment]
The issues was that caused by a 'repo.free()' call.
I'm not entirely sure if I correctly understand what it's good for ^^

**Comment by johnhaley81** [comment]
@adius a `repo.free()` will destroy the underlying libgit2 C-struct `git_repository` object. If you call that the JS object is effectively useless at that point and shouldn't be passed around anymore.

**Comment by adius** [comment]
Ok, then I guessed correctly =P
…and I just realized the problem was that although I called at it at the end,
it was possible that some async code was still using it and therefore it crashed.
Thanks for your help!
