### ISSUE TITLE
Create a pull request after pushing to remote

### ISSUE THREAD

**Issue by girishkvs** [nodegit/nodegit#999]
Hello,

Is there any way I can create a PR using nodegit similar to git request-pull ?

Thanks,
Girish

**Comment by tbranyen** [comment]
https://libgit2.github.com/libgit2/#HEAD is all we can support, and it doesn't look like request-pull exists yet. Might want to bug the libgit2 folks and see what the roadmap is.

Closing as it's not something actionable.
